# Final answer keys. Generated by keysolve.py (seed 20260901) and verified against
# every constraint in keysolve.violations(). Deliberately NOT minimum-churn: a
# minimum-churn key sits on the boundary of the constraint set, next door to the
# cycled key it replaces, and the constraints are only a proxy for "looks random".
KEYS = {
  "2.1": "DADBACBCABCBDACD",
  "2.2": "BADDACDADCACBDBCABCBACADBDCB",
}
# Questions pinned to their original letter because their options are ordered by
# cardinality (I only / I and II only / I, II, and III). Re-lettering those would
# strand "I, II, and III" at option A.
PINNED = {"2.1": {}, "2.2": {2: "A", 7: "D", 22: "C"}}

# ---- 2.2 Q25 replacement -------------------------------------------------
# Q25 duplicated Q7: same EK, same three I/II/III statements, same answer.
# The replacement keeps EK 2.2.B.1 (coverage in this quiz is exactly 2 per EK)
# but tests it from the misconception side rather than by enumeration.
Q25 = {
 "stem": "A hurricane floods a company's ground-floor server room, destroying several "
         "machines and taking customer-facing services offline for three days. A new "
         "analyst argues this was not a physical security incident because no adversary "
         "was involved. Why is the analyst incorrect?",
 "opts": [
   "Threats to physical security include natural disasters, which can cause physical "
   "damage or destruction to computers and data and disrupt digital services",
   "Threats to physical security are limited to human adversaries, but flooding counts "
   "as an adversary acting through the environment",
   "The flood is a vulnerability rather than a threat, because it exposed a weakness in "
   "the building's design",
   "The flood matters only because the destroyed machines held sensitive information, "
   "not because services went offline",
 ],
 "correct": 0,   # index into opts above, before permutation
 "why": "EK 2.2.B.1 states that threats to physical security include natural disasters "
        "as well as human adversaries, and that natural disasters can cause physical "
        "damage or destruction to computers and data and disrupt digital services. The "
        "flood is squarely a threat under that definition. {WRONG} is wrong because it "
        "keeps the human-adversary-only assumption and then stretches it. {VULN} confuses "
        "a threat with a vulnerability (EK 2.2.B.2): the low-lying server room is the "
        "vulnerability, the flood is the threat. {SCOPE} invents a limit the CED does not "
        "set, since disruption of digital services is named in the EK alongside damage.",
 "ced": "EK 2.2.B.1",
}

# ---- 2.2 KEY: pre-existing rationale bug ---------------------------------
# Q26's correct answer is A, but its rationale dismissed "Options A, B, and C".
KEY_RATIONALE_FIX = {
  ("2.2", 26): ("Options A, B, and C name attacks", "Options B, C, and D name attacks"),
}

# ---- 2.2 STUDENT: repair of a naive EK-citation strip --------------------
# Removing the citations left dangling prepositions, sentence fragments and
# options beginning with a bare em-dash. Keyed by (question, "stem"|letter).
STUDENT_REPAIRS = {
 ("2.2", 7,  "stem"): ("The College Board says threats to physical security include more than "
                       "human attackers. Which statement(s) are correct?"),
 ("2.2", 8,  "stem"): "A vulnerability is best defined as which of the following?",
 ("2.2", 9,  "stem"): ["Which of the following is ", "NOT", " one of the common ways an "
                       "asset can be compromised?"],
 ("2.2", 11, "stem"): ("An adversary gains entry to a records room that holds files of sensitive "
                       "customer information. Without damaging anything, they photograph the "
                       "documents and walk out. What has the adversary done?"),
 ("2.2", 12, "stem"): ("Having reached an unattended workstation, an adversary inserts a USB "
                       "drive loaded with malware into an open port, aiming to collect the "
                       "user's data or take control of the machine. Which statement best "
                       "describes this category of harm?"),
 ("2.2", 12, "A"): "Manipulating an authorized person into granting access",
 ("2.2", 12, "B"): "Plugging a malicious device into a port to collect data or gain control",
 ("2.2", 12, "C"): "A low-value asset that is unlikely to be exploited",
 ("2.2", 12, "D"): "Watching a user enter credentials to reuse them later",
 ("2.2", 13, "stem"): ("A teacher asks why physical destruction of a server is so damaging. "
                       "What is the most complete answer?"),
 ("2.2", 14, "A"): "Physical access to a device can let adversaries bypass many technical controls",
 ("2.2", 14, "B"): "Tailgating is following an authorized person in without their awareness",
 ("2.2", 14, "C"): "Low risks arise when a low-value asset is unlikely to be exploited",
 ("2.2", 14, "D"): "Adversaries often use social engineering during a physical attack",
 ("2.2", 19, "stem"): ("A trainer wants the clearest one-line definition of social engineering "
                       "as the College Board frames it for physical attacks. Which statement "
                       "best matches that definition?"),
 ("2.2", 22, "stem"): "Which statement(s) correctly describe shoulder surfing?",
 ("2.2", 23, "stem"): ("A teacher contrasts dumpster diving with the door attacks. Which feature "
                       "best captures what makes dumpster diving distinct?"),
 ("2.2", 27, "stem"): ("Which action best describes what an adversary can do after reaching an "
                       "area that holds sensitive information?"),
}

# ---- applied to BOTH copies, so KEY and STUDENT never diverge ------------
# "Per the CED" / "In CED terms" is teacher-facing sourcing language sitting in a
# student-facing stem. Same defect class that was stripped from the online banks.
SHARED_REPAIRS = {
 ("2.1", 4, "stem"): ("Investigators reconstruct an attack: the adversary first gathered freely "
                      "available information about the company from public websites and social "
                      "media, then used a stolen password to log in. Later they installed a remote "
                      "access trojan to keep their connection alive. Which phases occurred, in order?"),
 ("2.1", 5, "stem"): ("A risk analyst is rating an online store’s checkout system. The system "
                      "processes valuable payment data, a documented exploit for its flaw is widely "
                      "available, and a successful attack would cost an estimated $250,000 in losses. "
                      "Which factors is the analyst legitimately weighing to assess this risk?"),
 ("2.1", 5, "D"):    "The number of employees at the store, which is the primary driver of risk",
}

# "Which EK best explains...?" survives only in the teacher copy: the citation strip
# had already turned the student's version into "What best explains...?". Asking a
# student to name an EK code is teacher-facing anyway, so both copies get the
# statement wording and the KEY keeps its citation as a trailing parenthetical,
# which is what Q20/Q21/Q24 in this same quiz already do.
SHARED_REPAIRS.update({
 ("2.2", 10, "stem"): ("An adversary breaks into a building's electrical room and trips the breakers "
                       "feeding the server rack, then cuts a power cable. The servers and the services "
                       "they host go offline. Which statement best explains the result of this action?"),
 ("2.2", 12, "stem"): ("Having reached an unattended workstation, an adversary inserts a USB drive "
                       "loaded with malware into an open port, aiming to collect the user's data or "
                       "take control of the machine. Which statement best describes this category of harm?"),
 ("2.2", 14, "stem"): ("A server is protected by a strong password and sits behind a firewall, yet the "
                       "security lead insists the unlocked room it sits in still matters. Which "
                       "statement best supports that position?"),
 ("2.2", 26, "stem"): ("A storm topples a transformer outside a data center and an adversary later cuts "
                       "the wiring feeding a backup electrical panel, taking a rack of servers and their "
                       "hosted services offline. Which statement explains why disrupting power causes "
                       "this outcome?"),
 ("2.2", 28, "stem"): ("A laptop in a locked office uses full-disk encryption and a strong login "
                       "password, yet the security lead still treats an unlocked office door as a "
                       "serious problem. Which statement best supports treating physical exposure as a "
                       "threat to a digitally hardened device?"),
})

# Teacher copy only: move the leading "EK x.x.x - " onto the end as a parenthetical
# so the option reads as the same sentence the student answered. Keyed by the
# ORIGINAL letter, before re-lettering.
KEY_REPAIRS = {
 ("2.2", 12, "A"): "Manipulating an authorized person into granting access (EK 2.2.A.2)",
 ("2.2", 12, "B"): "Plugging a malicious device into a port to collect data or gain control (EK 2.2.B.5)",
 ("2.2", 12, "C"): "A low-value asset that is unlikely to be exploited (EK 2.2.C.4)",
 ("2.2", 12, "D"): "Watching a user enter credentials to reuse them later (EK 2.2.A.4)",
 ("2.2", 14, "A"): "Physical access to a device can let adversaries bypass many technical controls (EK 2.2.C.1)",
 ("2.2", 14, "B"): "Tailgating is following an authorized person in without their awareness (EK 2.2.A.3)",
 ("2.2", 14, "C"): "Low risks arise when a low-value asset is unlikely to be exploited (EK 2.2.C.4)",
 ("2.2", 14, "D"): "Adversaries often use social engineering during a physical attack (EK 2.2.A.1)",
}
