'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  AP CSA UNIT 4 FRQ PRACTICE: DATA COLLECTIONS.
//
//  NEARLY EVERY BUG IN THIS UNIT IS AN INDEX BUG IN A NEW COSTUME
//  Off by one at the end of an array, off by one at the end of an ArrayList,
//  removing while indexing forward, the row and column swapped, a binary search
//  whose bounds never shrink, a base case that returns the wrong value. The
//  questions here name that pattern rather than treating seventeen topics as
//  seventeen unrelated skills.
//
//  EVERY GRID IS DELIBERATELY NON SQUARE
//  A swapped pair of indexes crashes loudly on a 2 by 3 grid and silently
//  transposes on a 3 by 3 one. A square test case cannot tell a correct
//  traversal from a transposed one, so there are no square grids in this file.
//
//  ARRAYS ARE PASSED IN, NOT READ IN
//  The harness reads the data and hands the student's method a real array or
//  ArrayList. That keeps the graded skill on the collection rather than on
//  Scanner, and it means a hidden case is a hidden ARRAY, which no constant can
//  anticipate.
//
//  NO UNBOUNDED RECURSION. 4.16 and 4.17 recurse, and every mutant there changes
//  a returned VALUE or a base case that still terminates, never the step that
//  makes progress. The verifier runs each mutant under a 15 second timeout, and
//  a hang is indistinguishable from a broken harness rather than being a
//  demonstration of anything.
//
//  Nothing here states an expected output. scripts/verify-csa-frq.js runs each
//  `reference` through real javac/java to generate them.
// ─────────────────────────────────────────────────────────────────────────────

const U = 'unit-4';

// Every harness in this file reads a count then that many ints into an array.
// Written once so seventeen questions cannot drift into seventeen slightly
// different input formats.
function readArray(name) {
  return [
    `    int ${name}Len = input.nextInt();`,
    `    int[] ${name} = new int[${name}Len];`,
    `    for (int i = 0; i < ${name}Len; i++) {`,
    `      ${name}[i] = input.nextInt();`,
    '    }',
  ];
}

function harness(body) {
  return ['import java.util.Scanner;', 'import java.util.ArrayList;', '',
    'public class Main {', '  public static void main(String[] args) {',
    '    Scanner input = new Scanner(System.in);']
    .concat(body, ['  }', '}']).join('\n');
}

const FRQS = [
  // ── 4.1 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.1', unit: U,
    title: 'Ethical and Social Issues Around Data Collection',
    name: 'Aggregate, Do Not Identify',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'The ethical rule in this topic has a concrete programming shape: report the aggregate, not '
      + 'the individual. A count that can only be satisfied by one person is not anonymous, and this '
      + 'question asks you to detect exactly that, which is what a real suppression rule does.',
    given: 'The driver builds an int array of counts, one per group, and passes it to your methods. '
      + 'Write a class named Report. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int total(int[] counts) returns the sum of every count.' },
      { label: '(b)', text: 'public static int groups(int[] counts) returns how many groups there are.' },
      { label: '(c)', text: 'public static boolean isIdentifying(int[] counts, int minimum) returns whether ANY group has a count below minimum but above 0.' },
      { label: '(d)', text: 'public static int suppressed(int[] counts, int minimum) returns the total of only the groups that are at or above minimum.' },
    ],
    task: [
      'Write class Report with the four static methods described. No main method.',
      'A group with a count of 0 is not identifying, because nobody is in it. Only a small NON EMPTY group is.',
      'Part (d) leaves out the small groups entirely rather than replacing them with zero after the fact.',
    ],
    starter: [
      'class Report {',
      '  // (a) total(int[] counts) -> int',
      '',
      '  // (b) groups(int[] counts) -> int',
      '',
      '  // (c) isIdentifying(int[] counts, int minimum) -> boolean',
      '',
      '  // (d) suppressed(int[] counts, int minimum) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Report {',
      '  public static int total(int[] counts) {',
      '    int sum = 0;',
      '    for (int c : counts) {',
      '      sum = sum + c;',
      '    }',
      '    return sum;',
      '  }',
      '',
      '  public static int groups(int[] counts) {',
      '    return counts.length;',
      '  }',
      '',
      '  public static boolean isIdentifying(int[] counts, int minimum) {',
      '    for (int c : counts) {',
      '      if (c > 0 && c < minimum) {',
      '        return true;',
      '      }',
      '    }',
      '    return false;',
      '  }',
      '',
      '  public static int suppressed(int[] counts, int minimum) {',
      '    int sum = 0;',
      '    for (int c : counts) {',
      '      if (c >= minimum) {',
      '        sum = sum + c;',
      '      }',
      '    }',
      '    return sum;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness(readArray('counts').concat([
      '    int minimum = input.nextInt();',
      '',
      '    System.out.println(Report.total(counts));',
      '    System.out.println(Report.groups(counts));',
      '    System.out.println(Report.isIdentifying(counts, minimum));',
      '    System.out.println(Report.suppressed(counts, minimum));',
    ])),
    hints: [
      'An enhanced for loop reads every element and is the right tool whenever you do not need the index. Part (a), (c) and (d) never need one.',
      'Part (c) has two conditions joined by and: above zero AND below the minimum. Dropping the first makes every empty group look identifying.',
      'Part (d) is a filtered sum. The groups below the minimum contribute nothing rather than contributing zero after being counted.',
    ],
    seo: 'AP CSA 4.1 FRQ practice: aggregate group counts and detect when a small non empty group would identify individuals.',
    mutants: [
      { describe: 'part (c) treats an empty group as identifying',
        find: 'if (c > 0 && c < minimum) {', replace: 'if (c < minimum) {' },
      { describe: 'part (d) includes the groups it was supposed to suppress',
        find: '      if (c >= minimum) {\n        sum = sum + c;\n      }', replace: '      sum = sum + c;' },
      { describe: 'part (d) excludes a group sitting exactly on the minimum',
        find: 'if (c >= minimum) {', replace: 'if (c > minimum) {' },
    ],
    cases: [
      { stdin: '4\n10 20 2 30\n5\n', part: 3, hidden: 0 },
      // Chosen for (d): a group sitting EXACTLY on the minimum, which must be kept.
      { stdin: '3\n5 40 50\n5\n', part: 4, hidden: 0 },
      // Chosen for (c): an EMPTY group, which is not identifying.
      { stdin: '4\n0 30 40 0\n5\n', part: 3, hidden: 1 },
      // Chosen for (b): a single group.
      { stdin: '1\n99\n10\n', part: 2, hidden: 1 },
      // Chosen for (a): every group below the minimum, so the suppressed total is 0.
      { stdin: '3\n1 2 3\n10\n', part: 1, hidden: 1 },
    ],
  },

  // ── 4.2 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.2', unit: U,
    title: 'Introduction to Using Data Sets',
    name: 'Summarising a Data Set',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'The first thing anyone does with a data set is ask for its minimum, maximum and mean, and '
      + 'the first bug anyone writes is seeding the maximum at 0. On data that is entirely negative '
      + 'that reports a maximum which is not in the data at all, and no error is raised.',
    given: 'The driver builds an int array and passes it to your methods. Every array has at least one '
      + 'element. Write a class named Summary. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int max(int[] data) returns the largest value.' },
      { label: '(b)', text: 'public static int min(int[] data) returns the smallest value.' },
      { label: '(c)', text: 'public static int range(int[] data) returns the largest minus the smallest.' },
      { label: '(d)', text: 'public static int mean(int[] data) returns the sum divided by the length, using integer division.' },
    ],
    task: [
      'Write class Summary with the four static methods described. No main method.',
      'Seed the maximum and the minimum with the FIRST element, never with 0. The array may be entirely negative or entirely positive.',
      'Parts (a) and (b) should be written once each and reused by part (c).',
    ],
    starter: [
      'class Summary {',
      '  // (a) max(int[] data) -> int',
      '',
      '  // (b) min(int[] data) -> int',
      '',
      '  // (c) range(int[] data) -> int',
      '',
      '  // (d) mean(int[] data) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Summary {',
      '  public static int max(int[] data) {',
      '    int best = data[0];',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] > best) {',
      '        best = data[i];',
      '      }',
      '    }',
      '    return best;',
      '  }',
      '',
      '  public static int min(int[] data) {',
      '    int best = data[0];',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] < best) {',
      '        best = data[i];',
      '      }',
      '    }',
      '    return best;',
      '  }',
      '',
      '  public static int range(int[] data) {',
      '    return max(data) - min(data);',
      '  }',
      '',
      '  public static int mean(int[] data) {',
      '    int sum = 0;',
      '    for (int v : data) {',
      '      sum = sum + v;',
      '    }',
      '    return sum / data.length;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness(readArray('data').concat([
      '',
      '    System.out.println(Summary.max(data));',
      '    System.out.println(Summary.min(data));',
      '    System.out.println(Summary.range(data));',
      '    System.out.println(Summary.mean(data));',
    ])),
    hints: [
      'Seeding with data[0] and starting the loop at 1 is the standard shape. It works for any data because the seed is guaranteed to be a real element.',
      'A maximum seeded at 0 is correct only when the data happens to contain something positive. The hidden cases here do not.',
      'Part (c) is one line if parts (a) and (b) are right. Re-scanning the array a third time is another chance to seed one of them wrongly.',
    ],
    seo: 'AP CSA 4.2 FRQ practice: seed minimum and maximum with a real element so entirely negative data still summarises correctly.',
    mutants: [
      { describe: 'part (a) seeds the maximum at 0 instead of the first element',
        find: '  public static int max(int[] data) {\n    int best = data[0];', replace: '  public static int max(int[] data) {\n    int best = 0;' },
      { describe: 'part (b) seeds the minimum at 0 instead of the first element',
        find: '  public static int min(int[] data) {\n    int best = data[0];', replace: '  public static int min(int[] data) {\n    int best = 0;' },
      { describe: 'part (a) starts the loop at 0 but skips the last element',
        find: '    for (int i = 1; i < data.length; i++) {\n      if (data[i] > best) {', replace: '    for (int i = 1; i < data.length - 1; i++) {\n      if (data[i] > best) {' },
      { describe: 'part (c) subtracts the wrong way round',
        find: 'return max(data) - min(data);', replace: 'return min(data) - max(data);' },
    ],
    cases: [
      { stdin: '5\n4 9 1 7 3\n', part: 1, hidden: 0 },
      // Chosen for (d): a sum that does not divide evenly by the length.
      { stdin: '4\n1 2 3 5\n', part: 4, hidden: 0 },
      // Chosen for (a) and (b): every value NEGATIVE, so a zero seed reports a
      // maximum that does not appear in the data.
      { stdin: '4\n-8 -3 -20 -5\n', part: 1, hidden: 1 },
      // Chosen for (a): the largest value is LAST, which a loop that stops early misses.
      { stdin: '4\n2 3 4 99\n', part: 1, hidden: 1 },
      // Chosen for (b): the smallest value is LAST, the mirror of the row above.
      { stdin: '4\n40 30 20 -1\n', part: 2, hidden: 1 },
      // Chosen for (c): a single element, where the range is 0.
      { stdin: '1\n-6\n', part: 3, hidden: 1 },
    ],
  },

  // ── 4.3 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.3', unit: U,
    title: 'Array Creation and Access',
    name: 'Index Boundaries',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'Valid indexes run from 0 to length - 1. Everything in this topic follows from that one '
      + 'sentence, and every bug in it is a place where length was used as if it were an index.',
    given: 'The driver builds an int array and passes it to your methods. Every array has at least one '
      + 'element. Write a class named Access. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int first(int[] data) returns the first element.' },
      { label: '(b)', text: 'public static int last(int[] data) returns the last element.' },
      { label: '(c)', text: 'public static boolean isValid(int[] data, int index) returns whether index is a usable index for data.' },
      { label: '(d)', text: 'public static int at(int[] data, int index) returns the element at index, or -1 when the index is not usable.' },
    ],
    task: [
      'Write class Access with the four static methods described. No main method.',
      'A negative index is not usable either. Part (c) has to rule out both ends.',
      'Part (d) must not throw. Check with part (c) before reaching into the array.',
    ],
    starter: [
      'class Access {',
      '  // (a) first(int[] data) -> int',
      '',
      '  // (b) last(int[] data) -> int',
      '',
      '  // (c) isValid(int[] data, int index) -> boolean',
      '',
      '  // (d) at(int[] data, int index) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Access {',
      '  public static int first(int[] data) {',
      '    return data[0];',
      '  }',
      '',
      '  public static int last(int[] data) {',
      '    return data[data.length - 1];',
      '  }',
      '',
      '  public static boolean isValid(int[] data, int index) {',
      '    return index >= 0 && index < data.length;',
      '  }',
      '',
      '  public static int at(int[] data, int index) {',
      '    if (isValid(data, index)) {',
      '      return data[index];',
      '    }',
      '    return -1;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness(readArray('data').concat([
      '    int probe = input.nextInt();',
      '',
      '    System.out.println(Access.first(data));',
      '    System.out.println(Access.last(data));',
      '    System.out.println(Access.isValid(data, probe));',
      '    System.out.println(Access.at(data, probe));',
    ])),
    hints: [
      'data[data.length] is always out of bounds. The last element is at data.length - 1.',
      'Part (c) needs both halves. index < data.length alone accepts -1, which throws the moment part (d) uses it.',
      'The driver probes with an index that is sometimes valid and sometimes not, so both answers from part (d) are checked.',
    ],
    seo: 'AP CSA 4.3 FRQ practice: use valid array indexes from 0 to length minus one and guard access at both ends.',
    mutants: [
      { describe: 'part (b) indexes at length rather than length - 1',
        find: 'return data[data.length - 1];', replace: 'return data[data.length];' },
      { describe: 'part (c) forgets that a negative index is invalid',
        find: 'return index >= 0 && index < data.length;', replace: 'return index < data.length;' },
      { describe: 'part (c) accepts an index equal to the length',
        find: 'return index >= 0 && index < data.length;', replace: 'return index >= 0 && index <= data.length;' },
      { describe: 'part (d) returns 0 rather than -1 for an unusable index',
        find: '    return -1;\n  }\n}', replace: '    return 0;\n  }\n}' },
    ],
    cases: [
      { stdin: '4\n11 22 33 44\n2\n', part: 1, hidden: 0 },
      // Chosen for (c): the probe is exactly the LENGTH, one past the end.
      { stdin: '3\n5 6 7\n3\n', part: 3, hidden: 0 },
      // Chosen for (c): a NEGATIVE probe, the other invalid end. The values
      // differ from the row above so this case's whole answer is not already
      // printed there.
      { stdin: '3\n1 2 9\n-1\n', part: 3, hidden: 1 },
      // Chosen for (b): a single element, where first and last are the same.
      { stdin: '1\n8\n0\n', part: 2, hidden: 1 },
      // Chosen for (d): a valid probe landing on the last element.
      { stdin: '5\n2 4 6 8 10\n4\n', part: 4, hidden: 1 },
    ],
  },

  // ── 4.4 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.4', unit: U,
    title: 'Traversing Arrays',
    name: 'Forwards and Backwards',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'A backwards traversal starts at length - 1 and a forwards one stops before length, and '
      + 'writing either bound the other way round is the crash this topic is famous for. An enhanced '
      + 'for loop avoids both, at the cost of not knowing where it is.',
    given: 'The driver builds an int array and passes it to your methods. Write a class named Traverse. '
      + 'Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static String forwards(int[] data) returns every element separated by single spaces, or the empty String for an empty array.' },
      { label: '(b)', text: 'public static String backwards(int[] data) returns every element in reverse, separated by single spaces.' },
      { label: '(c)', text: 'public static int sumEvenIndexes(int[] data) returns the sum of the elements at indexes 0, 2, 4 and so on.' },
      { label: '(d)', text: 'public static int countMatching(int[] data, int target) returns how many elements equal target.' },
    ],
    task: [
      'Write class Traverse with the four static methods described. No main method.',
      'Parts (a) and (b) put a single space BETWEEN elements and none at the start.',
      'Part (c) is about the INDEX being even, not the value.',
    ],
    starter: [
      'class Traverse {',
      '  // (a) forwards(int[] data) -> String',
      '',
      '  // (b) backwards(int[] data) -> String',
      '',
      '  // (c) sumEvenIndexes(int[] data) -> int',
      '',
      '  // (d) countMatching(int[] data, int target) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Traverse {',
      '  public static String forwards(int[] data) {',
      '    String out = "";',
      '    for (int i = 0; i < data.length; i++) {',
      '      if (i > 0) {',
      '        out = out + " ";',
      '      }',
      '      out = out + data[i];',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static String backwards(int[] data) {',
      '    String out = "";',
      '    for (int i = data.length - 1; i >= 0; i--) {',
      '      if (i < data.length - 1) {',
      '        out = out + " ";',
      '      }',
      '      out = out + data[i];',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static int sumEvenIndexes(int[] data) {',
      '    int sum = 0;',
      '    for (int i = 0; i < data.length; i = i + 2) {',
      '      sum = sum + data[i];',
      '    }',
      '    return sum;',
      '  }',
      '',
      '  public static int countMatching(int[] data, int target) {',
      '    int count = 0;',
      '    for (int v : data) {',
      '      if (v == target) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness(readArray('data').concat([
      '    int target = input.nextInt();',
      '',
      '    System.out.println(Traverse.forwards(data));',
      '    System.out.println(Traverse.backwards(data));',
      '    System.out.println(Traverse.sumEvenIndexes(data));',
      '    System.out.println(Traverse.countMatching(data, target));',
    ])),
    hints: [
      'A backwards loop starts at data.length - 1 and continues while the index is at least 0. Starting at data.length throws on the very first pass.',
      'Part (c) steps the index by 2. The elements at odd indexes are skipped entirely, whatever their values.',
      'The separator goes before every element except the one that comes first in the output, which is a different element in part (a) and part (b).',
    ],
    seo: 'AP CSA 4.4 FRQ practice: traverse an array forwards and backwards with correct bounds and sum only the even indexes.',
    mutants: [
      { describe: 'part (b) starts at length, one past the end',
        find: 'for (int i = data.length - 1; i >= 0; i--) {', replace: 'for (int i = data.length; i >= 0; i--) {' },
      { describe: 'part (c) sums the even VALUES rather than the even indexes',
        find: '    for (int i = 0; i < data.length; i = i + 2) {\n      sum = sum + data[i];\n    }',
        replace: '    for (int i = 0; i < data.length; i++) {\n      if (data[i] % 2 == 0) {\n        sum = sum + data[i];\n      }\n    }' },
      { describe: 'part (a) stops one element short',
        find: 'for (int i = 0; i < data.length; i++) {\n      if (i > 0) {', replace: 'for (int i = 0; i < data.length - 1; i++) {\n      if (i > 0) {' },
      { describe: 'part (d) counts every element rather than the matches',
        find: '      if (v == target) {\n        count = count + 1;\n      }', replace: '      count = count + 1;' },
    ],
    cases: [
      { stdin: '5\n3 9 4 9 1\n9\n', part: 1, hidden: 0 },
      // Chosen for (c): odd values at even indexes, so summing even VALUES and
      // summing even INDEXES give different answers.
      { stdin: '4\n1 2 3 4\n2\n', part: 3, hidden: 0 },
      // Chosen for (b): a single element, where forwards and backwards agree.
      { stdin: '1\n42\n42\n', part: 2, hidden: 1 },
      // Chosen for (d): no element matches at all.
      { stdin: '3\n5 6 7\n99\n', part: 4, hidden: 1 },
      // Chosen for (b): an even length, where the reverse is fully interleaved.
      { stdin: '6\n10 20 30 40 50 60\n30\n', part: 2, hidden: 1 },
    ],
  },

  // ── 4.5 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.5', unit: U,
    title: 'Algorithms with Arrays',
    name: 'Which One Won',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'This is where the tie breaking rule finally becomes gradeable. Returning the VALUE of the '
      + 'largest element hides whether you kept the first or the last one; returning its INDEX does '
      + 'not. A strict greater-than keeps the earlier index and a greater-or-equal keeps the later one, '
      + 'and the exam always says which it wants.',
    given: 'The driver builds an int array and passes it to your methods. Every array has at least one '
      + 'element. Write a class named Find. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int indexOfMax(int[] data) returns the index of the largest value, and the SMALLEST such index when it appears more than once.' },
      { label: '(b)', text: 'public static int indexOfLastMax(int[] data) returns the LARGEST index at which the largest value appears.' },
      { label: '(c)', text: 'public static int indexOf(int[] data, int target) returns the first index holding target, or -1 when it is absent.' },
      { label: '(d)', text: 'public static boolean isSorted(int[] data) returns whether the values never decrease from left to right.' },
    ],
    task: [
      'Write class Find with the four static methods described. No main method.',
      'Parts (a) and (b) differ ONLY in their tie breaking. One uses a strict comparison and the other does not.',
      'A one element array is sorted, and so is an array whose values are all equal.',
    ],
    starter: [
      'class Find {',
      '  // (a) indexOfMax(int[] data) -> int, first winner on a tie',
      '',
      '  // (b) indexOfLastMax(int[] data) -> int, last winner on a tie',
      '',
      '  // (c) indexOf(int[] data, int target) -> int',
      '',
      '  // (d) isSorted(int[] data) -> boolean',
      '}',
    ].join('\n'),
    reference: [
      'class Find {',
      '  public static int indexOfMax(int[] data) {',
      '    int best = 0;',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] > data[best]) {',
      '        best = i;',
      '      }',
      '    }',
      '    return best;',
      '  }',
      '',
      '  public static int indexOfLastMax(int[] data) {',
      '    int best = 0;',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] >= data[best]) {',
      '        best = i;',
      '      }',
      '    }',
      '    return best;',
      '  }',
      '',
      '  public static int indexOf(int[] data, int target) {',
      '    for (int i = 0; i < data.length; i++) {',
      '      if (data[i] == target) {',
      '        return i;',
      '      }',
      '    }',
      '    return -1;',
      '  }',
      '',
      '  public static boolean isSorted(int[] data) {',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] < data[i - 1]) {',
      '        return false;',
      '      }',
      '    }',
      '    return true;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness(readArray('data').concat([
      '    int target = input.nextInt();',
      '',
      '    System.out.println(Find.indexOfMax(data));',
      '    System.out.println(Find.indexOfLastMax(data));',
      '    System.out.println(Find.indexOf(data, target));',
      '    System.out.println(Find.isSorted(data));',
    ])),
    hints: [
      'Track the INDEX of the best element rather than its value. Comparing data[i] to data[best] keeps both facts in one variable.',
      'A strict > never replaces on a tie, so the earliest winner survives. A >= replaces every time, so the latest one does.',
      'Part (d) compares each element to the one before it. Values that are equal do not break the ordering, so the test is < and not <=.',
    ],
    seo: 'AP CSA 4.5 FRQ practice: return the index of a maximum with a stated tie breaking rule, and search and check sortedness.',
    mutants: [
      { describe: 'part (a) replaces on a tie, so it reports the LAST maximum',
        find: '      if (data[i] > data[best]) {\n        best = i;', replace: '      if (data[i] >= data[best]) {\n        best = i;' },
      { describe: 'part (b) does not replace on a tie, so it reports the FIRST maximum',
        find: '      if (data[i] >= data[best]) {\n        best = i;', replace: '      if (data[i] > data[best]) {\n        best = i;' },
      { describe: 'part (c) returns the LAST match instead of the first',
        find: '      if (data[i] == target) {\n        return i;\n      }\n    }\n    return -1;',
        replace: '      if (data[i] == target) {\n        found = i;\n      }\n    }\n    return found;' },
      { describe: 'part (d) rejects an array with equal neighbours',
        find: 'if (data[i] < data[i - 1]) {', replace: 'if (data[i] <= data[i - 1]) {' },
    ],
    cases: [
      // Chosen for (a) and (b): the maximum appears TWICE, which is the only
      // shape where the two tie breaking rules give different answers.
      { stdin: '5\n3 9 4 9 1\n4\n', part: 1, hidden: 0 },
      // Chosen for (d): a sorted array with a repeated value.
      { stdin: '4\n1 2 2 5\n2\n', part: 4, hidden: 0 },
      // Chosen for (b): every value equal, so the first and last maxima are the
      // two ends of the array.
      { stdin: '4\n7 7 7 7\n7\n', part: 2, hidden: 1 },
      // Chosen for (c): the target is absent.
      { stdin: '3\n1 5 3\n99\n', part: 3, hidden: 1 },
      // Chosen for (c): the target appears twice, so first and last differ.
      { stdin: '5\n2 8 2 8 2\n2\n', part: 3, hidden: 1 },
    ],
  },

  // ── 4.6 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.6', unit: U,
    title: 'Using Text Files',
    name: 'Parsing Lines',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'Reading a file and reading standard input are the same problem once the data is in hand: '
      + 'text arrives as Strings and has to become numbers before it can be added up. "12" + "3" is '
      + '"123", and that is the bug this topic exists to prevent.',
    given: 'The driver reads whitespace separated tokens and passes them to your methods as a String '
      + 'array. Write a class named Lines. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int count(String[] tokens) returns how many tokens there are.' },
      { label: '(b)', text: 'public static int sum(String[] tokens) returns the sum of the tokens read as integers.' },
      { label: '(c)', text: 'public static String join(String[] tokens) returns the tokens separated by commas, with no comma at the start or end.' },
      { label: '(d)', text: 'public static int longest(String[] tokens) returns the length of the longest token, and 0 when there are none.' },
    ],
    task: [
      'Write class Lines with the four static methods described. No main method.',
      'Every token is a valid integer, so Integer.parseInt will not throw.',
      'Part (b) must ADD the numbers. Concatenating the Strings and parsing at the end is a different, much larger number.',
    ],
    starter: [
      'class Lines {',
      '  // (a) count(String[] tokens) -> int',
      '',
      '  // (b) sum(String[] tokens) -> int',
      '',
      '  // (c) join(String[] tokens) -> String',
      '',
      '  // (d) longest(String[] tokens) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Lines {',
      '  public static int count(String[] tokens) {',
      '    return tokens.length;',
      '  }',
      '',
      '  public static int sum(String[] tokens) {',
      '    int total = 0;',
      '    for (String t : tokens) {',
      '      total = total + Integer.parseInt(t);',
      '    }',
      '    return total;',
      '  }',
      '',
      '  public static String join(String[] tokens) {',
      '    String out = "";',
      '    for (int i = 0; i < tokens.length; i++) {',
      '      if (i > 0) {',
      '        out = out + ",";',
      '      }',
      '      out = out + tokens[i];',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static int longest(String[] tokens) {',
      '    int best = 0;',
      '    for (String t : tokens) {',
      '      if (t.length() > best) {',
      '        best = t.length();',
      '      }',
      '    }',
      '    return best;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int n = input.nextInt();',
      '    String[] tokens = new String[n];',
      '    for (int i = 0; i < n; i++) {',
      '      tokens[i] = input.next();',
      '    }',
      '',
      '    System.out.println(Lines.count(tokens));',
      '    System.out.println(Lines.sum(tokens));',
      '    System.out.println(Lines.join(tokens));',
      '    System.out.println(Lines.longest(tokens));',
    ]),
    hints: [
      'Integer.parseInt turns one token into a number. Parse each token as you go and add the numbers, rather than gluing the text together first.',
      'Part (d) can seed at 0 safely, because a length is never negative. That is the one place in this unit where a zero seed is correct.',
      'The comma in part (c) goes between tokens. Adding it after every token leaves one on the end, which the driver compares.',
    ],
    seo: 'AP CSA 4.6 FRQ practice: parse text tokens into integers before summing them, and join them back with separators.',
    mutants: [
      { describe: 'part (b) concatenates the text instead of adding the numbers',
        find: 'total = total + Integer.parseInt(t);', replace: 'total = Integer.parseInt("" + total + t);' },
      { describe: 'part (c) puts a comma before every token, including the first',
        find: '      if (i > 0) {\n        out = out + ",";\n      }\n      out = out + tokens[i];',
        replace: '      out = out + ",";\n      out = out + tokens[i];' },
      { describe: 'part (d) returns the length of the LAST token rather than the longest',
        find: '      if (t.length() > best) {\n        best = t.length();\n      }', replace: '      best = t.length();' },
    ],
    cases: [
      { stdin: '3\n12 3 40\n', part: 2, hidden: 0 },
      // Chosen for (d): the longest token is NOT last, which catches a running
      // best that is simply overwritten every pass.
      { stdin: '3\n1000 5 7\n', part: 4, hidden: 0 },
      // Chosen for (a): a single token.
      { stdin: '1\n9\n', part: 1, hidden: 1 },
      // Chosen for (c): several tokens of equal width, so only the separators differ.
      { stdin: '4\n11 22 33 44\n', part: 3, hidden: 1 },
      // Chosen for (b): negatives, which concatenation cannot reproduce.
      { stdin: '3\n-5 10 -2\n', part: 2, hidden: 1 },
    ],
  },

  // ── 4.7 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.7', unit: U,
    title: 'Wrapper Classes',
    name: 'Integer Is Not int',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'Two Integer objects holding the same number can be different objects, and == compares '
      + 'objects rather than values. Java caches the small ones, so == is true up to 127 and false at '
      + '128, which is the most reliably surprising fact in the whole course. equals is always right.',
    given: 'The driver passes you ints and Integer objects. Write a class named Boxes. Do not write a '
      + 'main method.',
    parts: [
      { label: '(a)', text: 'public static boolean sameValue(Integer a, Integer b) returns whether the two hold the same number, correctly for every value.' },
      { label: '(b)', text: 'public static int unbox(Integer a) returns the int inside.' },
      { label: '(c)', text: 'public static Integer box(int a) returns an Integer holding that value.' },
      { label: '(d)', text: 'public static int sum(Integer a, Integer b) returns the sum of the two values.' },
    ],
    task: [
      'Write class Boxes with the four static methods described. No main method.',
      'Part (a) must be right for large values too. The driver deliberately tests numbers on both sides of the cache boundary.',
      'Autoboxing does parts (b), (c) and (d) for you. The point of the question is part (a).',
    ],
    starter: [
      'class Boxes {',
      '  // (a) sameValue(Integer a, Integer b) -> boolean',
      '',
      '  // (b) unbox(Integer a) -> int',
      '',
      '  // (c) box(int a) -> Integer',
      '',
      '  // (d) sum(Integer a, Integer b) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Boxes {',
      '  public static boolean sameValue(Integer a, Integer b) {',
      '    return a.equals(b);',
      '  }',
      '',
      '  public static int unbox(Integer a) {',
      '    return a;',
      '  }',
      '',
      '  public static Integer box(int a) {',
      '    return a;',
      '  }',
      '',
      '  public static int sum(Integer a, Integer b) {',
      '    return a + b;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int x = input.nextInt();',
      '    int y = input.nextInt();',
      '',
      '    Integer a = Integer.valueOf(x);',
      '    Integer b = Integer.valueOf(y);',
      '    Integer c = new Integer(x);',
      '',
      '    System.out.println(Boxes.sameValue(a, b));',
      '    System.out.println(Boxes.sameValue(a, c));',
      '    System.out.println(Boxes.unbox(a));',
      '    System.out.println(Boxes.box(y));',
      '    System.out.println(Boxes.sum(a, b));',
    ]),
    hints: [
      'a.equals(b) compares the values inside. a == b compares whether they are the same object, which is true for small cached values and false for large ones.',
      'The driver builds one Integer with new, which ALWAYS makes a fresh object. Comparing it with == is false even when the number matches.',
      'Parts (b), (c) and (d) need no conversion code. Java boxes and unboxes automatically wherever the types line up.',
    ],
    seo: 'AP CSA 4.7 FRQ practice: compare Integer objects with equals rather than double equals, correct on both sides of the cache.',
    mutants: [
      { describe: 'part (a) compares Integer objects with == instead of equals',
        find: 'return a.equals(b);', replace: 'return a == b;' },
      { describe: 'part (d) returns the difference rather than the sum',
        find: '  public static int sum(Integer a, Integer b) {\n    return a + b;', replace: '  public static int sum(Integer a, Integer b) {\n    return a - b;' },
    ],
    cases: [
      // Chosen for (a): well inside the Integer cache, where == accidentally works.
      { stdin: '5 5\n', part: 1, hidden: 0 },
      // Chosen for (a): 127 and 128 straddle the cache boundary exactly.
      { stdin: '127 127\n', part: 1, hidden: 0 },
      // Chosen for (a): ABOVE the cache, where == is false and equals is true.
      { stdin: '128 128\n', part: 1, hidden: 1 },
      // Chosen for (d): large distinct values.
      { stdin: '1000 2000\n', part: 4, hidden: 1 },
      // Chosen for (b) and (c): negatives, also outside the cache in one direction.
      { stdin: '-200 -200\n', part: 2, hidden: 1 },
      { stdin: '300 7\n', part: 3, hidden: 1 },
    ],
  },

  // ── 4.8 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.8', unit: U,
    title: 'ArrayList Methods',
    name: 'Add, Set, Remove',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'An ArrayList shifts. add at an index pushes everything right, remove at an index pulls '
      + 'everything left, and set replaces without moving anything. Confusing set with add at the same '
      + 'index changes the size, which is the difference the exam looks for.',
    given: 'The driver builds an ArrayList of Integer and passes it to your methods. Write a class '
      + 'named Editor. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int size(ArrayList<Integer> list) returns how many elements it holds.' },
      { label: '(b)', text: 'public static void appendTwice(ArrayList<Integer> list, int value) adds value to the END of the list twice.' },
      { label: '(c)', text: 'public static void replaceFirst(ArrayList<Integer> list, int value) replaces the element at index 0 without changing the size. Do nothing when the list is empty.' },
      { label: '(d)', text: 'public static int removeLast(ArrayList<Integer> list) removes and returns the last element, or returns -1 and changes nothing when the list is empty.' },
    ],
    task: [
      'Write class Editor with the four static methods described. No main method.',
      'These methods change the list they are GIVEN. An ArrayList is an object, so the caller sees the change.',
      'Part (c) uses set and not add. add at index 0 pushes the old element aside and makes the list longer.',
    ],
    starter: [
      'import java.util.ArrayList;',
      '',
      'class Editor {',
      '  // (a) size(ArrayList<Integer> list) -> int',
      '',
      '  // (b) appendTwice(ArrayList<Integer> list, int value)',
      '',
      '  // (c) replaceFirst(ArrayList<Integer> list, int value)',
      '',
      '  // (d) removeLast(ArrayList<Integer> list) -> int',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.ArrayList;',
      '',
      'class Editor {',
      '  public static int size(ArrayList<Integer> list) {',
      '    return list.size();',
      '  }',
      '',
      '  public static void appendTwice(ArrayList<Integer> list, int value) {',
      '    list.add(value);',
      '    list.add(value);',
      '  }',
      '',
      '  public static void replaceFirst(ArrayList<Integer> list, int value) {',
      '    if (list.size() > 0) {',
      '      list.set(0, value);',
      '    }',
      '  }',
      '',
      '  public static int removeLast(ArrayList<Integer> list) {',
      '    if (list.size() == 0) {',
      '      return -1;',
      '    }',
      '    return list.remove(list.size() - 1);',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int n = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < n; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '    int value = input.nextInt();',
      '',
      '    System.out.println(Editor.size(list));',
      '    Editor.replaceFirst(list, value);',
      '    System.out.println(list);',
      '    Editor.appendTwice(list, value);',
      '    System.out.println(list);',
      '    System.out.println(Editor.removeLast(list));',
      '    System.out.println(list);',
    ]),
    hints: [
      'set(0, value) replaces. add(0, value) inserts. The driver prints the whole list right after, so a size that grew by one is immediately visible.',
      'remove(index) returns the element it removed, so part (d) needs no separate get.',
      'The last index is size() - 1. Using size() throws IndexOutOfBoundsException.',
    ],
    seo: 'AP CSA 4.8 FRQ practice: use ArrayList add, set and remove correctly, including the empty list and the last index.',
    mutants: [
      { describe: 'part (c) inserts at index 0 instead of replacing, growing the list',
        find: 'list.set(0, value);', replace: 'list.add(0, value);' },
      { describe: 'part (d) removes at size() rather than size() - 1',
        find: 'return list.remove(list.size() - 1);', replace: 'return list.remove(list.size());' },
      { describe: 'part (b) adds the value only once',
        find: '    list.add(value);\n    list.add(value);', replace: '    list.add(value);' },
      { describe: 'part (c) forgets to guard the empty list',
        find: '    if (list.size() > 0) {\n      list.set(0, value);\n    }', replace: '    list.set(0, value);' },
    ],
    cases: [
      { stdin: '3\n1 2 3\n99\n', part: 3, hidden: 0 },
      // Chosen for (c) and (d): an EMPTY list, where both guards are the only
      // thing between a correct answer and an exception.
      { stdin: '0\n7\n', part: 4, hidden: 0 },
      // Chosen for (a): a single element, so removing the last empties the list.
      { stdin: '1\n5\n8\n', part: 1, hidden: 1 },
      // Chosen for (b): the appended value already appears in the list.
      { stdin: '2\n4 4\n4\n', part: 2, hidden: 1 },
      { stdin: '5\n10 20 30 40 50\n0\n', part: 2, hidden: 1 },
    ],
  },

  // ── 4.9 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.9', unit: U,
    title: 'Traversing ArrayLists',
    name: 'Removing While Looping',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'Removing from a list while walking it forward skips the element that slides into the gap. '
      + 'It is not a crash and not an exception; it is a quietly wrong answer that only shows when two '
      + 'removable elements sit next to each other. Every hidden case here has exactly that.',
    given: 'The driver builds an ArrayList of Integer and passes it to your methods. Write a class '
      + 'named Prune. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int sum(ArrayList<Integer> list) returns the total of every element.' },
      { label: '(b)', text: 'public static int countAbove(ArrayList<Integer> list, int threshold) returns how many elements are strictly greater than threshold.' },
      { label: '(c)', text: 'public static void removeAllEqual(ArrayList<Integer> list, int target) removes EVERY element equal to target.' },
      { label: '(d)', text: 'public static int firstIndexAbove(ArrayList<Integer> list, int threshold) returns the first index holding a value above threshold, or -1.' },
    ],
    task: [
      'Write class Prune with the four static methods described. No main method.',
      'Part (c) must remove every match, including two that are adjacent. Walking backwards, or not advancing after a removal, both work.',
      'Part (d) stops at the first match.',
    ],
    starter: [
      'import java.util.ArrayList;',
      '',
      'class Prune {',
      '  // (a) sum(ArrayList<Integer> list) -> int',
      '',
      '  // (b) countAbove(ArrayList<Integer> list, int threshold) -> int',
      '',
      '  // (c) removeAllEqual(ArrayList<Integer> list, int target)',
      '',
      '  // (d) firstIndexAbove(ArrayList<Integer> list, int threshold) -> int',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.ArrayList;',
      '',
      'class Prune {',
      '  public static int sum(ArrayList<Integer> list) {',
      '    int total = 0;',
      '    for (int v : list) {',
      '      total = total + v;',
      '    }',
      '    return total;',
      '  }',
      '',
      '  public static int countAbove(ArrayList<Integer> list, int threshold) {',
      '    int count = 0;',
      '    for (int v : list) {',
      '      if (v > threshold) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '',
      '  public static void removeAllEqual(ArrayList<Integer> list, int target) {',
      '    for (int i = list.size() - 1; i >= 0; i--) {',
      '      if (list.get(i) == target) {',
      '        list.remove(i);',
      '      }',
      '    }',
      '  }',
      '',
      '  public static int firstIndexAbove(ArrayList<Integer> list, int threshold) {',
      '    for (int i = 0; i < list.size(); i++) {',
      '      if (list.get(i) > threshold) {',
      '        return i;',
      '      }',
      '    }',
      '    return -1;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int n = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < n; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '    int threshold = input.nextInt();',
      '    int target = input.nextInt();',
      '',
      '    System.out.println(Prune.sum(list));',
      '    System.out.println(Prune.countAbove(list, threshold));',
      '    System.out.println(Prune.firstIndexAbove(list, threshold));',
      '    Prune.removeAllEqual(list, target);',
      '    System.out.println(list);',
    ]),
    hints: [
      'Walking backwards is the simplest fix: removing an element only shifts the ones AFTER it, and you have already passed those.',
      'Going forwards, the fix is to not increment the index after a removal, because a new element has just slid into that position.',
      'Two adjacent matches are what expose the bug. One match on its own is removed correctly by both the right and the wrong loop.',
    ],
    seo: 'AP CSA 4.9 FRQ practice: remove every matching element from an ArrayList without skipping the one that slides into the gap.',
    mutants: [
      { describe: 'part (c) walks forward and skips the element that slides into the gap',
        find: '    for (int i = list.size() - 1; i >= 0; i--) {\n      if (list.get(i) == target) {\n        list.remove(i);\n      }\n    }',
        replace: '    for (int i = 0; i < list.size(); i++) {\n      if (list.get(i) == target) {\n        list.remove(i);\n      }\n    }' },
      { describe: 'part (b) counts values equal to the threshold as above it',
        find: '      if (v > threshold) {\n        count = count + 1;', replace: '      if (v >= threshold) {\n        count = count + 1;' },
      { describe: 'part (d) returns the last index above the threshold rather than the first',
        find: '      if (list.get(i) > threshold) {\n        return i;\n      }\n    }\n    return -1;',
        replace: '      if (list.get(i) > threshold) {\n        found = i;\n      }\n    }\n    return found;' },
    ],
    cases: [
      // The threshold EQUALS two of the values, which is the only shape where
      // > and >= disagree. Without it part (b)'s boundary cannot be scored.
      { stdin: '5\n1 5 2 5 9\n5\n5\n', part: 2, hidden: 0 },
      // Chosen for (d): nothing clears the threshold, so the answer is -1.
      { stdin: '3\n1 2 3\n99\n2\n', part: 4, hidden: 0 },
      // Chosen for (c): TWO ADJACENT matches, the shape a forward loop skips.
      { stdin: '5\n1 7 7 2 3\n5\n7\n', part: 3, hidden: 1 },
      // Chosen for (c): three in a row, and at the very end of the list.
      { stdin: '5\n4 9 9 9 1\n8\n9\n', part: 3, hidden: 1 },
      // Chosen for (a): every element matches, so the list ends up empty.
      { stdin: '3\n6 6 6\n5\n6\n', part: 1, hidden: 1 },
    ],
  },

  // ── 4.10 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.10', unit: U,
    title: 'Algorithms with ArrayLists',
    name: 'Build a New List',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'Filtering into a NEW list is safer than editing in place and is what most free response '
      + 'questions ask for. The trap is returning the list you were given, or building the new one but '
      + 'never returning it, both of which look finished on the page.',
    given: 'The driver builds an ArrayList of Integer and passes it to your methods. Write a class '
      + 'named Build. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static ArrayList<Integer> above(ArrayList<Integer> list, int threshold) returns a NEW list of the elements strictly greater than threshold, in their original order.' },
      { label: '(b)', text: 'public static ArrayList<Integer> doubled(ArrayList<Integer> list) returns a NEW list with every element multiplied by 2, leaving the original alone.' },
      { label: '(c)', text: 'public static ArrayList<Integer> reversed(ArrayList<Integer> list) returns a NEW list in the opposite order.' },
      { label: '(d)', text: 'public static int countDistinctValues(ArrayList<Integer> list) returns how many different values appear.' },
    ],
    task: [
      'Write class Build with the four static methods described. No main method.',
      'The original list must be unchanged after every one of these calls. The driver prints it again at the end to check.',
      'Part (d) counts VALUES, so a list of 4, 4, 7 has two distinct values.',
    ],
    starter: [
      'import java.util.ArrayList;',
      '',
      'class Build {',
      '  // (a) above(ArrayList<Integer> list, int threshold) -> ArrayList<Integer>',
      '',
      '  // (b) doubled(ArrayList<Integer> list) -> ArrayList<Integer>',
      '',
      '  // (c) reversed(ArrayList<Integer> list) -> ArrayList<Integer>',
      '',
      '  // (d) countDistinctValues(ArrayList<Integer> list) -> int',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.ArrayList;',
      '',
      'class Build {',
      '  public static ArrayList<Integer> above(ArrayList<Integer> list, int threshold) {',
      '    ArrayList<Integer> out = new ArrayList<Integer>();',
      '    for (int v : list) {',
      '      if (v > threshold) {',
      '        out.add(v);',
      '      }',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static ArrayList<Integer> doubled(ArrayList<Integer> list) {',
      '    ArrayList<Integer> out = new ArrayList<Integer>();',
      '    for (int v : list) {',
      '      out.add(v * 2);',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static ArrayList<Integer> reversed(ArrayList<Integer> list) {',
      '    ArrayList<Integer> out = new ArrayList<Integer>();',
      '    for (int i = list.size() - 1; i >= 0; i--) {',
      '      out.add(list.get(i));',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static int countDistinctValues(ArrayList<Integer> list) {',
      '    ArrayList<Integer> seen = new ArrayList<Integer>();',
      '    for (int v : list) {',
      '      if (!seen.contains(v)) {',
      '        seen.add(v);',
      '      }',
      '    }',
      '    return seen.size();',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int n = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < n; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '    int threshold = input.nextInt();',
      '',
      '    System.out.println(Build.above(list, threshold));',
      '    System.out.println(Build.doubled(list));',
      '    System.out.println(Build.reversed(list));',
      '    System.out.println(Build.countDistinctValues(list));',
      '    System.out.println(list);',
    ]),
    hints: [
      'Start each method with a brand new ArrayList and add into that. Returning the parameter hands back the caller\'s own list.',
      'The driver prints the ORIGINAL list last. If any of your methods edited it in place, that final line is wrong even when the earlier ones looked right.',
      'contains asks whether a value is already in a list, which is all part (d) needs.',
    ],
    seo: 'AP CSA 4.10 FRQ practice: filter, map and reverse an ArrayList into new lists while leaving the original untouched.',
    mutants: [
      { describe: 'part (b) doubles the original list in place and returns it',
        find: '    ArrayList<Integer> out = new ArrayList<Integer>();\n    for (int v : list) {\n      out.add(v * 2);\n    }\n    return out;',
        replace: '    for (int i = 0; i < list.size(); i++) {\n      list.set(i, list.get(i) * 2);\n    }\n    return list;' },
      { describe: 'part (a) keeps the values at or below the threshold instead',
        find: '      if (v > threshold) {\n        out.add(v);', replace: '      if (v <= threshold) {\n        out.add(v);' },
      { describe: 'part (d) counts every element rather than the distinct values',
        find: '      if (!seen.contains(v)) {\n        seen.add(v);\n      }', replace: '      seen.add(v);' },
      { describe: 'part (c) copies in the original order',
        find: 'for (int i = list.size() - 1; i >= 0; i--) {\n      out.add(list.get(i));', replace: 'for (int i = 0; i < list.size(); i++) {\n      out.add(list.get(i));' },
    ],
    cases: [
      { stdin: '5\n3 8 3 1 9\n4\n', part: 1, hidden: 0 },
      // Chosen for (d): every value distinct, so distinct count equals the size.
      { stdin: '4\n1 2 3 4\n2\n', part: 4, hidden: 0 },
      // Chosen for (d): every value the same, so the distinct count is 1.
      { stdin: '4\n5 5 5 5\n0\n', part: 4, hidden: 1 },
      // Chosen for (b): a value of 0, which doubles to itself.
      { stdin: '3\n0 -4 6\n-1\n', part: 2, hidden: 1 },
      // Chosen for (c): a single element, where the reverse equals the original.
      { stdin: '1\n11\n100\n', part: 3, hidden: 1 },
    ],
  },

  // ── 4.11 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.11', unit: U,
    title: '2D Array Creation and Access',
    name: 'Row Then Column',
    mode: 'driver',
    frqType: 'two-d-array',
    brief: 'grid[r][c] is row first and column second, and every grid in this question is deliberately '
      + 'NOT square. On a 3 by 3 grid a swapped pair of indexes quietly transposes the answer and every '
      + 'test still passes; on a 2 by 4 grid it throws immediately. That is the entire reason these '
      + 'dimensions are what they are.',
    given: 'The driver builds a rectangular 2D int array and passes it to your methods. Write a class '
      + 'named Cells. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int rows(int[][] grid) returns how many rows there are.' },
      { label: '(b)', text: 'public static int cols(int[][] grid) returns how many columns each row has. Assume at least one row.' },
      { label: '(c)', text: 'public static int at(int[][] grid, int r, int c) returns the value at row r and column c.' },
      { label: '(d)', text: 'public static int corners(int[][] grid) returns the sum of the four corner values.' },
    ],
    task: [
      'Write class Cells with the four static methods described. No main method.',
      'grid.length is the number of ROWS. grid[0].length is the number of COLUMNS.',
      'A grid with one row or one column still has four corners; some of them are the same cell.',
    ],
    starter: [
      'class Cells {',
      '  // (a) rows(int[][] grid) -> int',
      '',
      '  // (b) cols(int[][] grid) -> int',
      '',
      '  // (c) at(int[][] grid, int r, int c) -> int',
      '',
      '  // (d) corners(int[][] grid) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Cells {',
      '  public static int rows(int[][] grid) {',
      '    return grid.length;',
      '  }',
      '',
      '  public static int cols(int[][] grid) {',
      '    return grid[0].length;',
      '  }',
      '',
      '  public static int at(int[][] grid, int r, int c) {',
      '    return grid[r][c];',
      '  }',
      '',
      '  public static int corners(int[][] grid) {',
      '    int lastRow = grid.length - 1;',
      '    int lastCol = grid[0].length - 1;',
      '    return grid[0][0] + grid[0][lastCol] + grid[lastRow][0] + grid[lastRow][lastCol];',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int r = input.nextInt();',
      '    int c = input.nextInt();',
      '    int[][] grid = new int[r][c];',
      '    for (int i = 0; i < r; i++) {',
      '      for (int j = 0; j < c; j++) {',
      '        grid[i][j] = input.nextInt();',
      '      }',
      '    }',
      '    int pr = input.nextInt();',
      '    int pc = input.nextInt();',
      '',
      '    System.out.println(Cells.rows(grid));',
      '    System.out.println(Cells.cols(grid));',
      '    System.out.println(Cells.at(grid, pr, pc));',
      '    System.out.println(Cells.corners(grid));',
    ]),
    hints: [
      'grid.length counts the rows because a 2D array is an array OF rows. Each row is itself an array, so grid[0].length counts the columns.',
      'Swapping r and c in part (c) throws on a non square grid rather than returning the wrong number, which is a kinder failure than it looks.',
      'On a grid with a single row, the top and bottom corners are the same two cells, so two values get counted twice. That is what the question asks for.',
    ],
    seo: 'AP CSA 4.11 FRQ practice: index a 2D array row first and column second on deliberately non square grids.',
    mutants: [
      { describe: 'part (a) and part (b) are swapped, invisible on a square grid',
        find: '  public static int rows(int[][] grid) {\n    return grid.length;\n  }\n\n  public static int cols(int[][] grid) {\n    return grid[0].length;\n  }',
        replace: '  public static int rows(int[][] grid) {\n    return grid[0].length;\n  }\n\n  public static int cols(int[][] grid) {\n    return grid.length;\n  }' },
      { describe: 'part (c) indexes column first and row second',
        find: 'return grid[r][c];', replace: 'return grid[c][r];' },
      { describe: 'part (d) uses the row count as a column index',
        find: 'int lastCol = grid[0].length - 1;', replace: 'int lastCol = grid.length - 1;' },
    ],
    cases: [
      // Every grid here is non square, on purpose.
      { stdin: '2 4\n1 2 3 4\n5 6 7 8\n1 2\n', part: 1, hidden: 0 },
      { stdin: '3 2\n1 2\n3 4\n5 6\n2 1\n', part: 2, hidden: 0 },
      // Chosen for (d): a single row, where two corners coincide.
      { stdin: '1 4\n9 8 7 6\n0 3\n', part: 4, hidden: 1 },
      // Chosen for (c): a single column.
      { stdin: '4 1\n2\n4\n6\n8\n3 0\n', part: 3, hidden: 1 },
      { stdin: '2 5\n1 1 1 1 1\n2 2 2 2 2\n1 4\n', part: 4, hidden: 1 },
    ],
  },

  // ── 4.12 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.12', unit: U,
    title: 'Traversing 2D Arrays',
    name: 'Row Major and Column Major',
    mode: 'driver',
    frqType: 'two-d-array',
    brief: 'Row major walks each row left to right; column major walks each column top to bottom. They '
      + 'visit the same cells in a different ORDER, and on a non square grid swapping the loop bounds '
      + 'is not merely a different order but an immediate crash.',
    given: 'The driver builds a rectangular 2D int array and passes it to your methods. Write a class '
      + 'named Walk. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static String rowMajor(int[][] grid) returns every value in row major order, separated by single spaces.' },
      { label: '(b)', text: 'public static String columnMajor(int[][] grid) returns every value in column major order, separated by single spaces.' },
      { label: '(c)', text: 'public static int rowSum(int[][] grid, int r) returns the sum of row r.' },
      { label: '(d)', text: 'public static int colSum(int[][] grid, int c) returns the sum of column c.' },
    ],
    task: [
      'Write class Walk with the four static methods described. No main method.',
      'Part (b) needs the column loop on the OUTSIDE and must still bound each index by its own dimension.',
      'Separate the values with single spaces and do not start with one.',
    ],
    starter: [
      'class Walk {',
      '  // (a) rowMajor(int[][] grid) -> String',
      '',
      '  // (b) columnMajor(int[][] grid) -> String',
      '',
      '  // (c) rowSum(int[][] grid, int r) -> int',
      '',
      '  // (d) colSum(int[][] grid, int c) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Walk {',
      '  public static String rowMajor(int[][] grid) {',
      '    String out = "";',
      '    for (int r = 0; r < grid.length; r++) {',
      '      for (int c = 0; c < grid[0].length; c++) {',
      '        if (out.length() > 0) {',
      '          out = out + " ";',
      '        }',
      '        out = out + grid[r][c];',
      '      }',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static String columnMajor(int[][] grid) {',
      '    String out = "";',
      '    for (int c = 0; c < grid[0].length; c++) {',
      '      for (int r = 0; r < grid.length; r++) {',
      '        if (out.length() > 0) {',
      '          out = out + " ";',
      '        }',
      '        out = out + grid[r][c];',
      '      }',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static int rowSum(int[][] grid, int r) {',
      '    int sum = 0;',
      '    for (int c = 0; c < grid[0].length; c++) {',
      '      sum = sum + grid[r][c];',
      '    }',
      '    return sum;',
      '  }',
      '',
      '  public static int colSum(int[][] grid, int c) {',
      '    int sum = 0;',
      '    for (int r = 0; r < grid.length; r++) {',
      '      sum = sum + grid[r][c];',
      '    }',
      '    return sum;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int i = 0; i < rows; i++) {',
      '      for (int j = 0; j < cols; j++) {',
      '        grid[i][j] = input.nextInt();',
      '      }',
      '    }',
      '    int pr = input.nextInt();',
      '    int pc = input.nextInt();',
      '',
      '    System.out.println(Walk.rowMajor(grid));',
      '    System.out.println(Walk.columnMajor(grid));',
      '    System.out.println(Walk.rowSum(grid, pr));',
      '    System.out.println(Walk.colSum(grid, pc));',
    ]),
    hints: [
      'The outer loop decides the order. Row major has rows outside; column major has columns outside. The index bounds do not swap with them.',
      'A row sum walks the columns and a column sum walks the rows. That is easy to write backwards, and on a non square grid it throws rather than answering wrongly.',
      'Both traversals visit every cell exactly once, so the two Strings contain the same numbers in a different order. If yours do not, one of them has a bound wrong.',
    ],
    seo: 'AP CSA 4.12 FRQ practice: traverse a 2D array in row major and column major order and sum a single row and column.',
    mutants: [
      { describe: 'part (b) is written the same as row major, so the order never changes',
        find: '    for (int c = 0; c < grid[0].length; c++) {\n      for (int r = 0; r < grid.length; r++) {\n        if (out.length() > 0) {',
        replace: '    for (int r = 0; r < grid.length; r++) {\n      for (int c = 0; c < grid[0].length; c++) {\n        if (out.length() > 0) {' },
      { describe: 'part (c) sums a column instead of a row',
        find: '  public static int rowSum(int[][] grid, int r) {\n    int sum = 0;\n    for (int c = 0; c < grid[0].length; c++) {\n      sum = sum + grid[r][c];',
        replace: '  public static int rowSum(int[][] grid, int r) {\n    int sum = 0;\n    for (int c = 0; c < grid[0].length; c++) {\n      sum = sum + grid[c][r];' },
      { describe: 'part (d) stops one row short',
        find: '  public static int colSum(int[][] grid, int c) {\n    int sum = 0;\n    for (int r = 0; r < grid.length; r++) {',
        replace: '  public static int colSum(int[][] grid, int c) {\n    int sum = 0;\n    for (int r = 0; r < grid.length - 1; r++) {' },
    ],
    cases: [
      { stdin: '2 3\n1 2 3\n4 5 6\n1 2\n', part: 1, hidden: 0 },
      { stdin: '3 2\n1 2\n3 4\n5 6\n2 0\n', part: 2, hidden: 0 },
      // Chosen for (d): a tall thin grid, so a column sum that stops early is
      // wrong by a whole row.
      { stdin: '4 2\n1 1\n2 2\n3 3\n4 4\n0 1\n', part: 4, hidden: 1 },
      // Chosen for (c): a single row.
      { stdin: '1 5\n5 4 3 2 1\n0 4\n', part: 3, hidden: 1 },
      { stdin: '2 4\n10 20 30 40\n1 2 3 4\n1 3\n', part: 2, hidden: 1 },
    ],
  },

  // ── 4.13 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.13', unit: U,
    title: 'Implementing 2D Array Algorithms',
    name: 'Finding in a Grid',
    mode: 'driver',
    frqType: 'two-d-array',
    brief: 'Searching a grid means returning WHERE something is, and a position is two numbers. This '
      + 'question asks for the row and the column separately so that a transposed answer is visibly '
      + 'wrong rather than accidentally right.',
    given: 'The driver builds a rectangular 2D int array and passes it to your methods. Write a class '
      + 'named Search2D. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int maxValue(int[][] grid) returns the largest value anywhere in the grid.' },
      { label: '(b)', text: 'public static int rowOfMax(int[][] grid) returns the row index of the largest value, choosing the earliest in row major order on a tie.' },
      { label: '(c)', text: 'public static int colOfMax(int[][] grid) returns the column index of that same cell.' },
      { label: '(d)', text: 'public static int countEqual(int[][] grid, int target) returns how many cells hold target.' },
    ],
    task: [
      'Write class Search2D with the four static methods described. No main method.',
      'Seed the search with the cell at row 0 column 0, never with 0.',
      'Parts (b) and (c) must describe the SAME cell. Searching twice invites them to disagree on a tie.',
    ],
    starter: [
      'class Search2D {',
      '  // (a) maxValue(int[][] grid) -> int',
      '',
      '  // (b) rowOfMax(int[][] grid) -> int',
      '',
      '  // (c) colOfMax(int[][] grid) -> int',
      '',
      '  // (d) countEqual(int[][] grid, int target) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Search2D {',
      '  public static int maxValue(int[][] grid) {',
      '    return grid[rowOfMax(grid)][colOfMax(grid)];',
      '  }',
      '',
      '  public static int rowOfMax(int[][] grid) {',
      '    int bestRow = 0;',
      '    int bestCol = 0;',
      '    for (int r = 0; r < grid.length; r++) {',
      '      for (int c = 0; c < grid[0].length; c++) {',
      '        if (grid[r][c] > grid[bestRow][bestCol]) {',
      '          bestRow = r;',
      '          bestCol = c;',
      '        }',
      '      }',
      '    }',
      '    return bestRow;',
      '  }',
      '',
      '  public static int colOfMax(int[][] grid) {',
      '    int bestRow = 0;',
      '    int bestCol = 0;',
      '    for (int r = 0; r < grid.length; r++) {',
      '      for (int c = 0; c < grid[0].length; c++) {',
      '        if (grid[r][c] > grid[bestRow][bestCol]) {',
      '          bestRow = r;',
      '          bestCol = c;',
      '        }',
      '      }',
      '    }',
      '    return bestCol;',
      '  }',
      '',
      '  public static int countEqual(int[][] grid, int target) {',
      '    int count = 0;',
      '    for (int r = 0; r < grid.length; r++) {',
      '      for (int c = 0; c < grid[0].length; c++) {',
      '        if (grid[r][c] == target) {',
      '          count = count + 1;',
      '        }',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int i = 0; i < rows; i++) {',
      '      for (int j = 0; j < cols; j++) {',
      '        grid[i][j] = input.nextInt();',
      '      }',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    System.out.println(Search2D.maxValue(grid));',
      '    System.out.println(Search2D.rowOfMax(grid));',
      '    System.out.println(Search2D.colOfMax(grid));',
      '    System.out.println(Search2D.countEqual(grid, target));',
    ]),
    hints: [
      'Track the best POSITION rather than the best value, then read the value back out of the grid. That keeps parts (a), (b) and (c) describing one cell.',
      'A strict greater-than keeps the first cell found in row major order, which is what the tie breaking rule asks for.',
      'Seeding at grid[0][0] rather than 0 matters here for the same reason it did in 4.2: the grid may be entirely negative.',
    ],
    seo: 'AP CSA 4.13 FRQ practice: find the position of the largest value in a 2D array with a stated tie breaking rule.',
    mutants: [
      { describe: 'the search replaces on a tie, so it reports a later cell than the rule asks for',
        find: '  public static int rowOfMax(int[][] grid) {\n    int bestRow = 0;\n    int bestCol = 0;\n    for (int r = 0; r < grid.length; r++) {\n      for (int c = 0; c < grid[0].length; c++) {\n        if (grid[r][c] > grid[bestRow][bestCol]) {',
        replace: '  public static int rowOfMax(int[][] grid) {\n    int bestRow = 0;\n    int bestCol = 0;\n    for (int r = 0; r < grid.length; r++) {\n      for (int c = 0; c < grid[0].length; c++) {\n        if (grid[r][c] >= grid[bestRow][bestCol]) {' },
      { describe: 'part (c) returns the row rather than the column',
        find: '    return bestCol;\n  }', replace: '    return bestRow;\n  }' },
      { describe: 'part (d) misses the last column of every row',
        find: '        if (grid[r][c] == target) {\n          count = count + 1;',
        replace: '        if (c < grid[0].length - 1 && grid[r][c] == target) {\n          count = count + 1;' },
    ],
    cases: [
      { stdin: '2 3\n1 9 3\n4 5 6\n9\n', part: 2, hidden: 0 },
      // Chosen for (b) and (c): the maximum appears TWICE, so the tie rule decides.
      { stdin: '2 4\n7 2 7 1\n3 4 5 6\n7\n', part: 3, hidden: 0 },
      // Chosen for (a): every value negative, so a zero seed reports a maximum
      // that is not in the grid.
      { stdin: '2 3\n-9 -4 -7\n-2 -8 -5\n-4\n', part: 1, hidden: 1 },
      // Chosen for (d): the target sits in the LAST column, which a loop that
      // stops early never sees.
      { stdin: '3 2\n1 8\n2 8\n3 8\n8\n', part: 4, hidden: 1 },
      { stdin: '1 3\n5 5 5\n5\n', part: 4, hidden: 1 },
    ],
  },

  // ── 4.14 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.14', unit: U,
    title: 'Searching Algorithms',
    name: 'Linear and Binary',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'Binary search halves the range each pass, and every bug in it is a bound that fails to '
      + 'shrink. This question asks for the number of comparisons alongside the answer, so a search '
      + 'that finds the right element by doing linear work is visibly not a binary search.',
    given: 'The driver builds a SORTED int array and passes it to your methods. Write a class named '
      + 'Searcher. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int linear(int[] data, int target) returns the first index holding target, or -1.' },
      { label: '(b)', text: 'public static int binary(int[] data, int target) returns AN index holding target, or -1. The array is sorted.' },
      { label: '(c)', text: 'public static int binarySteps(int[] data, int target) returns how many times the loop body of your binary search runs.' },
      { label: '(d)', text: 'public static boolean contains(int[] data, int target) returns whether target is present.' },
    ],
    task: [
      'Write class Searcher with the four static methods described. No main method.',
      'A binary search keeps a low and a high index and moves one of them PAST the midpoint every pass. Setting low = mid rather than mid + 1 never terminates.',
      'Part (c) counts the passes of the same loop, so it must have the same shape as part (b).',
    ],
    starter: [
      'class Searcher {',
      '  // (a) linear(int[] data, int target) -> int',
      '',
      '  // (b) binary(int[] data, int target) -> int',
      '',
      '  // (c) binarySteps(int[] data, int target) -> int',
      '',
      '  // (d) contains(int[] data, int target) -> boolean',
      '}',
    ].join('\n'),
    reference: [
      'class Searcher {',
      '  public static int linear(int[] data, int target) {',
      '    for (int i = 0; i < data.length; i++) {',
      '      if (data[i] == target) {',
      '        return i;',
      '      }',
      '    }',
      '    return -1;',
      '  }',
      '',
      '  public static int binary(int[] data, int target) {',
      '    int low = 0;',
      '    int high = data.length - 1;',
      '    while (low <= high) {',
      '      int mid = (low + high) / 2;',
      '      if (data[mid] == target) {',
      '        return mid;',
      '      }',
      '      if (data[mid] < target) {',
      '        low = mid + 1;',
      '      } else {',
      '        high = mid - 1;',
      '      }',
      '    }',
      '    return -1;',
      '  }',
      '',
      '  public static int binarySteps(int[] data, int target) {',
      '    int low = 0;',
      '    int high = data.length - 1;',
      '    int steps = 0;',
      '    while (low <= high) {',
      '      steps = steps + 1;',
      '      int mid = (low + high) / 2;',
      '      if (data[mid] == target) {',
      '        return steps;',
      '      }',
      '      if (data[mid] < target) {',
      '        low = mid + 1;',
      '      } else {',
      '        high = mid - 1;',
      '      }',
      '    }',
      '    return steps;',
      '  }',
      '',
      '  public static boolean contains(int[] data, int target) {',
      '    return binary(data, target) >= 0;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness(readArray('data').concat([
      '    int target = input.nextInt();',
      '',
      '    System.out.println(Searcher.linear(data, target));',
      '    System.out.println(Searcher.binary(data, target) >= 0);',
      '    System.out.println(Searcher.binarySteps(data, target));',
      '    System.out.println(Searcher.contains(data, target));',
    ])),
    hints: [
      'The driver prints whether the binary search FOUND the target rather than which index it landed on, because with repeated values a correct binary search may legitimately return any of them.',
      'The step count is what separates a real binary search from a loop wearing its name. On sixteen sorted elements a binary search never needs more than five passes.',
      'Move low to mid + 1 and high to mid - 1. Using mid itself leaves the range the same size and the loop never ends.',
    ],
    seo: 'AP CSA 4.14 FRQ practice: implement linear and binary search and count the passes to prove the halving actually happens.',
    mutants: [
      { describe: 'the binary search never checks the last remaining element',
        find: '    while (low <= high) {\n      int mid = (low + high) / 2;\n      if (data[mid] == target) {\n        return mid;',
        replace: '    while (low < high) {\n      int mid = (low + high) / 2;\n      if (data[mid] == target) {\n        return mid;' },
      { describe: 'the binary search moves the wrong bound, so it searches the wrong half',
        find: '      if (data[mid] < target) {\n        low = mid + 1;\n      } else {\n        high = mid - 1;\n      }\n    }\n    return -1;',
        replace: '      if (data[mid] < target) {\n        high = mid - 1;\n      } else {\n        low = mid + 1;\n      }\n    }\n    return -1;' },
      { describe: 'part (a) returns the last match rather than the first',
        find: '      if (data[i] == target) {\n        return i;\n      }\n    }\n    return -1;',
        replace: '      if (data[i] == target) {\n        found = i;\n      }\n    }\n    return found;' },
      { describe: 'part (d) treats a -1 result as found',
        find: 'return binary(data, target) >= 0;', replace: 'return binary(data, target) >= -1;' },
    ],
    cases: [
      { stdin: '7\n1 3 5 7 9 11 13\n9\n', part: 2, hidden: 0 },
      // Chosen for (c): the target is at the very END, which is where a
      // while (low < high) bound stops looking.
      { stdin: '8\n2 4 6 8 10 12 14 16\n16\n', part: 3, hidden: 0 },
      // Chosen for (d): the target is absent, so the search must exhaust.
      { stdin: '5\n1 2 3 4 5\n99\n', part: 4, hidden: 1 },
      // Chosen for (a): the target appears twice, so first and last differ.
      { stdin: '6\n1 4 4 7 9 11\n4\n', part: 1, hidden: 1 },
      // Chosen for (c): a single element.
      { stdin: '1\n5\n5\n', part: 3, hidden: 1 },
    ],
  },

  // ── 4.15 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.15', unit: U,
    title: 'Sorting Algorithms',
    name: 'Selection and Insertion',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'A swap needs a temporary. Writing a = b; b = a; loses one of the values before the second '
      + 'line runs, and the array ends up with a duplicate rather than a swap. That is the same bug as '
      + 'the one in 2.1, now inside a sort where it is much harder to see.',
    given: 'The driver builds an int array and passes it to your methods. Write a class named Sorter. '
      + 'Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static void swap(int[] data, int i, int j) exchanges the two elements.' },
      { label: '(b)', text: 'public static int indexOfMinFrom(int[] data, int start) returns the index of the smallest element at or after start.' },
      { label: '(c)', text: 'public static void selectionSort(int[] data) sorts the array ascending, using parts (a) and (b).' },
      { label: '(d)', text: 'public static String show(int[] data) returns the elements separated by single spaces.' },
    ],
    task: [
      'Write class Sorter with the four static methods described. No main method.',
      'Part (a) needs a temporary variable. Without one the two elements both end up holding the same value.',
      'The array is sorted IN PLACE, so the caller sees the change.',
    ],
    starter: [
      'class Sorter {',
      '  // (a) swap(int[] data, int i, int j)',
      '',
      '  // (b) indexOfMinFrom(int[] data, int start) -> int',
      '',
      '  // (c) selectionSort(int[] data)',
      '',
      '  // (d) show(int[] data) -> String',
      '}',
    ].join('\n'),
    reference: [
      'class Sorter {',
      '  public static void swap(int[] data, int i, int j) {',
      '    int temp = data[i];',
      '    data[i] = data[j];',
      '    data[j] = temp;',
      '  }',
      '',
      '  public static int indexOfMinFrom(int[] data, int start) {',
      '    int best = start;',
      '    for (int i = start + 1; i < data.length; i++) {',
      '      if (data[i] < data[best]) {',
      '        best = i;',
      '      }',
      '    }',
      '    return best;',
      '  }',
      '',
      '  public static void selectionSort(int[] data) {',
      '    for (int i = 0; i < data.length - 1; i++) {',
      '      int m = indexOfMinFrom(data, i);',
      '      swap(data, i, m);',
      '    }',
      '  }',
      '',
      '  public static String show(int[] data) {',
      '    String out = "";',
      '    for (int i = 0; i < data.length; i++) {',
      '      if (i > 0) {',
      '        out = out + " ";',
      '      }',
      '      out = out + data[i];',
      '    }',
      '    return out;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness(readArray('data').concat([
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '',
      '    System.out.println(Sorter.indexOfMinFrom(data, 0));',
      '    Sorter.swap(data, a, b);',
      '    System.out.println(Sorter.show(data));',
      '    Sorter.swap(data, a, b);',
      '    Sorter.selectionSort(data);',
      '    System.out.println(Sorter.show(data));',
    ])),
    hints: [
      'The driver swaps the same pair TWICE, which should put the array back exactly as it was. A swap without a temporary fails that immediately.',
      'Selection sort only needs to run to the second to last element, because once everything before it is placed the last one has nowhere else to go.',
      'indexOfMinFrom seeds at start rather than at 0, which is what makes each pass ignore the part already sorted.',
    ],
    seo: 'AP CSA 4.15 FRQ practice: write a swap with a temporary and build selection sort on top of it, verified by a double swap.',
    mutants: [
      { describe: 'part (a) swaps without a temporary, so both elements end up equal',
        find: '    int temp = data[i];\n    data[i] = data[j];\n    data[j] = temp;', replace: '    data[i] = data[j];\n    data[j] = data[i];' },
      { describe: 'part (b) seeds at index 0 rather than at start',
        find: '    int best = start;\n    for (int i = start + 1; i < data.length; i++) {', replace: '    int best = 0;\n    for (int i = start + 1; i < data.length; i++) {' },
      { describe: 'part (c) sorts descending by taking the maximum instead',
        find: 'if (data[i] < data[best]) {', replace: 'if (data[i] > data[best]) {' },
      { describe: 'part (c) stops one pass too early',
        find: 'for (int i = 0; i < data.length - 1; i++) {\n      int m = indexOfMinFrom(data, i);', replace: 'for (int i = 0; i < data.length - 2; i++) {\n      int m = indexOfMinFrom(data, i);' },
    ],
    cases: [
      { stdin: '5\n5 3 9 1 7\n0 4\n', part: 1, hidden: 0 },
      // Chosen for (a): swapping an element with ITSELF, which must leave the
      // array unchanged and which a temporary-free swap survives by luck.
      { stdin: '4\n8 2 6 4\n2 2\n', part: 1, hidden: 0 },
      // Chosen for (c): already sorted, so only a descending sort shows up.
      { stdin: '4\n1 2 3 4\n0 1\n', part: 3, hidden: 1 },
      // Chosen for (c): reverse sorted, the most work a selection sort can do,
      // and where stopping one pass early leaves the last two out of order.
      { stdin: '5\n9 7 5 3 1\n1 3\n', part: 3, hidden: 1 },
      // Chosen for (b): duplicates, where the minimum appears more than once.
      { stdin: '4\n2 2 1 1\n0 3\n', part: 2, hidden: 1 },
      // Chosen for (d): a single element, where show returns one number with no
      // separator at all.
      { stdin: '1\n42\n0 0\n', part: 4, hidden: 1 },
    ],
  },

  // ── 4.16 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.16', unit: U,
    title: 'Recursion',
    name: 'Base Cases That Return the Right Thing',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'A missing base case makes recursion crash, and everyone learns to look for that. A base '
      + 'case that returns the WRONG VALUE is the mistake that actually appears on student work: the '
      + 'method terminates, the recursion is shaped correctly, and every answer is off by the same '
      + 'factor. A sum that bottoms out at 1 and a product that bottoms out at 0 are the same error.',
    given: 'Nothing is given. Write a class named Recurse. Assume n is at least 0. Do not write a main '
      + 'method.',
    parts: [
      { label: '(a)', text: 'public static int sumTo(int n) returns 1 + 2 + ... + n recursively, and 0 when n is 0.' },
      { label: '(b)', text: 'public static int factorial(int n) returns n! recursively, and 1 when n is 0.' },
      { label: '(c)', text: 'public static int countDigits(int n) returns how many digits n has, recursively. The number 0 has one digit.' },
      { label: '(d)', text: 'public static int power(int base, int exp) returns base to the exp, recursively, and 1 when exp is 0.' },
    ],
    task: [
      'Write class Recurse with the four static methods described. No main method.',
      'Every part here has a base case that must return a SPECIFIC value. A sum bottoms out at 0 and a product bottoms out at 1, and swapping those two is the whole question.',
      'Every recursive call must move toward the base case, or the method never returns.',
    ],
    starter: [
      'class Recurse {',
      '  // (a) sumTo(int n) -> int',
      '',
      '  // (b) factorial(int n) -> int',
      '',
      '  // (c) countDigits(int n) -> int',
      '',
      '  // (d) power(int base, int exp) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Recurse {',
      '  public static int sumTo(int n) {',
      '    if (n <= 0) {',
      '      return 0;',
      '    }',
      '    return n + sumTo(n - 1);',
      '  }',
      '',
      '  public static int factorial(int n) {',
      '    if (n <= 1) {',
      '      return 1;',
      '    }',
      '    return n * factorial(n - 1);',
      '  }',
      '',
      '  public static int countDigits(int n) {',
      '    if (n < 10) {',
      '      return 1;',
      '    }',
      '    return 1 + countDigits(n / 10);',
      '  }',
      '',
      '  public static int power(int base, int exp) {',
      '    if (exp <= 0) {',
      '      return 1;',
      '    }',
      '    return base * power(base, exp - 1);',
      '  }',
      '}',
    ].join('\n'),
    harness: harness([
      '    int n = input.nextInt();',
      '    int base = input.nextInt();',
      '    int exp = input.nextInt();',
      '',
      '    System.out.println(Recurse.sumTo(n));',
      '    System.out.println(Recurse.factorial(n));',
      '    System.out.println(Recurse.countDigits(n));',
      '    System.out.println(Recurse.power(base, exp));',
    ]),
    hints: [
      'The base case value is the identity of whatever the recursion combines. Addition combines with 0 and multiplication combines with 1.',
      'Part (c) bottoms out at any single digit number, which includes 0. Testing n == 0 instead throws away the last digit of every number.',
      'The recursive call must be smaller. n - 1 and n / 10 both reach their base cases; n itself never does.',
    ],
    seo: 'AP CSA 4.16 FRQ practice: write recursive methods whose base cases return the correct identity value rather than merely terminating.',
    mutants: [
      { describe: 'part (a) bottoms out at 1 instead of 0, so every sum is one too large',
        find: '    if (n <= 0) {\n      return 0;\n    }\n    return n + sumTo(n - 1);', replace: '    if (n <= 0) {\n      return 1;\n    }\n    return n + sumTo(n - 1);' },
      { describe: 'part (b) bottoms out at 0, so every factorial is 0',
        find: '    if (n <= 1) {\n      return 1;\n    }\n    return n * factorial(n - 1);', replace: '    if (n <= 1) {\n      return 0;\n    }\n    return n * factorial(n - 1);' },
      { describe: 'part (d) bottoms out at 0, so every power is 0',
        find: '    if (exp <= 0) {\n      return 1;\n    }\n    return base * power(base, exp - 1);', replace: '    if (exp <= 0) {\n      return 0;\n    }\n    return base * power(base, exp - 1);' },
      { describe: 'part (c) discards the result of its recursive call',
        find: 'return 1 + countDigits(n / 10);', replace: 'countDigits(n / 10);\n    return 1;' },
    ],
    cases: [
      { stdin: '5 2 3\n', part: 1, hidden: 0 },
      // Chosen for (b) and (d): n and exp are both 0, where the base case value
      // is the ONLY thing being returned.
      { stdin: '0 7 0\n', part: 2, hidden: 0 },
      // Chosen for (c): a multi digit number, so a discarded recursive result
      // reports 1 digit instead of three.
      { stdin: '742 3 4\n', part: 3, hidden: 1 },
      // Chosen for (d): a base of 1, where a wrong base case is still visible
      // because 1 to any power is 1 and 0 is not.
      { stdin: '1 1 9\n', part: 4, hidden: 1 },
      { stdin: '6 5 2\n', part: 4, hidden: 1 },
    ],
  },

  // ── 4.17 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.17', unit: U,
    title: 'Recursive Searching and Sorting',
    name: 'Recursion That Returns',
    mode: 'driver',
    frqType: 'array-arraylist',
    brief: 'The last topic of the course closes the thread opened in 1.10: a call whose result is '
      + 'discarded does nothing. In recursion that mistake is deadly, because the answer is built '
      + 'entirely out of returned values. Writing helper(...) on a line by itself instead of return '
      + 'helper(...) compiles, terminates, and answers wrongly every time.',
    given: 'The driver builds a SORTED int array and passes it to your methods. Write a class named '
      + 'RecSearch. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int find(int[] data, int target, int low, int high) searches recursively between low and high inclusive and returns an index holding target, or -1.' },
      { label: '(b)', text: 'public static int find(int[] data, int target) starts that search across the whole array.' },
      { label: '(c)', text: 'public static int maxFrom(int[] data, int i) returns the largest value at or after index i, recursively. Assume i is a valid index.' },
      { label: '(d)', text: 'public static int countFrom(int[] data, int target, int i) returns how many elements at or after i equal target, recursively.' },
    ],
    task: [
      'Write class RecSearch with the four methods described. No main method.',
      'Every recursive call\'s result must be RETURNED or combined into the answer. Calling and discarding compiles and answers wrongly.',
      'Part (a) returns -1 when low passes high, which is what makes the search end when the target is absent.',
    ],
    starter: [
      'class RecSearch {',
      '  // (a) find(int[] data, int target, int low, int high) -> int',
      '',
      '  // (b) find(int[] data, int target) -> int',
      '',
      '  // (c) maxFrom(int[] data, int i) -> int',
      '',
      '  // (d) countFrom(int[] data, int target, int i) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class RecSearch {',
      '  public static int find(int[] data, int target, int low, int high) {',
      '    if (low > high) {',
      '      return -1;',
      '    }',
      '    int mid = (low + high) / 2;',
      '    if (data[mid] == target) {',
      '      return mid;',
      '    }',
      '    if (data[mid] < target) {',
      '      return find(data, target, mid + 1, high);',
      '    }',
      '    return find(data, target, low, mid - 1);',
      '  }',
      '',
      '  public static int find(int[] data, int target) {',
      '    return find(data, target, 0, data.length - 1);',
      '  }',
      '',
      '  public static int maxFrom(int[] data, int i) {',
      '    if (i == data.length - 1) {',
      '      return data[i];',
      '    }',
      '    int rest = maxFrom(data, i + 1);',
      '    if (data[i] > rest) {',
      '      return data[i];',
      '    }',
      '    return rest;',
      '  }',
      '',
      '  public static int countFrom(int[] data, int target, int i) {',
      '    if (i >= data.length) {',
      '      return 0;',
      '    }',
      '    int rest = countFrom(data, target, i + 1);',
      '    if (data[i] == target) {',
      '      return 1 + rest;',
      '    }',
      '    return rest;',
      '  }',
      '}',
    ].join('\n'),
    harness: harness(readArray('data').concat([
      '    int target = input.nextInt();',
      '',
      '    System.out.println(RecSearch.find(data, target) >= 0);',
      '    System.out.println(RecSearch.find(data, target, 0, data.length - 1) >= 0);',
      '    System.out.println(RecSearch.maxFrom(data, 0));',
      '    System.out.println(RecSearch.countFrom(data, target, 0));',
    ])),
    hints: [
      'Two methods with the same name and different parameter lists are overloads, and the short one exists only to supply the starting bounds to the long one.',
      'Part (c) and part (d) both compute the answer for the REST of the array first, then fold the current element into it. That returned value is the whole answer.',
      'The driver prints whether the search succeeded rather than the index, because on repeated values a correct recursive search may land on any of them.',
    ],
    seo: 'AP CSA 4.17 FRQ practice: write recursive search and accumulation where every recursive result is returned rather than discarded.',
    mutants: [
      { describe: 'part (d) discards the recursive result, the thread opened back in 1.10',
        find: '    int rest = countFrom(data, target, i + 1);\n    if (data[i] == target) {\n      return 1 + rest;\n    }\n    return rest;',
        replace: '    countFrom(data, target, i + 1);\n    if (data[i] == target) {\n      return 1;\n    }\n    return 0;' },
      { describe: 'part (c) discards the recursive result and returns the current element',
        find: '    int rest = maxFrom(data, i + 1);\n    if (data[i] > rest) {\n      return data[i];\n    }\n    return rest;',
        replace: '    maxFrom(data, i + 1);\n    return data[i];' },
      { describe: 'part (a) recurses into the wrong half',
        find: '    if (data[mid] < target) {\n      return find(data, target, mid + 1, high);\n    }\n    return find(data, target, low, mid - 1);',
        replace: '    if (data[mid] < target) {\n      return find(data, target, low, mid - 1);\n    }\n    return find(data, target, mid + 1, high);' },
      { describe: 'part (b) searches only the first half of the array',
        find: 'return find(data, target, 0, data.length - 1);', replace: 'return find(data, target, 0, data.length / 2);' },
    ],
    cases: [
      { stdin: '7\n1 3 5 7 9 11 13\n11\n', part: 1, hidden: 0 },
      // Chosen for (d): the target appears more than once, so a discarded
      // recursive result reports 1 instead of the real count.
      { stdin: '6\n2 4 4 4 8 10\n4\n', part: 4, hidden: 0 },
      // Chosen for (c): the largest value is at the FRONT, so a method that
      // returns the current element without folding in the rest is right by
      // accident. Paired with the rows above where it is not.
      { stdin: '5\n1 2 3 4 5\n3\n', part: 3, hidden: 1 },
      // Chosen for (b): the target sits in the SECOND half, which a search
      // given the wrong upper bound never reaches.
      { stdin: '8\n1 2 3 4 5 6 7 8\n8\n', part: 2, hidden: 1 },
      // Chosen for (a): the target is absent entirely.
      { stdin: '4\n10 20 30 40\n25\n', part: 1, hidden: 1 },
    ],
  },
];

module.exports = { FRQS };
