'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  AP CSA UNIT 2 FRQ PRACTICE: SELECTION AND ITERATION.
//
//  EVERY ENTRY HERE IS `driver` MODE, AND UNIT 2 IS WHERE THAT BECOMES POSSIBLE
//  Unit 1 could only ask for a segment, because a segment cannot declare a
//  method and Unit 1 has not taught anything that needs one. From 2.1 the
//  student can write a method with a loop and a condition in it, which is what
//  the exam asks for, so from here on the question hands over a signature and a
//  hidden harness calls it.
//
//  That shape is not decoration. A driver-mode question CANNOT be passed by
//  printing: the harness prints, and the harness only prints what the student's
//  method RETURNED. Printing instead of returning is the single most common way
//  a fluent student loses free response points, and it is ungradeable in any
//  mode where the student owns the output.
//
//  THE UNIT 2 HAZARD: A BOOLEAN QUESTION THAT ONLY EVER ANSWERS true
//  Half of this unit returns booleans, and a boolean method has only two
//  answers, so `return true;` passes any case set that never asks for false.
//  Every boolean part here therefore has cases on BOTH sides, and the mutants
//  say so explicitly: `always returns true` is declared as a mistake and proven
//  to fail. Without that, a rubric row that looks covered is worth nothing.
//
//  NO INFINITE LOOPS. The verifier runs every reference and every mutant under a
//  15 second timeout, where a hang is indistinguishable from a broken harness.
//  A mutant that removes a loop update would hang rather than fail, so the
//  mutants here change comparisons and bounds, never the update itself.
//
//  Nothing here states an expected output. scripts/verify-csa-frq.js runs each
//  `reference` through real javac/java to generate them.
// ─────────────────────────────────────────────────────────────────────────────

const U = 'unit-2';

const FRQS = [
  // ── 2.1 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.1', unit: U,
    title: 'Algorithms with Selection and Repetition',
    name: 'Step Counter',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'An algorithm that repeats and an algorithm that chooses are the two halves of this unit, '
      + 'and the exam almost always asks for them together: loop over a range, decide something about '
      + 'each value, and report a total. Getting the loop right and the condition backwards still '
      + 'scores zero, which is why each part here isolates one of them.',
    given: 'Nothing is given. Write a class named Steps containing exactly the four static methods '
      + 'described below. Do not write a main method: a hidden driver calls your methods.',
    parts: [
      { label: '(a)', text: 'public static int sumTo(int n) returns 1 + 2 + ... + n, and 0 when n is less than 1.' },
      { label: '(b)', text: 'public static int countEvens(int n) returns how many of 1 through n are even.' },
      { label: '(c)', text: 'public static String verdict(int score) returns "PASS" when score is 60 or more, otherwise "FAIL".' },
      { label: '(d)', text: 'public static int firstMultiple(int start, int step) returns the smallest multiple of step that is at least start. Assume step is at least 1 and start is at least 0.' },
    ],
    task: [
      'Write class Steps with the four static methods exactly as described. No main method.',
      'Part (a) must return 0 rather than crash when n is 0 or negative. A loop that never runs already does this, so you may not need a special case at all.',
      'Every method RETURNS its answer. A method that prints it and returns nothing does not compile against the driver.',
    ],
    starter: [
      'class Steps {',
      '  // (a) sumTo(int n) -> int',
      '',
      '  // (b) countEvens(int n) -> int',
      '',
      '  // (c) verdict(int score) -> String',
      '',
      '  // (d) firstMultiple(int start, int step) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Steps {',
      '  public static int sumTo(int n) {',
      '    int total = 0;',
      '    for (int i = 1; i <= n; i++) {',
      '      total = total + i;',
      '    }',
      '    return total;',
      '  }',
      '',
      '  public static int countEvens(int n) {',
      '    int count = 0;',
      '    for (int i = 1; i <= n; i++) {',
      '      if (i % 2 == 0) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '',
      '  public static String verdict(int score) {',
      '    if (score >= 60) {',
      '      return "PASS";',
      '    }',
      '    return "FAIL";',
      '  }',
      '',
      '  public static int firstMultiple(int start, int step) {',
      '    int value = 0;',
      '    while (value < start) {',
      '      value = value + step;',
      '    }',
      '    return value;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    int score = input.nextInt();',
      '    int start = input.nextInt();',
      '    int step = input.nextInt();',
      '',
      '    System.out.println(Steps.sumTo(n));',
      '    System.out.println(Steps.countEvens(n));',
      '    System.out.println(Steps.verdict(score));',
      '    System.out.println(Steps.firstMultiple(start, step));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A for loop that starts at 1 and runs while i <= n never executes when n is 0 or negative, so part (a) returns its starting total of 0 with no extra check.',
      'Part (c) is a boundary question. 60 itself must be a PASS, so the test is >= and not >.',
      'Part (d) already answers correctly when start is 0, because 0 is a multiple of every step. Starting the search at step instead of 0 gets that one case wrong.',
    ],
    seo: 'AP CSA 2.1 FRQ practice: combine selection and repetition in four static methods called by a hidden driver you cannot edit.',
    mutants: [
      { describe: 'part (a) starts the loop at 0 and runs while i < n, dropping the last term',
        find: 'for (int i = 1; i <= n; i++) {\n      total = total + i;', replace: 'for (int i = 0; i < n; i++) {\n      total = total + i;' },
      { describe: 'part (c) uses > instead of >=, so exactly 60 fails',
        find: 'if (score >= 60) {', replace: 'if (score > 60) {' },
      { describe: 'part (d) starts the search at step, so a start of 0 answers step instead of 0',
        find: 'int value = 0;\n    while (value < start) {', replace: 'int value = step;\n    while (value < start) {' },
      { describe: 'part (b) counts odds instead of evens',
        find: 'if (i % 2 == 0) {', replace: 'if (i % 2 == 1) {' },
    ],
    cases: [
      { stdin: '10 60 0 7\n', part: 3, hidden: 0 },
      // Chosen for (a): n of 1, the smallest loop that still runs once.
      { stdin: '1 59 13 5\n', part: 1, hidden: 0 },
      // Chosen for (a): n of 0, where the loop never runs at all.
      { stdin: '0 100 1 1\n', part: 1, hidden: 1 },
      // Chosen for (b): an odd n, so counting odds and counting evens differ.
      { stdin: '7 60 20 20\n', part: 2, hidden: 1 },
      // Chosen for (d): start is already an exact multiple, so the answer is start itself.
      { stdin: '5 0 21 3\n', part: 4, hidden: 1 },
    ],
  },

  // ── 2.2 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.2', unit: U,
    title: 'Boolean Expressions',
    name: 'Range Checks',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'A boolean method has only two possible answers, which makes it the easiest kind of method '
      + 'to get accidentally right. Every part here is checked from both sides, because a method that '
      + 'always returns true is correct on half the inputs and worth no points.',
    given: 'Nothing is given. Write a class named Checks containing exactly the four static methods '
      + 'described below. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static boolean isPositive(int n) returns whether n is greater than zero.' },
      { label: '(b)', text: 'public static boolean inRange(int n, int low, int high) returns whether n is between low and high, inclusive of both.' },
      { label: '(c)', text: 'public static boolean isMultiple(int n, int factor) returns whether n divides evenly by factor. Assume factor is not zero.' },
      { label: '(d)', text: 'public static boolean sameParity(int a, int b) returns whether a and b are both even or both odd.' },
    ],
    task: [
      'Write class Checks with the four static methods exactly as described. No main method.',
      'None of these needs an if statement. A comparison already IS a boolean, so return the comparison itself.',
      'Part (b) is inclusive at both ends. low and high are each inside the range.',
    ],
    starter: [
      'class Checks {',
      '  // (a) isPositive(int n) -> boolean',
      '',
      '  // (b) inRange(int n, int low, int high) -> boolean',
      '',
      '  // (c) isMultiple(int n, int factor) -> boolean',
      '',
      '  // (d) sameParity(int a, int b) -> boolean',
      '}',
    ].join('\n'),
    reference: [
      'class Checks {',
      '  public static boolean isPositive(int n) {',
      '    return n > 0;',
      '  }',
      '',
      '  public static boolean inRange(int n, int low, int high) {',
      '    return n >= low && n <= high;',
      '  }',
      '',
      '  public static boolean isMultiple(int n, int factor) {',
      '    return n % factor == 0;',
      '  }',
      '',
      '  public static boolean sameParity(int a, int b) {',
      '    return a % 2 == b % 2;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    int low = input.nextInt();',
      '    int high = input.nextInt();',
      '    int factor = input.nextInt();',
      '    int other = input.nextInt();',
      '',
      '    System.out.println(Checks.isPositive(n));',
      '    System.out.println(Checks.inRange(n, low, high));',
      '    System.out.println(Checks.isMultiple(n, factor));',
      '    System.out.println(Checks.sameParity(n, other));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'if (x > 0) { return true; } else { return false; } is the long way of writing return x > 0. Both are correct; only one of them is the point of this lesson.',
      'Inclusive means the endpoints count. Using > and < instead of >= and <= excludes exactly the two values most likely to be tested.',
      'Two numbers have the same parity when both remainders match. Comparing a % 2 to b % 2 handles that in one expression without four separate cases.',
    ],
    seo: 'AP CSA 2.2 FRQ practice: return boolean expressions directly for range, multiple and parity checks without redundant if statements.',
    mutants: [
      { describe: 'part (a) always returns true',
        find: 'return n > 0;', replace: 'return true;' },
      { describe: 'part (b) excludes the endpoints, using strict comparisons',
        find: 'return n >= low && n <= high;', replace: 'return n > low && n < high;' },
      { describe: 'part (d) always returns true',
        find: 'return a % 2 == b % 2;', replace: 'return true;' },
      { describe: 'part (c) tests the remainder against 1 instead of 0',
        find: 'return n % factor == 0;', replace: 'return n % factor == 1;' },
    ],
    cases: [
      { stdin: '5 1 10 5 7\n', part: 1, hidden: 0 },
      // Chosen for (b): n sits exactly ON the low endpoint, which strict
      // comparisons exclude and inclusive ones accept.
      { stdin: '1 1 10 3 4\n', part: 2, hidden: 0 },
      // Chosen for (a): n is negative, the false side of part (a).
      { stdin: '-4 -10 -1 2 -8 \n', part: 1, hidden: 1 },
      // Chosen for (d): different parity, the false side of part (d).
      { stdin: '8 0 100 4 3\n', part: 4, hidden: 1 },
      // Chosen for (b): n above the high endpoint, and exactly on high below.
      // Chosen for (c): 10 does not divide by 7, the false side of isMultiple.
      { stdin: '10 1 10 7 10\n', part: 3, hidden: 1 },
    ],
  },

  // ── 2.3 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.3', unit: U,
    title: 'if Statements',
    name: 'Shipping Tiers',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'A tiered rule is the most common if question on the exam, and it has one trap: the order '
      + 'of the branches. Written from the loosest condition down, every input falls into the first '
      + 'branch and the rest are unreachable. The tiers here are arranged so that mistake changes the answer.',
    given: 'Nothing is given. Write a class named Shipping containing exactly the four static methods '
      + 'described below. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int fee(int weight) returns 5 when weight is under 10, 10 when weight is under 50, and 20 otherwise.' },
      { label: '(b)', text: 'public static String size(int weight) returns "SMALL" under 10, "MEDIUM" under 50, and "LARGE" otherwise.' },
      { label: '(c)', text: 'public static int discounted(int fee, boolean member) returns half the fee (integer division) for a member, and the full fee otherwise.' },
      { label: '(d)', text: 'public static int total(int weight, boolean member) returns the discounted fee for that weight.' },
    ],
    task: [
      'Write class Shipping with the four static methods exactly as described. No main method.',
      'Part (d) must call your own part (a) and part (c) rather than repeating their rules. A tier rule written twice is a tier rule that will disagree with itself later.',
      '"Under 10" means strictly less than 10. A weight of exactly 10 is in the middle tier.',
    ],
    starter: [
      'class Shipping {',
      '  // (a) fee(int weight) -> int',
      '',
      '  // (b) size(int weight) -> String',
      '',
      '  // (c) discounted(int fee, boolean member) -> int',
      '',
      '  // (d) total(int weight, boolean member) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Shipping {',
      '  public static int fee(int weight) {',
      '    if (weight < 10) {',
      '      return 5;',
      '    } else if (weight < 50) {',
      '      return 10;',
      '    }',
      '    return 20;',
      '  }',
      '',
      '  public static String size(int weight) {',
      '    if (weight < 10) {',
      '      return "SMALL";',
      '    } else if (weight < 50) {',
      '      return "MEDIUM";',
      '    }',
      '    return "LARGE";',
      '  }',
      '',
      '  public static int discounted(int fee, boolean member) {',
      '    if (member) {',
      '      return fee / 2;',
      '    }',
      '    return fee;',
      '  }',
      '',
      '  public static int total(int weight, boolean member) {',
      '    return discounted(fee(weight), member);',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int weight = input.nextInt();',
      '    boolean member = input.nextBoolean();',
      '',
      '    System.out.println(Shipping.fee(weight));',
      '    System.out.println(Shipping.size(weight));',
      '    System.out.println(Shipping.discounted(100, member));',
      '    System.out.println(Shipping.total(weight, member));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Check the tightest condition first. If you test weight < 50 before weight < 10, then a weight of 3 is under 50 and takes the middle tier, and the small tier can never be reached.',
      'A boolean parameter does not need == true. if (member) is the whole condition.',
      'Part (d) is one line if you reuse the methods you already wrote. Copying the tier rules into it is how the two versions drift apart when a price changes.',
    ],
    seo: 'AP CSA 2.3 FRQ practice: order if and else if branches correctly for a tiered shipping rule and reuse your own methods.',
    mutants: [
      { describe: 'part (a) tests the loosest tier first, making the small tier unreachable',
        find: 'if (weight < 10) {\n      return 5;\n    } else if (weight < 50) {\n      return 10;\n    }',
        replace: 'if (weight < 50) {\n      return 10;\n    } else if (weight < 10) {\n      return 5;\n    }' },
      { describe: 'part (b) uses <= at the tier boundary, so exactly 10 is SMALL',
        find: 'if (weight < 10) {\n      return "SMALL";', replace: 'if (weight <= 10) {\n      return "SMALL";' },
      { describe: 'part (c) discounts non-members instead of members',
        find: 'if (member) {\n      return fee / 2;', replace: 'if (!member) {\n      return fee / 2;' },
      { describe: 'part (d) ignores membership and returns the undiscounted fee',
        find: 'return discounted(fee(weight), member);', replace: 'return fee(weight);' },
    ],
    cases: [
      { stdin: '3 true\n', part: 1, hidden: 0 },
      // Chosen for (b): exactly ON the first tier boundary, where < and <= differ.
      { stdin: '10 false\n', part: 2, hidden: 0 },
      // Chosen for (d): heavy and a member, so the discount and the top tier
      // both have to be right.
      { stdin: '80 true\n', part: 4, hidden: 1 },
      // Chosen for (c): non-member, the other side of the discount branch.
      { stdin: '49 true\n', part: 3, hidden: 1 },
      { stdin: '50 true\n', part: 2, hidden: 1 },
    ],
  },

  // ── 2.4 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.4', unit: U,
    title: 'Nested if Statements',
    name: 'Admission Rules',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'Nesting is where the dangling else lives. An else belongs to the NEAREST unmatched if, '
      + 'not to the one it lines up with on the page, and indentation has no effect on which. This '
      + 'question has a case for every leaf of the decision tree so a misattached else cannot hide.',
    given: 'Nothing is given. Write a class named Admission containing exactly the four static methods '
      + 'described below. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static String tier(int age) returns "CHILD" under 13, "TEEN" under 20, "ADULT" under 65, and "SENIOR" otherwise.' },
      { label: '(b)', text: 'public static int price(int age) returns 0 for CHILD, 8 for TEEN, 15 for ADULT and 10 for SENIOR.' },
      { label: '(c)', text: 'public static boolean needsGuardian(int age, boolean afterSix) returns true only when the visitor is a CHILD, or is a TEEN and it is after six.' },
      { label: '(d)', text: 'public static int charge(int age, boolean afterSix) returns the price, plus 5 when a guardian is needed.' },
    ],
    task: [
      'Write class Admission with the four static methods exactly as described. No main method.',
      'Part (b) and part (c) should decide the tier by calling your part (a) rather than repeating the age boundaries. Four boundaries written three times is twelve chances to mistype one.',
      'Every boundary is exclusive at the top: 13 is a TEEN, 20 is an ADULT, 65 is a SENIOR.',
    ],
    starter: [
      'class Admission {',
      '  // (a) tier(int age) -> String',
      '',
      '  // (b) price(int age) -> int',
      '',
      '  // (c) needsGuardian(int age, boolean afterSix) -> boolean',
      '',
      '  // (d) charge(int age, boolean afterSix) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Admission {',
      '  public static String tier(int age) {',
      '    if (age < 13) {',
      '      return "CHILD";',
      '    } else if (age < 20) {',
      '      return "TEEN";',
      '    } else if (age < 65) {',
      '      return "ADULT";',
      '    }',
      '    return "SENIOR";',
      '  }',
      '',
      '  public static int price(int age) {',
      '    String t = tier(age);',
      '    if (t.equals("CHILD")) {',
      '      return 0;',
      '    } else if (t.equals("TEEN")) {',
      '      return 8;',
      '    } else if (t.equals("ADULT")) {',
      '      return 15;',
      '    }',
      '    return 10;',
      '  }',
      '',
      '  public static boolean needsGuardian(int age, boolean afterSix) {',
      '    String t = tier(age);',
      '    if (t.equals("CHILD")) {',
      '      return true;',
      '    }',
      '    return t.equals("TEEN") && afterSix;',
      '  }',
      '',
      '  public static int charge(int age, boolean afterSix) {',
      '    int base = price(age);',
      '    if (needsGuardian(age, afterSix)) {',
      '      return base + 5;',
      '    }',
      '    return base;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int age = input.nextInt();',
      '    boolean afterSix = input.nextBoolean();',
      '',
      '    System.out.println(Admission.tier(age));',
      '    System.out.println(Admission.price(age));',
      '    System.out.println(Admission.needsGuardian(age, afterSix));',
      '    System.out.println(Admission.charge(age, afterSix));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Compare Strings with equals, never with ==. Two Strings holding the same characters can be different objects, and == asks whether they are the same object.',
      'Part (c) is true for every CHILD regardless of the hour, and for a TEEN only after six. An ADULT is never true, whatever the hour.',
      'Build each method on the one before it. If part (a) is right, parts (b), (c) and (d) never need to mention 13, 20 or 65 at all.',
    ],
    seo: 'AP CSA 2.4 FRQ practice: build a four tier decision with nested conditions and reuse it rather than repeating the age boundaries.',
    mutants: [
      { describe: 'part (a) makes 13 a CHILD, using <= at the first boundary',
        find: 'if (age < 13) {\n      return "CHILD";', replace: 'if (age <= 13) {\n      return "CHILD";' },
      { describe: 'part (c) needs a guardian for any teen, whatever the hour',
        find: 'return t.equals("TEEN") && afterSix;', replace: 'return t.equals("TEEN");' },
      { describe: 'part (d) never adds the guardian surcharge',
        find: 'if (needsGuardian(age, afterSix)) {\n      return base + 5;\n    }', replace: 'if (false) {\n      return base + 5;\n    }' },
      { describe: 'part (b) prices seniors as adults',
        find: '    } else if (t.equals("ADULT")) {\n      return 15;\n    }\n    return 10;', replace: '    }\n    return 15;' },
    ],
    cases: [
      { stdin: '30 false\n', part: 2, hidden: 0 },
      // Chosen for (c): a teen BEFORE six, the false leg of the compound rule.
      { stdin: '15 false\n', part: 3, hidden: 0 },
      // Chosen for (a): exactly 13, the boundary a <= turns into a CHILD.
      { stdin: '13 true\n', part: 1, hidden: 1 },
      // Chosen for (d): a child, so the surcharge applies to a base price of 0.
      { stdin: '7 false\n', part: 4, hidden: 1 },
      // Chosen for (b): a senior, the tier a collapsed else clause misprices.
      { stdin: '70 true\n', part: 2, hidden: 1 },
    ],
  },

  // ── 2.5 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.5', unit: U,
    title: 'Compound Boolean Expressions',
    name: 'Eligibility',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'The exam tests && and || by making one of them wrong in a way that is right most of the '
      + 'time. Swapping && for || in a two condition rule gives the same answer on three of the four '
      + 'combinations. Every part here has a case for the combination that separates them.',
    given: 'Nothing is given. Write a class named Eligible containing exactly the four static methods '
      + 'described below. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static boolean canDrive(int age, boolean hasLicense) returns whether the person is at least 16 AND has a license.' },
      { label: '(b)', text: 'public static boolean freeEntry(int age, boolean member) returns whether the person is under 6 OR is a member.' },
      { label: '(c)', text: 'public static boolean needsReview(int score, int absences) returns whether the score is under 70 OR absences are over 10.' },
      { label: '(d)', text: 'public static boolean honorRoll(int score, int absences) returns whether the score is at least 90 AND absences are at most 3.' },
    ],
    task: [
      'Write class Eligible with the four static methods exactly as described. No main method.',
      'None of these needs an if. Return the compound expression itself.',
      'Read each boundary carefully: "at least 16" is >= 16, "under 6" is < 6, "over 10" is > 10, "at most 3" is <= 3.',
    ],
    starter: [
      'class Eligible {',
      '  // (a) canDrive(int age, boolean hasLicense) -> boolean',
      '',
      '  // (b) freeEntry(int age, boolean member) -> boolean',
      '',
      '  // (c) needsReview(int score, int absences) -> boolean',
      '',
      '  // (d) honorRoll(int score, int absences) -> boolean',
      '}',
    ].join('\n'),
    reference: [
      'class Eligible {',
      '  public static boolean canDrive(int age, boolean hasLicense) {',
      '    return age >= 16 && hasLicense;',
      '  }',
      '',
      '  public static boolean freeEntry(int age, boolean member) {',
      '    return age < 6 || member;',
      '  }',
      '',
      '  public static boolean needsReview(int score, int absences) {',
      '    return score < 70 || absences > 10;',
      '  }',
      '',
      '  public static boolean honorRoll(int score, int absences) {',
      '    return score >= 90 && absences <= 3;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int age = input.nextInt();',
      '    boolean flag = input.nextBoolean();',
      '    int score = input.nextInt();',
      '    int absences = input.nextInt();',
      '',
      '    System.out.println(Eligible.canDrive(age, flag));',
      '    System.out.println(Eligible.freeEntry(age, flag));',
      '    System.out.println(Eligible.needsReview(score, absences));',
      '    System.out.println(Eligible.honorRoll(score, absences));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      '&& needs both sides true. || needs only one. Read the sentence again: "and" versus "or" is the whole question.',
      'A rule with two conditions has four combinations. Test all four in your head before you submit: true/true, true/false, false/true, false/false.',
      '"At most 3" includes 3 itself, so it is <= 3. Writing < 3 silently excludes the student with exactly three absences.',
    ],
    seo: 'AP CSA 2.5 FRQ practice: write compound boolean rules with and and or, getting both the operator and the boundary right.',
    mutants: [
      { describe: 'part (a) uses || instead of &&',
        find: 'return age >= 16 && hasLicense;', replace: 'return age >= 16 || hasLicense;' },
      { describe: 'part (b) uses && instead of ||',
        find: 'return age < 6 || member;', replace: 'return age < 6 && member;' },
      { describe: 'part (c) uses && instead of ||',
        find: 'return score < 70 || absences > 10;', replace: 'return score < 70 && absences > 10;' },
      { describe: 'part (d) excludes exactly three absences',
        find: 'return score >= 90 && absences <= 3;', replace: 'return score >= 90 && absences < 3;' },
    ],
    cases: [
      { stdin: '17 true 95 2\n', part: 1, hidden: 0 },
      // Chosen for (a) and (b): old enough but NO license, and not a member.
      // This is the combination where && and || disagree.
      { stdin: '17 false 95 2\n', part: 1, hidden: 0 },
      // Chosen for (c): a passing score with too many absences, so only the
      // second half of the OR is true.
      { stdin: '30 false 88 12\n', part: 3, hidden: 1 },
      // Chosen for (d): a high score with exactly three absences, the boundary.
      { stdin: '5 false 90 3\n', part: 4, hidden: 1 },
      // Chosen for (b): young AND not a member, so only the first half is true.
      { stdin: '4 false 60 0\n', part: 2, hidden: 1 },
    ],
  },

  // ── 2.6 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.6', unit: U,
    title: 'Comparing Boolean Expressions',
    name: 'De Morgan in Practice',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'Two boolean expressions are equivalent when they agree on EVERY input, and the exam tests '
      + 'that with the one rule students reliably get backwards: not (A and B) is (not A) OR (not B), '
      + 'never (not A) and (not B). This question asks for the same rule written both ways so they can '
      + 'be compared directly.',
    given: 'Nothing is given. Write a class named Logic containing exactly the four static methods '
      + 'described below. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static boolean bothOpen(boolean a, boolean b) returns whether both are true.' },
      { label: '(b)', text: 'public static boolean notBothOpen(boolean a, boolean b) returns the opposite of part (a), written WITHOUT calling part (a).' },
      { label: '(c)', text: 'public static boolean neitherOpen(boolean a, boolean b) returns whether both are false.' },
      { label: '(d)', text: 'public static boolean onlyFirstOpen(boolean a, boolean b) returns whether a is true and b is false.' },
    ],
    task: [
      'Write class Logic with the four static methods exactly as described. No main method.',
      'Parts (b) and (c) are DIFFERENT rules and the driver will show you where they differ. "Not both" is true when one is open; "neither" is not.',
      'Part (d) is true only for the first door. It is deliberately not symmetric: onlyFirstOpen(true, false) and onlyFirstOpen(false, true) must give different answers.',
    ],
    starter: [
      'class Logic {',
      '  // (a) bothOpen(boolean a, boolean b) -> boolean',
      '',
      '  // (b) notBothOpen(boolean a, boolean b) -> boolean, without calling bothOpen',
      '',
      '  // (c) neitherOpen(boolean a, boolean b) -> boolean',
      '',
      '  // (d) onlyFirstOpen(boolean a, boolean b) -> boolean',
      '}',
    ].join('\n'),
    reference: [
      'class Logic {',
      '  public static boolean bothOpen(boolean a, boolean b) {',
      '    return a && b;',
      '  }',
      '',
      '  public static boolean notBothOpen(boolean a, boolean b) {',
      '    return !a || !b;',
      '  }',
      '',
      '  public static boolean neitherOpen(boolean a, boolean b) {',
      '    return !a && !b;',
      '  }',
      '',
      '  public static boolean onlyFirstOpen(boolean a, boolean b) {',
      '    return a && !b;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    boolean a = input.nextBoolean();',
      '    boolean b = input.nextBoolean();',
      '',
      '    System.out.println(Logic.bothOpen(a, b));',
      '    System.out.println(Logic.notBothOpen(a, b));',
      '    System.out.println(Logic.neitherOpen(a, b));',
      '    System.out.println(Logic.onlyFirstOpen(a, b));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Distributing a not across an and flips the connector too. !(a && b) is !a || !b. Writing !a && !b gives you "neither", which is a different rule that happens to agree when both are false.',
      'Part (d) needs both halves: a must be true AND b must be false. Returning a alone is right on three of the four rows, which is exactly the kind of nearly correct that a full truth table catches.',
      'Fill in the four row truth table for your parts (b) and (c) before submitting. They must disagree on two of the four rows.',
    ],
    seo: 'AP CSA 2.6 FRQ practice: compare equivalent boolean expressions and apply De Morgan without collapsing not both into neither.',
    mutants: [
      { describe: 'part (b) distributes the not without flipping the connector, becoming neither',
        find: 'return !a || !b;', replace: 'return !a && !b;' },
      { describe: 'part (c) is written as not both instead of neither',
        find: 'return !a && !b;', replace: 'return !a || !b;' },
      { describe: 'part (d) ignores the second door and returns a alone',
        find: 'return a && !b;', replace: 'return a;' },
      { describe: 'part (d) is written symmetrically, so it cannot tell the two doors apart',
        find: 'return a && !b;', replace: 'return a != b;' },
      { describe: 'part (a) uses || instead of &&',
        find: 'return a && b;', replace: 'return a || b;' },
    ],
    cases: [
      // All four rows of the truth table appear, which for a two boolean
      // question is the only case set that can prove an equivalence.
      { stdin: 'true true\n', part: 1, hidden: 0 },
      // Chosen for (b) and (c): the row where "not both" and "neither" disagree.
      { stdin: 'true false\n', part: 2, hidden: 0 },
      { stdin: 'false true\n', part: 4, hidden: 1 },
      { stdin: 'false false\n', part: 3, hidden: 1 },
    ],
  },

  // ── 2.7 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.7', unit: U,
    title: 'while Loops',
    name: 'Digit Machine',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'A while loop is the right tool when you do not know the count in advance, which is exactly '
      + 'the case for taking a number apart digit by digit. The trap is the zero case: a loop written '
      + 'as "while there are digits left" runs zero times for the number 0 and reports that 0 has no digits.',
    given: 'Nothing is given. Write a class named Digits containing exactly the four static methods '
      + 'described below. Assume every argument is zero or positive. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int count(int n) returns how many digits n has. The number 0 has one digit.' },
      { label: '(b)', text: 'public static int sum(int n) returns the sum of the digits of n.' },
      { label: '(c)', text: 'public static int lastDigit(int n) returns the final digit of n.' },
      { label: '(d)', text: 'public static int reverse(int n) returns n with its digits reversed. Leading zeros simply disappear, so 100 reverses to 1.' },
    ],
    task: [
      'Write class Digits with the four static methods exactly as described. No main method.',
      'Part (a) must return 1 for the number 0. A plain while (n > 0) loop returns 0, which is the bug this part is about.',
      'Every loop here must change n, or it will never end. The verifier gives up after fifteen seconds and reports a timeout, not a wrong answer.',
    ],
    starter: [
      'class Digits {',
      '  // (a) count(int n) -> int, and count(0) is 1',
      '',
      '  // (b) sum(int n) -> int',
      '',
      '  // (c) lastDigit(int n) -> int',
      '',
      '  // (d) reverse(int n) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Digits {',
      '  public static int count(int n) {',
      '    int digits = 0;',
      '    while (n > 0) {',
      '      digits = digits + 1;',
      '      n = n / 10;',
      '    }',
      '    if (digits == 0) {',
      '      return 1;',
      '    }',
      '    return digits;',
      '  }',
      '',
      '  public static int sum(int n) {',
      '    int total = 0;',
      '    while (n > 0) {',
      '      total = total + n % 10;',
      '      n = n / 10;',
      '    }',
      '    return total;',
      '  }',
      '',
      '  public static int lastDigit(int n) {',
      '    return n % 10;',
      '  }',
      '',
      '  public static int reverse(int n) {',
      '    int out = 0;',
      '    while (n > 0) {',
      '      out = out * 10 + n % 10;',
      '      n = n / 10;',
      '    }',
      '    return out;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '',
      '    System.out.println(Digits.count(n));',
      '    System.out.println(Digits.sum(n));',
      '    System.out.println(Digits.lastDigit(n));',
      '    System.out.println(Digits.reverse(n));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'n % 10 gives the last digit and n / 10 removes it. Those two together are the whole technique for every part here.',
      'Part (a) is the only one that needs a special case, because 0 has a digit but no digits greater than zero to loop over.',
      'Part (d) builds its answer by multiplying by 10 and adding the next digit. Adding first and multiplying after gives a different, wrong number.',
    ],
    seo: 'AP CSA 2.7 FRQ practice: take a number apart with a while loop and handle the zero case that a naive loop condition misses.',
    mutants: [
      { describe: 'part (a) drops the zero special case, so count(0) returns 0',
        find: 'if (digits == 0) {\n      return 1;\n    }\n    return digits;', replace: 'return digits;' },
      { describe: 'part (d) multiplies after adding instead of before',
        find: 'out = out * 10 + n % 10;', replace: 'out = (out + n % 10) * 10;' },
      { describe: 'part (b) sums by dividing rather than taking the remainder',
        find: 'total = total + n % 10;', replace: 'total = total + n / 10;' },
      { describe: 'part (c) returns the first digit instead of the last',
        find: '  public static int lastDigit(int n) {\n    return n % 10;', replace: '  public static int lastDigit(int n) {\n    while (n >= 10) { n = n / 10; }\n    return n;' },
    ],
    cases: [
      { stdin: '4821\n', part: 2, hidden: 0 },
      // Chosen for (c): a single digit, where first and last coincide.
      { stdin: '7\n', part: 3, hidden: 0 },
      // Chosen for (a): zero, the case the loop condition cannot see.
      { stdin: '0\n', part: 1, hidden: 1 },
      // Chosen for (d): trailing zeros, which vanish on reversal.
      { stdin: '100\n', part: 4, hidden: 1 },
      { stdin: '90009\n', part: 4, hidden: 1 },
    ],
  },

  // ── 2.8 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.8', unit: U,
    title: 'for Loops',
    name: 'Accumulator Identities',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'Every accumulator starts at its identity: 0 for a sum, 1 for a product, and the FIRST '
      + 'value for a maximum. Starting a maximum at 0 is the most common accumulator bug on the exam, '
      + 'and it is invisible until every value happens to be negative.',
    given: 'Nothing is given. Write a class named Totals containing exactly the four static methods '
      + 'described below. Assume count is at least 1. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int sumRange(int low, int high) returns the sum of every integer from low to high inclusive, and 0 when low is greater than high.' },
      { label: '(b)', text: 'public static int product(int n) returns 1 times 2 times ... times n, and 1 when n is less than 1.' },
      { label: '(c)', text: 'public static int largestMultiple(int limit, int step) returns the largest multiple of step that is at most limit. Assume step is at least 1 and limit is at least 0.' },
      { label: '(d)', text: 'public static int countDivisors(int n) returns how many integers from 1 to n divide n evenly. Assume n is at least 1.' },
    ],
    task: [
      'Write class Totals with the four static methods exactly as described. No main method.',
      'Part (b) starts its accumulator at 1, not 0. A product that starts at 0 stays 0 forever.',
      'Every loop here counts up to a known bound, which is what a for loop is for.',
    ],
    starter: [
      'class Totals {',
      '  // (a) sumRange(int low, int high) -> int',
      '',
      '  // (b) product(int n) -> int',
      '',
      '  // (c) largestMultiple(int limit, int step) -> int',
      '',
      '  // (d) countDivisors(int n) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Totals {',
      '  public static int sumRange(int low, int high) {',
      '    int total = 0;',
      '    for (int i = low; i <= high; i++) {',
      '      total = total + i;',
      '    }',
      '    return total;',
      '  }',
      '',
      '  public static int product(int n) {',
      '    int result = 1;',
      '    for (int i = 2; i <= n; i++) {',
      '      result = result * i;',
      '    }',
      '    return result;',
      '  }',
      '',
      '  public static int largestMultiple(int limit, int step) {',
      '    return limit / step * step;',
      '  }',
      '',
      '  public static int countDivisors(int n) {',
      '    int count = 0;',
      '    for (int i = 1; i <= n; i++) {',
      '      if (n % i == 0) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int low = input.nextInt();',
      '    int high = input.nextInt();',
      '    int n = input.nextInt();',
      '    int limit = input.nextInt();',
      '    int step = input.nextInt();',
      '    int divisorOf = input.nextInt();',
      '',
      '    System.out.println(Totals.sumRange(low, high));',
      '    System.out.println(Totals.product(n));',
      '    System.out.println(Totals.largestMultiple(limit, step));',
      '    System.out.println(Totals.countDivisors(divisorOf));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A sum starts at 0 and a product starts at 1. Those are the values that leave the answer unchanged when nothing is combined into them, which is why they are called identities.',
      'Part (a) returns 0 for an empty range without a special case, because a for loop whose condition is false at the start never runs.',
      'Part (c) needs no loop at all. Integer division already truncates to a whole number of steps, so limit / step * step is the answer.',
    ],
    seo: 'AP CSA 2.8 FRQ practice: start each accumulator at the correct identity for sums, products, divisors and multiples.',
    mutants: [
      { describe: 'part (b) starts its product accumulator at 0, so every answer is 0',
        find: 'int result = 1;\n    for (int i = 2; i <= n; i++) {', replace: 'int result = 0;\n    for (int i = 2; i <= n; i++) {' },
      { describe: 'part (a) stops one short of high',
        find: 'for (int i = low; i <= high; i++) {', replace: 'for (int i = low; i < high; i++) {' },
      { describe: 'part (d) skips 1 as a divisor',
        find: 'for (int i = 1; i <= n; i++) {\n      if (n % i == 0) {', replace: 'for (int i = 2; i <= n; i++) {\n      if (n % i == 0) {' },
      { describe: 'part (c) rounds up to the next multiple instead of down',
        find: 'return limit / step * step;', replace: 'return (limit + step - 1) / step * step;' },
    ],
    cases: [
      { stdin: '1 5 4 20 6 12\n', part: 1, hidden: 0 },
      // Chosen for (b): a product large enough that a zero identity is obvious.
      { stdin: '3 3 5 17 3 7\n', part: 2, hidden: 0 },
      // Chosen for (a): an empty range where low is above high.
      { stdin: '9 2 1 10 5 16\n', part: 1, hidden: 1 },
      // Chosen for (c): limit is already an exact multiple, so rounding up
      // overshoots by a whole step.
      { stdin: '2 4 0 12 4 9\n', part: 3, hidden: 1 },
      // Chosen for (d): a prime, which has exactly two divisors.
      { stdin: '5 6 6 30 7 13\n', part: 4, hidden: 1 },
    ],
  },

  // ── 2.9 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.9', unit: U,
    title: 'Implementing Selection and Iteration Algorithms',
    name: 'Running Statistics',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'This is the shape of a real free response question: loop over values, keep several running '
      + 'answers at once, and report them. The maximum here is seeded with the first value rather than '
      + 'with zero, because the data can be entirely negative and a zero seed would report a maximum '
      + 'that never appeared in the input.',
    given: 'The driver reads a count and then that many integers, and passes them to your methods one '
      + 'call at a time is NOT how this works: each method receives the count and reads nothing. '
      + 'Instead each method is given the values it needs as parameters. Write a class named Stats '
      + 'containing exactly the four static methods described below. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int betterMax(int running, int next) returns whichever of the two is larger.' },
      { label: '(b)', text: 'public static int rangeSum(int low, int high, int skip) returns the sum of low through high inclusive, leaving out any value that divides evenly by skip. Assume skip is at least 2.' },
      { label: '(c)', text: 'public static int countAbove(int low, int high, int threshold) returns how many integers from low to high inclusive are strictly greater than threshold.' },
      { label: '(d)', text: 'public static int firstAbove(int low, int high, int threshold) returns the first integer from low upward that is strictly greater than threshold, or high + 1 if there is none.' },
    ],
    task: [
      'Write class Stats with the four static methods exactly as described. No main method.',
      'Part (d) must stop at the FIRST match. A loop that keeps going and overwrites its answer returns the last match instead.',
      '"Strictly greater" excludes the threshold itself in both part (c) and part (d).',
    ],
    starter: [
      'class Stats {',
      '  // (a) betterMax(int running, int next) -> int',
      '',
      '  // (b) rangeSum(int low, int high, int skip) -> int',
      '',
      '  // (c) countAbove(int low, int high, int threshold) -> int',
      '',
      '  // (d) firstAbove(int low, int high, int threshold) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Stats {',
      '  public static int betterMax(int running, int next) {',
      '    if (next > running) {',
      '      return next;',
      '    }',
      '    return running;',
      '  }',
      '',
      '  public static int rangeSum(int low, int high, int skip) {',
      '    int total = 0;',
      '    for (int i = low; i <= high; i++) {',
      '      if (i % skip != 0) {',
      '        total = total + i;',
      '      }',
      '    }',
      '    return total;',
      '  }',
      '',
      '  public static int countAbove(int low, int high, int threshold) {',
      '    int count = 0;',
      '    for (int i = low; i <= high; i++) {',
      '      if (i > threshold) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '',
      '  public static int firstAbove(int low, int high, int threshold) {',
      '    for (int i = low; i <= high; i++) {',
      '      if (i > threshold) {',
      '        return i;',
      '      }',
      '    }',
      '    return high + 1;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int low = input.nextInt();',
      '    int high = input.nextInt();',
      '    int skip = input.nextInt();',
      '    int threshold = input.nextInt();',
      '',
      '    System.out.println(Stats.betterMax(low, high));',
      '    System.out.println(Stats.rangeSum(low, high, skip));',
      '    System.out.println(Stats.countAbove(low, high, threshold));',
      '    System.out.println(Stats.firstAbove(low, high, threshold));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Part (a) is where a running maximum comes from. Returning next when it is strictly greater keeps the EARLIER value on a tie, which is usually what a question means by "the first largest".',
      'Part (d) returns from inside the loop. That is what makes it stop at the first match rather than the last.',
      'Part (b) skips a value when it divides evenly, so the condition to KEEP a value is i % skip != 0.',
    ],
    seo: 'AP CSA 2.9 FRQ practice: implement running maximum, filtered sum, count and first match algorithms that stop at the right moment.',
    mutants: [
      { describe: 'part (d) keeps looping and returns the LAST match instead of the first',
        find: '      if (i > threshold) {\n        return i;\n      }\n    }\n    return high + 1;',
        replace: '      int found = high + 1;\n      if (i > threshold) {\n        found = i;\n      }\n      if (i == high) {\n        return found;\n      }\n    }\n    return high + 1;' },
      { describe: 'part (c) counts values equal to the threshold as above it',
        find: '      if (i > threshold) {\n        count = count + 1;', replace: '      if (i >= threshold) {\n        count = count + 1;' },
      { describe: 'part (b) keeps the multiples and skips everything else',
        find: 'if (i % skip != 0) {', replace: 'if (i % skip == 0) {' },
      // Note: > versus >= is NOT a mutant here. betterMax returns a VALUE, and
      // on a tie both branches return the same number, so no case can tell them
      // apart. That distinction only becomes gradeable when an INDEX is tracked,
      // which is 4.5. Claiming it here would be a rubric row that cannot fail.
      { describe: 'part (a) keeps the smaller value instead of the larger',
        find: 'if (next > running) {', replace: 'if (next < running) {' },
    ],
    cases: [
      { stdin: '1 10 3 5\n', part: 2, hidden: 0 },
      // Chosen for (c): the threshold sits exactly inside the range, so counting
      // it as "above" is off by one.
      { stdin: '1 6 2 6\n', part: 3, hidden: 0 },
      // Chosen for (d): nothing in the range clears the threshold, so the
      // not-found answer is what is being tested.
      { stdin: '1 5 2 99\n', part: 4, hidden: 1 },
      // Chosen for (a): low and high are equal, the tie case.
      { stdin: '4 4 3 0\n', part: 1, hidden: 1 },
      // Chosen for (d): every value clears it, so the first is the answer.
      { stdin: '10 20 4 -5\n', part: 4, hidden: 1 },
    ],
  },

  // ── 2.10 ───────────────────────────────────────────────────────────────────
  {
    lesson: '2.10', unit: U,
    title: 'Implementing String Algorithms',
    name: 'Scanning a String',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'Every String algorithm on the exam is a loop from 0 to length() - 1 with charAt inside it. '
      + 'The two ways to lose the point are looping to length() (which throws) and comparing characters '
      + 'with equals (which does not compile for a char).',
    given: 'Nothing is given. Write a class named Scan containing exactly the four static methods '
      + 'described below. Assume every String argument is not null. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int countChar(String s, String target) returns how many times the first character of target appears in s. Assume target has at least one character.' },
      { label: '(b)', text: 'public static String reverse(String s) returns s with its characters in the opposite order.' },
      { label: '(c)', text: 'public static boolean isPalindrome(String s) returns whether s reads the same forwards and backwards. The empty String is a palindrome.' },
      { label: '(d)', text: 'public static int countVowels(String s) returns how many of the characters a, e, i, o and u appear in s, lower case only.' },
    ],
    task: [
      'Write class Scan with the four static methods exactly as described. No main method.',
      'A loop over a String runs from 0 while i < s.length(). Using <= reads one character past the end and throws.',
      'Characters compare with ==, not equals. s.charAt(i) == \'a\' is the comparison; s.charAt(i).equals("a") does not compile.',
    ],
    starter: [
      'class Scan {',
      '  // (a) countChar(String s, String target) -> int',
      '',
      '  // (b) reverse(String s) -> String',
      '',
      '  // (c) isPalindrome(String s) -> boolean',
      '',
      '  // (d) countVowels(String s) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Scan {',
      '  public static int countChar(String s, String target) {',
      '    char want = target.charAt(0);',
      '    int count = 0;',
      '    for (int i = 0; i < s.length(); i++) {',
      '      if (s.charAt(i) == want) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '',
      '  public static String reverse(String s) {',
      '    String out = "";',
      '    for (int i = s.length() - 1; i >= 0; i--) {',
      '      out = out + s.charAt(i);',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static boolean isPalindrome(String s) {',
      '    return s.equals(reverse(s));',
      '  }',
      '',
      '  public static int countVowels(String s) {',
      '    int count = 0;',
      '    for (int i = 0; i < s.length(); i++) {',
      '      char c = s.charAt(i);',
      '      if (c == 97 || c == 101 || c == 105 || c == 111 || c == 117) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String s = input.next();',
      '    String target = input.next();',
      '',
      '    System.out.println(Scan.countChar(s, target));',
      '    System.out.println(Scan.reverse(s));',
      '    System.out.println(Scan.isPalindrome(s));',
      '    System.out.println(Scan.countVowels(s));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The last valid index is length() - 1. A loop that runs while i <= s.length() throws StringIndexOutOfBoundsException on the very last pass.',
      'Building a String by adding characters one at a time is fine here. Start with the empty String, which is the identity for concatenation exactly as 0 is for a sum.',
      'Part (c) is one line once part (b) works. A palindrome is a String equal to its own reversal, and reusing your own method is both shorter and harder to get wrong.',
    ],
    seo: 'AP CSA 2.10 FRQ practice: loop over a String with charAt to count, reverse and test for a palindrome without running off the end.',
    mutants: [
      { describe: 'part (b) builds the reversal forwards, returning the original',
        find: 'for (int i = s.length() - 1; i >= 0; i--) {\n      out = out + s.charAt(i);',
        replace: 'for (int i = 0; i < s.length(); i++) {\n      out = out + s.charAt(i);' },
      { describe: 'part (a) counts every character rather than only the target',
        find: '      if (s.charAt(i) == want) {\n        count = count + 1;', replace: '      if (true) {\n        count = count + 1;' },
      { describe: 'part (d) misses the vowel u',
        find: 'if (c == 97 || c == 101 || c == 105 || c == 111 || c == 117) {', replace: 'if (c == 97 || c == 101 || c == 105 || c == 111) {' },
      { describe: 'part (c) always returns true',
        find: 'return s.equals(reverse(s));', replace: 'return true;' },
    ],
    cases: [
      { stdin: 'banana a\n', part: 1, hidden: 0 },
      // Chosen for (c): an actual palindrome, so the true side is shown.
      { stdin: 'racecar r\n', part: 3, hidden: 0 },
      // Chosen for (d): contains u, the vowel a short list drops.
      { stdin: 'unusual u\n', part: 4, hidden: 1 },
      // Chosen for (b): a single character, where forwards and backwards agree.
      { stdin: 'z z\n', part: 2, hidden: 1 },
      // Chosen for (b): asymmetric, so a forwards build is visibly wrong.
      { stdin: 'stressed d\n', part: 2, hidden: 1 },
    ],
  },

  // ── 2.11 ───────────────────────────────────────────────────────────────────
  {
    lesson: '2.11', unit: U,
    title: 'Nested Iteration',
    name: 'Rows and Columns',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'A nested loop multiplies. The outer loop body runs once per row, the inner one runs fully '
      + 'inside each of those, and the counter that belongs to the outer loop must not be reset by the '
      + 'inner one. Every rectangle here is deliberately NOT square, because a square hides a swapped '
      + 'pair of bounds completely.',
    given: 'Nothing is given. Write a class named Grid containing exactly the four static methods '
      + 'described below. Assume rows and cols are each at least 1. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int cells(int rows, int cols) returns how many cells a rows by cols rectangle has.' },
      { label: '(b)', text: 'public static int sumProducts(int rows, int cols) returns the sum of r times c over every r from 1 to rows and every c from 1 to cols.' },
      { label: '(c)', text: 'public static int countPairs(int n) returns how many ordered pairs (i, j) with 1 <= i < j <= n exist.' },
      { label: '(d)', text: 'public static String rowLabel(int row, int cols) returns the numbers 1 through cols each multiplied by row, separated by single spaces, with no space at the start.' },
    ],
    task: [
      'Write class Grid with the four static methods exactly as described. No main method.',
      'Part (a) and part (b) both use a nested loop. Count the cells rather than assuming the shape is square.',
      'Part (d) separates the numbers with single spaces and must not begin with one. Adding the separator BEFORE each item except the first is the usual way.',
    ],
    starter: [
      'class Grid {',
      '  // (a) cells(int rows, int cols) -> int',
      '',
      '  // (b) sumProducts(int rows, int cols) -> int',
      '',
      '  // (c) countPairs(int n) -> int',
      '',
      '  // (d) rowLabel(int row, int cols) -> String',
      '}',
    ].join('\n'),
    reference: [
      'class Grid {',
      '  public static int cells(int rows, int cols) {',
      '    int count = 0;',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '',
      '  public static int sumProducts(int rows, int cols) {',
      '    int total = 0;',
      '    for (int r = 1; r <= rows; r++) {',
      '      for (int c = 1; c <= cols; c++) {',
      '        total = total + r * c;',
      '      }',
      '    }',
      '    return total;',
      '  }',
      '',
      '  public static int countPairs(int n) {',
      '    int count = 0;',
      '    for (int i = 1; i <= n; i++) {',
      '      for (int j = i + 1; j <= n; j++) {',
      '        count = count + 1;',
      '      }',
      '    }',
      '    return count;',
      '  }',
      '',
      '  public static String rowLabel(int row, int cols) {',
      '    String out = "";',
      '    for (int c = 1; c <= cols; c++) {',
      '      if (c > 1) {',
      '        out = out + " ";',
      '      }',
      '      out = out + row * c;',
      '    }',
      '    return out;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '',
      '    System.out.println(Grid.cells(rows, cols));',
      '    System.out.println(Grid.sumProducts(rows, cols));',
      '    System.out.println(Grid.countPairs(rows));',
      '    System.out.println(Grid.rowLabel(rows, cols));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The accumulator belongs OUTSIDE both loops. Declaring it inside the outer loop resets it on every row and reports only the last row.',
      'Part (c) starts its inner loop at i + 1, which is what makes each pair count once rather than twice.',
      'Part (d) adds the space before each item after the first. Dropping the c > 1 guard puts a space at the very start of the line, which the driver does compare.',
    ],
    seo: 'AP CSA 2.11 FRQ practice: write nested loops over non square rectangles and build a separated row label with no trailing space.',
    mutants: [
      { describe: 'part (b) resets its accumulator inside the outer loop',
        find: '    int total = 0;\n    for (int r = 1; r <= rows; r++) {',
        replace: '    int total = 0;\n    for (int r = 1; r <= rows; r++) {\n      total = 0;' },
      { describe: 'part (a) swaps the two bounds, which only matters on a non square grid',
        find: '    for (int r = 0; r < rows; r++) {\n      for (int c = 0; c < cols; c++) {\n        count = count + 1;',
        replace: '    for (int r = 0; r < cols; r++) {\n      for (int c = 0; c < cols; c++) {\n        count = count + 1;' },
      { describe: 'part (c) starts the inner loop at i, counting each element with itself',
        find: 'for (int j = i + 1; j <= n; j++) {', replace: 'for (int j = i; j <= n; j++) {' },
      // Note: a TRAILING space is not a mutant here, because the grader
      // normalises trailing whitespace off every line before comparing. Only a
      // leading separator survives normalisation, so that is the mistake this
      // rubric row can actually score.
      { describe: 'part (d) puts the separator before every item, including the first',
        find: '      if (c > 1) {\n        out = out + " ";\n      }\n      out = out + row * c;',
        replace: '      out = out + " ";\n      out = out + row * c;' },
    ],
    cases: [
      // Every case is deliberately non square: a swapped bound is invisible on
      // a square grid and this question is entirely about swapped bounds.
      { stdin: '2 5\n', part: 1, hidden: 0 },
      { stdin: '3 2\n', part: 2, hidden: 0 },
      // Chosen for (c): rows of 1, where no pair exists at all.
      { stdin: '1 4\n', part: 3, hidden: 1 },
      // Chosen for (d): a single column, so a trailing space is the only
      // difference between right and wrong.
      { stdin: '4 1\n', part: 4, hidden: 1 },
      { stdin: '5 3\n', part: 3, hidden: 1 },
    ],
  },

  // ── 2.12 ───────────────────────────────────────────────────────────────────
  {
    lesson: '2.12', unit: U,
    title: 'Informal Run-Time Analysis',
    name: 'Counting the Work',
    mode: 'driver',
    frqType: 'methods-and-control',
    brief: 'Run-time analysis on this exam is literal: how many times does the statement inside the '
      + 'loop actually execute? Rather than asking for a name like "quadratic", this question asks you '
      + 'to COUNT, which is the same skill without the vocabulary in the way, and it is checkable.',
    given: 'Nothing is given. Write a class named Work containing exactly the four static methods '
      + 'described below. Assume n is at least 0. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'public static int singleLoop(int n) returns how many times the body of a loop running i from 0 while i < n executes.' },
      { label: '(b)', text: 'public static int nestedLoop(int n) returns how many times the inner body executes when both loops run from 0 while less than n.' },
      { label: '(c)', text: 'public static int triangleLoop(int n) returns how many times the inner body executes when the inner loop starts at i + 1 and runs while less than n.' },
      { label: '(d)', text: 'public static int halvingLoop(int n) returns how many times the body executes when the counter starts at n and is halved by integer division until it reaches 0.' },
    ],
    task: [
      'Write class Work with the four static methods exactly as described. No main method.',
      'Write the loops and count, rather than reasoning out a formula. The point of this lesson is that the count is something you can determine exactly.',
      'Part (d) must terminate. Halving by integer division reaches 0 from any starting value, but only if the counter actually changes on every pass.',
    ],
    starter: [
      'class Work {',
      '  // (a) singleLoop(int n) -> int',
      '',
      '  // (b) nestedLoop(int n) -> int',
      '',
      '  // (c) triangleLoop(int n) -> int',
      '',
      '  // (d) halvingLoop(int n) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Work {',
      '  public static int singleLoop(int n) {',
      '    int steps = 0;',
      '    for (int i = 0; i < n; i++) {',
      '      steps = steps + 1;',
      '    }',
      '    return steps;',
      '  }',
      '',
      '  public static int nestedLoop(int n) {',
      '    int steps = 0;',
      '    for (int i = 0; i < n; i++) {',
      '      for (int j = 0; j < n; j++) {',
      '        steps = steps + 1;',
      '      }',
      '    }',
      '    return steps;',
      '  }',
      '',
      '  public static int triangleLoop(int n) {',
      '    int steps = 0;',
      '    for (int i = 0; i < n; i++) {',
      '      for (int j = i + 1; j < n; j++) {',
      '        steps = steps + 1;',
      '      }',
      '    }',
      '    return steps;',
      '  }',
      '',
      '  public static int halvingLoop(int n) {',
      '    int steps = 0;',
      '    int value = n;',
      '    while (value > 0) {',
      '      steps = steps + 1;',
      '      value = value / 2;',
      '    }',
      '    return steps;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '',
      '    System.out.println(Work.singleLoop(n));',
      '    System.out.println(Work.nestedLoop(n));',
      '    System.out.println(Work.triangleLoop(n));',
      '    System.out.println(Work.halvingLoop(n));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Part (b) is n times n and part (c) is about half of that. Comparing the two numbers the driver prints is the whole insight of this lesson: the same nesting can do very different amounts of work.',
      'Every part returns 0 for n of 0, because none of the loops run. That is worth checking, because a formula written from memory often does not.',
      'Part (d) grows very slowly. Doubling n adds ONE step, which is what makes halving so much better than counting down by one.',
    ],
    seo: 'AP CSA 2.12 FRQ practice: count exactly how many times each loop body runs for single, nested, triangular and halving loops.',
    mutants: [
      { describe: 'part (c) starts the inner loop at i, counting the diagonal too',
        find: 'for (int j = i + 1; j < n; j++) {', replace: 'for (int j = i; j < n; j++) {' },
      { describe: 'part (d) counts one extra pass after the value reaches zero',
        find: '    int steps = 0;\n    int value = n;\n    while (value > 0) {', replace: '    int steps = 1;\n    int value = n;\n    while (value > 0) {' },
      { describe: 'part (b) runs the inner loop to a fixed bound instead of n',
        find: '      for (int j = 0; j < n; j++) {\n        steps = steps + 1;', replace: '      for (int j = 0; j < 3; j++) {\n        steps = steps + 1;' },
      { describe: 'part (a) counts one past the end',
        find: 'for (int i = 0; i < n; i++) {\n      steps = steps + 1;', replace: 'for (int i = 0; i <= n; i++) {\n      steps = steps + 1;' },
    ],
    cases: [
      { stdin: '4\n', part: 2, hidden: 0 },
      // Chosen for (a): n of 0, where every count must be 0.
      { stdin: '0\n', part: 1, hidden: 0 },
      // Chosen for (c): n of 1, where the nested count is 1 and the triangular
      // count is 0. A diagonal that should not be counted shows up here.
      { stdin: '1\n', part: 3, hidden: 1 },
      // Chosen for (d): a power of two boundary, where the halving count ticks over.
      { stdin: '8\n', part: 4, hidden: 1 },
      { stdin: '7\n', part: 4, hidden: 1 },
    ],
  },
];

module.exports = { FRQS };
