'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  AP CSA UNIT 3 FRQ PRACTICE: CLASS CREATION.
//
//  THIS IS THE UNIT THE `driver` MODE EXISTS FOR
//  Every free response question that says "write the class" is ungradeable in
//  any mode where the student owns the output, because a student can print the
//  expected answer without building anything. Here the hidden harness
//  constructs their object, calls their methods and prints what it observes.
//  Nothing the student prints is measured, so the only way through is to
//  actually store state and return it.
//
//  UNIT 3 FAILS SILENTLY, AND THE QUESTIONS ARE BUILT AROUND THAT
//  Units 1 and 2 fail loudly: wrong output, a crash, an off by one you can see.
//  A broken Unit 3 class compiles cleanly, looks textbook correct, and every
//  getter returns 0 or every counter returns 1. A student whose only debugging
//  technique is reading the error message has nothing to read.
//
//  So every mutant in this file is a bug that produces NO error message: a
//  constructor parameter that shadows the field it should set, an instance
//  counter that should have been static, a getter that hands out the object's
//  own array, a constructor written with a return type so it is quietly a
//  method instead. Those are the Unit 3 mistakes that actually reach a teacher.
//
//  THE HARNESS ALWAYS CALLS MORE THAN ONCE
//  A class bug that only shows on the second object (a static counter, a shared
//  reference, a field that was never assigned) is invisible to a harness that
//  builds one object. Every harness here builds at least two.
//
//  Nothing here states an expected output. scripts/verify-csa-frq.js runs each
//  `reference` through real javac/java to generate them.
// ─────────────────────────────────────────────────────────────────────────────

const U = 'unit-3';

const FRQS = [
  // ── 3.1 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.1', unit: U,
    title: 'Abstraction and Program Design',
    name: 'One Place for Each Fact',
    mode: 'driver',
    frqType: 'class',
    brief: 'Abstraction on the exam means the caller does not get to know how you stored anything. '
      + 'This class is asked for two facts that are really one: a total and a count. Store both and '
      + 'they will disagree the first time something changes; store the ingredients and compute the '
      + 'rest, and they cannot.',
    given: 'Nothing is given. Write a class named Tally. Do not write a main method: a hidden driver '
      + 'constructs your object, calls its methods, and prints what it observes.',
    parts: [
      { label: '(a)', text: 'A constructor Tally() that starts with nothing recorded.' },
      { label: '(b)', text: 'public void add(int value) records one more value.' },
      { label: '(c)', text: 'public int getCount() returns how many values have been recorded, and public int getTotal() returns their sum.' },
      { label: '(d)', text: 'public int getAverage() returns the total divided by the count using integer division, and 0 when nothing has been recorded.' },
    ],
    task: [
      'Write class Tally with the constructor and methods described. No main method.',
      'Part (d) must not divide by zero. A Tally with nothing in it returns 0 rather than crashing.',
      'Do not store the average. It is computed from the total and the count, and a stored copy is a third fact that can disagree with the other two.',
    ],
    starter: [
      'class Tally {',
      '  // fields',
      '',
      '  // (a) Tally()',
      '',
      '  // (b) add(int value)',
      '',
      '  // (c) getCount() -> int, getTotal() -> int',
      '',
      '  // (d) getAverage() -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Tally {',
      '  private int total;',
      '  private int count;',
      '',
      '  public Tally() {',
      '    total = 0;',
      '    count = 0;',
      '  }',
      '',
      '  public void add(int value) {',
      '    total = total + value;',
      '    count = count + 1;',
      '  }',
      '',
      '  public int getCount() {',
      '    return count;',
      '  }',
      '',
      '  public int getTotal() {',
      '    return total;',
      '  }',
      '',
      '  public int getAverage() {',
      '    if (count == 0) {',
      '      return 0;',
      '    }',
      '    return total / count;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '',
      '    Tally empty = new Tally();',
      '    System.out.println(empty.getCount());',
      '    System.out.println(empty.getAverage());',
      '',
      '    Tally t = new Tally();',
      '    for (int i = 0; i < n; i++) {',
      '      t.add(input.nextInt());',
      '    }',
      '    System.out.println(t.getCount());',
      '    System.out.println(t.getTotal());',
      '    System.out.println(t.getAverage());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The driver builds an EMPTY Tally first and asks it for an average. If your getAverage divides without checking, that call throws ArithmeticException before anything else is printed.',
      'add changes two fields at once. Forgetting to increment the count gives a total that looks right and an average that is wildly wrong, with no error message.',
      'Integer division is what the question asks for. 7 / 2 is 3, and no rounding is wanted.',
    ],
    seo: 'AP CSA 3.1 FRQ practice: design a Tally class that stores only what it must and computes the rest, including an empty average.',
    mutants: [
      { describe: 'getAverage divides without guarding the empty case, so an empty Tally throws',
        find: '    if (count == 0) {\n      return 0;\n    }\n    return total / count;', replace: '    return total / count;' },
      { describe: 'add forgets to increment the count',
        find: '    total = total + value;\n    count = count + 1;', replace: '    total = total + value;' },
      { describe: 'add counts but never accumulates the total',
        find: '    total = total + value;\n    count = count + 1;', replace: '    count = count + 1;' },
    ],
    cases: [
      { stdin: '4\n10 20 30 41\n', part: 3, hidden: 0 },
      // Chosen for (d): a single value, so the average equals the total.
      { stdin: '1\n7\n', part: 4, hidden: 0 },
      // Chosen for (d): a total that does not divide evenly by the count.
      { stdin: '3\n1 1 2\n', part: 4, hidden: 1 },
      // Chosen for (b): nothing added at all, so both Tally objects are empty
      // and the guard in getAverage is the only thing standing.
      { stdin: '0\n', part: 2, hidden: 1 },
      // Chosen for (a): negatives, which a total seeded wrongly cannot fake.
      { stdin: '2\n-5 -9\n', part: 1, hidden: 1 },
    ],
  },

  // ── 3.2 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.2', unit: U,
    title: 'Impact of Program Design',
    name: 'Changing the Rule in One Place',
    mode: 'driver',
    frqType: 'class',
    brief: 'A design is good when a rule change touches one method. This class applies the same '
      + 'threshold in three places, and the question is written so that a student who copies the '
      + 'comparison three times still passes the visible cases and fails the hidden one where the '
      + 'threshold is different.',
    given: 'Nothing is given. Write a class named Grader. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'A constructor Grader(int threshold) that remembers the passing threshold.' },
      { label: '(b)', text: 'public boolean passes(int score) returns whether score is at least the threshold.' },
      { label: '(c)', text: 'public String label(int score) returns "PASS" or "FAIL", decided by part (b).' },
      { label: '(d)', text: 'public int countPassing(int a, int b, int c) returns how many of the three scores pass, decided by part (b).' },
    ],
    task: [
      'Write class Grader with the constructor and methods described. No main method.',
      'Parts (c) and (d) must call part (b). The threshold comparison is written ONCE, in passes.',
      '"At least" includes the threshold itself.',
    ],
    starter: [
      'class Grader {',
      '  // field',
      '',
      '  // (a) Grader(int threshold)',
      '',
      '  // (b) passes(int score) -> boolean',
      '',
      '  // (c) label(int score) -> String',
      '',
      '  // (d) countPassing(int a, int b, int c) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Grader {',
      '  private int threshold;',
      '',
      '  public Grader(int threshold) {',
      '    this.threshold = threshold;',
      '  }',
      '',
      '  public boolean passes(int score) {',
      '    return score >= threshold;',
      '  }',
      '',
      '  public String label(int score) {',
      '    if (passes(score)) {',
      '      return "PASS";',
      '    }',
      '    return "FAIL";',
      '  }',
      '',
      '  public int countPassing(int a, int b, int c) {',
      '    int count = 0;',
      '    if (passes(a)) {',
      '      count = count + 1;',
      '    }',
      '    if (passes(b)) {',
      '      count = count + 1;',
      '    }',
      '    if (passes(c)) {',
      '      count = count + 1;',
      '    }',
      '    return count;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int threshold = input.nextInt();',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '    int c = input.nextInt();',
      '',
      '    Grader g = new Grader(threshold);',
      '    System.out.println(g.passes(a));',
      '    System.out.println(g.label(b));',
      '    System.out.println(g.countPassing(a, b, c));',
      '',
      '    Grader strict = new Grader(threshold + 20);',
      '    System.out.println(strict.countPassing(a, b, c));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The driver builds a SECOND Grader with a different threshold and asks it the same question. A comparison hardcoded to 60 passes the first object and fails the second.',
      'this.threshold = threshold; is how a constructor parameter and a field with the same name are told apart. Writing threshold = threshold; assigns the parameter to itself and leaves the field at 0.',
      'countPassing is three calls to passes. Repeating the comparison inside it is the design mistake the second Grader is there to catch.',
    ],
    seo: 'AP CSA 3.2 FRQ practice: write the threshold rule once and reuse it, so a second object with a different threshold still answers correctly.',
    // The shadowing hint has to be able to show the idiom it is teaching. This
    // one line is boilerplate every constructor in Unit 3 uses, not the answer
    // to this question, which is the reuse of passes() by the other methods.
    teaches: ['this.threshold = threshold;'],
    mutants: [
      { describe: 'the constructor assigns the parameter to itself, leaving the field at 0',
        find: 'this.threshold = threshold;', replace: 'threshold = threshold;' },
      { describe: 'countPassing hardcodes the threshold instead of calling passes',
        find: '    if (passes(a)) {\n      count = count + 1;\n    }\n    if (passes(b)) {',
        replace: '    if (a >= 60) {\n      count = count + 1;\n    }\n    if (passes(b)) {' },
      { describe: 'passes excludes the threshold itself',
        find: 'return score >= threshold;', replace: 'return score > threshold;' },
      { describe: 'label returns the two verdicts the wrong way round',
        find: '    if (passes(score)) {\n      return "PASS";\n    }\n    return "FAIL";',
        replace: '    if (passes(score)) {\n      return "FAIL";\n    }\n    return "PASS";' },
    ],
    cases: [
      { stdin: '60 75 55 90\n', part: 2, hidden: 0 },
      // Chosen for (b): a score EXACTLY on the threshold.
      { stdin: '70 70 69 71\n', part: 2, hidden: 0 },
      // Chosen for (d): the stricter second Grader excludes scores the first
      // accepted, which a hardcoded 60 cannot reproduce.
      { stdin: '50 55 65 75\n', part: 4, hidden: 1 },
      // Chosen for (a): a threshold of 0, where an unassigned field would
      // accidentally be correct, paired with a nonzero threshold elsewhere.
      { stdin: '0 -5 0 5\n', part: 1, hidden: 1 },
      // Chosen for (c): all three below the threshold.
      { stdin: '90 10 20 30\n', part: 3, hidden: 1 },
    ],
  },

  // ── 3.3 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.3', unit: U,
    title: 'Anatomy of a Class',
    name: 'Fields, Not Locals',
    mode: 'driver',
    frqType: 'class',
    brief: 'The difference between a field and a local variable is the difference between a class that '
      + 'remembers and one that does not, and Java will not warn you which you wrote. A local declared '
      + 'inside a method shadows the field of the same name, the method compiles, and every getter '
      + 'afterwards returns the field it never touched.',
    given: 'Nothing is given. Write a class named Locker. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'A constructor Locker(String owner, int capacity) that stores both.' },
      { label: '(b)', text: 'public String getOwner() and public int getCapacity() return what was stored.' },
      { label: '(c)', text: 'public void store(int items) adds items to what is inside, never letting the contents exceed the capacity.' },
      { label: '(d)', text: 'public int getContents() returns how much is inside, and public int getSpace() returns how much room is left.' },
    ],
    task: [
      'Write class Locker with the constructor and methods described. No main method.',
      'A new Locker is empty. Storing more than fits fills it to capacity and discards the rest rather than overflowing.',
      'The contents belong to the object, not to the store method. A count declared inside store is forgotten the moment store returns.',
    ],
    starter: [
      'class Locker {',
      '  // fields',
      '',
      '  // (a) Locker(String owner, int capacity)',
      '',
      '  // (b) getOwner() -> String, getCapacity() -> int',
      '',
      '  // (c) store(int items)',
      '',
      '  // (d) getContents() -> int, getSpace() -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Locker {',
      '  private String owner;',
      '  private int capacity;',
      '  private int contents;',
      '',
      '  public Locker(String owner, int capacity) {',
      '    this.owner = owner;',
      '    this.capacity = capacity;',
      '    this.contents = 0;',
      '  }',
      '',
      '  public String getOwner() {',
      '    return owner;',
      '  }',
      '',
      '  public int getCapacity() {',
      '    return capacity;',
      '  }',
      '',
      '  public void store(int items) {',
      '    contents = contents + items;',
      '    if (contents > capacity) {',
      '      contents = capacity;',
      '    }',
      '  }',
      '',
      '  public int getContents() {',
      '    return contents;',
      '  }',
      '',
      '  public int getSpace() {',
      '    return capacity - contents;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String owner = input.next();',
      '    int capacity = input.nextInt();',
      '    int first = input.nextInt();',
      '    int second = input.nextInt();',
      '',
      '    Locker locker = new Locker(owner, capacity);',
      '    System.out.println(locker.getOwner());',
      '    System.out.println(locker.getCapacity());',
      '    System.out.println(locker.getContents());',
      '',
      '    locker.store(first);',
      '    System.out.println(locker.getContents());',
      '    locker.store(second);',
      '    System.out.println(locker.getContents());',
      '    System.out.println(locker.getSpace());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The driver calls store TWICE and asks for the contents in between. A store method that keeps its running total in a local variable prints the first amount and then the second amount, never their sum.',
      'Declaring int contents = 0; inside store creates a NEW variable that hides the field. It compiles, it runs, and the field stays at 0 forever.',
      'getSpace is derived from the capacity and the contents. Storing it as a fourth field means two numbers that can disagree.',
    ],
    seo: 'AP CSA 3.3 FRQ practice: store state in fields rather than locals, so a Locker remembers its contents between two calls.',
    mutants: [
      { describe: 'store keeps its total in a local that shadows the field',
        find: '    contents = contents + items;\n    if (contents > capacity) {\n      contents = capacity;\n    }',
        replace: '    int contents = items;\n    if (contents > capacity) {\n      contents = capacity;\n    }' },
      { describe: 'store lets the contents exceed the capacity',
        find: '    if (contents > capacity) {\n      contents = capacity;\n    }', replace: '' },
      { describe: 'the constructor never assigns the capacity field',
        find: '    this.capacity = capacity;\n    this.contents = 0;', replace: '    this.contents = 0;' },
      { describe: 'getSpace returns the contents rather than the room left',
        find: 'return capacity - contents;', replace: 'return contents;' },
    ],
    cases: [
      { stdin: 'ana 100 30 45\n', part: 2, hidden: 0 },
      // Chosen for (c): the second store OVERFLOWS, so the cap matters.
      { stdin: 'bo 50 40 30\n', part: 3, hidden: 0 },
      // Chosen for (d): fills exactly to capacity, so the space left is 0.
      { stdin: 'cy 20 10 10\n', part: 4, hidden: 1 },
      // Chosen for (a): storing nothing at all, so only the constructor is tested.
      { stdin: 'dee 7 0 0\n', part: 1, hidden: 1 },
      // Chosen for (c): the FIRST store already overflows on its own.
      { stdin: 'eli 5 99 1\n', part: 3, hidden: 1 },
    ],
  },

  // ── 3.4 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.4', unit: U,
    title: 'Constructors',
    name: 'Two Ways to Build',
    mode: 'driver',
    frqType: 'class',
    brief: 'A constructor has no return type. Give it one and it silently becomes an ordinary method '
      + 'with the same name as the class, the compiler accepts it, every object is built by the '
      + 'default constructor instead, and every field is 0 or null. There is no error message '
      + 'anywhere in that sentence, which is why it is worth a question of its own.',
    given: 'Nothing is given. Write a class named Ticket. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'A constructor Ticket(String event, int price) that stores both.' },
      { label: '(b)', text: 'A constructor Ticket(String event) that stores the event with a price of 10.' },
      { label: '(c)', text: 'public String getEvent() and public int getPrice() return what was stored.' },
      { label: '(d)', text: 'public String describe() returns the event, a space, then the price.' },
    ],
    task: [
      'Write class Ticket with the two constructors and the methods described. No main method.',
      'The one argument constructor should call the two argument one rather than repeating the assignments. this(event, 10); is how, and it must be the first statement.',
      'A constructor is named exactly like the class and has NO return type, not even void.',
    ],
    starter: [
      'class Ticket {',
      '  // fields',
      '',
      '  // (a) Ticket(String event, int price)',
      '',
      '  // (b) Ticket(String event), price defaults to 10',
      '',
      '  // (c) getEvent() -> String, getPrice() -> int',
      '',
      '  // (d) describe() -> String',
      '}',
    ].join('\n'),
    reference: [
      'class Ticket {',
      '  private String event;',
      '  private int price;',
      '',
      '  public Ticket(String event, int price) {',
      '    this.event = event;',
      '    this.price = price;',
      '  }',
      '',
      '  public Ticket(String event) {',
      '    this(event, 10);',
      '  }',
      '',
      '  public String getEvent() {',
      '    return event;',
      '  }',
      '',
      '  public int getPrice() {',
      '    return price;',
      '  }',
      '',
      '  public String describe() {',
      '    return event + " " + price;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String event = input.next();',
      '    int price = input.nextInt();',
      '    String other = input.next();',
      '',
      '    Ticket full = new Ticket(event, price);',
      '    System.out.println(full.getEvent());',
      '    System.out.println(full.getPrice());',
      '    System.out.println(full.describe());',
      '',
      '    Ticket cheap = new Ticket(other);',
      '    System.out.println(cheap.getPrice());',
      '    System.out.println(cheap.describe());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'public void Ticket(String event, int price) is NOT a constructor. It is a method that happens to share the name of the class, and every object then gets built by the invisible default constructor with all fields at 0 and null.',
      'this(event, 10); calls your other constructor. It has to be the very first statement in the body.',
      'The driver builds both kinds of Ticket. A one argument constructor that forgets the default price prints 0 rather than 10.',
    ],
    seo: 'AP CSA 3.4 FRQ practice: write two constructors, chain one to the other with this, and avoid the silent return type mistake.',
    mutants: [
      { describe: 'the one argument constructor forgets the default price',
        find: '  public Ticket(String event) {\n    this(event, 10);\n  }', replace: '  public Ticket(String event) {\n    this.event = event;\n  }' },
      { describe: 'the two argument constructor shadows its own fields',
        find: '    this.event = event;\n    this.price = price;', replace: '    event = event;\n    price = price;' },
      { describe: 'describe omits the separating space',
        find: 'return event + " " + price;', replace: 'return event + price;' },
      { describe: 'the default price is 1 rather than 10',
        find: 'this(event, 10);', replace: 'this(event, 1);' },
    ],
    cases: [
      { stdin: 'Concert 45 Matinee\n', part: 1, hidden: 0 },
      // Chosen for (b): the explicit price EQUALS the default, so only the
      // second object can tell a missing default from a working one.
      { stdin: 'Gala 10 Preview\n', part: 2, hidden: 0 },
      // Chosen for (d): a price of 0, which is what an unassigned field holds.
      { stdin: 'Free 0 Trial\n', part: 4, hidden: 1 },
      { stdin: 'Opening 250 Rehearsal\n', part: 3, hidden: 1 },
      { stdin: 'Late 7 Early\n', part: 2, hidden: 1 },
    ],
  },

  // ── 3.5 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.5', unit: U,
    title: 'Methods: How to Write Them',
    name: 'Return, Do Not Print',
    mode: 'driver',
    frqType: 'class',
    brief: 'A void method that prints and an int method that returns look equally correct on a screen. '
      + 'Only one of them can be used by the code that called it. This question is graded entirely on '
      + 'what your methods hand back, so a class that prints the right answers scores zero, which is '
      + 'exactly what happens in May.',
    given: 'Nothing is given. Write a class named Account. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'A constructor Account(int balance) that stores the opening balance.' },
      { label: '(b)', text: 'public void deposit(int amount) adds amount to the balance, ignoring any amount that is zero or negative.' },
      { label: '(c)', text: 'public boolean withdraw(int amount) takes amount out and returns true, or changes nothing and returns false when the amount is more than the balance or is not positive.' },
      { label: '(d)', text: 'public int getBalance() returns the current balance.' },
    ],
    task: [
      'Write class Account with the constructor and methods described. No main method.',
      'Part (c) returns whether the withdrawal happened. A method that prints "declined" and returns nothing cannot be used by the driver at all.',
      'A refused withdrawal must leave the balance untouched. Deducting and then refusing is the bug this part is looking for.',
    ],
    starter: [
      'class Account {',
      '  // field',
      '',
      '  // (a) Account(int balance)',
      '',
      '  // (b) deposit(int amount)',
      '',
      '  // (c) withdraw(int amount) -> boolean',
      '',
      '  // (d) getBalance() -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Account {',
      '  private int balance;',
      '',
      '  public Account(int balance) {',
      '    this.balance = balance;',
      '  }',
      '',
      '  public void deposit(int amount) {',
      '    if (amount > 0) {',
      '      balance = balance + amount;',
      '    }',
      '  }',
      '',
      '  public boolean withdraw(int amount) {',
      '    if (amount <= 0 || amount > balance) {',
      '      return false;',
      '    }',
      '    balance = balance - amount;',
      '    return true;',
      '  }',
      '',
      '  public int getBalance() {',
      '    return balance;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int opening = input.nextInt();',
      '    int deposit = input.nextInt();',
      '    int take = input.nextInt();',
      '',
      '    Account a = new Account(opening);',
      '    a.deposit(deposit);',
      '    System.out.println(a.getBalance());',
      '    System.out.println(a.withdraw(take));',
      '    System.out.println(a.getBalance());',
      '    System.out.println(a.withdraw(take));',
      '    System.out.println(a.getBalance());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The driver withdraws the SAME amount twice. If the first succeeds and drains the account, the second must return false and leave the balance where it is.',
      'Deducting first and checking afterwards leaves the balance wrong on every refusal, and the getBalance line right after the false is where it shows.',
      'A withdrawal of exactly the whole balance is allowed. Only more than the balance is refused.',
    ],
    seo: 'AP CSA 3.5 FRQ practice: write methods that return their result rather than printing it, and leave state untouched when refusing.',
    mutants: [
      { describe: 'withdraw deducts before checking, so a refused withdrawal still moves the balance',
        find: '    if (amount <= 0 || amount > balance) {\n      return false;\n    }\n    balance = balance - amount;\n    return true;',
        replace: '    balance = balance - amount;\n    if (amount <= 0 || balance < 0) {\n      return false;\n    }\n    return true;' },
      { describe: 'withdraw refuses an amount equal to the whole balance',
        find: 'if (amount <= 0 || amount > balance) {', replace: 'if (amount <= 0 || amount >= balance) {' },
      { describe: 'deposit accepts negative amounts',
        find: '    if (amount > 0) {\n      balance = balance + amount;\n    }', replace: '    balance = balance + amount;' },
      { describe: 'withdraw always reports success',
        find: '      return false;\n    }\n    balance = balance - amount;\n    return true;', replace: '      return true;\n    }\n    balance = balance - amount;\n    return true;' },
    ],
    cases: [
      { stdin: '100 50 60\n', part: 3, hidden: 0 },
      // Chosen for (c): the withdrawal is EXACTLY the balance, which is allowed,
      // and the second attempt on an empty account must be refused.
      { stdin: '40 60 100\n', part: 3, hidden: 0 },
      // Chosen for (b): a negative deposit, which must be ignored.
      { stdin: '80 -30 20\n', part: 2, hidden: 1 },
      // Chosen for (c): a withdrawal of 0, refused as not positive.
      { stdin: '25 25 0\n', part: 3, hidden: 1 },
      // Chosen for (a): an opening balance of 0 with nothing added.
      { stdin: '0 0 5\n', part: 1, hidden: 1 },
      // Chosen for (d): a large balance never withdrawn from, so getBalance is
      // the only part whose answer this row pins down.
      { stdin: '500 250 10\n', part: 4, hidden: 1 },
    ],
  },

  // ── 3.6 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.6', unit: U,
    title: 'Methods: Passing and Returning Object References',
    name: 'The Half Fix',
    mode: 'driver',
    frqType: 'class',
    brief: 'When a method returns the object\'s own array, the caller can change the object from '
      + 'outside it, and nothing in the class can stop them. Students usually find half of this: they '
      + 'copy on the way OUT and not on the way IN, or the reverse. A half fixed class is what actually '
      + 'gets handed in, so that is what this question is built to detect.',
    given: 'Nothing is given. Write a class named Roster. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'A constructor Roster(int[] scores) that stores a COPY of the array it is given.' },
      { label: '(b)', text: 'public int[] getScores() returns a COPY of the stored array.' },
      { label: '(c)', text: 'public int get(int index) returns the stored value at that index.' },
      { label: '(d)', text: 'public int size() returns how many scores are stored.' },
    ],
    task: [
      'Write class Roster with the constructor and methods described. No main method.',
      'Both directions need a copy. The driver changes the array it handed you AND changes the array you handed back, then asks what you have stored.',
      'Copy by looping and assigning element by element. A new array of the same length, filled in a loop, is all that is needed.',
    ],
    starter: [
      'class Roster {',
      '  // field',
      '',
      '  // (a) Roster(int[] scores), storing a copy',
      '',
      '  // (b) getScores() -> int[], returning a copy',
      '',
      '  // (c) get(int index) -> int',
      '',
      '  // (d) size() -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Roster {',
      '  private int[] scores;',
      '',
      '  public Roster(int[] scores) {',
      '    this.scores = new int[scores.length];',
      '    for (int i = 0; i < scores.length; i++) {',
      '      this.scores[i] = scores[i];',
      '    }',
      '  }',
      '',
      '  public int[] getScores() {',
      '    int[] copy = new int[scores.length];',
      '    for (int i = 0; i < scores.length; i++) {',
      '      copy[i] = scores[i];',
      '    }',
      '    return copy;',
      '  }',
      '',
      '  public int get(int index) {',
      '    return scores[index];',
      '  }',
      '',
      '  public int size() {',
      '    return scores.length;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    int[] data = new int[n];',
      '    for (int i = 0; i < n; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int poison = input.nextInt();',
      '',
      '    Roster r = new Roster(data);',
      '    System.out.println(r.size());',
      '    System.out.println(r.get(0));',
      '',
      '    data[0] = poison;',
      '    System.out.println(r.get(0));',
      '',
      '    int[] handed = r.getScores();',
      '    handed[0] = poison;',
      '    System.out.println(r.get(0));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The driver pokes at the array it gave you, then pokes at the array you gave it, and asks for element 0 after each. Only a class that copied in BOTH directions gives the same answer all three times.',
      'this.scores = scores; stores the caller\'s array itself, not a copy. Every later change they make is a change to your object.',
      'A copy is a new array plus a loop. new int[scores.length] then assign each element across.',
    ],
    seo: 'AP CSA 3.6 FRQ practice: copy an array into and out of a class so no caller can reach in and change its private state.',
    mutants: [
      { describe: 'the constructor stores the caller array itself, so changing it changes the object',
        find: '    this.scores = new int[scores.length];\n    for (int i = 0; i < scores.length; i++) {\n      this.scores[i] = scores[i];\n    }',
        replace: '    this.scores = scores;' },
      { describe: 'getScores hands out the object\'s own array, the half fix students actually write',
        find: '    int[] copy = new int[scores.length];\n    for (int i = 0; i < scores.length; i++) {\n      copy[i] = scores[i];\n    }\n    return copy;',
        replace: '    return scores;' },
      { describe: 'size returns a fixed length rather than the array\'s',
        find: 'return scores.length;', replace: 'return 3;' },
    ],
    cases: [
      { stdin: '4\n10 20 30 40\n99\n', part: 1, hidden: 0 },
      // Chosen for (d): a length that is NOT 3, so a hardcoded size shows up.
      { stdin: '2\n5 6\n77\n', part: 4, hidden: 0 },
      // Chosen for (b): a single element, the smallest array that can still be
      // poisoned from outside.
      { stdin: '1\n8\n-1\n', part: 2, hidden: 1 },
      // Chosen for (c): the poison value EQUALS the original first element, so
      // a leaked reference is invisible here. Paired with the rows above, this
      // is the case that proves the others are doing the work.
      { stdin: '3\n7 8 9\n7\n', part: 3, hidden: 1 },
      { stdin: '5\n1 2 3 4 5\n1000\n', part: 2, hidden: 1 },
    ],
  },

  // ── 3.7 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.7', unit: U,
    title: 'Class Variables and Methods',
    name: 'Shared or Not',
    mode: 'driver',
    frqType: 'class',
    brief: 'A static field belongs to the class and an instance field belongs to each object, and '
      + 'choosing wrong produces a counter that says 1 forever or a serial number that every object '
      + 'shares. Both compile. Both look right until you build the second object, which is why the '
      + 'driver here builds three.',
    given: 'Nothing is given. Write a class named Badge. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'A constructor Badge(String name) that stores the name and assigns this badge the next serial number, starting at 1.' },
      { label: '(b)', text: 'public String getName() and public int getSerial() return this badge\'s own values.' },
      { label: '(c)', text: 'public static int getIssued() returns how many Badge objects have been made in total.' },
      { label: '(d)', text: 'public static void reset() sets the issued count back to 0, so the next badge is serial 1 again.' },
    ],
    task: [
      'Write class Badge with the constructor and methods described. No main method.',
      'The count of badges issued belongs to the CLASS. The serial number belongs to each OBJECT.',
      'Part (c) and part (d) are static, so they are called on Badge itself rather than on a badge.',
    ],
    starter: [
      'class Badge {',
      '  // fields: which is static, which is not?',
      '',
      '  // (a) Badge(String name)',
      '',
      '  // (b) getName() -> String, getSerial() -> int',
      '',
      '  // (c) static getIssued() -> int',
      '',
      '  // (d) static reset()',
      '}',
    ].join('\n'),
    reference: [
      'class Badge {',
      '  private static int issued = 0;',
      '  private String name;',
      '  private int serial;',
      '',
      '  public Badge(String name) {',
      '    this.name = name;',
      '    issued = issued + 1;',
      '    this.serial = issued;',
      '  }',
      '',
      '  public String getName() {',
      '    return name;',
      '  }',
      '',
      '  public int getSerial() {',
      '    return serial;',
      '  }',
      '',
      '  public static int getIssued() {',
      '    return issued;',
      '  }',
      '',
      '  public static void reset() {',
      '    issued = 0;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String a = input.next();',
      '    String b = input.next();',
      '    String c = input.next();',
      '',
      '    Badge first = new Badge(a);',
      '    Badge second = new Badge(b);',
      '    System.out.println(first.getSerial());',
      '    System.out.println(second.getSerial());',
      '    System.out.println(Badge.getIssued());',
      '    System.out.println(first.getName());',
      '',
      '    Badge.reset();',
      '    Badge third = new Badge(c);',
      '    System.out.println(third.getSerial());',
      '    System.out.println(Badge.getIssued());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The driver prints the serial of the FIRST badge after building the second. If the serial is static, both badges share it and the first one has silently changed.',
      'The count is incremented before the serial is read, which is what makes the first badge serial 1 rather than 0.',
      'A static method cannot read an instance field, and the compiler will say so. That error is a useful signal that you put a field on the wrong side.',
    ],
    seo: 'AP CSA 3.7 FRQ practice: decide which fields are static and which belong to each object, proven with three badges and a reset.',
    mutants: [
      { describe: 'the serial number is static, so every badge shares one number',
        find: '  private String name;\n  private int serial;', replace: '  private String name;\n  private static int serial;' },
      { describe: 'the serial is read before the count is incremented, so the first badge is 0',
        find: '    issued = issued + 1;\n    this.serial = issued;', replace: '    this.serial = issued;\n    issued = issued + 1;' },
      { describe: 'the issued count is an instance field, so it is 1 for every badge',
        find: '  private static int issued = 0;', replace: '  private int issued = 0;' },
      { describe: 'reset does not actually clear the count',
        find: '  public static void reset() {\n    issued = 0;\n  }', replace: '  public static void reset() {\n  }' },
    ],
    cases: [
      { stdin: 'ana bo cy\n', part: 1, hidden: 0 },
      // Chosen for (b): distinct names, so a shared name field is visible.
      { stdin: 'zed yan xu\n', part: 2, hidden: 0 },
      // Chosen for (c): identical names, so ONLY the numbers can distinguish a
      // correct class from one that shares its instance state.
      { stdin: 'same same same\n', part: 3, hidden: 1 },
      { stdin: 'q r s\n', part: 4, hidden: 1 },
      { stdin: 'alpha beta gamma\n', part: 4, hidden: 1 },
    ],
  },

  // ── 3.8 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.8', unit: U,
    title: 'Scope and Access',
    name: 'What the Name Reaches',
    mode: 'driver',
    frqType: 'class',
    brief: 'Which variable a name reaches is decided by where it was declared, not by what it is '
      + 'called. A parameter named like a field hides that field for the whole method, and the method '
      + 'still compiles and still runs. Every part of this question is a place that mistake can hide.',
    given: 'Nothing is given. Write a class named Counter. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'A constructor Counter(int start, int step) that stores both, where step is how much each bump adds.' },
      { label: '(b)', text: 'public void bump() adds step to the current value.' },
      { label: '(c)', text: 'public void bumpBy(int step) adds THAT step to the current value, without changing the stored step.' },
      { label: '(d)', text: 'public int getValue() and public int getStep() return the current value and the stored step.' },
    ],
    task: [
      'Write class Counter with the constructor and methods described. No main method.',
      'Part (c) takes a parameter called step, which hides the field of the same name for that whole method. Adding the parameter is correct here; changing the FIELD is not.',
      'After a call to bumpBy, getStep must still return the value the constructor was given.',
    ],
    starter: [
      'class Counter {',
      '  // fields',
      '',
      '  // (a) Counter(int start, int step)',
      '',
      '  // (b) bump()',
      '',
      '  // (c) bumpBy(int step)',
      '',
      '  // (d) getValue() -> int, getStep() -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Counter {',
      '  private int value;',
      '  private int step;',
      '',
      '  public Counter(int start, int step) {',
      '    this.value = start;',
      '    this.step = step;',
      '  }',
      '',
      '  public void bump() {',
      '    value = value + step;',
      '  }',
      '',
      '  public void bumpBy(int step) {',
      '    value = value + step;',
      '  }',
      '',
      '  public int getValue() {',
      '    return value;',
      '  }',
      '',
      '  public int getStep() {',
      '    return this.step;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int start = input.nextInt();',
      '    int step = input.nextInt();',
      '    int once = input.nextInt();',
      '',
      '    Counter c = new Counter(start, step);',
      '    System.out.println(c.getValue());',
      '    System.out.println(c.getStep());',
      '    c.bump();',
      '    System.out.println(c.getValue());',
      '    c.bumpBy(once);',
      '    System.out.println(c.getValue());',
      '    System.out.println(c.getStep());',
      '    c.bump();',
      '    System.out.println(c.getValue());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The driver calls bump AFTER bumpBy and asks for the value again. If bumpBy overwrote the stored step, that last bump adds the wrong amount and the mistake finally becomes visible.',
      'Inside bumpBy, the bare name step means the parameter. To reach the field you would have to write this.step, which is exactly what this method must NOT change.',
      'The constructor has the same collision. this.step = step; assigns the parameter to the field; step = step; assigns the parameter to itself and leaves the field at 0.',
    ],
    seo: 'AP CSA 3.8 FRQ practice: work out which variable a name reaches when a parameter shadows a field, and leave the field unchanged.',
    mutants: [
      { describe: 'bumpBy overwrites the stored step with the parameter',
        find: '  public void bumpBy(int step) {\n    value = value + step;\n  }', replace: '  public void bumpBy(int step) {\n    this.step = step;\n    value = value + step;\n  }' },
      { describe: 'the constructor assigns the step parameter to itself, leaving the field at 0',
        find: '    this.value = start;\n    this.step = step;', replace: '    this.value = start;\n    step = step;' },
      { describe: 'bump adds 1 instead of the stored step',
        find: '  public void bump() {\n    value = value + step;\n  }', replace: '  public void bump() {\n    value = value + 1;\n  }' },
    ],
    cases: [
      { stdin: '0 5 100\n', part: 1, hidden: 0 },
      // Chosen for (c): the one-off amount DIFFERS from the stored step, which
      // is the only way an overwritten field shows up on the final bump.
      { stdin: '10 3 50\n', part: 3, hidden: 0 },
      // Chosen for (b): a step of 1, where bump adding 1 is accidentally right.
      // Paired with the rows above, which have steps other than 1.
      { stdin: '7 1 9\n', part: 2, hidden: 1 },
      // Chosen for (d): a negative step, counting down.
      { stdin: '100 -4 -20\n', part: 4, hidden: 1 },
      // Chosen for (c): the one-off amount EQUALS the stored step, so an
      // overwrite is invisible in this row alone.
      { stdin: '2 6 6\n', part: 3, hidden: 1 },
    ],
  },

  // ── 3.9 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.9', unit: U,
    title: 'The this Keyword',
    name: 'Which Object Am I',
    mode: 'driver',
    frqType: 'class',
    brief: 'this is the object the method was called on, and it becomes necessary the moment a method '
      + 'takes another object of the same class as a parameter. Inside a comparison of two Points, '
      + 'a bare field name means MINE and the parameter\'s field means theirs, and getting that '
      + 'backwards produces an answer that is right whenever the two happen to be equal.',
    given: 'Nothing is given. Write a class named Point. Do not write a main method.',
    parts: [
      { label: '(a)', text: 'A constructor Point(int x, int y) that stores both, using this to tell the parameters from the fields.' },
      { label: '(b)', text: 'public int getX() and public int getY() return this point\'s coordinates.' },
      { label: '(c)', text: 'public boolean sameAs(Point other) returns whether both coordinates match.' },
      { label: '(d)', text: 'public int distanceTo(Point other) returns the horizontal distance plus the vertical distance, never negative.' },
    ],
    task: [
      'Write class Point with the constructor and methods described. No main method.',
      'In part (c) and part (d), the bare names x and y mean THIS point. The other point\'s values come through other.',
      'Part (d) must never be negative. Math.abs on each difference does that without an if.',
    ],
    starter: [
      'class Point {',
      '  // fields',
      '',
      '  // (a) Point(int x, int y)',
      '',
      '  // (b) getX() -> int, getY() -> int',
      '',
      '  // (c) sameAs(Point other) -> boolean',
      '',
      '  // (d) distanceTo(Point other) -> int',
      '}',
    ].join('\n'),
    reference: [
      'class Point {',
      '  private int x;',
      '  private int y;',
      '',
      '  public Point(int x, int y) {',
      '    this.x = x;',
      '    this.y = y;',
      '  }',
      '',
      '  public int getX() {',
      '    return x;',
      '  }',
      '',
      '  public int getY() {',
      '    return y;',
      '  }',
      '',
      '  public boolean sameAs(Point other) {',
      '    return x == other.getX() && y == other.getY();',
      '  }',
      '',
      '  public int distanceTo(Point other) {',
      '    return Math.abs(x - other.getX()) + Math.abs(y - other.getY());',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int ax = input.nextInt();',
      '    int ay = input.nextInt();',
      '    int bx = input.nextInt();',
      '    int by = input.nextInt();',
      '',
      '    Point a = new Point(ax, ay);',
      '    Point b = new Point(bx, by);',
      '    System.out.println(a.getX());',
      '    System.out.println(a.getY());',
      '    System.out.println(a.sameAs(b));',
      '    System.out.println(a.distanceTo(b));',
      '    System.out.println(b.distanceTo(a));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The driver measures the distance in BOTH directions. A method that subtracts without taking the magnitude gives a negative answer one of those two times.',
      'A constructor whose parameters are named like its fields needs this on the left of each assignment. Without it, both assignments do nothing at all.',
      'Comparing two points needs both coordinates. Checking only x is correct whenever the y values happen to agree, which is exactly the kind of nearly right the hidden cases are built to catch.',
    ],
    seo: 'AP CSA 3.9 FRQ practice: use this to separate a point from the point passed to it when comparing and measuring distance.',
    mutants: [
      { describe: 'distanceTo subtracts without taking the magnitude, so one direction is negative',
        find: 'return Math.abs(x - other.getX()) + Math.abs(y - other.getY());', replace: 'return (x - other.getX()) + (y - other.getY());' },
      { describe: 'sameAs compares only the x coordinate',
        find: 'return x == other.getX() && y == other.getY();', replace: 'return x == other.getX();' },
      { describe: 'the constructor omits this, so both assignments do nothing',
        find: '    this.x = x;\n    this.y = y;', replace: '    x = x;\n    y = y;' },
      { describe: 'distanceTo measures from the other point to itself, always zero',
        find: 'return Math.abs(x - other.getX()) + Math.abs(y - other.getY());', replace: 'return Math.abs(other.getX() - other.getX()) + Math.abs(other.getY() - other.getY());' },
    ],
    cases: [
      { stdin: '1 2 4 6\n', part: 4, hidden: 0 },
      // Chosen for (c): the two points are IDENTICAL, the true side of sameAs
      // and a distance of zero.
      { stdin: '3 3 3 3\n', part: 3, hidden: 0 },
      // Chosen for (c): x matches but y does NOT, which is the row that catches
      // a comparison written on one coordinate only.
      { stdin: '5 1 5 9\n', part: 3, hidden: 1 },
      // Chosen for (d): the second point is left of and below the first, so an
      // unsigned subtraction goes negative.
      { stdin: '10 10 2 4\n', part: 4, hidden: 1 },
      // Chosen for (a): zeros, which is what unassigned fields hold.
      { stdin: '0 0 7 8\n', part: 1, hidden: 1 },
      // Chosen for (b): large distinct coordinates, so the two getters cannot
      // be confused with each other or with the second point's.
      { stdin: '12 34 -7 -9\n', part: 2, hidden: 1 },
    ],
  },
];

module.exports = { FRQS };
