'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  AP CSA UNIT 4: DATA COLLECTIONS - 17 code exercises, one per lesson.
//
//  ORDER IS RESPECTED HERE TOO
//  4.2 introduces data sets and the enhanced for loop BEFORE 4.3 teaches array
//  creation, so 4.2's starter builds the array and the student writes only the
//  traversal. From 4.3 on, the student builds their own.
//
//  2026-08-20: 4.6, 4.7, 4.13, 4.14, 4.15 AND 4.17 WERE RECONTENTED
//  Confirmed against the actual 2025-2026 CED text (see
//  docs/csa-codehs-exercise-reference.md and
//  docs/runs/2026-08-19-claude-code-csa-unit4-ced-mismatch.md): these six
//  positions were authored against the wrong topic. Fixed here, before this unit
//  had shipped to any storefront page, so there is no live mismatch to migrate
//  away from, only draft content to correct:
//    4.6  Using Text Files (was Arrays as Parameters and Return Values)
//    4.7  Wrapper Classes (was ArrayList Introduction)
//    4.13 Implementing 2D Array Algorithms (was Searching and Sorting)
//    4.14 Searching Algorithms (was Reading Data from Files)
//    4.15 Sorting Algorithms (was Using Data Sets with Arrays and ArrayLists)
//    4.17 Recursive Searching and Sorting (was Informal Code Analysis, a
//         duplicate of 2.12's topic under a title that is not a real Unit 4
//         CED topic at all)
//  4.14's old file-reading exercise is the one piece of prior content that
//  matched a real CED topic, just eight lessons from where it belongs: it moved
//  to 4.6 rather than being rewritten. The old 4.13 (linear search plus a hand
//  written sort, combined) split cleanly into the new 4.14 (search alone,
//  against data the exercise now states is already sorted) and the new 4.15
//  (both required sorts, selection AND insertion, which the old exercise only
//  had one of). The old 4.6 (array aliasing through parameters) and old 4.7
//  (ArrayList construction) did not match any real Unit 4 CED topic anywhere
//  else in the unit either, per the run note's own assessment, so neither was
//  carried forward.
//
//  4.6 IS `program` MODE NOW, NOT `driver`
//  The exercise moved here is a Scanner-driven read loop, not a
//  "write a method, we call it" exercise, so it keeps the `program` mode it had
//  as 4.14. Judge0 has no filesystem to hand a student a real file in, so this
//  exercise pipes a file's contents in on standard input and says so plainly.
//  The skill is the real one: driving a Scanner with hasNextInt rather than
//  knowing in advance how much data a file holds.
//
//  Expected outputs come from running each reference through real javac/java.
// ─────────────────────────────────────────────────────────────────────────────

const U = 'unit-4';

const exercises = [
  // ── 4.1 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.1', unit: U,
    handle: 'ap-csa-lesson-4-1-ethical-social-issues-data-collection',
    title: 'Ethical and Social Issues Around Data Collection',
    name: 'Report the Aggregate, Not the Person',
    mode: 'program',
    brief: 'Data minimisation is a thing you write, not a thing you agree with. This program is handed identifying records and has to answer questions about the group without ever printing anything that points at one person.',
    task: [
      'Read an integer count, then that many records. Each record is an id number and then an age, on one line.',
      'Print the number of records you read.',
      'Print the average age as an integer, using integer division.',
      'Print how many of the people were 18 or older.',
      'Print the range, meaning the oldest age minus the youngest.',
      'Print no id, and no individual age. The grader checks that the ids never appear in your output.',
    ],
    reads: 'A count, then that many lines of two integers: an id and an age.',
    prints: 'Four lines: the record count, the average age, the count of adults and the age range.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '',
      '    // Read the ids, use none of them.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '',
      '    int total = 0;',
      '    int adults = 0;',
      '    int oldest = 0;',
      '    int youngest = 0;',
      '    for (int i = 0; i < count; i++) {',
      '      input.nextInt();',
      '      int age = input.nextInt();',
      '      total = total + age;',
      '      if (age >= 18) {',
      '        adults = adults + 1;',
      '      }',
      '      if (i == 0 || age > oldest) {',
      '        oldest = age;',
      '      }',
      '      if (i == 0 || age < youngest) {',
      '        youngest = age;',
      '      }',
      '    }',
      '    System.out.println(count);',
      '    System.out.println(total / count);',
      '    System.out.println(adults);',
      '    System.out.println(oldest - youngest);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'You still have to READ the id to get past it to the age. Reading it and not keeping it is exactly the point.',
      'The average is asked for as an integer, so plain int division is correct here and no cast is wanted.',
      'Seed the oldest and youngest from the first record rather than from 0, or a data set of teenagers reports a youngest age of 0.',
    ],
    seo: 'AP CSA 4.1 coding exercise: summarise a data set with aggregate statistics while never printing an identifying value.',
    cases: [
      { stdin: '4\n101 17\n102 23\n103 40\n104 12\n', hidden: 0 },
      { stdin: '1\n900 18\n', hidden: 0 },
      { stdin: '5\n1 65\n2 65\n3 65\n4 65\n5 65\n', hidden: 1 },
      { stdin: '3\n7 1\n8 99\n9 50\n', hidden: 1 },
      { stdin: '6\n11 13\n12 14\n13 15\n14 16\n15 17\n16 18\n', hidden: 1 },
    ],
  },

  // ── 4.2 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.2', unit: U,
    handle: 'ap-csa-lesson-4-2-introduction-to-using-data-sets',
    title: 'Introduction to Using Data Sets',
    name: 'For Each, Not For i',
    mode: 'program',
    brief: 'The enhanced for loop hands you the values and never the positions. That makes it the right tool for a total and the wrong tool the moment you need to know where you are, which is the distinction this exercise is built around.',
    task: [
      'The array is built for you from the input. Do not change that part.',
      'Using an ENHANCED for loop, print the sum of the values.',
      'Using an enhanced for loop, print how many of them are odd.',
      'Using an enhanced for loop, print the largest value.',
      'On the last line print the number of values, which the array itself can tell you.',
    ],
    reads: 'An integer count, then that many integers.',
    prints: 'Four lines: the sum, the count of odd values, the largest value and how many values there were.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    // From here on, use for (int value : data) and not an index.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    int sum = 0;',
      '    for (int value : data) {',
      '      sum = sum + value;',
      '    }',
      '    System.out.println(sum);',
      '',
      '    int odd = 0;',
      '    for (int value : data) {',
      '      if (value % 2 != 0) {',
      '        odd = odd + 1;',
      '      }',
      '    }',
      '    System.out.println(odd);',
      '',
      '    int largest = data[0];',
      '    for (int value : data) {',
      '      if (value > largest) {',
      '        largest = value;',
      '      }',
      '    }',
      '    System.out.println(largest);',
      '',
      '    System.out.println(data.length);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'for (int value : data) reads every element in order. There is no i, and you do not need one for any of these three answers.',
      'data.length is a field, not a method, so there are no parentheses after it.',
      'A negative odd number is still odd. value % 2 != 0 is true for -3, while value % 2 == 1 is not.',
    ],
    seo: 'AP CSA 4.2 coding exercise: traverse a data set three times with the enhanced for loop and read its length.',
    cases: [
      { stdin: '5\n4 7 2 9 1\n', hidden: 0 },
      { stdin: '1\n6\n', hidden: 0 },
      { stdin: '4\n-3 -8 -5 -2\n', hidden: 1 },
      { stdin: '6\n0 0 0 0 0 1\n', hidden: 1 },
      { stdin: '3\n100 100 99\n', hidden: 1 },
    ],
  },

  // ── 4.3 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.3', unit: U,
    handle: 'ap-csa-lesson-4-3-array-creation-and-access',
    title: 'Array Creation and Access',
    name: 'Build It, Index It',
    mode: 'program',
    brief: 'An array of length n has indexes 0 through n minus 1, and asking for index n is the single most common runtime error in this unit. Two of the lines here are about the ends of the array for that reason.',
    task: [
      'Read an integer count, then create an int array of that length.',
      'Read that many values into the array, in order.',
      'Print the length of the array.',
      'Print the FIRST element, then the LAST element, each on its own line.',
      'Print the element at the middle index, which is the length divided by 2 using integer division.',
      'Print the sum of the first and last elements.',
    ],
    reads: 'An integer count of at least 1, then that many integers.',
    prints: 'Five lines: the length, the first element, the last element, the middle element and the sum of the ends.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '',
      '    // new int[count] makes the array. A loop fills it.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    System.out.println(data.length);',
      '    System.out.println(data[0]);',
      '    System.out.println(data[data.length - 1]);',
      '    System.out.println(data[data.length / 2]);',
      '    System.out.println(data[0] + data[data.length - 1]);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The last index is length - 1. data[data.length] is one past the end and throws ArrayIndexOutOfBoundsException.',
      'new int[count] fills the array with zeros. Your loop is what puts the real values in.',
      'For an array of length 5 the middle index is 2, which has two elements on each side. For length 4 it is 2, which is the right hand middle.',
    ],
    seo: 'AP CSA 4.3 coding exercise: create an int array, fill it from input and access the first, last and middle elements.',
    cases: [
      { stdin: '5\n10 20 30 40 50\n', hidden: 0 },
      { stdin: '1\n7\n', hidden: 0 },
      { stdin: '4\n2 4 6 8\n', hidden: 1 },
      { stdin: '6\n-1 -2 -3 -4 -5 -6\n', hidden: 1 },
      { stdin: '2\n99 1\n', hidden: 1 },
    ],
  },

  // ── 4.4 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.4', unit: U,
    handle: 'ap-csa-lesson-4-4-traversing-arrays',
    title: 'Traversing Arrays',
    name: 'Both Directions',
    mode: 'program',
    brief: 'Sometimes you need the index and sometimes you only need the value. This exercise asks for both in the same program so the choice between an indexed loop and an enhanced one has to be made deliberately.',
    task: [
      'Read an integer count, then that many integers into an array.',
      'Print every element on its own line, front to back.',
      'Print every element on its own line, back to front.',
      'Print the index of the largest element. When it appears more than once, print the FIRST index it appears at.',
      'Print the sum of the elements at even indexes.',
    ],
    reads: 'An integer count of at least 1, then that many integers.',
    prints: 'The elements forwards, then backwards, then the index of the maximum, then the sum at even indexes.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    // Two traversals, then two answers that need the index.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    for (int value : data) {',
      '      System.out.println(value);',
      '    }',
      '    for (int i = data.length - 1; i >= 0; i--) {',
      '      System.out.println(data[i]);',
      '    }',
      '',
      '    int best = 0;',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] > data[best]) {',
      '        best = i;',
      '      }',
      '    }',
      '    System.out.println(best);',
      '',
      '    int evenSum = 0;',
      '    for (int i = 0; i < data.length; i = i + 2) {',
      '      evenSum = evenSum + data[i];',
      '    }',
      '    System.out.println(evenSum);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The backwards loop starts at length - 1 and tests i >= 0. Starting at length is the off by one that throws.',
      'Use a strict > when hunting the maximum index, so a repeated maximum keeps the first position rather than the last.',
      'Even INDEXES means 0, 2, 4 and so on, which is not the same as even values. Step the loop by 2.',
    ],
    seo: 'AP CSA 4.4 coding exercise: traverse an array forwards and backwards and use the index to find a maximum position.',
    cases: [
      { stdin: '5\n3 9 4 9 1\n', hidden: 0 },
      { stdin: '1\n42\n', hidden: 0 },
      { stdin: '4\n-2 -7 -1 -9\n', hidden: 1 },
      { stdin: '6\n5 5 5 5 5 5\n', hidden: 1 },
      { stdin: '3\n1 2 3\n', hidden: 1 },
    ],
  },

  // ── 4.5 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.5', unit: U,
    handle: 'ap-csa-lesson-4-5-algorithms-with-arrays',
    title: 'Algorithms with Arrays',
    name: 'Four Standard Algorithms',
    mode: 'program',
    brief: 'These four turn up on the exam in some form every year. Writing them once from an empty editor is worth more than reading them ten times.',
    task: [
      'Read an integer count, then that many integers into an array.',
      'Print the sum of all the elements.',
      'Print the average as a double, so a whole number still shows a decimal point.',
      'Print how many elements are strictly greater than that average.',
      'Print true when the array is in non decreasing order, and false otherwise.',
      'Print the number of pairs of neighbouring elements that are equal.',
    ],
    reads: 'An integer count of at least 1, then that many integers.',
    prints: 'Five lines: the sum, the average, the count above average, the sorted check and the equal neighbour count.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    // Five answers. Two of them compare neighbours.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    int sum = 0;',
      '    for (int value : data) {',
      '      sum = sum + value;',
      '    }',
      '    System.out.println(sum);',
      '',
      '    double average = (double) sum / data.length;',
      '    System.out.println(average);',
      '',
      '    int above = 0;',
      '    for (int value : data) {',
      '      if (value > average) {',
      '        above = above + 1;',
      '      }',
      '    }',
      '    System.out.println(above);',
      '',
      '    boolean sorted = true;',
      '    int equalPairs = 0;',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] < data[i - 1]) {',
      '        sorted = false;',
      '      }',
      '      if (data[i] == data[i - 1]) {',
      '        equalPairs = equalPairs + 1;',
      '      }',
      '    }',
      '    System.out.println(sorted);',
      '    System.out.println(equalPairs);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Cast the sum to double before dividing, or the average of 7 and 2 comes out as 4.0 instead of 4.5.',
      'A neighbour comparison starts at i = 1 and looks back at i - 1, so it never reads past either end.',
      'A one element array is sorted and has zero equal pairs. The loop simply does not run, which is the right answer.',
    ],
    seo: 'AP CSA 4.5 coding exercise: sum, average, count above average, check sorted order and find equal neighbours in an array.',
    cases: [
      { stdin: '5\n4 7 2 9 1\n', hidden: 0 },
      { stdin: '4\n1 2 2 5\n', hidden: 0 },
      { stdin: '1\n8\n', hidden: 1 },
      { stdin: '6\n3 3 3 3 3 3\n', hidden: 1 },
      { stdin: '5\n9 7 5 3 1\n', hidden: 1 },
    ],
  },

  // ── 4.6 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.6', unit: U,
    handle: 'ap-csa-lesson-4-6-using-text-files',
    title: 'Using Text Files',
    name: 'Read Until It Runs Out',
    mode: 'program',
    brief: "Judge0 has no filesystem to hand a student a real file in, so this exercise pipes a text file's contents in on standard input instead and says so plainly. The skill is the real one: driving a Scanner with hasNextInt rather than knowing in advance how much data a file holds, which is exactly what reading a file with Scanner(File) requires.",
    task: [
      'Treat standard input as the contents of a text file: read integers with a Scanner until there are no more, using hasNextInt to control the loop.',
      'You are NOT told how many values the file holds. Do not read a count.',
      'Print how many values you read.',
      'Print the total.',
      'Print the largest and then the smallest, each on its own line.',
      'When the file is empty, print 0 for the count and 0 for the total and nothing else.',
    ],
    reads: "Any number of integers, including none, separated by whitespace, standing in for a text file's contents.",
    prints: 'The count and the total always, then the largest and smallest when the file held at least one value.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '',
      '    // while (input.hasNextInt()) { ... }',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '',
      '    int count = 0;',
      '    int total = 0;',
      '    int largest = 0;',
      '    int smallest = 0;',
      '    while (input.hasNextInt()) {',
      '      int value = input.nextInt();',
      '      if (count == 0 || value > largest) {',
      '        largest = value;',
      '      }',
      '      if (count == 0 || value < smallest) {',
      '        smallest = value;',
      '      }',
      '      count = count + 1;',
      '      total = total + value;',
      '    }',
      '',
      '    System.out.println(count);',
      '    System.out.println(total);',
      '    if (count > 0) {',
      '      System.out.println(largest);',
      '      System.out.println(smallest);',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A Scanner built on a File, new Scanner(new File("data.txt")), is driven exactly the same way as this one built on System.in. hasNextInt and nextInt do not care where the data came from.',
      'Calling nextInt() when nothing is left throws NoSuchElementException, which is exactly what the hasNextInt guard prevents.',
      'The empty input case prints two lines and stops. Guard the largest and smallest so they are not printed for data that never arrived.',
    ],
    seo: 'AP CSA 4.6 coding exercise: drive a Scanner with hasNextInt to read text data of unknown length, the same way you would read a text file.',
    cases: [
      { stdin: '4 8 15 16 23 42\n', hidden: 0 },
      { stdin: '7\n', hidden: 0 },
      { stdin: '', hidden: 1 },
      { stdin: '-5 -10 -1\n', hidden: 1 },
      { stdin: '3 3 3 3 3 3 3 3 3 3\n', hidden: 1 },
    ],
  },

  // ── 4.7 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.7', unit: U,
    handle: 'ap-csa-lesson-4-7-wrapper-classes',
    title: 'Wrapper Classes',
    name: 'Parse It, Compare It, Bound It',
    mode: 'program',
    brief: 'Scanner.next() always hands back a String, even when the text is nothing but digits, so turning it into a number you can do arithmetic on is a step of its own. This exercise makes that step explicit and asks you to compare the results as Integer objects rather than with a bare > sign.',
    task: [
      'Read an integer count n, then n more tokens as text. Convert each one to an int with Integer.parseInt and store the results in an int array.',
      'Print the sum of the values.',
      'Find the largest value by boxing each element with Integer.valueOf and comparing with compareTo, not with > or <. Print it.',
      'Print true when doubling the sum would overflow a 32 bit int, meaning it would exceed Integer.MAX_VALUE, and false otherwise. Use the Integer.MAX_VALUE constant; do not hardcode the number.',
      'Read one more token as text and convert it to a double with Double.parseDouble. Print it.',
    ],
    reads: 'An integer count n, then n numeral tokens, then one more token that is a decimal number.',
    prints: 'The sum, the largest value found by compareTo, the overflow check, and the parsed decimal.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] values = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      String token = input.next();',
      '      values[i] = Integer.parseInt(token);',
      '    }',
      '',
      '    // Sum first. Then find the largest using Integer.valueOf and compareTo, not > or <.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] values = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      String token = input.next();',
      '      values[i] = Integer.parseInt(token);',
      '    }',
      '',
      '    int sum = 0;',
      '    for (int value : values) {',
      '      sum = sum + value;',
      '    }',
      '    System.out.println(sum);',
      '',
      '    Integer largest = Integer.valueOf(values[0]);',
      '    for (int value : values) {',
      '      Integer boxed = Integer.valueOf(value);',
      '      if (boxed.compareTo(largest) > 0) {',
      '        largest = boxed;',
      '      }',
      '    }',
      '    System.out.println(largest);',
      '',
      '    long doubled = (long) sum * 2;',
      '    System.out.println(doubled > Integer.MAX_VALUE);',
      '',
      '    String decimalToken = input.next();',
      '    double decimal = Double.parseDouble(decimalToken);',
      '    System.out.println(decimal);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Integer.parseInt turns a String of digits into an int. Scanner.next() always returns a String, even when the text looks like a number, which is why the conversion is needed at all.',
      'compareTo returns negative, zero or positive, not true or false. boxed.compareTo(largest) > 0 means boxed is the bigger of the two.',
      'Cast the sum to long before doubling it, or the overflow check happens too late: an int that has already overflowed cannot tell you that it overflowed.',
    ],
    seo: 'AP CSA 4.7 coding exercise: parse Strings with Integer.parseInt, compare Integer objects with compareTo, and check for overflow.',
    cases: [
      { stdin: '4\n3 -1 4 -1\n2.5\n', hidden: 0 },
      { stdin: '1\n0\n3.14\n', hidden: 0 },
      { stdin: '3\n2147483647 0 0\n0.0\n', hidden: 1 },
      { stdin: '5\n-100 -50 -25 -10 -1\n-1.5\n', hidden: 1 },
      { stdin: '2\n100000000 100000000\n100.25\n', hidden: 1 },
    ],
  },

  // ── 4.8 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.8', unit: U,
    handle: 'ap-csa-lesson-4-8-arraylist-methods',
    title: 'ArrayList Methods',
    name: 'Add, Set, Remove',
    mode: 'program',
    brief: 'add with an index shifts everything right and remove shifts everything left, while set changes one slot and moves nothing. Three methods that look similar and do genuinely different things to the positions around them.',
    task: [
      'Read an integer count, then that many integers, and put them in an ArrayList of Integer.',
      'Print the list.',
      'Add the value 99 at index 1, then print the list.',
      'Set index 0 to the value 0, then print the list.',
      'Remove the element at index 2 and print what remove returned, then print the list.',
      'Print the size on the last line. Print a list as its default Java form, for example [1, 2, 3].',
    ],
    reads: 'An integer count of at least 3, then that many integers.',
    prints: 'The list four times as the operations are applied, the removed value, and finally the size.',
    starter: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '',
      '    // System.out.println(list) prints it in the [1, 2, 3] form for you.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    System.out.println(list);',
      '    list.add(1, 99);',
      '    System.out.println(list);',
      '    list.set(0, 0);',
      '    System.out.println(list);',
      '    System.out.println(list.remove(2));',
      '    System.out.println(list);',
      '    System.out.println(list.size());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'add(1, 99) inserts and pushes everything from index 1 onward one place to the right. The list gets longer.',
      'set(0, 0) replaces what is already there. The list stays the same length.',
      'remove(int index) hands back the element it took out, so you can print the return value directly.',
    ],
    seo: 'AP CSA 4.8 coding exercise: use ArrayList add with an index, set, remove and size and watch the positions shift.',
    cases: [
      { stdin: '4\n10 20 30 40\n', hidden: 0 },
      { stdin: '3\n1 2 3\n', hidden: 0 },
      { stdin: '5\n-1 -2 -3 -4 -5\n', hidden: 1 },
      { stdin: '6\n7 7 7 7 7 7\n', hidden: 1 },
      { stdin: '3\n99 99 99\n', hidden: 1 },
    ],
  },

  // ── 4.9 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.9', unit: U,
    handle: 'ap-csa-lesson-4-9-traversing-arraylists',
    title: 'Traversing ArrayLists',
    name: 'Removing While You Walk',
    mode: 'program',
    brief: 'Removing an element during a forward traversal makes the loop skip the next one, which is the classic ArrayList bug and is on the exam. Doing it backwards avoids the problem entirely, and this exercise asks for both so the difference is visible in the output.',
    task: [
      'Read an integer count, then that many integers into an ArrayList of Integer.',
      'Print the sum using an enhanced for loop.',
      'Make a copy of the list. Walk the copy FORWARDS with an index and remove every even value, without adjusting the index after a removal. Print the result, bug and all.',
      'Make another copy. Walk it BACKWARDS and remove every even value. Print that result.',
      'Print true when the two results are equal and false when the forward version missed something.',
    ],
    reads: 'An integer count of at least 1, then that many integers.',
    prints: 'The sum, the forward result, the backward result and whether they matched.',
    starter: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    // new ArrayList<Integer>(list) makes a copy you can damage safely.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    int sum = 0;',
      '    for (int value : list) {',
      '      sum = sum + value;',
      '    }',
      '    System.out.println(sum);',
      '',
      '    ArrayList<Integer> forward = new ArrayList<Integer>(list);',
      '    for (int i = 0; i < forward.size(); i++) {',
      '      if (forward.get(i) % 2 == 0) {',
      '        forward.remove(i);',
      '      }',
      '    }',
      '    System.out.println(forward);',
      '',
      '    ArrayList<Integer> backward = new ArrayList<Integer>(list);',
      '    for (int i = backward.size() - 1; i >= 0; i--) {',
      '      if (backward.get(i) % 2 == 0) {',
      '        backward.remove(i);',
      '      }',
      '    }',
      '    System.out.println(backward);',
      '',
      '    System.out.println(forward.equals(backward));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'After remove(i) everything shifts left, so the element that moved into position i never gets tested. Two evens in a row is where it shows.',
      'The backward loop is immune because everything that shifts has already been visited.',
      'Comparing two ArrayLists with equals compares their contents in order, which is what the last line wants.',
    ],
    seo: 'AP CSA 4.9 coding exercise: see why removing from an ArrayList while traversing forwards skips elements, and fix it.',
    cases: [
      { stdin: '6\n1 2 4 3 6 5\n', hidden: 0 },
      { stdin: '4\n1 3 5 7\n', hidden: 0 },
      { stdin: '5\n2 2 2 2 2\n', hidden: 1 },
      { stdin: '1\n8\n', hidden: 1 },
      { stdin: '7\n1 2 3 4 6 8 9\n', hidden: 1 },
    ],
  },

  // ── 4.10 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.10', unit: U,
    handle: 'ap-csa-lesson-4-10-algorithms-with-arraylists',
    title: 'Algorithms with ArrayLists',
    name: 'Shift, Swap, Split',
    mode: 'program',
    brief: 'These three come up on the free response question in some disguise nearly every year. All three are about positions rather than values, which is why an enhanced for loop is no help for any of them.',
    task: [
      'Read an integer count, then that many integers into an ArrayList of Integer.',
      'Print the list with the first element moved to the end and everything else shifted left by one.',
      'Print the original list with its first and last elements swapped.',
      'Print a list of only the values at even indexes of the original.',
      'Print a list of only the values at odd indexes of the original.',
      'The original list must be printed unchanged on the last line, so work on copies.',
    ],
    reads: 'An integer count of at least 2, then that many integers.',
    prints: 'The rotated list, the swapped list, the even index list, the odd index list, and the untouched original.',
    starter: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    // Five printed lines. The original is the last one and must be unchanged.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    ArrayList<Integer> rotated = new ArrayList<Integer>(list);',
      '    rotated.add(rotated.remove(0));',
      '    System.out.println(rotated);',
      '',
      '    ArrayList<Integer> swapped = new ArrayList<Integer>(list);',
      '    int last = swapped.size() - 1;',
      '    int keep = swapped.get(0);',
      '    swapped.set(0, swapped.get(last));',
      '    swapped.set(last, keep);',
      '    System.out.println(swapped);',
      '',
      '    ArrayList<Integer> evens = new ArrayList<Integer>();',
      '    ArrayList<Integer> odds = new ArrayList<Integer>();',
      '    for (int i = 0; i < list.size(); i++) {',
      '      if (i % 2 == 0) {',
      '        evens.add(list.get(i));',
      '      } else {',
      '        odds.add(list.get(i));',
      '      }',
      '    }',
      '    System.out.println(evens);',
      '    System.out.println(odds);',
      '',
      '    System.out.println(list);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'remove(0) returns the element it took out, so add(remove(0)) rotates the list in a single line.',
      'A swap needs a third variable to hold the first value, or the assignment overwrites it before you have used it.',
      'new ArrayList<Integer>(list) copies. Assigning one list variable to another just makes a second name for the same list, and the last line will show it.',
    ],
    seo: 'AP CSA 4.10 coding exercise: rotate, swap and split an ArrayList by index while leaving the original untouched.',
    cases: [
      { stdin: '5\n1 2 3 4 5\n', hidden: 0 },
      { stdin: '2\n8 9\n', hidden: 0 },
      { stdin: '6\n-1 -2 -3 -4 -5 -6\n', hidden: 1 },
      { stdin: '4\n7 7 7 7\n', hidden: 1 },
      { stdin: '3\n100 0 100\n', hidden: 1 },
    ],
  },

  // ── 4.11 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.11', unit: U,
    handle: 'ap-csa-lesson-4-11-2d-array-creation-and-access',
    title: '2D Array Creation and Access',
    name: 'Rows First, Then Columns',
    mode: 'program',
    brief: 'grid[r][c] is row then column, in that order, always. Swapping them compiles perfectly and gives the wrong answer on every rectangle that is not a square, which is why this exercise never uses one.',
    task: [
      'Read two integers, rows and cols, then rows times cols integers filling the grid row by row.',
      'Print the number of rows, then the number of columns, each on its own line.',
      'Print the value in the top left corner, then the bottom right corner.',
      'Print the sum of the first row.',
      'Print the sum of the first column.',
    ],
    reads: 'Two integers, rows and cols, then rows times cols integers in row order.',
    prints: 'Six lines: the row count, the column count, two corners and two sums.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '',
      '    // Fill it, then answer the six questions.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        grid[r][c] = input.nextInt();',
      '      }',
      '    }',
      '',
      '    System.out.println(grid.length);',
      '    System.out.println(grid[0].length);',
      '    System.out.println(grid[0][0]);',
      '    System.out.println(grid[rows - 1][cols - 1]);',
      '',
      '    int rowSum = 0;',
      '    for (int c = 0; c < cols; c++) {',
      '      rowSum = rowSum + grid[0][c];',
      '    }',
      '    System.out.println(rowSum);',
      '',
      '    int colSum = 0;',
      '    for (int r = 0; r < rows; r++) {',
      '      colSum = colSum + grid[r][0];',
      '    }',
      '    System.out.println(colSum);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'grid.length is the number of ROWS. grid[0].length is the number of columns in row 0.',
      'Summing the first row holds the row index at 0 and moves the column. Summing the first column does the opposite.',
      'The bottom right corner is grid[rows - 1][cols - 1]. Both indexes stop one short.',
    ],
    seo: 'AP CSA 4.11 coding exercise: build a 2D array from input and access rows, columns and corners in the right order.',
    cases: [
      { stdin: '2 3\n1 2 3\n4 5 6\n', hidden: 0 },
      { stdin: '1 1\n9\n', hidden: 0 },
      { stdin: '3 2\n10 20\n30 40\n50 60\n', hidden: 1 },
      { stdin: '4 1\n1\n2\n3\n4\n', hidden: 1 },
      { stdin: '2 5\n-1 -2 -3 -4 -5\n5 4 3 2 1\n', hidden: 1 },
    ],
  },

  // ── 4.12 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.12', unit: U,
    handle: 'ap-csa-lesson-4-12-traversing-2d-arrays',
    title: 'Traversing 2D Arrays',
    name: 'Across, Down, Diagonal',
    mode: 'program',
    brief: 'Row major order is the default and column major order is the one that catches people out, because it needs the loops in the opposite nesting from the one that feels natural.',
    task: [
      'Read rows and cols, then the grid values in row order.',
      'Print all values in ROW major order, one per line: every value of row 0, then every value of row 1, and so on.',
      'Print all values in COLUMN major order, one per line: every value of column 0 top to bottom, then column 1, and so on.',
      'Print the sum of every value.',
      'Print the largest value anywhere in the grid.',
    ],
    reads: 'Two integers, rows and cols, then rows times cols integers in row order.',
    prints: 'Every value row major, then every value column major, then the total and the maximum.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        grid[r][c] = input.nextInt();',
      '      }',
      '    }',
      '',
      '    // Two full traversals, then two summary answers.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        grid[r][c] = input.nextInt();',
      '      }',
      '    }',
      '',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        System.out.println(grid[r][c]);',
      '      }',
      '    }',
      '',
      '    for (int c = 0; c < cols; c++) {',
      '      for (int r = 0; r < rows; r++) {',
      '        System.out.println(grid[r][c]);',
      '      }',
      '    }',
      '',
      '    int total = 0;',
      '    int max = grid[0][0];',
      '    for (int[] row : grid) {',
      '      for (int value : row) {',
      '        total = total + value;',
      '        if (value > max) {',
      '          max = value;',
      '        }',
      '      }',
      '    }',
      '    System.out.println(total);',
      '    System.out.println(max);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Column major order puts the COLUMN loop on the outside. The subscript is still grid[r][c], only the nesting changes.',
      'The enhanced for over a 2D array gives you a whole row at a time, so it takes two of them: for (int[] row : grid) then for (int value : row).',
      'Seed the maximum with grid[0][0] rather than 0, or a grid of negatives reports 0.',
    ],
    seo: 'AP CSA 4.12 coding exercise: traverse a 2D array in row major and column major order and summarise every value.',
    cases: [
      { stdin: '2 3\n1 2 3\n4 5 6\n', hidden: 0 },
      { stdin: '1 4\n7 8 9 10\n', hidden: 0 },
      { stdin: '3 3\n-1 -2 -3\n-4 -5 -6\n-7 -8 -9\n', hidden: 1 },
      { stdin: '4 2\n1 1\n2 2\n3 3\n4 4\n', hidden: 1 },
      { stdin: '2 2\n5 5\n5 5\n', hidden: 1 },
    ],
  },

  // ── 4.13 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.13', unit: U,
    handle: 'ap-csa-lesson-4-13-implementing-2d-array-algorithms',
    title: 'Implementing 2D Array Algorithms',
    name: 'Rows, Columns, and the Biggest Value',
    mode: 'program',
    brief: 'Every 2D array algorithm is really a 1D array algorithm run once per row or once per column, plus bookkeeping about which row or column is winning. This exercise asks for both directions, the single largest value and where it sits, and a grid built by swapping which index means row and which means column.',
    task: [
      'Read rows and cols, then rows times cols integers filling the grid, row by row.',
      'Print the index of the row with the largest row sum. When two rows tie, print the first one.',
      'Print the index of the column with the largest column sum. When two columns tie, print the first one.',
      'Print the largest single value anywhere in the grid, then the row and column where it FIRST appears in row major order.',
      'Build the TRANSPOSE of the grid: a new grid with cols rows and rows columns, where transposed[c][r] equals grid[r][c]. Print every value of the transpose in row major order, one per line.',
    ],
    reads: 'Two integers, rows and cols, then rows times cols integers in row order.',
    prints: 'The best row index, the best column index, the largest value and its row and column, then every value of the transposed grid.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        grid[r][c] = input.nextInt();',
      '      }',
      '    }',
      '',
      '    // Row sums, column sums, the largest value and its position, then the transpose.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        grid[r][c] = input.nextInt();',
      '      }',
      '    }',
      '',
      '    int bestRow = 0;',
      '    int bestRowSum = 0;',
      '    for (int r = 0; r < rows; r++) {',
      '      int rowSum = 0;',
      '      for (int c = 0; c < cols; c++) {',
      '        rowSum = rowSum + grid[r][c];',
      '      }',
      '      if (r == 0 || rowSum > bestRowSum) {',
      '        bestRow = r;',
      '        bestRowSum = rowSum;',
      '      }',
      '    }',
      '    System.out.println(bestRow);',
      '',
      '    int bestCol = 0;',
      '    int bestColSum = 0;',
      '    for (int c = 0; c < cols; c++) {',
      '      int colSum = 0;',
      '      for (int r = 0; r < rows; r++) {',
      '        colSum = colSum + grid[r][c];',
      '      }',
      '      if (c == 0 || colSum > bestColSum) {',
      '        bestCol = c;',
      '        bestColSum = colSum;',
      '      }',
      '    }',
      '    System.out.println(bestCol);',
      '',
      '    int maxValue = grid[0][0];',
      '    int maxRow = 0;',
      '    int maxCol = 0;',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        if (grid[r][c] > maxValue) {',
      '          maxValue = grid[r][c];',
      '          maxRow = r;',
      '          maxCol = c;',
      '        }',
      '      }',
      '    }',
      '    System.out.println(maxValue);',
      '    System.out.println(maxRow);',
      '    System.out.println(maxCol);',
      '',
      '    int[][] transposed = new int[cols][rows];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        transposed[c][r] = grid[r][c];',
      '      }',
      '    }',
      '    for (int c = 0; c < cols; c++) {',
      '      for (int r = 0; r < rows; r++) {',
      '        System.out.println(transposed[c][r]);',
      '      }',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A row or column sum needs its own running total reset to 0 before each row or column starts, or the sums bleed into each other.',
      'Seed bestRowSum and bestColSum from index 0 rather than from 0 itself, or a grid that is entirely negative reports index 0 as never the best.',
      'transposed[c][r] = grid[r][c] is the whole transpose: the new grid has cols rows and rows columns, and every value just changes which index it is read by.',
    ],
    seo: 'AP CSA 4.13 coding exercise: implement row sum, column sum, locate the maximum value and build the transpose of a 2D array.',
    cases: [
      { stdin: '2 3\n1 2 3\n4 5 6\n', hidden: 0 },
      { stdin: '1 1\n9\n', hidden: 0 },
      { stdin: '3 2\n10 20\n30 40\n50 60\n', hidden: 1 },
      { stdin: '2 2\n-1 -2\n-3 -4\n', hidden: 1 },
      { stdin: '4 1\n1\n2\n3\n4\n', hidden: 1 },
    ],
  },

  // ── 4.14 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.14', unit: U,
    handle: 'ap-csa-lesson-4-14-searching-algorithms',
    title: 'Searching Algorithms',
    name: 'Scan It, Then Halve It',
    mode: 'program',
    brief: 'Linear search costs nothing to set up and can cost the whole array. Binary search costs a sorted array up front and pays it back in comparisons. This exercise hands you data that is already sorted, on purpose, so the only variable left is which search you run and how many comparisons it takes.',
    task: [
      'Read a count, then that many integers, ALREADY in sorted increasing order, then a target value.',
      'Print the index found by a LINEAR search that scans from the front and stops at the first match, or -1 when the target is not present.',
      'Print how many comparisons the linear search made, counting one per element it looked at, including the one that matched.',
      'Print the index found by a BINARY search of the same sorted array, or -1 when the target is not present.',
      'Print how many comparisons the binary search made.',
    ],
    reads: 'An integer count of at least 1, then that many integers already in sorted increasing order, then a target value.',
    prints: 'The linear index, the linear comparison count, the binary index and the binary comparison count.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    // The array arrives already sorted. Search it two ways and count comparisons.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    int linearIndex = -1;',
      '    int linearComparisons = 0;',
      '    for (int i = 0; i < data.length && linearIndex == -1; i++) {',
      '      linearComparisons = linearComparisons + 1;',
      '      if (data[i] == target) {',
      '        linearIndex = i;',
      '      }',
      '    }',
      '    System.out.println(linearIndex);',
      '    System.out.println(linearComparisons);',
      '',
      '    int low = 0;',
      '    int high = data.length - 1;',
      '    int binaryIndex = -1;',
      '    int binaryComparisons = 0;',
      '    while (low <= high && binaryIndex == -1) {',
      '      int mid = (low + high) / 2;',
      '      binaryComparisons = binaryComparisons + 1;',
      '      if (data[mid] == target) {',
      '        binaryIndex = mid;',
      '      } else if (data[mid] < target) {',
      '        low = mid + 1;',
      '      } else {',
      '        high = mid - 1;',
      '      }',
      '    }',
      '    System.out.println(binaryIndex);',
      '    System.out.println(binaryComparisons);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The array is already sorted for you, on purpose: binary search only works on sorted data, and Sorting Algorithms is its own lesson right after this one.',
      'Linear search counts one comparison per element it actually looks at. A target at index 0 costs one comparison; a target that is not there costs the whole length.',
      'Binary search throws away half the remaining range on every comparison, which is why it needs so few even on a long array.',
    ],
    seo: 'AP CSA 4.14 coding exercise: search a sorted array with linear search and binary search and count how many comparisons each makes.',
    cases: [
      { stdin: '7\n1 2 3 5 7 8 9\n7\n', hidden: 0 },
      { stdin: '5\n1 2 3 4 5\n1\n', hidden: 0 },
      { stdin: '6\n2 4 6 8 10 12\n7\n', hidden: 1 },
      { stdin: '1\n42\n42\n', hidden: 1 },
      { stdin: '8\n1 2 3 4 5 6 7 8\n8\n', hidden: 1 },
    ],
  },

  // ── 4.15 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.15', unit: U,
    handle: 'ap-csa-lesson-4-15-sorting-algorithms',
    title: 'Sorting Algorithms',
    name: 'Two Sorts, One Answer',
    mode: 'program',
    brief: 'Selection sort finds the smallest remaining value and swaps it into place. Insertion sort takes each value and slides it left past everything bigger already in place. Different work, same final order, and this exercise counts the work each one actually does to prove it.',
    task: [
      'Read a count, then that many integers, unsorted.',
      'Copy the array. Sort the copy with SELECTION sort, written out by hand: repeatedly find the smallest remaining value and swap it into place. Print the sorted result.',
      'Print how many swaps selection sort made. Only count a swap when the smallest remaining value was not already in place.',
      'Copy the ORIGINAL unsorted array again. Sort this second copy with INSERTION sort, written out by hand: take each value and shift it left past every larger value already in place. Print the sorted result.',
      'Print how many shifts insertion sort made. Count one shift for every value moved one position to the right inside the loop; the final placement of the key is not itself a counted shift.',
      'Print true when the two sorted results match and false otherwise, as a check that both algorithms reached the same order.',
    ],
    reads: 'An integer count of at least 1, then that many integers, unsorted.',
    prints: 'The selection sorted array, its swap count, the insertion sorted array, its shift count, and whether the two agree.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    // Copy data, sort the copy with selection sort by hand, print it and the swap count.',
      '    // Copy data AGAIN from the original, sort that copy with insertion sort by hand,',
      '    // print it and the shift count. Then print whether the two results match.',
      '  }',
      '',
      '  private static void printArray(int[] a) {',
      '    String out = "";',
      '    for (int i = 0; i < a.length; i++) {',
      '      if (i > 0) {',
      '        out = out + " ";',
      '      }',
      '      out = out + a[i];',
      '    }',
      '    System.out.println(out);',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    int[] selection = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      selection[i] = data[i];',
      '    }',
      '    int swaps = 0;',
      '    for (int i = 0; i < selection.length - 1; i++) {',
      '      int small = i;',
      '      for (int j = i + 1; j < selection.length; j++) {',
      '        if (selection[j] < selection[small]) {',
      '          small = j;',
      '        }',
      '      }',
      '      if (small != i) {',
      '        int keep = selection[i];',
      '        selection[i] = selection[small];',
      '        selection[small] = keep;',
      '        swaps = swaps + 1;',
      '      }',
      '    }',
      '    printArray(selection);',
      '    System.out.println(swaps);',
      '',
      '    int[] insertion = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      insertion[i] = data[i];',
      '    }',
      '    int shifts = 0;',
      '    for (int i = 1; i < insertion.length; i++) {',
      '      int key = insertion[i];',
      '      int j = i - 1;',
      '      while (j >= 0 && insertion[j] > key) {',
      '        insertion[j + 1] = insertion[j];',
      '        j = j - 1;',
      '        shifts = shifts + 1;',
      '      }',
      '      insertion[j + 1] = key;',
      '    }',
      '    printArray(insertion);',
      '    System.out.println(shifts);',
      '',
      '    boolean same = true;',
      '    for (int i = 0; i < count; i++) {',
      '      if (selection[i] != insertion[i]) {',
      '        same = false;',
      '      }',
      '    }',
      '    System.out.println(same);',
      '  }',
      '',
      '  private static void printArray(int[] a) {',
      '    String out = "";',
      '    for (int i = 0; i < a.length; i++) {',
      '      if (i > 0) {',
      '        out = out + " ";',
      '      }',
      '      out = out + a[i];',
      '    }',
      '    System.out.println(out);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Selection sort only counts as a swap when small != i. A value that is already the smallest in its remaining range should not increment the count.',
      'Insertion sort shifts existing elements right one at a time inside the while loop; placing the key at insertion[j + 1] after the loop ends is not itself a counted shift.',
      'Sort a fresh COPY of the original data for each algorithm, or the second sort starts from data the first one already rearranged.',
    ],
    seo: 'AP CSA 4.15 coding exercise: implement selection sort and insertion sort by hand, count their swaps and shifts, and confirm they agree.',
    cases: [
      { stdin: '5\n5 2 8 1 9\n', hidden: 0 },
      { stdin: '1\n1\n', hidden: 0 },
      { stdin: '3\n3 3 3\n', hidden: 1 },
      { stdin: '4\n9 8 7 6\n', hidden: 1 },
      { stdin: '5\n-5 10 -3 0 7\n', hidden: 1 },
    ],
  },

  // ── 4.16 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.16', unit: U,
    handle: 'ap-csa-lesson-4-16-recursion',
    title: 'Recursion',
    name: 'The Base Case First',
    mode: 'program',
    brief: 'Every recursive method needs a base case and a call that gets closer to it. Write the base case first and the rest usually falls out; write it last and the program runs forever.',
    task: [
      'Read one integer n, which is 0 or more, and then a word.',
      'Write a recursive method that returns the factorial of n, and print it. The factorial of 0 is 1.',
      'Write a recursive method that returns the sum of the digits of n, and print it.',
      'Write a recursive method that returns the word reversed, and print it.',
      'Write a recursive method that returns how many times the method was called to compute the factorial, counting the base case, and print it.',
      'Every one of these must be recursive. Do not use a loop.',
    ],
    reads: 'An integer of 0 or more, then a word.',
    prints: 'Four lines: the factorial, the digit sum, the reversed word and the call count.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static int factorial(int n) {',
      '    return 0;',
      '  }',
      '',
      '  public static int digitSum(int n) {',
      '    return 0;',
      '  }',
      '',
      '  public static String reverse(String s) {',
      '    return "";',
      '  }',
      '',
      '  public static int calls(int n) {',
      '    return 0;',
      '  }',
      '',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    String word = input.next();',
      '',
      '    // Four printed lines.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static int factorial(int n) {',
      '    if (n <= 1) {',
      '      return 1;',
      '    }',
      '    return n * factorial(n - 1);',
      '  }',
      '',
      '  public static int digitSum(int n) {',
      '    if (n < 10) {',
      '      return n;',
      '    }',
      '    return n % 10 + digitSum(n / 10);',
      '  }',
      '',
      '  public static String reverse(String s) {',
      '    if (s.length() <= 1) {',
      '      return s;',
      '    }',
      '    return reverse(s.substring(1)) + s.substring(0, 1);',
      '  }',
      '',
      '  public static int calls(int n) {',
      '    if (n <= 1) {',
      '      return 1;',
      '    }',
      '    return 1 + calls(n - 1);',
      '  }',
      '',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    String word = input.next();',
      '',
      '    System.out.println(factorial(n));',
      '    System.out.println(digitSum(n));',
      '    System.out.println(reverse(word));',
      '    System.out.println(calls(n));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'factorial stops at 1 or below and returns 1, which covers both 0 and 1 with one test.',
      'Reversing a String recursively is the reverse of everything after the first character, with the first character stuck on the end.',
      'The call count for factorial(5) is 5, because the base case call counts too. Trace factorial(1) and factorial(0) by hand if the number is off by one.',
    ],
    seo: 'AP CSA 4.16 coding exercise: write four recursive methods with correct base cases, including a recursive String reverse.',
    cases: [
      { stdin: '5 stack\n', hidden: 0 },
      { stdin: '0 a\n', hidden: 0 },
      { stdin: '1 recursion\n', hidden: 1 },
      { stdin: '9 zzz\n', hidden: 1 },
      { stdin: '12 palindrome\n', hidden: 1 },
    ],
  },

  // ── 4.17 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.17', unit: U,
    handle: 'ap-csa-lesson-4-17-recursive-searching-and-sorting',
    title: 'Recursive Searching and Sorting',
    name: 'Split It Until It Sorts Itself',
    mode: 'program',
    brief: 'A recursive binary search is the same idea as the iterative one, restated as a method that calls a smaller version of itself instead of looping. A recursive sort takes that further: mergeSort does not sort anything directly, it only trusts that a shorter mergeSort already did, and glues the two results together.',
    task: [
      'Read a count, then that many integers ALREADY sorted increasing, then a target value.',
      'Write a RECURSIVE method binarySearch(data, target, low, high) that returns the index of target or -1. Print the result.',
      'Write a second recursive method searchCalls(data, target, low, high) with the exact same recursive shape, that returns how many times the method was called, counting the call that finally returns. Print it.',
      'Read a second count, then that many integers, unsorted.',
      'Write a RECURSIVE method mergeSort(data) that returns a NEW sorted array: split the array in half, call mergeSort on each half, and merge the two sorted halves back together. Print the sorted result, values separated by single spaces.',
      'binarySearch, searchCalls and mergeSort must each call themselves; do not use a loop inside any of the three. The step that merges two already-sorted halves back together is not the recursive part and may use a loop.',
    ],
    reads: 'A count, then that many integers already sorted increasing, then a target, then a second count, then that many unsorted integers.',
    prints: 'The binary search index, the recursive call count, then the merge sorted second array on one line.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static int binarySearch(int[] data, int target, int low, int high) {',
      '    return -1;',
      '  }',
      '',
      '  public static int searchCalls(int[] data, int target, int low, int high) {',
      '    return 0;',
      '  }',
      '',
      '  public static int[] mergeSort(int[] data) {',
      '    // Base case: length 0 or 1 is already sorted. Otherwise split, recurse, merge.',
      '    return data;',
      '  }',
      '',
      '  private static int[] merge(int[] left, int[] right) {',
      '    int[] out = new int[left.length + right.length];',
      '    int i = 0;',
      '    int j = 0;',
      '    int k = 0;',
      '    while (i < left.length && j < right.length) {',
      '      if (left[i] <= right[j]) {',
      '        out[k] = left[i];',
      '        i = i + 1;',
      '      } else {',
      '        out[k] = right[j];',
      '        j = j + 1;',
      '      }',
      '      k = k + 1;',
      '    }',
      '    while (i < left.length) {',
      '      out[k] = left[i];',
      '      i = i + 1;',
      '      k = k + 1;',
      '    }',
      '    while (j < right.length) {',
      '      out[k] = right[j];',
      '      j = j + 1;',
      '      k = k + 1;',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    // Call binarySearch and searchCalls here.',
      '',
      '    int mCount = input.nextInt();',
      '    int[] unsorted = new int[mCount];',
      '    for (int i = 0; i < mCount; i++) {',
      '      unsorted[i] = input.nextInt();',
      '    }',
      '',
      '    // Call mergeSort here and print the result space separated.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static int binarySearch(int[] data, int target, int low, int high) {',
      '    if (low > high) {',
      '      return -1;',
      '    }',
      '    int mid = (low + high) / 2;',
      '    if (data[mid] == target) {',
      '      return mid;',
      '    } else if (data[mid] < target) {',
      '      return binarySearch(data, target, mid + 1, high);',
      '    } else {',
      '      return binarySearch(data, target, low, mid - 1);',
      '    }',
      '  }',
      '',
      '  public static int searchCalls(int[] data, int target, int low, int high) {',
      '    if (low > high) {',
      '      return 1;',
      '    }',
      '    int mid = (low + high) / 2;',
      '    if (data[mid] == target) {',
      '      return 1;',
      '    } else if (data[mid] < target) {',
      '      return 1 + searchCalls(data, target, mid + 1, high);',
      '    } else {',
      '      return 1 + searchCalls(data, target, low, mid - 1);',
      '    }',
      '  }',
      '',
      '  public static int[] mergeSort(int[] data) {',
      '    if (data.length <= 1) {',
      '      return data;',
      '    }',
      '    int mid = data.length / 2;',
      '    int[] left = new int[mid];',
      '    int[] right = new int[data.length - mid];',
      '    for (int i = 0; i < mid; i++) {',
      '      left[i] = data[i];',
      '    }',
      '    for (int i = mid; i < data.length; i++) {',
      '      right[i - mid] = data[i];',
      '    }',
      '    int[] sortedLeft = mergeSort(left);',
      '    int[] sortedRight = mergeSort(right);',
      '    return merge(sortedLeft, sortedRight);',
      '  }',
      '',
      '  private static int[] merge(int[] left, int[] right) {',
      '    int[] out = new int[left.length + right.length];',
      '    int i = 0;',
      '    int j = 0;',
      '    int k = 0;',
      '    while (i < left.length && j < right.length) {',
      '      if (left[i] <= right[j]) {',
      '        out[k] = left[i];',
      '        i = i + 1;',
      '      } else {',
      '        out[k] = right[j];',
      '        j = j + 1;',
      '      }',
      '      k = k + 1;',
      '    }',
      '    while (i < left.length) {',
      '      out[k] = left[i];',
      '      i = i + 1;',
      '      k = k + 1;',
      '    }',
      '    while (j < right.length) {',
      '      out[k] = right[j];',
      '      j = j + 1;',
      '      k = k + 1;',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    System.out.println(binarySearch(data, target, 0, data.length - 1));',
      '    System.out.println(searchCalls(data, target, 0, data.length - 1));',
      '',
      '    int mCount = input.nextInt();',
      '    int[] unsorted = new int[mCount];',
      '    for (int i = 0; i < mCount; i++) {',
      '      unsorted[i] = input.nextInt();',
      '    }',
      '    int[] sorted = mergeSort(unsorted);',
      '    String out = "";',
      '    for (int i = 0; i < sorted.length; i++) {',
      '      if (i > 0) {',
      '        out = out + " ";',
      '      }',
      '      out = out + sorted[i];',
      '    }',
      '    System.out.println(out);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'binarySearch and searchCalls follow the exact same recursive shape as each other: one returns the answer, the other returns how many calls it took, including the call that finally returns.',
      'mergeSort splits the array in half, calls itself on each half, and merges the two sorted results. The base case is an array of length 0 or 1, which is already sorted.',
      'merge is given because combining two sorted halves is not the recursive part of merge sort; the recursion is entirely in how the array gets split down to that base case.',
    ],
    seo: 'AP CSA 4.17 coding exercise: write a recursive binary search with a call counter and a recursive merge sort.',
    cases: [
      { stdin: '7\n1 2 3 5 7 8 9\n7\n5\n5 2 8 1 9\n', hidden: 0 },
      { stdin: '1\n42\n42\n1\n7\n', hidden: 0 },
      { stdin: '6\n2 4 6 8 10 12\n7\n4\n9 8 7 6\n', hidden: 1 },
      { stdin: '1\n5\n1\n1\n0\n', hidden: 1 },
      { stdin: '8\n1 2 3 4 5 6 7 8\n8\n3\n3 3 3\n', hidden: 1 },
    ],
  },
];

module.exports = { exercises };
