'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  AP CSA UNIT 3: CLASS CREATION - 9 code exercises, one per lesson.
//
//  EVERY ONE OF THESE IS A `driver` EXERCISE, AND THAT IS THE POINT
//  Unit 3 is about writing a class. A bare code segment cannot declare one, so
//  under the old grader this unit had no gradeable code item at all. Here the
//  student submits class definitions and NO main, and a hidden harness
//  constructs their object, calls their methods and prints what it observes.
//
//  Two things follow from that, and both are why this shape was chosen:
//
//    1. The student cannot print their way to a pass. They never see the
//       harness, so there is no output to imitate. The only way to make the
//       harness print the right thing is for the class to actually behave.
//    2. The API has to be stated exactly. A harness calls `getBalance()`, not
//       "a getter", so every exercise here lists the required signatures and the
//       page renders them as a contract. That is not bureaucracy: it is the same
//       thing the AP free response question does when it gives you the class
//       header and asks you to complete it.
//
//  THE HARNESS READS ITS OWN INPUT
//  Each harness takes its values from stdin, so one harness plus different
//  stdin gives hidden cases that drive the same class with values the page never
//  shows. The harness is identical across an exercise's cases; only the input
//  moves.
//
//  Expected outputs come from running the reference class through the real
//  harness with real javac/java. See seed/csa-exercises/index.js.
// ─────────────────────────────────────────────────────────────────────────────

const U = 'unit-3';

const exercises = [
  // ── 3.1 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.1', unit: U,
    handle: 'ap-csa-lesson-3-1-abstraction-and-program-design',
    title: 'Abstraction and Program Design',
    name: 'One Field, Three Views',
    mode: 'driver',
    brief: 'Abstraction is deciding what the outside world gets to know. This class stores a single number and offers three different views of it, and nobody using it can tell which one is the real one.',
    api: [
      'class Duration',
      'Duration(int totalSeconds)',
      'int getMinutes()',
      'int getSeconds()',
      'int getTotalSeconds()',
      'void add(int seconds)',
      'String format()',
    ],
    task: [
      'Write a class named Duration that stores a length of time in ONE private instance variable holding a whole number of seconds.',
      'The constructor takes the total number of seconds.',
      'getMinutes returns the number of whole minutes, and getSeconds returns the seconds left over after those minutes.',
      'getTotalSeconds returns the stored total, and add(seconds) increases it.',
      'format returns the minutes, then a colon, then the leftover seconds, with no spaces. For 125 seconds that is 2:5.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Duration {',
      '  // One private instance variable. Not two.',
      '',
      '  public Duration(int totalSeconds) {',
      '',
      '  }',
      '',
      '  public int getMinutes() {',
      '    return 0;',
      '  }',
      '',
      '  public int getSeconds() {',
      '    return 0;',
      '  }',
      '',
      '  public int getTotalSeconds() {',
      '    return 0;',
      '  }',
      '',
      '  public void add(int seconds) {',
      '',
      '  }',
      '',
      '  public String format() {',
      '    return "";',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Duration {',
      '  private int totalSeconds;',
      '',
      '  public Duration(int totalSeconds) {',
      '    this.totalSeconds = totalSeconds;',
      '  }',
      '',
      '  public int getMinutes() {',
      '    return totalSeconds / 60;',
      '  }',
      '',
      '  public int getSeconds() {',
      '    return totalSeconds % 60;',
      '  }',
      '',
      '  public int getTotalSeconds() {',
      '    return totalSeconds;',
      '  }',
      '',
      '  public void add(int seconds) {',
      '    totalSeconds = totalSeconds + seconds;',
      '  }',
      '',
      '  public String format() {',
      '    return getMinutes() + ":" + getSeconds();',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    int start = in.nextInt();',
      '    int extra = in.nextInt();',
      '    Duration d = new Duration(start);',
      '    System.out.println(d.getMinutes());',
      '    System.out.println(d.getSeconds());',
      '    System.out.println(d.format());',
      '    d.add(extra);',
      '    System.out.println(d.getTotalSeconds());',
      '    System.out.println(d.format());',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Duration d = new Duration(125);',
      '    System.out.println(d.format());',
      '    d.add(60);',
      '    System.out.println(d.format());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Storing minutes and seconds separately makes add() hard, because 45 seconds plus 30 has to carry. One total is the design that keeps every method short.',
      'getMinutes and getSeconds compute from the stored total every time they are called. They do not store anything of their own.',
      'format can call your own getMinutes and getSeconds rather than repeating the arithmetic.',
    ],
    seo: 'AP CSA 3.1 coding exercise: design a Duration class that stores one value and exposes minutes, seconds and a formatted view.',
    cases: [
      { stdin: '125 60\n', hidden: 0 },
      { stdin: '59 1\n', hidden: 0 },
      { stdin: '0 3600\n', hidden: 1 },
      { stdin: '3599 2\n', hidden: 1 },
      { stdin: '7205 0\n', hidden: 1 },
    ],
  },

  // ── 3.2 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.2', unit: U,
    handle: 'ap-csa-lesson-3-2-impact-of-program-design',
    title: 'Impact of Program Design',
    name: 'Scoreboard Interface',
    mode: 'driver',
    brief: 'What a method returns is a design decision with consequences. leader returns a NAME and margin returns a NUMBER, and a caller that only had the raw scores would have to work both out for itself every time.',
    api: [
      'class Scoreboard',
      'Scoreboard(String homeName, String awayName)',
      'void scoreHome(int points)',
      'void scoreAway(int points)',
      'int getHomeScore()',
      'int getAwayScore()',
      'String leader()',
      'int margin()',
    ],
    task: [
      'Write a class named Scoreboard that tracks two team names and their scores. Both scores start at zero.',
      'scoreHome and scoreAway add points to the right team.',
      'getHomeScore and getAwayScore return the current scores.',
      'leader returns the name of the team that is ahead, or the exact word TIE when the scores are equal.',
      'margin returns how far ahead the leader is, which is never negative.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Scoreboard {',
      '  // Instance variables for the two names and the two scores.',
      '',
      '  public Scoreboard(String homeName, String awayName) {',
      '',
      '  }',
      '',
      '  public void scoreHome(int points) {',
      '',
      '  }',
      '',
      '  public void scoreAway(int points) {',
      '',
      '  }',
      '',
      '  public int getHomeScore() {',
      '    return 0;',
      '  }',
      '',
      '  public int getAwayScore() {',
      '    return 0;',
      '  }',
      '',
      '  public String leader() {',
      '    return "";',
      '  }',
      '',
      '  public int margin() {',
      '    return 0;',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Scoreboard {',
      '  private String homeName;',
      '  private String awayName;',
      '  private int homeScore;',
      '  private int awayScore;',
      '',
      '  public Scoreboard(String homeName, String awayName) {',
      '    this.homeName = homeName;',
      '    this.awayName = awayName;',
      '  }',
      '',
      '  public void scoreHome(int points) {',
      '    homeScore = homeScore + points;',
      '  }',
      '',
      '  public void scoreAway(int points) {',
      '    awayScore = awayScore + points;',
      '  }',
      '',
      '  public int getHomeScore() {',
      '    return homeScore;',
      '  }',
      '',
      '  public int getAwayScore() {',
      '    return awayScore;',
      '  }',
      '',
      '  public String leader() {',
      '    if (homeScore > awayScore) {',
      '      return homeName;',
      '    } else if (awayScore > homeScore) {',
      '      return awayName;',
      '    }',
      '    return "TIE";',
      '  }',
      '',
      '  public int margin() {',
      '    return Math.abs(homeScore - awayScore);',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    String home = in.next();',
      '    String away = in.next();',
      '    Scoreboard board = new Scoreboard(home, away);',
      '    System.out.println(board.leader());',
      '    int plays = in.nextInt();',
      '    for (int i = 0; i < plays; i++) {',
      '      int who = in.nextInt();',
      '      int points = in.nextInt();',
      '      if (who == 1) {',
      '        board.scoreHome(points);',
      '      } else {',
      '        board.scoreAway(points);',
      '      }',
      '    }',
      '    System.out.println(board.getHomeScore());',
      '    System.out.println(board.getAwayScore());',
      '    System.out.println(board.leader());',
      '    System.out.println(board.margin());',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scoreboard board = new Scoreboard("Lions", "Bears");',
      '    board.scoreHome(7);',
      '    board.scoreAway(3);',
      '    System.out.println(board.leader());',
      '    System.out.println(board.margin());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A brand new Scoreboard has both scores at zero, so leader() has to answer TIE before anybody has scored.',
      'margin is never negative. Math.abs on the difference handles both directions in one expression.',
      'Return the stored name, not a copy you typed out. The team names come from whoever built the object.',
    ],
    seo: 'AP CSA 3.2 coding exercise: design a Scoreboard class whose methods return a leading team name and a margin.',
    cases: [
      { stdin: 'Lions Bears\n3\n1 7\n2 3\n1 3\n', hidden: 0 },
      { stdin: 'Reds Blues\n0\n', hidden: 0 },
      { stdin: 'Hawks Owls\n4\n2 6\n2 6\n1 6\n1 6\n', hidden: 1 },
      { stdin: 'Ants Bees\n2\n2 21\n1 3\n', hidden: 1 },
      { stdin: 'North South\n1\n1 100\n', hidden: 1 },
    ],
  },

  // ── 3.3 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.3', unit: U,
    handle: 'ap-csa-lesson-3-3-anatomy-of-a-class',
    title: 'Anatomy of a Class',
    name: 'Private Data, Public Doors',
    mode: 'driver',
    brief: 'Instance variables private, methods public. The accessor lets the outside read and the mutator lets it write, and every rule the class enforces lives in the mutator because that is the only way in.',
    api: [
      'class Student',
      'Student(String name, int grade)',
      'String getName()',
      'int getGrade()',
      'void setGrade(int grade)',
      'boolean isPassing()',
    ],
    task: [
      'Write a class named Student with two PRIVATE instance variables: a name and a grade.',
      'The constructor sets both.',
      'getName and getGrade return them.',
      'setGrade changes the grade, but it must refuse anything below 0 or above 100 and leave the grade unchanged in that case.',
      'isPassing returns true when the grade is 60 or more.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Student {',
      '  // Two private instance variables.',
      '',
      '  public Student(String name, int grade) {',
      '',
      '  }',
      '',
      '  public String getName() {',
      '    return "";',
      '  }',
      '',
      '  public int getGrade() {',
      '    return 0;',
      '  }',
      '',
      '  public void setGrade(int grade) {',
      '    // Reject anything outside 0 to 100.',
      '  }',
      '',
      '  public boolean isPassing() {',
      '    return false;',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Student {',
      '  private String name;',
      '  private int grade;',
      '',
      '  public Student(String name, int grade) {',
      '    this.name = name;',
      '    this.grade = grade;',
      '  }',
      '',
      '  public String getName() {',
      '    return name;',
      '  }',
      '',
      '  public int getGrade() {',
      '    return grade;',
      '  }',
      '',
      '  public void setGrade(int grade) {',
      '    if (grade >= 0 && grade <= 100) {',
      '      this.grade = grade;',
      '    }',
      '  }',
      '',
      '  public boolean isPassing() {',
      '    return grade >= 60;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    String name = in.next();',
      '    int start = in.nextInt();',
      '    Student s = new Student(name, start);',
      '    System.out.println(s.getName());',
      '    System.out.println(s.getGrade());',
      '    System.out.println(s.isPassing());',
      '    int attempts = in.nextInt();',
      '    for (int i = 0; i < attempts; i++) {',
      '      s.setGrade(in.nextInt());',
      '      System.out.println(s.getGrade());',
      '    }',
      '    System.out.println(s.isPassing());',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Student s = new Student("Rae", 72);',
      '    System.out.println(s.getGrade());',
      '    s.setGrade(150);',
      '    System.out.println(s.getGrade());',
      '    s.setGrade(55);',
      '    System.out.println(s.isPassing());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The parameter in setGrade has the same name as the instance variable, so this.grade is the field and grade on its own is the parameter.',
      'A rejected grade changes nothing at all. Do not set it to 0 or to 100, just leave it alone.',
      'The constructor is not asked to validate, so a Student can be built with an out of range grade. Only setGrade guards.',
    ],
    seo: 'AP CSA 3.3 coding exercise: write a Student class with private fields, accessors and a mutator that validates its input.',
    cases: [
      { stdin: 'Rae 72\n3\n150\n55\n-4\n', hidden: 0 },
      { stdin: 'Kim 100\n1\n0\n', hidden: 0 },
      { stdin: 'Jae 59\n2\n60\n101\n', hidden: 1 },
      { stdin: 'Tam 45\n0\n', hidden: 1 },
      { stdin: 'Lou 88\n4\n-1\n101\n100\n60\n', hidden: 1 },
    ],
  },

  // ── 3.4 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.4', unit: U,
    handle: 'ap-csa-lesson-3-4-constructors',
    title: 'Constructors',
    name: 'Three Ways to Build It',
    mode: 'driver',
    brief: 'Overloaded constructors are chosen by what you pass, not by what you name. Three constructors here take three different argument lists, and the compiler picks between them before your program ever runs.',
    api: [
      'class Rectangle',
      'Rectangle(int width, int height)',
      'Rectangle(int side)',
      'Rectangle()',
      'int getWidth()',
      'int getHeight()',
      'int getArea()',
      'int getPerimeter()',
    ],
    task: [
      'Write a class named Rectangle with private width and height.',
      'The two argument constructor sets width and height.',
      'The one argument constructor makes a square with that side length.',
      'The no argument constructor makes a 1 by 1 rectangle.',
      'getWidth, getHeight, getArea and getPerimeter return what their names say. The perimeter is twice the width plus twice the height.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Rectangle {',
      '  private int width;',
      '  private int height;',
      '',
      '  public Rectangle(int width, int height) {',
      '',
      '  }',
      '',
      '  public Rectangle(int side) {',
      '',
      '  }',
      '',
      '  public Rectangle() {',
      '',
      '  }',
      '',
      '  public int getWidth() {',
      '    return 0;',
      '  }',
      '',
      '  public int getHeight() {',
      '    return 0;',
      '  }',
      '',
      '  public int getArea() {',
      '    return 0;',
      '  }',
      '',
      '  public int getPerimeter() {',
      '    return 0;',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Rectangle {',
      '  private int width;',
      '  private int height;',
      '',
      '  public Rectangle(int width, int height) {',
      '    this.width = width;',
      '    this.height = height;',
      '  }',
      '',
      '  public Rectangle(int side) {',
      '    this(side, side);',
      '  }',
      '',
      '  public Rectangle() {',
      '    this(1, 1);',
      '  }',
      '',
      '  public int getWidth() {',
      '    return width;',
      '  }',
      '',
      '  public int getHeight() {',
      '    return height;',
      '  }',
      '',
      '  public int getArea() {',
      '    return width * height;',
      '  }',
      '',
      '  public int getPerimeter() {',
      '    return 2 * width + 2 * height;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    int w = in.nextInt();',
      '    int h = in.nextInt();',
      '    int side = in.nextInt();',
      '    Rectangle a = new Rectangle(w, h);',
      '    Rectangle b = new Rectangle(side);',
      '    Rectangle c = new Rectangle();',
      '    System.out.println(a.getArea());',
      '    System.out.println(a.getPerimeter());',
      '    System.out.println(b.getWidth());',
      '    System.out.println(b.getHeight());',
      '    System.out.println(b.getArea());',
      '    System.out.println(c.getArea());',
      '    System.out.println(c.getPerimeter());',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    System.out.println(new Rectangle(3, 4).getArea());',
      '    System.out.println(new Rectangle(5).getArea());',
      '    System.out.println(new Rectangle().getPerimeter());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A constructor has no return type, not even void, and its name matches the class exactly.',
      'this(side, side) calls another constructor of the same class, so the square version does not have to repeat the assignments.',
      'Writing any constructor removes the free no argument one Java would have given you, which is why the empty one has to be declared.',
    ],
    seo: 'AP CSA 3.4 coding exercise: write three overloaded Rectangle constructors and have them share work with this().',
    cases: [
      { stdin: '3 4 5\n', hidden: 0 },
      { stdin: '1 1 1\n', hidden: 0 },
      { stdin: '10 2 7\n', hidden: 1 },
      { stdin: '0 9 0\n', hidden: 1 },
      { stdin: '6 6 12\n', hidden: 1 },
    ],
  },

  // ── 3.5 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.5', unit: U,
    handle: 'ap-csa-lesson-3-5-methods-how-to-write-them',
    title: 'Methods: How to Write Them',
    name: 'Five Headers, Five Bodies',
    mode: 'driver',
    brief: 'Return type, name, parameters, body. Four of these methods hand something back and one hands back nothing at all, and getting the return type wrong is a compile error rather than a wrong answer.',
    api: [
      'class Toolkit',
      'int triple(int n)',
      'double average(int a, int b)',
      'boolean isEven(int n)',
      'String repeat(String s, int times)',
      'void remember(int n)',
      'int getLast()',
    ],
    task: [
      'Write a class named Toolkit with the six methods listed above.',
      'triple returns three times n. isEven returns whether n divides evenly by 2.',
      'average returns the exact average of the two ints as a double, so 3 and 4 give 3.5 and not 3.',
      'repeat returns s joined to itself times times. Zero times gives the empty String.',
      'remember stores n and returns nothing. getLast returns the last value remembered, or 0 before anything has been.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Toolkit {',
      '  // remember needs somewhere to put the value.',
      '',
      '  public int triple(int n) {',
      '    return 0;',
      '  }',
      '',
      '  public double average(int a, int b) {',
      '    return 0.0;',
      '  }',
      '',
      '  public boolean isEven(int n) {',
      '    return false;',
      '  }',
      '',
      '  public String repeat(String s, int times) {',
      '    return "";',
      '  }',
      '',
      '  public void remember(int n) {',
      '',
      '  }',
      '',
      '  public int getLast() {',
      '    return 0;',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Toolkit {',
      '  private int last;',
      '',
      '  public int triple(int n) {',
      '    return n * 3;',
      '  }',
      '',
      '  public double average(int a, int b) {',
      '    return (a + b) / 2.0;',
      '  }',
      '',
      '  public boolean isEven(int n) {',
      '    return n % 2 == 0;',
      '  }',
      '',
      '  public String repeat(String s, int times) {',
      '    String out = "";',
      '    for (int i = 0; i < times; i++) {',
      '      out = out + s;',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public void remember(int n) {',
      '    last = n;',
      '  }',
      '',
      '  public int getLast() {',
      '    return last;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    int a = in.nextInt();',
      '    int b = in.nextInt();',
      '    String s = in.next();',
      '    int times = in.nextInt();',
      '    Toolkit t = new Toolkit();',
      '    System.out.println(t.getLast());',
      '    System.out.println(t.triple(a));',
      '    System.out.println(t.average(a, b));',
      '    System.out.println(t.isEven(a));',
      '    System.out.println(t.isEven(b));',
      '    System.out.println(t.repeat(s, times));',
      '    t.remember(a + b);',
      '    System.out.println(t.getLast());',
      '    t.remember(t.triple(b));',
      '    System.out.println(t.getLast());',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Toolkit t = new Toolkit();',
      '    System.out.println(t.triple(5));',
      '    System.out.println(t.average(3, 4));',
      '    System.out.println(t.repeat("ab", 3));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      '(a + b) / 2 divides two ints and loses the half. Dividing by 2.0 makes it a double division.',
      'A void method has no return statement with a value after it. It changes something instead of handing something back.',
      'repeat with times of 0 returns the empty String, so start your result at "" and let the loop not run.',
    ],
    seo: 'AP CSA 3.5 coding exercise: write value returning and void methods with int, double, boolean and String return types.',
    cases: [
      { stdin: '3 4 ab 3\n', hidden: 0 },
      { stdin: '10 10 x 1\n', hidden: 0 },
      { stdin: '-5 8 hey 0\n', hidden: 1 },
      { stdin: '7 2 zz 5\n', hidden: 1 },
      { stdin: '0 1 q 2\n', hidden: 1 },
    ],
  },

  // ── 3.6 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.6', unit: U,
    handle: 'ap-csa-lesson-3-6-methods-passing-returning-object-references',
    title: 'Methods: Passing and Returning Object References',
    name: 'Boxes That Know About Boxes',
    mode: 'driver',
    brief: 'A method that takes an object can change it, and a method that returns one hands back a reference rather than a copy. absorb proves the first and bigger proves the second, and the harness checks both by looking at the original objects afterwards.',
    api: [
      'class Box',
      'Box(int size)',
      'int getSize()',
      'void absorb(Box other)',
      'Box bigger(Box other)',
    ],
    task: [
      'Write a class named Box with a private size.',
      'absorb(other) adds the other box size to this box size, and sets the OTHER box size to 0.',
      'bigger(other) returns whichever of the two boxes has the larger size, returning this box when they are equal.',
      'Return the actual object, not a new Box built from its size. The grader checks that by changing the returned box and looking at the original.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Box {',
      '  private int size;',
      '',
      '  public Box(int size) {',
      '    this.size = size;',
      '  }',
      '',
      '  public int getSize() {',
      '    return size;',
      '  }',
      '',
      '  public void absorb(Box other) {',
      '    // Grow by other size, then empty the other box.',
      '  }',
      '',
      '  public Box bigger(Box other) {',
      '    return null;',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Box {',
      '  private int size;',
      '',
      '  public Box(int size) {',
      '    this.size = size;',
      '  }',
      '',
      '  public int getSize() {',
      '    return size;',
      '  }',
      '',
      '  public void absorb(Box other) {',
      '    size = size + other.size;',
      '    other.size = 0;',
      '  }',
      '',
      '  public Box bigger(Box other) {',
      '    if (other.size > size) {',
      '      return other;',
      '    }',
      '    return this;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    Box a = new Box(in.nextInt());',
      '    Box b = new Box(in.nextInt());',
      '    Box c = new Box(in.nextInt());',
      '    System.out.println(a.bigger(b).getSize());',
      '    a.absorb(b);',
      '    System.out.println(a.getSize());',
      '    System.out.println(b.getSize());',
      '    Box winner = a.bigger(c);',
      '    winner.absorb(new Box(1000));',
      '    System.out.println(a.getSize());',
      '    System.out.println(c.getSize());',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Box a = new Box(3);',
      '    Box b = new Box(9);',
      '    System.out.println(a.bigger(b).getSize());',
      '    a.absorb(b);',
      '    System.out.println(a.getSize() + " " + b.getSize());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Inside Box you can reach other.size directly. A class can see the private members of every object of its own type.',
      'return this; hands back the object the method was called on. It is a reference, so the caller and you are looking at one box.',
      'Returning new Box(size) would pass the size checks and fail the last two lines, because changing the copy leaves the original alone.',
    ],
    seo: 'AP CSA 3.6 coding exercise: pass an object into a method that changes it and return an object reference from another.',
    cases: [
      { stdin: '3 9 4\n', hidden: 0 },
      { stdin: '5 5 5\n', hidden: 0 },
      { stdin: '1 2 100\n', hidden: 1 },
      { stdin: '50 0 7\n', hidden: 1 },
      { stdin: '0 0 1\n', hidden: 1 },
    ],
  },

  // ── 3.7 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.7', unit: U,
    handle: 'ap-csa-lesson-3-7-class-variables-and-methods',
    title: 'Class Variables and Methods',
    name: 'One Counter for Everybody',
    mode: 'driver',
    brief: 'A static variable belongs to the class, so every object shares the one copy. That is exactly what a ticket counter needs and exactly what a ticket holder name must never be.',
    api: [
      'class Ticket',
      'Ticket(String holder)',
      'String getHolder()',
      'int getNumber()',
      'static int getIssued()',
      'static void reset()',
    ],
    task: [
      'Write a class named Ticket. Each ticket has its own holder name and its own number.',
      'Keep a STATIC count of how many tickets have been created. It starts at zero.',
      'The constructor increases that count and gives this ticket the new count as its number, so the first ticket ever made is number 1.',
      'getIssued is a static method returning the count, and it must be callable as Ticket.getIssued() without any object.',
      'reset is static and sets the count back to zero. It does not change any ticket that already exists.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Ticket {',
      '  // One of these belongs to the class. Two of them belong to each object.',
      '',
      '  public Ticket(String holder) {',
      '',
      '  }',
      '',
      '  public String getHolder() {',
      '    return "";',
      '  }',
      '',
      '  public int getNumber() {',
      '    return 0;',
      '  }',
      '',
      '  public static int getIssued() {',
      '    return 0;',
      '  }',
      '',
      '  public static void reset() {',
      '',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Ticket {',
      '  private static int issued;',
      '  private String holder;',
      '  private int number;',
      '',
      '  public Ticket(String holder) {',
      '    issued++;',
      '    this.holder = holder;',
      '    this.number = issued;',
      '  }',
      '',
      '  public String getHolder() {',
      '    return holder;',
      '  }',
      '',
      '  public int getNumber() {',
      '    return number;',
      '  }',
      '',
      '  public static int getIssued() {',
      '    return issued;',
      '  }',
      '',
      '  public static void reset() {',
      '    issued = 0;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    System.out.println(Ticket.getIssued());',
      '    int n = in.nextInt();',
      '    Ticket last = null;',
      '    for (int i = 0; i < n; i++) {',
      '      last = new Ticket(in.next());',
      '      System.out.println(last.getNumber());',
      '    }',
      '    System.out.println(Ticket.getIssued());',
      '    if (last != null) {',
      '      System.out.println(last.getHolder());',
      '    }',
      '    Ticket.reset();',
      '    System.out.println(Ticket.getIssued());',
      '    if (last != null) {',
      '      System.out.println(last.getNumber());',
      '    }',
      '    Ticket after = new Ticket(in.next());',
      '    System.out.println(after.getNumber());',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Ticket a = new Ticket("Ada");',
      '    Ticket b = new Ticket("Bo");',
      '    System.out.println(a.getNumber() + " " + b.getNumber());',
      '    System.out.println(Ticket.getIssued());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The holder name and the ticket number are per object, so they are NOT static. Only the running count is.',
      'A static method cannot read an instance variable, because there is no object for it to read one from. If getIssued will not compile, the count is not static.',
      'reset only changes the shared count. A ticket already holding number 3 keeps it, which is the point of the last printed line.',
    ],
    seo: 'AP CSA 3.7 coding exercise: use a static class variable to number tickets and static methods to read and reset it.',
    cases: [
      { stdin: '3\nAda\nBo\nCy\nDee\n', hidden: 0 },
      { stdin: '1\nSol\nRay\n', hidden: 0 },
      { stdin: '0\nZed\n', hidden: 1 },
      { stdin: '5\na\nb\nc\nd\ne\nf\n', hidden: 1 },
      { stdin: '2\nMax\nMax\nMax\n', hidden: 1 },
    ],
  },

  // ── 3.8 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.8', unit: U,
    handle: 'ap-csa-lesson-3-8-scope-and-access',
    title: 'Scope and Access',
    name: 'Same Name, Different Variable',
    mode: 'driver',
    brief: 'A local variable with the same name as an instance variable does not touch it. This class has both, on purpose, and the only way to pass is to know which one each line is talking about.',
    api: [
      'class Vault',
      'Vault(int balance)',
      'int getBalance()',
      'int previewDeposit(int amount)',
      'void deposit(int amount)',
      'int getDepositCount()',
    ],
    task: [
      'Write a class named Vault with a private instance variable named balance and a private count of deposits.',
      'previewDeposit must declare a LOCAL variable also named balance, set it to the instance balance plus the amount, and return it. It must not change the instance variable or the count.',
      'deposit adds the amount to the INSTANCE balance and increases the deposit count by one.',
      'getBalance returns the instance balance and getDepositCount returns the count.',
      'The grader calls previewDeposit and then checks that nothing changed.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Vault {',
      '  private int balance;',
      '  private int depositCount;',
      '',
      '  public Vault(int balance) {',
      '    this.balance = balance;',
      '  }',
      '',
      '  public int getBalance() {',
      '    return balance;',
      '  }',
      '',
      '  public int previewDeposit(int amount) {',
      '    // Declare a local int balance here. Do not change the field.',
      '    return 0;',
      '  }',
      '',
      '  public void deposit(int amount) {',
      '',
      '  }',
      '',
      '  public int getDepositCount() {',
      '    return 0;',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Vault {',
      '  private int balance;',
      '  private int depositCount;',
      '',
      '  public Vault(int balance) {',
      '    this.balance = balance;',
      '  }',
      '',
      '  public int getBalance() {',
      '    return balance;',
      '  }',
      '',
      '  public int previewDeposit(int amount) {',
      '    int balance = this.balance + amount;',
      '    return balance;',
      '  }',
      '',
      '  public void deposit(int amount) {',
      '    balance = balance + amount;',
      '    depositCount++;',
      '  }',
      '',
      '  public int getDepositCount() {',
      '    return depositCount;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    Vault v = new Vault(in.nextInt());',
      '    int first = in.nextInt();',
      '    int second = in.nextInt();',
      '    System.out.println(v.previewDeposit(first));',
      '    System.out.println(v.getBalance());',
      '    System.out.println(v.getDepositCount());',
      '    v.deposit(first);',
      '    System.out.println(v.getBalance());',
      '    System.out.println(v.previewDeposit(second));',
      '    System.out.println(v.getBalance());',
      '    v.deposit(second);',
      '    System.out.println(v.getBalance());',
      '    System.out.println(v.getDepositCount());',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Vault v = new Vault(100);',
      '    System.out.println(v.previewDeposit(50));',
      '    System.out.println(v.getBalance());',
      '    v.deposit(50);',
      '    System.out.println(v.getBalance());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Once a local named balance exists, the bare word balance means the local for the rest of that method. this.balance is the only way back to the field.',
      'previewDeposit changes nothing, so calling it twice in a row must give the same answer twice.',
      'depositCount goes up in deposit only. If your preview touches it, the third printed line will be wrong.',
    ],
    seo: 'AP CSA 3.8 coding exercise: shadow an instance variable with a local of the same name and use this to reach the field.',
    cases: [
      { stdin: '100 50 25\n', hidden: 0 },
      { stdin: '0 0 0\n', hidden: 0 },
      { stdin: '-40 100 -10\n', hidden: 1 },
      { stdin: '7 7 7\n', hidden: 1 },
      { stdin: '1000 1 999\n', hidden: 1 },
    ],
  },

  // ── 3.9 ────────────────────────────────────────────────────────────────────
  {
    lesson: '3.9', unit: U,
    handle: 'ap-csa-lesson-3-9-this-keyword',
    title: 'The this Keyword',
    name: 'Returning Yourself',
    mode: 'driver',
    brief: 'this is a reference to the object the method was called on, which means a method can hand the object back. Do that and calls chain, which is a real pattern and not a trick.',
    api: [
      'class Robot',
      'Robot(String name, int x)',
      'Robot move(int dx)',
      'Robot rename(String name)',
      'String getName()',
      'int getX()',
      'String describe()',
    ],
    task: [
      'Write a class named Robot with a private name and a private x position.',
      'The constructor takes a name and a starting x, and its parameters must have the SAME names as the instance variables, so this is required to tell them apart.',
      'move(dx) adds dx to x and returns this robot, so calls can be chained.',
      'rename(name) changes the name and returns this robot.',
      'describe returns the name, then an @ sign, then x, with no spaces.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class Robot {',
      '  private String name;',
      '  private int x;',
      '',
      '  public Robot(String name, int x) {',
      '    // Both parameters are shadowing. Use this.',
      '  }',
      '',
      '  public Robot move(int dx) {',
      '    return null;',
      '  }',
      '',
      '  public Robot rename(String name) {',
      '    return null;',
      '  }',
      '',
      '  public String getName() {',
      '    return "";',
      '  }',
      '',
      '  public int getX() {',
      '    return 0;',
      '  }',
      '',
      '  public String describe() {',
      '    return "";',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class Robot {',
      '  private String name;',
      '  private int x;',
      '',
      '  public Robot(String name, int x) {',
      '    this.name = name;',
      '    this.x = x;',
      '  }',
      '',
      '  public Robot move(int dx) {',
      '    this.x = this.x + dx;',
      '    return this;',
      '  }',
      '',
      '  public Robot rename(String name) {',
      '    this.name = name;',
      '    return this;',
      '  }',
      '',
      '  public String getName() {',
      '    return name;',
      '  }',
      '',
      '  public int getX() {',
      '    return x;',
      '  }',
      '',
      '  public String describe() {',
      '    return name + "@" + x;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    String name = in.next();',
      '    int x = in.nextInt();',
      '    int d1 = in.nextInt();',
      '    int d2 = in.nextInt();',
      '    String newName = in.next();',
      '    Robot r = new Robot(name, x);',
      '    System.out.println(r.describe());',
      '    System.out.println(r.move(d1).move(d2).describe());',
      '    System.out.println(r.getX());',
      '    Robot same = r.rename(newName);',
      '    System.out.println(same.describe());',
      '    System.out.println(r.getName());',
      '    System.out.println(same.move(d1) == r);',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Robot r = new Robot("Ada", 0);',
      '    System.out.println(r.move(3).move(4).describe());',
      '    System.out.println(r.rename("Bo").describe());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'this.name = name; assigns the parameter to the field. Writing name = name; assigns the parameter to itself and leaves the field empty.',
      'return this; is what makes r.move(3).move(4) work: the first move hands back the same robot for the second one to be called on.',
      'The last check compares references with ==, so returning a new Robot instead of this prints false.',
    ],
    seo: 'AP CSA 3.9 coding exercise: use this to resolve shadowed parameters and return this so method calls can chain.',
    cases: [
      { stdin: 'Ada 0 3 4 Bo\n', hidden: 0 },
      { stdin: 'Zip 10 -10 0 Zip\n', hidden: 0 },
      { stdin: 'Rover -5 2 2 Fido\n', hidden: 1 },
      { stdin: 'Q 100 -50 -50 R\n', hidden: 1 },
      { stdin: 'Nine 1 1 1 Ten\n', hidden: 1 },
    ],
  },
];

module.exports = { exercises };
