'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  AP CSA UNIT 4: DATA COLLECTIONS - 17 code exercises, one per lesson.
//
//  ORDER IS RESPECTED HERE TOO
//  4.2 introduces data sets and the enhanced for loop BEFORE 4.3 teaches array
//  creation, so 4.2's starter builds the array and the student writes only the
//  traversal. From 4.3 on, the student builds their own.
//
//  4.6 IS A `driver` EXERCISE ON PURPOSE
//  "Write a method that takes an array and returns an array" cannot be graded by
//  looking at what a program printed: a student could print the right numbers
//  without ever writing the method. The hidden harness calls the methods by name
//  and prints what they returned, so the method has to exist and has to work.
//
//  4.14 AND THE FILE THAT IS NOT A FILE
//  Judge0 has no filesystem to hand a student a data file in, so 4.14 pipes the
//  data in on standard input and the exercise says so plainly. The skill being
//  practised is the real one: driving a Scanner with hasNextLine and hasNextInt
//  rather than knowing in advance how much data is coming.
//
//  Expected outputs come from running each reference through real javac/java.
// ─────────────────────────────────────────────────────────────────────────────

const U = 'unit-4';

const exercises = [
  // ── 4.1 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.1', unit: U,
    handle: 'ap-csa-lesson-4-1-ethical-social-issues-data-collection',
    title: 'Ethical and Social Issues Around Data Collection',
    name: 'Report the Aggregate, Not the Person',
    mode: 'program',
    brief: 'Data minimisation is a thing you write, not a thing you agree with. This program is handed identifying records and has to answer questions about the group without ever printing anything that points at one person.',
    task: [
      'Read an integer count, then that many records. Each record is an id number and then an age, on one line.',
      'Print the number of records you read.',
      'Print the average age as an integer, using integer division.',
      'Print how many of the people were 18 or older.',
      'Print the range, meaning the oldest age minus the youngest.',
      'Print no id, and no individual age. The grader checks that the ids never appear in your output.',
    ],
    reads: 'A count, then that many lines of two integers: an id and an age.',
    prints: 'Four lines: the record count, the average age, the count of adults and the age range.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '',
      '    // Read the ids, use none of them.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '',
      '    int total = 0;',
      '    int adults = 0;',
      '    int oldest = 0;',
      '    int youngest = 0;',
      '    for (int i = 0; i < count; i++) {',
      '      input.nextInt();',
      '      int age = input.nextInt();',
      '      total = total + age;',
      '      if (age >= 18) {',
      '        adults = adults + 1;',
      '      }',
      '      if (i == 0 || age > oldest) {',
      '        oldest = age;',
      '      }',
      '      if (i == 0 || age < youngest) {',
      '        youngest = age;',
      '      }',
      '    }',
      '    System.out.println(count);',
      '    System.out.println(total / count);',
      '    System.out.println(adults);',
      '    System.out.println(oldest - youngest);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'You still have to READ the id to get past it to the age. Reading it and not keeping it is exactly the point.',
      'The average is asked for as an integer, so plain int division is correct here and no cast is wanted.',
      'Seed the oldest and youngest from the first record rather than from 0, or a data set of teenagers reports a youngest age of 0.',
    ],
    seo: 'AP CSA 4.1 coding exercise: summarise a data set with aggregate statistics while never printing an identifying value.',
    cases: [
      { stdin: '4\n101 17\n102 23\n103 40\n104 12\n', hidden: 0 },
      { stdin: '1\n900 18\n', hidden: 0 },
      { stdin: '5\n1 65\n2 65\n3 65\n4 65\n5 65\n', hidden: 1 },
      { stdin: '3\n7 1\n8 99\n9 50\n', hidden: 1 },
      { stdin: '6\n11 13\n12 14\n13 15\n14 16\n15 17\n16 18\n', hidden: 1 },
    ],
  },

  // ── 4.2 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.2', unit: U,
    handle: 'ap-csa-lesson-4-2-introduction-to-using-data-sets',
    title: 'Introduction to Using Data Sets',
    name: 'For Each, Not For i',
    mode: 'program',
    brief: 'The enhanced for loop hands you the values and never the positions. That makes it the right tool for a total and the wrong tool the moment you need to know where you are, which is the distinction this exercise is built around.',
    task: [
      'The array is built for you from the input. Do not change that part.',
      'Using an ENHANCED for loop, print the sum of the values.',
      'Using an enhanced for loop, print how many of them are odd.',
      'Using an enhanced for loop, print the largest value.',
      'On the last line print the number of values, which the array itself can tell you.',
    ],
    reads: 'An integer count, then that many integers.',
    prints: 'Four lines: the sum, the count of odd values, the largest value and how many values there were.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    // From here on, use for (int value : data) and not an index.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    int sum = 0;',
      '    for (int value : data) {',
      '      sum = sum + value;',
      '    }',
      '    System.out.println(sum);',
      '',
      '    int odd = 0;',
      '    for (int value : data) {',
      '      if (value % 2 != 0) {',
      '        odd = odd + 1;',
      '      }',
      '    }',
      '    System.out.println(odd);',
      '',
      '    int largest = data[0];',
      '    for (int value : data) {',
      '      if (value > largest) {',
      '        largest = value;',
      '      }',
      '    }',
      '    System.out.println(largest);',
      '',
      '    System.out.println(data.length);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'for (int value : data) reads every element in order. There is no i, and you do not need one for any of these three answers.',
      'data.length is a field, not a method, so there are no parentheses after it.',
      'A negative odd number is still odd. value % 2 != 0 is true for -3, while value % 2 == 1 is not.',
    ],
    seo: 'AP CSA 4.2 coding exercise: traverse a data set three times with the enhanced for loop and read its length.',
    cases: [
      { stdin: '5\n4 7 2 9 1\n', hidden: 0 },
      { stdin: '1\n6\n', hidden: 0 },
      { stdin: '4\n-3 -8 -5 -2\n', hidden: 1 },
      { stdin: '6\n0 0 0 0 0 1\n', hidden: 1 },
      { stdin: '3\n100 100 99\n', hidden: 1 },
    ],
  },

  // ── 4.3 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.3', unit: U,
    handle: 'ap-csa-lesson-4-3-array-creation-and-access',
    title: 'Array Creation and Access',
    name: 'Build It, Index It',
    mode: 'program',
    brief: 'An array of length n has indexes 0 through n minus 1, and asking for index n is the single most common runtime error in this unit. Two of the lines here are about the ends of the array for that reason.',
    task: [
      'Read an integer count, then create an int array of that length.',
      'Read that many values into the array, in order.',
      'Print the length of the array.',
      'Print the FIRST element, then the LAST element, each on its own line.',
      'Print the element at the middle index, which is the length divided by 2 using integer division.',
      'Print the sum of the first and last elements.',
    ],
    reads: 'An integer count of at least 1, then that many integers.',
    prints: 'Five lines: the length, the first element, the last element, the middle element and the sum of the ends.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '',
      '    // new int[count] makes the array. A loop fills it.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    System.out.println(data.length);',
      '    System.out.println(data[0]);',
      '    System.out.println(data[data.length - 1]);',
      '    System.out.println(data[data.length / 2]);',
      '    System.out.println(data[0] + data[data.length - 1]);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The last index is length - 1. data[data.length] is one past the end and throws ArrayIndexOutOfBoundsException.',
      'new int[count] fills the array with zeros. Your loop is what puts the real values in.',
      'For an array of length 5 the middle index is 2, which has two elements on each side. For length 4 it is 2, which is the right hand middle.',
    ],
    seo: 'AP CSA 4.3 coding exercise: create an int array, fill it from input and access the first, last and middle elements.',
    cases: [
      { stdin: '5\n10 20 30 40 50\n', hidden: 0 },
      { stdin: '1\n7\n', hidden: 0 },
      { stdin: '4\n2 4 6 8\n', hidden: 1 },
      { stdin: '6\n-1 -2 -3 -4 -5 -6\n', hidden: 1 },
      { stdin: '2\n99 1\n', hidden: 1 },
    ],
  },

  // ── 4.4 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.4', unit: U,
    handle: 'ap-csa-lesson-4-4-traversing-arrays',
    title: 'Traversing Arrays',
    name: 'Both Directions',
    mode: 'program',
    brief: 'Sometimes you need the index and sometimes you only need the value. This exercise asks for both in the same program so the choice between an indexed loop and an enhanced one has to be made deliberately.',
    task: [
      'Read an integer count, then that many integers into an array.',
      'Print every element on its own line, front to back.',
      'Print every element on its own line, back to front.',
      'Print the index of the largest element. When it appears more than once, print the FIRST index it appears at.',
      'Print the sum of the elements at even indexes.',
    ],
    reads: 'An integer count of at least 1, then that many integers.',
    prints: 'The elements forwards, then backwards, then the index of the maximum, then the sum at even indexes.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    // Two traversals, then two answers that need the index.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    for (int value : data) {',
      '      System.out.println(value);',
      '    }',
      '    for (int i = data.length - 1; i >= 0; i--) {',
      '      System.out.println(data[i]);',
      '    }',
      '',
      '    int best = 0;',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] > data[best]) {',
      '        best = i;',
      '      }',
      '    }',
      '    System.out.println(best);',
      '',
      '    int evenSum = 0;',
      '    for (int i = 0; i < data.length; i = i + 2) {',
      '      evenSum = evenSum + data[i];',
      '    }',
      '    System.out.println(evenSum);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The backwards loop starts at length - 1 and tests i >= 0. Starting at length is the off by one that throws.',
      'Use a strict > when hunting the maximum index, so a repeated maximum keeps the first position rather than the last.',
      'Even INDEXES means 0, 2, 4 and so on, which is not the same as even values. Step the loop by 2.',
    ],
    seo: 'AP CSA 4.4 coding exercise: traverse an array forwards and backwards and use the index to find a maximum position.',
    cases: [
      { stdin: '5\n3 9 4 9 1\n', hidden: 0 },
      { stdin: '1\n42\n', hidden: 0 },
      { stdin: '4\n-2 -7 -1 -9\n', hidden: 1 },
      { stdin: '6\n5 5 5 5 5 5\n', hidden: 1 },
      { stdin: '3\n1 2 3\n', hidden: 1 },
    ],
  },

  // ── 4.5 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.5', unit: U,
    handle: 'ap-csa-lesson-4-5-algorithms-with-arrays',
    title: 'Algorithms with Arrays',
    name: 'Four Standard Algorithms',
    mode: 'program',
    brief: 'These four turn up on the exam in some form every year. Writing them once from an empty editor is worth more than reading them ten times.',
    task: [
      'Read an integer count, then that many integers into an array.',
      'Print the sum of all the elements.',
      'Print the average as a double, so a whole number still shows a decimal point.',
      'Print how many elements are strictly greater than that average.',
      'Print true when the array is in non decreasing order, and false otherwise.',
      'Print the number of pairs of neighbouring elements that are equal.',
    ],
    reads: 'An integer count of at least 1, then that many integers.',
    prints: 'Five lines: the sum, the average, the count above average, the sorted check and the equal neighbour count.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    // Five answers. Two of them compare neighbours.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '',
      '    int sum = 0;',
      '    for (int value : data) {',
      '      sum = sum + value;',
      '    }',
      '    System.out.println(sum);',
      '',
      '    double average = (double) sum / data.length;',
      '    System.out.println(average);',
      '',
      '    int above = 0;',
      '    for (int value : data) {',
      '      if (value > average) {',
      '        above = above + 1;',
      '      }',
      '    }',
      '    System.out.println(above);',
      '',
      '    boolean sorted = true;',
      '    int equalPairs = 0;',
      '    for (int i = 1; i < data.length; i++) {',
      '      if (data[i] < data[i - 1]) {',
      '        sorted = false;',
      '      }',
      '      if (data[i] == data[i - 1]) {',
      '        equalPairs = equalPairs + 1;',
      '      }',
      '    }',
      '    System.out.println(sorted);',
      '    System.out.println(equalPairs);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Cast the sum to double before dividing, or the average of 7 and 2 comes out as 4.0 instead of 4.5.',
      'A neighbour comparison starts at i = 1 and looks back at i - 1, so it never reads past either end.',
      'A one element array is sorted and has zero equal pairs. The loop simply does not run, which is the right answer.',
    ],
    seo: 'AP CSA 4.5 coding exercise: sum, average, count above average, check sorted order and find equal neighbours in an array.',
    cases: [
      { stdin: '5\n4 7 2 9 1\n', hidden: 0 },
      { stdin: '4\n1 2 2 5\n', hidden: 0 },
      { stdin: '1\n8\n', hidden: 1 },
      { stdin: '6\n3 3 3 3 3 3\n', hidden: 1 },
      { stdin: '5\n9 7 5 3 1\n', hidden: 1 },
    ],
  },

  // ── 4.6 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.6', unit: U,
    handle: 'ap-csa-lesson-4-6-arrays-as-parameters-and-return-values',
    title: 'Arrays as Parameters and Return Values',
    name: 'Hand It Over, Get One Back',
    mode: 'driver',
    brief: 'An array parameter is a reference, so a method that changes it changes the caller array too. One of these methods does exactly that and another deliberately does not, and the harness checks the original array afterwards to tell them apart.',
    api: [
      'class ArrayTools',
      'int sum(int[] data)',
      'int[] doubled(int[] data)',
      'void doubleInPlace(int[] data)',
      'int[] withoutNegatives(int[] data)',
    ],
    task: [
      'Write a class named ArrayTools with the four methods above.',
      'sum returns the total of the elements, and returns 0 for an empty array.',
      'doubled returns a NEW array where every element is twice the original, leaving the array it was given untouched.',
      'doubleInPlace doubles the elements of the array it was handed and returns nothing.',
      'withoutNegatives returns a new array holding only the elements that are 0 or greater, in their original order.',
    ],
    reads: 'The grader supplies the input. Your class does not read anything.',
    prints: 'Your class prints nothing. The grader prints what your methods return.',
    starter: [
      'class ArrayTools {',
      '  public int sum(int[] data) {',
      '    return 0;',
      '  }',
      '',
      '  public int[] doubled(int[] data) {',
      '    // A NEW array. Do not change data.',
      '    return null;',
      '  }',
      '',
      '  public void doubleInPlace(int[] data) {',
      '    // Change the array you were given.',
      '  }',
      '',
      '  public int[] withoutNegatives(int[] data) {',
      '    // Count first, then build an array of exactly the right length.',
      '    return null;',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'class ArrayTools {',
      '  public int sum(int[] data) {',
      '    int total = 0;',
      '    for (int value : data) {',
      '      total = total + value;',
      '    }',
      '    return total;',
      '  }',
      '',
      '  public int[] doubled(int[] data) {',
      '    int[] out = new int[data.length];',
      '    for (int i = 0; i < data.length; i++) {',
      '      out[i] = data[i] * 2;',
      '    }',
      '    return out;',
      '  }',
      '',
      '  public void doubleInPlace(int[] data) {',
      '    for (int i = 0; i < data.length; i++) {',
      '      data[i] = data[i] * 2;',
      '    }',
      '  }',
      '',
      '  public int[] withoutNegatives(int[] data) {',
      '    int keep = 0;',
      '    for (int value : data) {',
      '      if (value >= 0) {',
      '        keep = keep + 1;',
      '      }',
      '    }',
      '    int[] out = new int[keep];',
      '    int at = 0;',
      '    for (int value : data) {',
      '      if (value >= 0) {',
      '        out[at] = value;',
      '        at = at + 1;',
      '      }',
      '    }',
      '    return out;',
      '  }',
      '}',
    ].join('\n'),
    harness: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner in = new Scanner(System.in);',
      '    int n = in.nextInt();',
      '    int[] data = new int[n];',
      '    for (int i = 0; i < n; i++) {',
      '      data[i] = in.nextInt();',
      '    }',
      '    ArrayTools t = new ArrayTools();',
      '    System.out.println(t.sum(data));',
      '    int[] twice = t.doubled(data);',
      '    System.out.println(show(twice));',
      '    System.out.println(show(data));',
      '    System.out.println(show(t.withoutNegatives(data)));',
      '    t.doubleInPlace(data);',
      '    System.out.println(show(data));',
      '    System.out.println(t.sum(data));',
      '  }',
      '',
      '  private static String show(int[] a) {',
      '    String out = "";',
      '    for (int i = 0; i < a.length; i++) {',
      '      if (i > 0) {',
      '        out = out + ",";',
      '      }',
      '      out = out + a[i];',
      '    }',
      '    return "[" + out + "]";',
      '  }',
      '}',
    ].join('\n'),
    runHarness: [
      'public class Main {',
      '  public static void main(String[] args) {',
      '    ArrayTools t = new ArrayTools();',
      '    int[] a = {3, -1, 4};',
      '    System.out.println(t.sum(a));',
      '    System.out.println(t.doubled(a).length);',
      '    System.out.println(t.withoutNegatives(a).length);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'doubled has to build new int[data.length] and fill it. Writing into data instead passes the second printed line and fails the third.',
      'doubleInPlace returns void and still changes the caller array, because the parameter is a reference to the same array.',
      'withoutNegatives cannot resize an array once it exists, so count the keepers on a first pass and allocate exactly that many.',
    ],
    seo: 'AP CSA 4.6 coding exercise: write methods that take an array, return a new array and modify an array in place.',
    cases: [
      { stdin: '5\n3 -1 4 -1 5\n', hidden: 0 },
      { stdin: '3\n1 2 3\n', hidden: 0 },
      { stdin: '4\n-5 -4 -3 -2\n', hidden: 1 },
      { stdin: '1\n0\n', hidden: 1 },
      { stdin: '6\n10 -10 0 7 -7 1\n', hidden: 1 },
    ],
  },

  // ── 4.7 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.7', unit: U,
    handle: 'ap-csa-lesson-4-7-arraylist-introduction',
    title: 'ArrayList Introduction',
    name: 'A List That Grows',
    mode: 'program',
    brief: 'An array has to know its size before it holds anything. An ArrayList does not, and this exercise is built so that not knowing is the only way through it.',
    task: [
      'Read words one at a time until the word STOP appears. STOP itself is not part of the data.',
      'Store each word in an ArrayList of String.',
      'Print how many words you collected.',
      'Print the first word, then the last word, each on its own line.',
      'Print every word, one per line, in the order they arrived.',
      'The count is not given to you anywhere, which is the point of the exercise.',
    ],
    reads: 'Words, one per line, ending with the word STOP. At least one word comes before STOP.',
    prints: 'The size, the first word, the last word, then every word in order.',
    starter: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    ArrayList<String> words = new ArrayList<String>();',
      '',
      '    // Read until STOP. add, size, get.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    ArrayList<String> words = new ArrayList<String>();',
      '',
      '    String word = input.next();',
      '    while (!word.equals("STOP")) {',
      '      words.add(word);',
      '      word = input.next();',
      '    }',
      '',
      '    System.out.println(words.size());',
      '    System.out.println(words.get(0));',
      '    System.out.println(words.get(words.size() - 1));',
      '    for (String w : words) {',
      '      System.out.println(w);',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'size() is a method on an ArrayList, while length is a field on an array. The parentheses are the difference.',
      'Read one word before the loop and read the next one at the bottom of the loop, so STOP is tested before it is ever added.',
      'get(words.size() - 1) is the last element, for the same reason length - 1 is the last index of an array.',
    ],
    seo: 'AP CSA 4.7 coding exercise: collect an unknown number of words in an ArrayList and read its size and elements.',
    cases: [
      { stdin: 'red\ngreen\nblue\nSTOP\n', hidden: 0 },
      { stdin: 'solo\nSTOP\n', hidden: 0 },
      { stdin: 'a\nb\nc\nd\ne\nf\ng\nSTOP\n', hidden: 1 },
      { stdin: 'STOPPED\nnearly\nSTOP\n', hidden: 1 },
      { stdin: 'one\none\none\nSTOP\n', hidden: 1 },
    ],
  },

  // ── 4.8 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.8', unit: U,
    handle: 'ap-csa-lesson-4-8-arraylist-methods',
    title: 'ArrayList Methods',
    name: 'Add, Set, Remove',
    mode: 'program',
    brief: 'add with an index shifts everything right and remove shifts everything left, while set changes one slot and moves nothing. Three methods that look similar and do genuinely different things to the positions around them.',
    task: [
      'Read an integer count, then that many integers, and put them in an ArrayList of Integer.',
      'Print the list.',
      'Add the value 99 at index 1, then print the list.',
      'Set index 0 to the value 0, then print the list.',
      'Remove the element at index 2 and print what remove returned, then print the list.',
      'Print the size on the last line. Print a list as its default Java form, for example [1, 2, 3].',
    ],
    reads: 'An integer count of at least 3, then that many integers.',
    prints: 'The list four times as the operations are applied, the removed value, and finally the size.',
    starter: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '',
      '    // System.out.println(list) prints it in the [1, 2, 3] form for you.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    System.out.println(list);',
      '    list.add(1, 99);',
      '    System.out.println(list);',
      '    list.set(0, 0);',
      '    System.out.println(list);',
      '    System.out.println(list.remove(2));',
      '    System.out.println(list);',
      '    System.out.println(list.size());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'add(1, 99) inserts and pushes everything from index 1 onward one place to the right. The list gets longer.',
      'set(0, 0) replaces what is already there. The list stays the same length.',
      'remove(int index) hands back the element it took out, so you can print the return value directly.',
    ],
    seo: 'AP CSA 4.8 coding exercise: use ArrayList add with an index, set, remove and size and watch the positions shift.',
    cases: [
      { stdin: '4\n10 20 30 40\n', hidden: 0 },
      { stdin: '3\n1 2 3\n', hidden: 0 },
      { stdin: '5\n-1 -2 -3 -4 -5\n', hidden: 1 },
      { stdin: '6\n7 7 7 7 7 7\n', hidden: 1 },
      { stdin: '3\n99 99 99\n', hidden: 1 },
    ],
  },

  // ── 4.9 ────────────────────────────────────────────────────────────────────
  {
    lesson: '4.9', unit: U,
    handle: 'ap-csa-lesson-4-9-traversing-arraylists',
    title: 'Traversing ArrayLists',
    name: 'Removing While You Walk',
    mode: 'program',
    brief: 'Removing an element during a forward traversal makes the loop skip the next one, which is the classic ArrayList bug and is on the exam. Doing it backwards avoids the problem entirely, and this exercise asks for both so the difference is visible in the output.',
    task: [
      'Read an integer count, then that many integers into an ArrayList of Integer.',
      'Print the sum using an enhanced for loop.',
      'Make a copy of the list. Walk the copy FORWARDS with an index and remove every even value, without adjusting the index after a removal. Print the result, bug and all.',
      'Make another copy. Walk it BACKWARDS and remove every even value. Print that result.',
      'Print true when the two results are equal and false when the forward version missed something.',
    ],
    reads: 'An integer count of at least 1, then that many integers.',
    prints: 'The sum, the forward result, the backward result and whether they matched.',
    starter: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    // new ArrayList<Integer>(list) makes a copy you can damage safely.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    int sum = 0;',
      '    for (int value : list) {',
      '      sum = sum + value;',
      '    }',
      '    System.out.println(sum);',
      '',
      '    ArrayList<Integer> forward = new ArrayList<Integer>(list);',
      '    for (int i = 0; i < forward.size(); i++) {',
      '      if (forward.get(i) % 2 == 0) {',
      '        forward.remove(i);',
      '      }',
      '    }',
      '    System.out.println(forward);',
      '',
      '    ArrayList<Integer> backward = new ArrayList<Integer>(list);',
      '    for (int i = backward.size() - 1; i >= 0; i--) {',
      '      if (backward.get(i) % 2 == 0) {',
      '        backward.remove(i);',
      '      }',
      '    }',
      '    System.out.println(backward);',
      '',
      '    System.out.println(forward.equals(backward));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'After remove(i) everything shifts left, so the element that moved into position i never gets tested. Two evens in a row is where it shows.',
      'The backward loop is immune because everything that shifts has already been visited.',
      'Comparing two ArrayLists with equals compares their contents in order, which is what the last line wants.',
    ],
    seo: 'AP CSA 4.9 coding exercise: see why removing from an ArrayList while traversing forwards skips elements, and fix it.',
    cases: [
      { stdin: '6\n1 2 4 3 6 5\n', hidden: 0 },
      { stdin: '4\n1 3 5 7\n', hidden: 0 },
      { stdin: '5\n2 2 2 2 2\n', hidden: 1 },
      { stdin: '1\n8\n', hidden: 1 },
      { stdin: '7\n1 2 3 4 6 8 9\n', hidden: 1 },
    ],
  },

  // ── 4.10 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.10', unit: U,
    handle: 'ap-csa-lesson-4-10-algorithms-with-arraylists',
    title: 'Algorithms with ArrayLists',
    name: 'Shift, Swap, Split',
    mode: 'program',
    brief: 'These three come up on the free response question in some disguise nearly every year. All three are about positions rather than values, which is why an enhanced for loop is no help for any of them.',
    task: [
      'Read an integer count, then that many integers into an ArrayList of Integer.',
      'Print the list with the first element moved to the end and everything else shifted left by one.',
      'Print the original list with its first and last elements swapped.',
      'Print a list of only the values at even indexes of the original.',
      'Print a list of only the values at odd indexes of the original.',
      'The original list must be printed unchanged on the last line, so work on copies.',
    ],
    reads: 'An integer count of at least 2, then that many integers.',
    prints: 'The rotated list, the swapped list, the even index list, the odd index list, and the untouched original.',
    starter: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    // Five printed lines. The original is the last one and must be unchanged.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    ArrayList<Integer> list = new ArrayList<Integer>();',
      '    for (int i = 0; i < count; i++) {',
      '      list.add(input.nextInt());',
      '    }',
      '',
      '    ArrayList<Integer> rotated = new ArrayList<Integer>(list);',
      '    rotated.add(rotated.remove(0));',
      '    System.out.println(rotated);',
      '',
      '    ArrayList<Integer> swapped = new ArrayList<Integer>(list);',
      '    int last = swapped.size() - 1;',
      '    int keep = swapped.get(0);',
      '    swapped.set(0, swapped.get(last));',
      '    swapped.set(last, keep);',
      '    System.out.println(swapped);',
      '',
      '    ArrayList<Integer> evens = new ArrayList<Integer>();',
      '    ArrayList<Integer> odds = new ArrayList<Integer>();',
      '    for (int i = 0; i < list.size(); i++) {',
      '      if (i % 2 == 0) {',
      '        evens.add(list.get(i));',
      '      } else {',
      '        odds.add(list.get(i));',
      '      }',
      '    }',
      '    System.out.println(evens);',
      '    System.out.println(odds);',
      '',
      '    System.out.println(list);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'remove(0) returns the element it took out, so add(remove(0)) rotates the list in a single line.',
      'A swap needs a third variable to hold the first value, or the assignment overwrites it before you have used it.',
      'new ArrayList<Integer>(list) copies. Assigning one list variable to another just makes a second name for the same list, and the last line will show it.',
    ],
    seo: 'AP CSA 4.10 coding exercise: rotate, swap and split an ArrayList by index while leaving the original untouched.',
    cases: [
      { stdin: '5\n1 2 3 4 5\n', hidden: 0 },
      { stdin: '2\n8 9\n', hidden: 0 },
      { stdin: '6\n-1 -2 -3 -4 -5 -6\n', hidden: 1 },
      { stdin: '4\n7 7 7 7\n', hidden: 1 },
      { stdin: '3\n100 0 100\n', hidden: 1 },
    ],
  },

  // ── 4.11 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.11', unit: U,
    handle: 'ap-csa-lesson-4-11-2d-array-creation-and-access',
    title: '2D Array Creation and Access',
    name: 'Rows First, Then Columns',
    mode: 'program',
    brief: 'grid[r][c] is row then column, in that order, always. Swapping them compiles perfectly and gives the wrong answer on every rectangle that is not a square, which is why this exercise never uses one.',
    task: [
      'Read two integers, rows and cols, then rows times cols integers filling the grid row by row.',
      'Print the number of rows, then the number of columns, each on its own line.',
      'Print the value in the top left corner, then the bottom right corner.',
      'Print the sum of the first row.',
      'Print the sum of the first column.',
    ],
    reads: 'Two integers, rows and cols, then rows times cols integers in row order.',
    prints: 'Six lines: the row count, the column count, two corners and two sums.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '',
      '    // Fill it, then answer the six questions.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        grid[r][c] = input.nextInt();',
      '      }',
      '    }',
      '',
      '    System.out.println(grid.length);',
      '    System.out.println(grid[0].length);',
      '    System.out.println(grid[0][0]);',
      '    System.out.println(grid[rows - 1][cols - 1]);',
      '',
      '    int rowSum = 0;',
      '    for (int c = 0; c < cols; c++) {',
      '      rowSum = rowSum + grid[0][c];',
      '    }',
      '    System.out.println(rowSum);',
      '',
      '    int colSum = 0;',
      '    for (int r = 0; r < rows; r++) {',
      '      colSum = colSum + grid[r][0];',
      '    }',
      '    System.out.println(colSum);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'grid.length is the number of ROWS. grid[0].length is the number of columns in row 0.',
      'Summing the first row holds the row index at 0 and moves the column. Summing the first column does the opposite.',
      'The bottom right corner is grid[rows - 1][cols - 1]. Both indexes stop one short.',
    ],
    seo: 'AP CSA 4.11 coding exercise: build a 2D array from input and access rows, columns and corners in the right order.',
    cases: [
      { stdin: '2 3\n1 2 3\n4 5 6\n', hidden: 0 },
      { stdin: '1 1\n9\n', hidden: 0 },
      { stdin: '3 2\n10 20\n30 40\n50 60\n', hidden: 1 },
      { stdin: '4 1\n1\n2\n3\n4\n', hidden: 1 },
      { stdin: '2 5\n-1 -2 -3 -4 -5\n5 4 3 2 1\n', hidden: 1 },
    ],
  },

  // ── 4.12 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.12', unit: U,
    handle: 'ap-csa-lesson-4-12-traversing-2d-arrays',
    title: 'Traversing 2D Arrays',
    name: 'Across, Down, Diagonal',
    mode: 'program',
    brief: 'Row major order is the default and column major order is the one that catches people out, because it needs the loops in the opposite nesting from the one that feels natural.',
    task: [
      'Read rows and cols, then the grid values in row order.',
      'Print all values in ROW major order, one per line: every value of row 0, then every value of row 1, and so on.',
      'Print all values in COLUMN major order, one per line: every value of column 0 top to bottom, then column 1, and so on.',
      'Print the sum of every value.',
      'Print the largest value anywhere in the grid.',
    ],
    reads: 'Two integers, rows and cols, then rows times cols integers in row order.',
    prints: 'Every value row major, then every value column major, then the total and the maximum.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        grid[r][c] = input.nextInt();',
      '      }',
      '    }',
      '',
      '    // Two full traversals, then two summary answers.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '    int[][] grid = new int[rows][cols];',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        grid[r][c] = input.nextInt();',
      '      }',
      '    }',
      '',
      '    for (int r = 0; r < rows; r++) {',
      '      for (int c = 0; c < cols; c++) {',
      '        System.out.println(grid[r][c]);',
      '      }',
      '    }',
      '',
      '    for (int c = 0; c < cols; c++) {',
      '      for (int r = 0; r < rows; r++) {',
      '        System.out.println(grid[r][c]);',
      '      }',
      '    }',
      '',
      '    int total = 0;',
      '    int max = grid[0][0];',
      '    for (int[] row : grid) {',
      '      for (int value : row) {',
      '        total = total + value;',
      '        if (value > max) {',
      '          max = value;',
      '        }',
      '      }',
      '    }',
      '    System.out.println(total);',
      '    System.out.println(max);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Column major order puts the COLUMN loop on the outside. The subscript is still grid[r][c], only the nesting changes.',
      'The enhanced for over a 2D array gives you a whole row at a time, so it takes two of them: for (int[] row : grid) then for (int value : row).',
      'Seed the maximum with grid[0][0] rather than 0, or a grid of negatives reports 0.',
    ],
    seo: 'AP CSA 4.12 coding exercise: traverse a 2D array in row major and column major order and summarise every value.',
    cases: [
      { stdin: '2 3\n1 2 3\n4 5 6\n', hidden: 0 },
      { stdin: '1 4\n7 8 9 10\n', hidden: 0 },
      { stdin: '3 3\n-1 -2 -3\n-4 -5 -6\n-7 -8 -9\n', hidden: 1 },
      { stdin: '4 2\n1 1\n2 2\n3 3\n4 4\n', hidden: 1 },
      { stdin: '2 2\n5 5\n5 5\n', hidden: 1 },
    ],
  },

  // ── 4.13 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.13', unit: U,
    handle: 'ap-csa-lesson-4-13-searching-and-sorting',
    title: 'Searching and Sorting',
    name: 'Find It, Then Order It',
    mode: 'program',
    brief: 'Linear search works on anything and binary search needs the data sorted first. Doing both on the same array, in that order, is the fastest way to see why the sort is the price of the faster search.',
    task: [
      'Read an integer count, then that many integers into an array, then one more integer to search for.',
      'Print the index found by a LINEAR search of the unsorted array, or -1 when it is not there.',
      'Sort the array into increasing order using selection sort or insertion sort, written out by hand.',
      'Print the sorted array as its values separated by single spaces on one line.',
      'Print the index found by a BINARY search of the sorted array, or -1 when it is not there.',
      'Print the number of comparisons your binary search made.',
    ],
    reads: 'An integer count of at least 1, then that many integers, then the target value.',
    prints: 'Five lines: the linear index, the sorted values, the binary index and the comparison count.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    // Search, sort, search again. Write the sort out; do not call a library.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    int linear = -1;',
      '    for (int i = 0; i < data.length; i++) {',
      '      if (data[i] == target && linear == -1) {',
      '        linear = i;',
      '      }',
      '    }',
      '    System.out.println(linear);',
      '',
      '    for (int i = 0; i < data.length - 1; i++) {',
      '      int small = i;',
      '      for (int j = i + 1; j < data.length; j++) {',
      '        if (data[j] < data[small]) {',
      '          small = j;',
      '        }',
      '      }',
      '      int keep = data[i];',
      '      data[i] = data[small];',
      '      data[small] = keep;',
      '    }',
      '',
      '    String out = "";',
      '    for (int i = 0; i < data.length; i++) {',
      '      if (i > 0) {',
      '        out = out + " ";',
      '      }',
      '      out = out + data[i];',
      '    }',
      '    System.out.println(out);',
      '',
      '    int low = 0;',
      '    int high = data.length - 1;',
      '    int found = -1;',
      '    int comparisons = 0;',
      '    while (low <= high && found == -1) {',
      '      int mid = (low + high) / 2;',
      '      comparisons = comparisons + 1;',
      '      if (data[mid] == target) {',
      '        found = mid;',
      '      } else if (data[mid] < target) {',
      '        low = mid + 1;',
      '      } else {',
      '        high = mid - 1;',
      '      }',
      '    }',
      '    System.out.println(found);',
      '    System.out.println(comparisons);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The linear search reports the FIRST match. Once you have found one, stop replacing it.',
      'Selection sort finds the smallest remaining value and swaps it into place, one position per pass of the outer loop.',
      'Count one comparison per pass of the binary search loop, meaning each time you look at a middle element.',
    ],
    seo: 'AP CSA 4.13 coding exercise: write a linear search, a hand written selection sort and a binary search on one array.',
    cases: [
      { stdin: '7\n9 3 7 1 8 2 5\n7\n', hidden: 0 },
      { stdin: '5\n5 4 3 2 1\n1\n', hidden: 0 },
      { stdin: '6\n2 4 6 8 10 12\n7\n', hidden: 1 },
      { stdin: '1\n42\n42\n', hidden: 1 },
      { stdin: '8\n8 7 6 5 4 3 2 1\n8\n', hidden: 1 },
    ],
  },

  // ── 4.14 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.14', unit: U,
    handle: 'ap-csa-lesson-4-14-reading-data-from-files',
    title: 'Reading Data from Files',
    name: 'Read Until It Runs Out',
    mode: 'program',
    brief: 'Reading a file means not knowing how much is coming, so the loop is driven by hasNext rather than by a count. The grader pipes the file in on standard input, so your Scanner code is the same code you would write over a File.',
    task: [
      'Read integers with a Scanner until there are no more, using hasNextInt to control the loop.',
      'You are NOT told how many there are. Do not read a count.',
      'Print how many values you read.',
      'Print the total.',
      'Print the largest and then the smallest, each on its own line.',
      'When the input is empty, print 0 for the count and 0 for the total and nothing else.',
    ],
    reads: 'Any number of integers, including none, separated by whitespace.',
    prints: 'The count and the total always, then the largest and smallest when there was at least one value.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '',
      '    // while (input.hasNextInt()) { ... }',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '',
      '    int count = 0;',
      '    int total = 0;',
      '    int largest = 0;',
      '    int smallest = 0;',
      '    while (input.hasNextInt()) {',
      '      int value = input.nextInt();',
      '      if (count == 0 || value > largest) {',
      '        largest = value;',
      '      }',
      '      if (count == 0 || value < smallest) {',
      '        smallest = value;',
      '      }',
      '      count = count + 1;',
      '      total = total + value;',
      '    }',
      '',
      '    System.out.println(count);',
      '    System.out.println(total);',
      '    if (count > 0) {',
      '      System.out.println(largest);',
      '      System.out.println(smallest);',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'hasNextInt() asks whether another integer is waiting without consuming it. nextInt() is what consumes it.',
      'Calling nextInt() when nothing is left throws NoSuchElementException, which is exactly what the hasNextInt guard prevents.',
      'The empty input case prints two lines and stops. Guard the largest and smallest so they are not printed for data that never arrived.',
    ],
    seo: 'AP CSA 4.14 coding exercise: drive a Scanner with hasNextInt to read an unknown amount of data and summarise it.',
    cases: [
      { stdin: '4 8 15 16 23 42\n', hidden: 0 },
      { stdin: '7\n', hidden: 0 },
      { stdin: '', hidden: 1 },
      { stdin: '-5 -10 -1\n', hidden: 1 },
      { stdin: '3 3 3 3 3 3 3 3 3 3\n', hidden: 1 },
    ],
  },

  // ── 4.15 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.15', unit: U,
    handle: 'ap-csa-lesson-4-15-using-data-sets-with-arrays-and-arraylists',
    title: 'Using Data Sets with Arrays and ArrayLists',
    name: 'The Right Container for the Job',
    mode: 'program',
    brief: 'The array is right when the size is known and fixed. The ArrayList is right when it is not. This exercise needs both in the same program, so the choice has to be made twice for two different reasons.',
    task: [
      'Read an integer count, then that many scores into an int ARRAY, because the size is known.',
      'Read a threshold value.',
      'Collect every score at or above the threshold into an ArrayList of Integer, because that size is not known until you look.',
      'Print the ArrayList.',
      'Print how many made the cut, then how many did not.',
      'Print the average of the ones that made the cut as a double, or the word NONE when nothing did.',
    ],
    reads: 'An integer count of at least 1, then that many integers, then a threshold.',
    prints: 'The list of qualifying scores, the two counts, and the qualifying average or NONE.',
    starter: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] scores = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      scores[i] = input.nextInt();',
      '    }',
      '    int threshold = input.nextInt();',
      '',
      '    // Fixed size in, unknown size out.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      'import java.util.ArrayList;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] scores = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      scores[i] = input.nextInt();',
      '    }',
      '    int threshold = input.nextInt();',
      '',
      '    ArrayList<Integer> kept = new ArrayList<Integer>();',
      '    int total = 0;',
      '    for (int score : scores) {',
      '      if (score >= threshold) {',
      '        kept.add(score);',
      '        total = total + score;',
      '      }',
      '    }',
      '',
      '    System.out.println(kept);',
      '    System.out.println(kept.size());',
      '    System.out.println(scores.length - kept.size());',
      '    if (kept.size() == 0) {',
      '      System.out.println("NONE");',
      '    } else {',
      '      System.out.println((double) total / kept.size());',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'You cannot know how many scores clear the threshold before you have looked at them, which is precisely when an ArrayList is the right answer.',
      'The number that missed the cut is the array length minus the list size. There is no need to count it separately.',
      'Dividing by kept.size() when nothing qualified is a divide by zero, which is why the NONE case is asked for.',
    ],
    seo: 'AP CSA 4.15 coding exercise: read a fixed data set into an array and filter it into an ArrayList of unknown size.',
    cases: [
      { stdin: '6\n55 90 72 88 61 40\n70\n', hidden: 0 },
      { stdin: '3\n10 20 30\n5\n', hidden: 0 },
      { stdin: '4\n1 2 3 4\n100\n', hidden: 1 },
      { stdin: '1\n50\n50\n', hidden: 1 },
      { stdin: '5\n-10 0 10 20 30\n0\n', hidden: 1 },
    ],
  },

  // ── 4.16 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.16', unit: U,
    handle: 'ap-csa-lesson-4-16-recursion',
    title: 'Recursion',
    name: 'The Base Case First',
    mode: 'program',
    brief: 'Every recursive method needs a base case and a call that gets closer to it. Write the base case first and the rest usually falls out; write it last and the program runs forever.',
    task: [
      'Read one integer n, which is 0 or more, and then a word.',
      'Write a recursive method that returns the factorial of n, and print it. The factorial of 0 is 1.',
      'Write a recursive method that returns the sum of the digits of n, and print it.',
      'Write a recursive method that returns the word reversed, and print it.',
      'Write a recursive method that returns how many times the method was called to compute the factorial, counting the base case, and print it.',
      'Every one of these must be recursive. Do not use a loop.',
    ],
    reads: 'An integer of 0 or more, then a word.',
    prints: 'Four lines: the factorial, the digit sum, the reversed word and the call count.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static int factorial(int n) {',
      '    return 0;',
      '  }',
      '',
      '  public static int digitSum(int n) {',
      '    return 0;',
      '  }',
      '',
      '  public static String reverse(String s) {',
      '    return "";',
      '  }',
      '',
      '  public static int calls(int n) {',
      '    return 0;',
      '  }',
      '',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    String word = input.next();',
      '',
      '    // Four printed lines.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static int factorial(int n) {',
      '    if (n <= 1) {',
      '      return 1;',
      '    }',
      '    return n * factorial(n - 1);',
      '  }',
      '',
      '  public static int digitSum(int n) {',
      '    if (n < 10) {',
      '      return n;',
      '    }',
      '    return n % 10 + digitSum(n / 10);',
      '  }',
      '',
      '  public static String reverse(String s) {',
      '    if (s.length() <= 1) {',
      '      return s;',
      '    }',
      '    return reverse(s.substring(1)) + s.substring(0, 1);',
      '  }',
      '',
      '  public static int calls(int n) {',
      '    if (n <= 1) {',
      '      return 1;',
      '    }',
      '    return 1 + calls(n - 1);',
      '  }',
      '',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    String word = input.next();',
      '',
      '    System.out.println(factorial(n));',
      '    System.out.println(digitSum(n));',
      '    System.out.println(reverse(word));',
      '    System.out.println(calls(n));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'factorial stops at 1 or below and returns 1, which covers both 0 and 1 with one test.',
      'Reversing a String recursively is the reverse of everything after the first character, with the first character stuck on the end.',
      'The call count for factorial(5) is 5, because the base case call counts too. Trace factorial(1) and factorial(0) by hand if the number is off by one.',
    ],
    seo: 'AP CSA 4.16 coding exercise: write four recursive methods with correct base cases, including a recursive String reverse.',
    cases: [
      { stdin: '5 stack\n', hidden: 0 },
      { stdin: '0 a\n', hidden: 0 },
      { stdin: '1 recursion\n', hidden: 1 },
      { stdin: '9 zzz\n', hidden: 1 },
      { stdin: '12 palindrome\n', hidden: 1 },
    ],
  },

  // ── 4.17 ───────────────────────────────────────────────────────────────────
  {
    lesson: '4.17', unit: U,
    handle: 'ap-csa-lesson-4-17-informal-code-analysis',
    title: 'Informal Code Analysis',
    name: 'How Many Times Did It Run',
    mode: 'program',
    brief: 'Analysing a collection algorithm means counting the operations that touch the data, not the lines of source. Every count here comes out of a real loop, so nothing has to be taken on trust.',
    task: [
      'Read an integer count, then that many integers into an array, then a target value.',
      'Print how many array accesses a linear search for the target makes before it stops. Stop at the first match.',
      'Print how many accesses a full traversal of the whole array makes.',
      'Print how many comparisons a selection sort of the array makes, counting one per inner loop pass.',
      'Print how many accesses a nested traversal of every ordered pair of positions makes, which is the array length squared.',
    ],
    reads: 'An integer count of at least 1, then that many integers, then a target.',
    prints: 'Four counts, one per line.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    // Count as the loops actually run. Do not use a formula.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '    int[] data = new int[count];',
      '    for (int i = 0; i < count; i++) {',
      '      data[i] = input.nextInt();',
      '    }',
      '    int target = input.nextInt();',
      '',
      '    int searchAccesses = 0;',
      '    boolean found = false;',
      '    for (int i = 0; i < data.length && !found; i++) {',
      '      searchAccesses = searchAccesses + 1;',
      '      if (data[i] == target) {',
      '        found = true;',
      '      }',
      '    }',
      '    System.out.println(searchAccesses);',
      '',
      '    int fullAccesses = 0;',
      '    for (int i = 0; i < data.length; i++) {',
      '      fullAccesses = fullAccesses + 1;',
      '    }',
      '    System.out.println(fullAccesses);',
      '',
      '    int[] copy = new int[data.length];',
      '    for (int i = 0; i < data.length; i++) {',
      '      copy[i] = data[i];',
      '    }',
      '    int comparisons = 0;',
      '    for (int i = 0; i < copy.length - 1; i++) {',
      '      int small = i;',
      '      for (int j = i + 1; j < copy.length; j++) {',
      '        comparisons = comparisons + 1;',
      '        if (copy[j] < copy[small]) {',
      '          small = j;',
      '        }',
      '      }',
      '      int keep = copy[i];',
      '      copy[i] = copy[small];',
      '      copy[small] = keep;',
      '    }',
      '    System.out.println(comparisons);',
      '',
      '    int pairAccesses = 0;',
      '    for (int i = 0; i < data.length; i++) {',
      '      for (int j = 0; j < data.length; j++) {',
      '        pairAccesses = pairAccesses + 1;',
      '      }',
      '    }',
      '    System.out.println(pairAccesses);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A linear search that finds the target at index 0 makes one access. A target that is not there makes as many as the array is long.',
      'Selection sort always makes the same number of comparisons for a given length, whatever order the data is in. That is why it is quadratic in every case.',
      'Sort a COPY. Sorting the array itself would change what the last count is measuring.',
    ],
    seo: 'AP CSA 4.17 coding exercise: count the real accesses and comparisons made by a search, a traversal and a selection sort.',
    cases: [
      { stdin: '5\n9 3 7 1 8\n7\n', hidden: 0 },
      { stdin: '4\n1 2 3 4\n1\n', hidden: 0 },
      { stdin: '6\n5 5 5 5 5 5\n0\n', hidden: 1 },
      { stdin: '1\n42\n42\n', hidden: 1 },
      { stdin: '8\n8 7 6 5 4 3 2 1\n1\n', hidden: 1 },
    ],
  },
];

module.exports = { exercises };
