'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  AP CSA UNIT 2: SELECTION AND ITERATION - 12 code exercises, one per lesson.
//
//  ORDER MATTERS AND IS RESPECTED
//  2.1 comes BEFORE if statements are taught in 2.3, so its exercise makes a
//  choice without one (Math.max and Math.min are selection, they just do not
//  look like it) and replaces a loop with a closed form. From 2.3 the exercises
//  use selection freely, and from 2.7 they use loops. No exercise here needs
//  anything from Unit 3 or Unit 4.
//
//  WHY SO MANY OF THESE READ A COUNT FIRST
//  A loop over "n values, then the values" is the shape the AP exam uses for
//  array traversal in Unit 4, so meeting it here on plain Scanner reads means
//  the pattern is already familiar when the arrays arrive.
//
//  Every expected output is produced by running the reference through real
//  javac/java. See seed/csa-exercises/index.js for the shape and the rules.
// ─────────────────────────────────────────────────────────────────────────────

const U = 'unit-2';

const exercises = [
  // ── 2.1 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.1', unit: U,
    handle: 'ap-csa-lesson-2-1-algorithms-selection-repetition',
    title: 'Algorithms with Selection and Repetition',
    name: 'Choosing Without an if',
    mode: 'program',
    brief: 'Selection and repetition are ideas before they are keywords. This exercise makes a real choice and does a real repetition without using an if or a loop, so the ideas arrive before the syntax does.',
    task: [
      'Read three integers: a, b and c.',
      'Print the largest of the three using Math.max, which selects without an if statement.',
      'Print the smallest using Math.min.',
      'Print the middle value, which is the total minus the largest minus the smallest.',
      'Read one more integer n, then print the sum of every whole number from 1 to n using the closed form n * (n + 1) / 2, which does a repetition without a loop.',
    ],
    reads: 'Four integers on separate lines: a, b, c, then n.',
    prints: 'Four lines: the largest, the smallest, the middle value and the sum from 1 to n.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '    int c = input.nextInt();',
      '    int n = input.nextInt();',
      '',
      '    // Four lines, and not an if or a loop anywhere.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '    int c = input.nextInt();',
      '    int n = input.nextInt();',
      '',
      '    int big = Math.max(a, Math.max(b, c));',
      '    int small = Math.min(a, Math.min(b, c));',
      '    System.out.println(big);',
      '    System.out.println(small);',
      '    System.out.println(a + b + c - big - small);',
      '    System.out.println(n * (n + 1) / 2);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Math.max takes two arguments, so three values need two calls: Math.max(a, Math.max(b, c)).',
      'The middle value trick works even when two of the three are equal. Try it on 5, 5, 2 by hand and see.',
      'n * (n + 1) is always even, so the / 2 is exact and integer division loses nothing here.',
    ],
    seo: 'AP CSA 2.1 coding exercise: select a maximum and minimum without an if and sum 1 to n without a loop. Auto graded Java.',
    cases: [
      { stdin: '4\n9\n2\n5\n', hidden: 0 },
      { stdin: '7\n7\n7\n1\n', hidden: 0 },
      { stdin: '-3\n0\n-10\n10\n', hidden: 1 },
      { stdin: '100\n1\n50\n0\n', hidden: 1 },
      { stdin: '5\n5\n2\n99\n', hidden: 1 },
    ],
  },

  // ── 2.2 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.2', unit: U,
    handle: 'ap-csa-lesson-2-2-boolean-expressions',
    title: 'Boolean Expressions',
    name: 'True or False, Printed',
    mode: 'program',
    brief: 'A boolean expression is a value, not a question. Printing one directly is the fastest way to stop thinking of comparisons as something that only lives inside an if.',
    task: [
      'Read two integers, a and b.',
      'Print the value of a > b.',
      'Print the value of a == b.',
      'Print the value of a != b.',
      'Print the value of a <= b.',
      'Store a >= b in a boolean variable and print that variable on the last line.',
    ],
    reads: 'Two integers on separate lines: a, then b.',
    prints: 'Five lines, each true or false.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '',
      '    // Five lines of true or false. No if statement is needed or wanted.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '',
      '    System.out.println(a > b);',
      '    System.out.println(a == b);',
      '    System.out.println(a != b);',
      '    System.out.println(a <= b);',
      '    boolean atLeast = a >= b;',
      '    System.out.println(atLeast);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'System.out.println(a > b) prints the word true or the word false. You do not need an if to produce them.',
      '= assigns and == compares. boolean atLeast = a >= b; uses both in one line, and they mean different things.',
      'a != b is always the opposite of a == b, so those two lines can never match.',
    ],
    seo: 'AP CSA 2.2 coding exercise: evaluate and print relational boolean expressions in Java and store one in a boolean variable.',
    cases: [
      { stdin: '5\n3\n', hidden: 0 },
      { stdin: '4\n4\n', hidden: 0 },
      { stdin: '-8\n2\n', hidden: 1 },
      { stdin: '0\n0\n', hidden: 1 },
      { stdin: '17\n100\n', hidden: 1 },
    ],
  },

  // ── 2.3 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.3', unit: U,
    handle: 'ap-csa-lesson-2-3-if-statements',
    title: 'if Statements',
    name: 'Grade Bands',
    mode: 'program',
    brief: 'A chain of else if stops at the first branch that matches. Writing the same chain as four separate ifs changes what it does, and this exercise is graded on the difference.',
    task: [
      'Read one integer score between 0 and 100.',
      'Print the letter grade: A for 90 and above, B for 80 to 89, C for 70 to 79, D for 60 to 69, and F below 60.',
      'On the second line print PASS when the score is 60 or more and FAIL otherwise.',
      'On the third line print how far the score is from 100.',
    ],
    reads: 'A single integer from 0 to 100.',
    prints: 'Three lines: the letter grade, PASS or FAIL, and the distance from 100.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int score = input.nextInt();',
      '',
      '    // Use one if / else if chain for the letter, not five separate ifs.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int score = input.nextInt();',
      '',
      '    if (score >= 90) {',
      '      System.out.println("A");',
      '    } else if (score >= 80) {',
      '      System.out.println("B");',
      '    } else if (score >= 70) {',
      '      System.out.println("C");',
      '    } else if (score >= 60) {',
      '      System.out.println("D");',
      '    } else {',
      '      System.out.println("F");',
      '    }',
      '',
      '    if (score >= 60) {',
      '      System.out.println("PASS");',
      '    } else {',
      '      System.out.println("FAIL");',
      '    }',
      '',
      '    System.out.println(100 - score);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Order the chain from the highest band down. Starting at score >= 60 puts every A in the D branch.',
      'else if means the test is only reached when everything above it was false, so you do not need score >= 80 && score < 90.',
      'Exactly one letter should be printed. If you see two, you wrote separate ifs instead of one chain.',
    ],
    seo: 'AP CSA 2.3 coding exercise: write an if else if chain that turns a score into a letter grade and a pass or fail.',
    cases: [
      { stdin: '95\n', hidden: 0 },
      { stdin: '72\n', hidden: 0 },
      { stdin: '60\n', hidden: 1 },
      { stdin: '0\n', hidden: 1 },
      { stdin: '89\n', hidden: 1 },
      { stdin: '100\n', hidden: 1 },
    ],
  },

  // ── 2.4 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.4', unit: U,
    handle: 'ap-csa-lesson-2-4-nested-if-statements',
    title: 'Nested if Statements',
    name: 'Ticket Window',
    mode: 'program',
    brief: 'Nesting is for decisions that only make sense once an earlier one has been settled. The discount here does not exist for adults at all, so testing for it at the top level would be answering a question nobody asked.',
    task: [
      'Read an age as an integer, then a day number where 1 means a weekday and 2 means a weekend.',
      'Under 13 is a child ticket at 8. 13 to 64 is an adult ticket at 14. 65 and over is a senior ticket at 9.',
      'Inside the child case only, a weekend adds 2 to the price.',
      'Inside the senior case only, a weekday takes 3 off the price.',
      'Print the ticket type on the first line and the final price on the second.',
    ],
    reads: 'Two integers on separate lines: age, then 1 for a weekday or 2 for a weekend.',
    prints: 'Two lines: CHILD, ADULT or SENIOR, then the price.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int age = input.nextInt();',
      '    int day = input.nextInt();',
      '',
      '    // Decide the type first, then adjust the price inside that branch.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int age = input.nextInt();',
      '    int day = input.nextInt();',
      '',
      '    String type;',
      '    int price;',
      '    if (age < 13) {',
      '      type = "CHILD";',
      '      price = 8;',
      '      if (day == 2) {',
      '        price = price + 2;',
      '      }',
      '    } else if (age < 65) {',
      '      type = "ADULT";',
      '      price = 14;',
      '    } else {',
      '      type = "SENIOR";',
      '      price = 9;',
      '      if (day == 1) {',
      '        price = price - 3;',
      '      }',
      '    }',
      '',
      '    System.out.println(type);',
      '    System.out.println(price);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The day adjustment belongs INSIDE the child branch and INSIDE the senior branch, never beside them. An adult price never moves.',
      'Once you are in the else if, age < 13 is already known to be false, so age < 65 is the whole adult test.',
      'Declaring String type; and int price; before the chain lets every branch assign them and one print at the end read them.',
    ],
    seo: 'AP CSA 2.4 coding exercise: nest if statements so a discount applies only inside the branch it belongs to. Auto graded.',
    cases: [
      { stdin: '10\n2\n', hidden: 0 },
      { stdin: '30\n1\n', hidden: 0 },
      { stdin: '70\n1\n', hidden: 1 },
      { stdin: '65\n2\n', hidden: 1 },
      { stdin: '12\n1\n', hidden: 1 },
      { stdin: '13\n2\n', hidden: 1 },
    ],
  },

  // ── 2.5 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.5', unit: U,
    handle: 'ap-csa-lesson-2-5-compound-boolean-expressions',
    title: 'Compound Boolean Expressions',
    name: 'In Range, Out of Range',
    mode: 'program',
    brief: 'Every one of these is a single boolean expression printed directly, so there is nowhere for a stray if to hide the logic. If the expression is wrong the printed value says so immediately.',
    task: [
      'Read three integers: low, high and value.',
      'Print whether value is inside the range, meaning it is at least low AND at most high.',
      'Print whether value is outside the range, using OR rather than negating the first answer.',
      'Print whether value equals low OR equals high.',
      'Print the negation of the first expression using the ! operator, which should always match the second line.',
    ],
    reads: 'Three integers on separate lines: low, high, value.',
    prints: 'Four lines, each true or false.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int low = input.nextInt();',
      '    int high = input.nextInt();',
      '    int value = input.nextInt();',
      '',
      '    // Four printed booleans. No if statements.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int low = input.nextInt();',
      '    int high = input.nextInt();',
      '    int value = input.nextInt();',
      '',
      '    boolean inside = value >= low && value <= high;',
      '    System.out.println(inside);',
      '    System.out.println(value < low || value > high);',
      '    System.out.println(value == low || value == high);',
      '    System.out.println(!inside);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Java has no low <= value <= high. It has to be written as two comparisons joined with &&.',
      'The opposite of "at least low and at most high" is "below low or above high". The and becomes an or, which is De Morgan and is 2.6.',
      'Lines 2 and 4 must agree on every input. If they ever disagree, one of your two expressions is wrong.',
    ],
    seo: 'AP CSA 2.5 coding exercise: build compound boolean expressions with &&, || and ! for a numeric range check in Java.',
    cases: [
      { stdin: '1\n10\n5\n', hidden: 0 },
      { stdin: '1\n10\n10\n', hidden: 0 },
      { stdin: '20\n30\n19\n', hidden: 1 },
      { stdin: '-5\n5\n-5\n', hidden: 1 },
      { stdin: '7\n7\n7\n', hidden: 1 },
      { stdin: '0\n100\n250\n', hidden: 1 },
    ],
  },

  // ── 2.6 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.6', unit: U,
    handle: 'ap-csa-lesson-2-6-comparing-boolean-expressions',
    title: 'Comparing Boolean Expressions',
    name: 'De Morgan, Checked',
    mode: 'program',
    brief: 'Two expressions are equivalent when they agree on every input, not when they look similar. This exercise prints both sides of two De Morgan pairs and then prints whether they matched, so equivalence stops being something you take on faith.',
    task: [
      'Read two integers, a and b.',
      'Build p as a > 0 and q as b > 0.',
      'Print !(p && q), then print !p || !q, which De Morgan says is the same thing.',
      'Print whether those two agreed, as a single boolean.',
      'Print !(p || q), then !p && !q, then whether THOSE two agreed.',
    ],
    reads: 'Two integers on separate lines: a, then b.',
    prints: 'Six lines of true or false: the first pair, whether it agreed, the second pair, and whether it agreed.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '    boolean p = a > 0;',
      '    boolean q = b > 0;',
      '',
      '    // Six printed booleans, in the order the task lists them.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '    boolean p = a > 0;',
      '    boolean q = b > 0;',
      '',
      '    boolean left1 = !(p && q);',
      '    boolean right1 = !p || !q;',
      '    System.out.println(left1);',
      '    System.out.println(right1);',
      '    System.out.println(left1 == right1);',
      '',
      '    boolean left2 = !(p || q);',
      '    boolean right2 = !p && !q;',
      '    System.out.println(left2);',
      '    System.out.println(right2);',
      '    System.out.println(left2 == right2);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Negating a compound expression flips the operator too: not (p and q) becomes (not p) or (not q).',
      'Two booleans are compared with ==, exactly like two ints. left1 == right1 is a boolean expression in its own right.',
      'Lines 3 and 6 should be true for every input you can think of. If either is ever false, the expression above it is not the one De Morgan describes.',
    ],
    seo: 'AP CSA 2.6 coding exercise: verify both De Morgan laws in Java by printing each side and testing whether they agree.',
    cases: [
      { stdin: '5\n3\n', hidden: 0 },
      { stdin: '-1\n4\n', hidden: 0 },
      { stdin: '0\n0\n', hidden: 1 },
      { stdin: '7\n-7\n', hidden: 1 },
      { stdin: '-2\n-9\n', hidden: 1 },
    ],
  },

  // ── 2.7 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.7', unit: U,
    handle: 'ap-csa-lesson-2-7-while-loops',
    title: 'while Loops',
    name: 'Digit Peeler',
    mode: 'program',
    brief: 'A while loop is the right shape when you do not know how many times you are going round. Peeling the digits off a number is the classic case: the number itself decides when to stop.',
    task: [
      'Read one non-negative integer n.',
      'Using a while loop, print each digit of n on its own line, from the LAST digit to the first.',
      'After the loop, print how many digits you printed.',
      'Print the sum of those digits on the final line.',
      'Treat 0 as having one digit, which is 0.',
    ],
    reads: 'A single non-negative integer.',
    prints: 'One line per digit from last to first, then the digit count, then the digit sum.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '',
      '    // n % 10 is the last digit. n / 10 removes it.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '',
      '    int count = 0;',
      '    int sum = 0;',
      '    if (n == 0) {',
      '      System.out.println(0);',
      '      count = 1;',
      '    }',
      '    while (n > 0) {',
      '      int digit = n % 10;',
      '      System.out.println(digit);',
      '      sum = sum + digit;',
      '      count = count + 1;',
      '      n = n / 10;',
      '    }',
      '    System.out.println(count);',
      '    System.out.println(sum);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'n % 10 gives the last digit and n / 10 throws it away. Doing both every pass is the whole loop.',
      'If you never change n inside the loop, the condition never becomes false and the run times out.',
      'Zero needs its own line before the loop, because while (n > 0) never runs for it.',
    ],
    seo: 'AP CSA 2.7 coding exercise: use a while loop to peel the digits off an integer, then count and sum them. Auto graded.',
    cases: [
      { stdin: '4271\n', hidden: 0 },
      { stdin: '9\n', hidden: 0 },
      { stdin: '0\n', hidden: 1 },
      { stdin: '1000000\n', hidden: 1 },
      { stdin: '505\n', hidden: 1 },
    ],
  },

  // ── 2.8 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.8', unit: U,
    handle: 'ap-csa-lesson-2-8-for-loops',
    title: 'for Loops',
    name: 'Three Ways Round',
    mode: 'program',
    brief: 'A for loop puts the start, the stop and the step on one line, which makes off by one errors easier to see and easier to make. Three loops here, each with a different bound.',
    task: [
      'Read two integers, n and step.',
      'Using a for loop, print every number from 1 to n on its own line.',
      'Then print the sum of the squares of 1 through n on one line.',
      'Then, counting DOWN from n to 1 with a step of the given size, print each value you land on, one per line.',
      'Assume n is at least 1 and step is at least 1.',
    ],
    reads: 'Two integers on separate lines: n, then step.',
    prints: 'n lines counting up, then the sum of squares, then the values counted down by step.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    int step = input.nextInt();',
      '',
      '    // Three loops. Watch the bounds on each one.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '    int step = input.nextInt();',
      '',
      '    for (int i = 1; i <= n; i++) {',
      '      System.out.println(i);',
      '    }',
      '',
      '    int sum = 0;',
      '    for (int i = 1; i <= n; i++) {',
      '      sum = sum + i * i;',
      '    }',
      '    System.out.println(sum);',
      '',
      '    for (int i = n; i >= 1; i = i - step) {',
      '      System.out.println(i);',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'i <= n runs n times when i starts at 1. i < n runs n - 1 times, which is the off by one this exercise is looking for.',
      'The countdown starts at n, tests i >= 1, and subtracts step. It will usually not land exactly on 1, and that is correct.',
      'The counter declared inside the for header disappears at the closing brace, so all three loops can reuse the name i.',
    ],
    seo: 'AP CSA 2.8 coding exercise: write three for loops with different bounds and steps, including a countdown. Auto graded Java.',
    cases: [
      { stdin: '5\n2\n', hidden: 0 },
      { stdin: '1\n1\n', hidden: 0 },
      { stdin: '10\n3\n', hidden: 1 },
      { stdin: '7\n7\n', hidden: 1 },
      { stdin: '4\n1\n', hidden: 1 },
    ],
  },

  // ── 2.9 ────────────────────────────────────────────────────────────────────
  {
    lesson: '2.9', unit: U,
    handle: 'ap-csa-lesson-2-9-implementing-selection-iteration-algorithms',
    title: 'Implementing Selection and Iteration Algorithms',
    name: 'One Pass, Four Answers',
    mode: 'program',
    brief: 'Selection inside iteration is where the two halves of this unit meet. Every answer here comes out of a single pass over the values, which is the habit the free response question rewards.',
    task: [
      'Read an integer count, then that many integers.',
      'Print the largest value.',
      'Print the smallest value.',
      'Print how many of them were even.',
      'Print the sum of only the values greater than zero.',
      'Assume the count is at least 1.',
    ],
    reads: 'An integer count, then that many integers, each on its own line.',
    prints: 'Four lines: the maximum, the minimum, the count of even values and the sum of the positive ones.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '',
      '    // One loop. Track four things as you go.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int count = input.nextInt();',
      '',
      '    int max = 0;',
      '    int min = 0;',
      '    int evens = 0;',
      '    int positiveSum = 0;',
      '    for (int i = 0; i < count; i++) {',
      '      int value = input.nextInt();',
      '      if (i == 0 || value > max) {',
      '        max = value;',
      '      }',
      '      if (i == 0 || value < min) {',
      '        min = value;',
      '      }',
      '      if (value % 2 == 0) {',
      '        evens = evens + 1;',
      '      }',
      '      if (value > 0) {',
      '        positiveSum = positiveSum + value;',
      '      }',
      '    }',
      '    System.out.println(max);',
      '    System.out.println(min);',
      '    System.out.println(evens);',
      '    System.out.println(positiveSum);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Starting max at 0 is a bug when every value is negative. Either seed it with the first value or treat i == 0 as a special case.',
      'A negative even number is still even: -4 % 2 is 0, so the test works without any extra handling.',
      'Read inside the loop, not before it. The count tells you how many times to go round, and nothing else.',
    ],
    seo: 'AP CSA 2.9 coding exercise: find max, min, an even count and a positive sum in a single pass with selection inside a loop.',
    cases: [
      { stdin: '5\n3\n8\n1\n6\n2\n', hidden: 0 },
      { stdin: '1\n7\n', hidden: 0 },
      { stdin: '4\n-5\n-2\n-9\n-1\n', hidden: 1 },
      { stdin: '6\n0\n0\n0\n0\n0\n0\n', hidden: 1 },
      { stdin: '3\n-10\n15\n-3\n', hidden: 1 },
    ],
  },

  // ── 2.10 ───────────────────────────────────────────────────────────────────
  {
    lesson: '2.10', unit: U,
    handle: 'ap-csa-lesson-2-10-implementing-string-algorithms',
    title: 'Implementing String Algorithms',
    name: 'Walking the Word',
    mode: 'program',
    brief: 'A String is walked with charAt and length, index by index. Every String algorithm on the exam is a loop over those two methods, so this is the pattern rather than one of many.',
    task: [
      'Read a single word.',
      'Print how many vowels it contains, counting a, e, i, o and u in lower case only.',
      'Print the word reversed.',
      'Print true when the word reads the same forwards and backwards, and false otherwise.',
      'Print the word with every vowel removed.',
    ],
    reads: 'A single lower case word.',
    prints: 'Four lines: the vowel count, the reversed word, the palindrome check and the word with no vowels.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String word = input.next();',
      '',
      '    // word.charAt(i) gives one character. word.length() gives how many.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String word = input.next();',
      '',
      '    int vowels = 0;',
      '    String reversed = "";',
      '    String stripped = "";',
      '    for (int i = 0; i < word.length(); i++) {',
      '      String ch = word.substring(i, i + 1);',
      '      boolean isVowel = ch.equals("a") || ch.equals("e") || ch.equals("i")',
      '          || ch.equals("o") || ch.equals("u");',
      '      if (isVowel) {',
      '        vowels = vowels + 1;',
      '      } else {',
      '        stripped = stripped + ch;',
      '      }',
      '      reversed = ch + reversed;',
      '    }',
      '    System.out.println(vowels);',
      '    System.out.println(reversed);',
      '    System.out.println(word.equals(reversed));',
      '    System.out.println(stripped);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Building the reverse is one line: put each new character in FRONT of what you have so far.',
      'Compare Strings with equals, never with ==. Two Strings that read the same can still be different objects.',
      'A word made only of vowels leaves an empty last line. An empty line is a correct answer here, not a missing one.',
    ],
    seo: 'AP CSA 2.10 coding exercise: loop over a String to count vowels, reverse it, test for a palindrome and strip vowels.',
    cases: [
      { stdin: 'racecar\n', hidden: 0 },
      { stdin: 'java\n', hidden: 0 },
      { stdin: 'rhythm\n', hidden: 1 },
      { stdin: 'aeiou\n', hidden: 1 },
      { stdin: 'level\n', hidden: 1 },
    ],
  },

  // ── 2.11 ───────────────────────────────────────────────────────────────────
  {
    lesson: '2.11', unit: U,
    handle: 'ap-csa-lesson-2-11-nested-iteration',
    title: 'Nested Iteration',
    name: 'Rows and Columns',
    mode: 'program',
    brief: 'The inner loop finishes completely for every single pass of the outer one. Printing a shape makes that visible, because a misplaced newline turns a rectangle into a column.',
    task: [
      'Read two integers, rows and cols.',
      'Print a rectangle of asterisks with that many rows and columns, one row per line.',
      'Print a left aligned triangle where row i has i asterisks, for i from 1 to rows.',
      'Print the number of times the inner loop body ran while drawing the rectangle.',
      'Print the number of times it ran while drawing the triangle.',
    ],
    reads: 'Two integers on separate lines: rows, then cols. Both are at least 1.',
    prints: 'The rectangle, then the triangle, then two counts.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '',
      '    // System.out.print adds nothing after it. System.out.println ends the line.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int rows = input.nextInt();',
      '    int cols = input.nextInt();',
      '',
      '    int rectSteps = 0;',
      '    for (int r = 1; r <= rows; r++) {',
      '      for (int c = 1; c <= cols; c++) {',
      '        System.out.print("*");',
      '        rectSteps = rectSteps + 1;',
      '      }',
      '      System.out.println();',
      '    }',
      '',
      '    int triSteps = 0;',
      '    for (int r = 1; r <= rows; r++) {',
      '      for (int c = 1; c <= r; c++) {',
      '        System.out.print("*");',
      '        triSteps = triSteps + 1;',
      '      }',
      '      System.out.println();',
      '    }',
      '',
      '    System.out.println(rectSteps);',
      '    System.out.println(triSteps);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Use System.out.print inside the inner loop and an empty System.out.println() after it, so the line break happens once per row.',
      'The triangle inner loop stops at the OUTER counter, not at cols. That single change is what makes it a triangle.',
      'The rectangle count is always rows times cols. The triangle count is the sum 1 + 2 + ... + rows, which is why it grows more slowly.',
    ],
    seo: 'AP CSA 2.11 coding exercise: nest loops to draw a rectangle and a triangle and count how often the inner body runs.',
    cases: [
      { stdin: '3\n4\n', hidden: 0 },
      { stdin: '1\n1\n', hidden: 0 },
      { stdin: '5\n2\n', hidden: 1 },
      { stdin: '2\n6\n', hidden: 1 },
      { stdin: '6\n6\n', hidden: 1 },
    ],
  },

  // ── 2.12 ───────────────────────────────────────────────────────────────────
  {
    lesson: '2.12', unit: U,
    handle: 'ap-csa-lesson-2-12-informal-run-time-analysis',
    title: 'Informal Run-Time Analysis',
    name: 'Counting the Steps',
    mode: 'program',
    brief: 'Run time analysis is counting, and counting is something a program can do to itself. Print the real step counts for three loop shapes and the growth rates stop being abstractions.',
    task: [
      'Read one integer n, which is at least 1.',
      'Count and print how many times the body of a single loop from 1 to n runs.',
      'Count and print how many times the body of a nested loop, both from 1 to n, runs.',
      'Count and print how many times a loop that starts at n and halves each pass runs before reaching 0.',
      'Count and print how many times the body of a triangular nested loop runs, where the inner loop goes from 1 to the outer counter.',
    ],
    reads: 'A single integer of at least 1.',
    prints: 'Four counts, one per line: linear, quadratic, halving and triangular.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '',
      '    // Actually run the loops and count. Do not use a formula.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int n = input.nextInt();',
      '',
      '    int linear = 0;',
      '    for (int i = 1; i <= n; i++) {',
      '      linear = linear + 1;',
      '    }',
      '    System.out.println(linear);',
      '',
      '    int quadratic = 0;',
      '    for (int i = 1; i <= n; i++) {',
      '      for (int j = 1; j <= n; j++) {',
      '        quadratic = quadratic + 1;',
      '      }',
      '    }',
      '    System.out.println(quadratic);',
      '',
      '    int halving = 0;',
      '    int k = n;',
      '    while (k > 0) {',
      '      halving = halving + 1;',
      '      k = k / 2;',
      '    }',
      '    System.out.println(halving);',
      '',
      '    int triangular = 0;',
      '    for (int i = 1; i <= n; i++) {',
      '      for (int j = 1; j <= i; j++) {',
      '        triangular = triangular + 1;',
      '      }',
      '    }',
      '    System.out.println(triangular);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The nested count should come out as exactly n times n. If it does not, one of the loops has the wrong bound.',
      'Integer division is what makes the halving loop end: 1 / 2 is 0, so the last pass is the one that finishes it.',
      'The triangular count is about half the nested one. Both are quadratic, which is why the exam calls them the same order of growth.',
    ],
    seo: 'AP CSA 2.12 coding exercise: count the real steps of linear, nested, halving and triangular loops to compare growth rates.',
    cases: [
      { stdin: '5\n', hidden: 0 },
      { stdin: '1\n', hidden: 0 },
      { stdin: '16\n', hidden: 1 },
      { stdin: '100\n', hidden: 1 },
      { stdin: '7\n', hidden: 1 },
    ],
  },
];

module.exports = { exercises };
