'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  AP CSA UNIT 1: USING OBJECTS AND METHODS - 15 code exercises, one per lesson.
//
//  THE CONSTRAINT THAT SHAPES EVERY EXERCISE HERE
//  Unit 1 comes before selection (2.3) and before iteration (2.7). Not one of
//  these tasks may need an `if` or a loop, and none of them do. They are
//  straight-line programs, which is exactly what the unit teaches: declare,
//  assign, call, print.
//
//  INPUT BEFORE 1.4
//  1.4 is the lesson that teaches Scanner, so 1.1 through 1.3 cannot be expected
//  to write one. Their starters hand the input lines over already written and
//  say so, which previews 1.4 instead of gatekeeping on it. From 1.4 the student
//  writes the Scanner themselves, because that IS the lesson.
//
//  THE PROVIDED CLASS IN 1.12 THROUGH 1.14
//  Those three lessons are about USING an object someone else wrote, so the
//  starter contains a finished class and the student writes only the Main that
//  instantiates it and calls its methods. That is the real shape of the lesson
//  and it is only possible because these exercises submit a whole file rather
//  than a segment.
//
//  Every expected output in this file is produced by running the `reference`
//  through real javac/java (scripts/verify-csa-exercises.js). Nothing here
//  states an expected output, because a hand-written one is a guess.
// ─────────────────────────────────────────────────────────────────────────────

const U = 'unit-1';

// The Scanner boilerplate handed to lessons that have not met Scanner yet.
const GIVEN = '    // Reading input is Lesson 1.4. It is written for you here.';

const exercises = [
  // ── 1.1 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.1', unit: U,
    handle: 'ap-csa-lesson-1-1-intro-algorithms',
    title: 'Introduction to Algorithms, Programming, and Compilers',
    name: 'Step Tracker',
    mode: 'program',
    brief: 'An algorithm is an ordered sequence of steps, and order is the whole point. '
      + 'This one asks you to report the total after every step, so a step done out of order shows up immediately.',
    task: [
      'Read three integers: a starting step count, a number of steps gained, and a number of steps lost.',
      'Print the starting count.',
      'Add the gain, then print the new total.',
      'Subtract the loss, then print the new total.',
      'Print the total one more time, doubled, as a stretch goal for tomorrow.',
    ],
    reads: 'Three integers on separate lines: start, gained, lost.',
    prints: 'Four lines: the start, the total after the gain, the total after the loss, and that final total doubled.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      GIVEN,
      '    Scanner input = new Scanner(System.in);',
      '    int start = input.nextInt();',
      '    int gained = input.nextInt();',
      '    int lost = input.nextInt();',
      '',
      '    // Your algorithm goes here. Four printed lines, in order.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int start = input.nextInt();',
      '    int gained = input.nextInt();',
      '    int lost = input.nextInt();',
      '',
      '    int total = start;',
      '    System.out.println(total);',
      '    total = total + gained;',
      '    System.out.println(total);',
      '    total = total - lost;',
      '    System.out.println(total);',
      '    System.out.println(total * 2);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Keep one variable for the running total and change it step by step. Printing start + gained - lost in one line gets the last number right and the middle ones wrong.',
      'System.out.println prints its argument and then moves to a new line. Four calls means four lines.',
      'The order of the printed lines is part of the answer. A correct total printed in the wrong place still fails.',
    ],
    seo: 'AP CSA 1.1 coding exercise: implement a four step algorithm in Java and print the running total after each step. Auto graded.',
    cases: [
      { stdin: '1000\n2500\n400\n', hidden: 0 },
      { stdin: '0\n10\n3\n', hidden: 0 },
      { stdin: '7500\n120\n9000\n', hidden: 1 },
      { stdin: '42\n0\n0\n', hidden: 1 },
      { stdin: '-15\n50\n5\n', hidden: 1 },
    ],
  },

  // ── 1.2 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.2', unit: U,
    handle: 'ap-csa-lesson-1-2-variables-data-types',
    title: 'Variables and Data Types',
    name: 'Snack Bar Order',
    mode: 'program',
    brief: 'Three types, three jobs. Picking int where you needed double is the single most common way a correct-looking program prints the wrong number.',
    task: [
      'Read a snack name (one word), then a whole number of them, then the price of one as a decimal.',
      'Store each in a variable of the right type: String, int, double.',
      'Print the name, then the count, then the unit price, each on its own line.',
      'Print the total cost on the fourth line.',
    ],
    reads: 'A word, then an integer, then a decimal number, each on its own line.',
    prints: 'Four lines: the snack name, the count, the unit price, and the total cost.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      GIVEN,
      '    Scanner input = new Scanner(System.in);',
      '    String snack = input.next();',
      '    int count = input.nextInt();',
      '    double price = input.nextDouble();',
      '',
      '    // Print the four lines. Think about which type the total has to be.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String snack = input.next();',
      '    int count = input.nextInt();',
      '    double price = input.nextDouble();',
      '',
      '    double total = count * price;',
      '    System.out.println(snack);',
      '    System.out.println(count);',
      '    System.out.println(price);',
      '    System.out.println(total);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A count of items is a whole number, so it is an int. A price is not, so it is a double.',
      'An int times a double is a double in Java. Store the total in a double or you will lose the cents.',
      'Printing a double always shows a decimal point: 6 prints as 6, but 6.0 prints as 6.0.',
    ],
    seo: 'AP CSA 1.2 coding exercise: declare String, int and double variables for a snack order and print the total. Auto graded in the browser.',
    cases: [
      { stdin: 'pretzel\n3\n2.5\n', hidden: 0 },
      { stdin: 'water\n1\n1.25\n', hidden: 0 },
      { stdin: 'burrito\n4\n7.75\n', hidden: 1 },
      { stdin: 'gum\n12\n0.5\n', hidden: 1 },
      { stdin: 'nachos\n0\n4.25\n', hidden: 1 },
    ],
  },

  // ── 1.3 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.3', unit: U,
    handle: 'ap-csa-lesson-1-3-expressions-assignment',
    title: 'Expressions and Output',
    name: 'Five Operators',
    mode: 'program',
    brief: 'Integer division and the remainder operator are the two the exam tests hardest, because they are the two that do not behave the way arithmetic class taught you.',
    task: [
      'Read two integers, a and b. You may assume b is not zero.',
      'Print a + b, then a - b, then a * b, then a / b, then a % b.',
      'Each result goes on its own line, in that order.',
    ],
    reads: 'Two integers on separate lines: a, then b.',
    prints: 'Five lines: the sum, the difference, the product, the quotient and the remainder.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      GIVEN,
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '',
      '    // Five lines, in the order given.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '',
      '    System.out.println(a + b);',
      '    System.out.println(a - b);',
      '    System.out.println(a * b);',
      '    System.out.println(a / b);',
      '    System.out.println(a % b);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'int / int throws away the fraction rather than rounding. 7 / 2 is 3, and 4 / 9 is 0.',
      'a % b is what is left over after the division. 4 % 9 is 4, because 9 goes into 4 zero times with 4 left.',
      'When a is negative Java keeps the sign of a in the remainder, so -7 % 3 is -1.',
    ],
    seo: 'AP CSA 1.3 coding exercise: print the sum, difference, product, integer quotient and remainder of two ints. Auto graded Java practice.',
    cases: [
      { stdin: '17\n5\n', hidden: 0 },
      { stdin: '9\n3\n', hidden: 0 },
      { stdin: '4\n9\n', hidden: 1 },
      { stdin: '100\n7\n', hidden: 1 },
      { stdin: '-7\n3\n', hidden: 1 },
    ],
  },

  // ── 1.4 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.4', unit: U,
    handle: 'ap-csa-lesson-1-4-assignment-statements-input',
    title: 'Assignment Statements and Input',
    name: 'Locker Assignment',
    mode: 'program',
    brief: 'This is the first exercise where you write the Scanner yourself. The order you call next, nextInt and nextDouble in has to match the order the values arrive in, and nothing warns you when it does not.',
    task: [
      'Create a Scanner that reads from System.in.',
      'Read a student first name (one word), then a locker number as an int, then a shelf height in metres as a double.',
      'Print the name, then the locker number, then the height, each on its own line.',
      'Print the locker number again on the fourth line, this time plus 100, which is what the second floor uses.',
    ],
    reads: 'A word, then an integer, then a decimal number, each on its own line.',
    prints: 'Four lines: the name, the locker number, the shelf height and the second floor locker number.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    // Create the Scanner, read the three values, print the four lines.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String name = input.next();',
      '    int locker = input.nextInt();',
      '    double height = input.nextDouble();',
      '',
      '    System.out.println(name);',
      '    System.out.println(locker);',
      '    System.out.println(height);',
      '    System.out.println(locker + 100);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'The import is already at the top. You still need Scanner input = new Scanner(System.in);',
      'next() reads one word, nextInt() reads a whole number, nextDouble() reads a decimal. Call them in the order the values arrive.',
      'Calling nextInt() when the next value is a word throws InputMismatchException. If you see that, your reads are out of order.',
    ],
    seo: 'AP CSA 1.4 coding exercise: write a Scanner to read a String, an int and a double from input, then print them. Auto graded.',
    cases: [
      { stdin: 'Maya\n214\n1.5\n', hidden: 0 },
      { stdin: 'Devon\n7\n0.75\n', hidden: 0 },
      { stdin: 'Priya\n1188\n2.25\n', hidden: 1 },
      { stdin: 'Sam\n0\n1.0\n', hidden: 1 },
      { stdin: 'Alex\n905\n3.125\n', hidden: 1 },
    ],
  },

  // ── 1.5 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.5', unit: U,
    handle: 'ap-csa-lesson-1-5-casting-range',
    title: 'Casting and Range of Variables',
    name: 'Class Average',
    mode: 'program',
    brief: 'Casting after the division is too late. This exercise prints both answers side by side so the difference is impossible to miss.',
    task: [
      'Read two integers: a total number of points and a count of students. Assume the count is not zero.',
      'Print the integer average, computed with int division.',
      'Print the exact average as a double, by casting BEFORE you divide.',
      'Print the exact average again, this time truncated back to an int with a cast.',
    ],
    reads: 'Two integers on separate lines: total, then count.',
    prints: 'Three lines: the int division result, the exact average as a double, and that average cast back to an int.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int total = input.nextInt();',
      '    int count = input.nextInt();',
      '',
      '    // Three lines. Two of them are the same division, cast differently.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int total = input.nextInt();',
      '    int count = input.nextInt();',
      '',
      '    System.out.println(total / count);',
      '    double exact = (double) total / count;',
      '    System.out.println(exact);',
      '    System.out.println((int) exact);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      '(double) total / count casts total first, so the division is a double division. (double) (total / count) divides as ints first and then converts the already wrong answer.',
      'Casting a double to an int truncates toward zero. It does not round: (int) 3.9 is 3.',
      'A double always prints with a decimal point. If your second line shows 3 instead of 3.0, you divided as ints somewhere.',
    ],
    seo: 'AP CSA 1.5 coding exercise: compare int division with a double cast average in Java, then truncate it back. Auto graded practice.',
    cases: [
      { stdin: '7\n2\n', hidden: 0 },
      { stdin: '10\n4\n', hidden: 0 },
      { stdin: '9\n3\n', hidden: 1 },
      { stdin: '1\n8\n', hidden: 1 },
      { stdin: '100\n8\n', hidden: 1 },
    ],
  },

  // ── 1.6 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.6', unit: U,
    handle: 'ap-csa-lesson-1-6-compound-assignment',
    title: 'Compound Assignment Operators',
    name: 'Score Multiplier',
    mode: 'program',
    brief: 'Every compound operator rewrites the variable it is applied to. Print after each one and the sequence stops being something you have to hold in your head.',
    task: [
      'Read one integer as the starting score.',
      'Apply these four operators to it, in this order: += 10, then *= 3, then -= 4, then %= 7.',
      'Print the score after each one, so four lines in total.',
    ],
    reads: 'A single integer.',
    prints: 'Four lines: the score after each of the four compound assignments.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int score = input.nextInt();',
      '',
      '    // Four operators, four printed lines, in order.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int score = input.nextInt();',
      '',
      '    score += 10;',
      '    System.out.println(score);',
      '    score *= 3;',
      '    System.out.println(score);',
      '    score -= 4;',
      '    System.out.println(score);',
      '    score %= 7;',
      '    System.out.println(score);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'score += 10 is short for score = score + 10. It changes score, it does not just compute a value.',
      'Each operator works on the result of the one before it, so the order matters more than the arithmetic does.',
      'A negative starting score can leave a negative remainder at the end. That is correct Java, not a bug in your code.',
    ],
    seo: 'AP CSA 1.6 coding exercise: apply +=, *=, -= and %= in order and print the score after each step. Auto graded Java practice.',
    cases: [
      { stdin: '5\n', hidden: 0 },
      { stdin: '0\n', hidden: 0 },
      { stdin: '-3\n', hidden: 1 },
      { stdin: '100\n', hidden: 1 },
      { stdin: '4\n', hidden: 1 },
    ],
  },

  // ── 1.7 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.7', unit: U,
    handle: 'ap-csa-lesson-1-7-api-libraries',
    title: 'Application Program Interface (API) and Libraries',
    name: 'Reading the Docs',
    mode: 'program',
    brief: 'A library is code someone else already wrote and documented. This one asks you to call four methods you have never used, working only from what the task tells you about them.',
    task: [
      'Read a line containing digits as a String, then read an integer n.',
      'Use Integer.parseInt to turn the String into an int, add n to it, and print the result.',
      'Print String.valueOf(n) joined onto the end of the original String.',
      'Print Integer.toBinaryString(n).',
      'Print Integer.MAX_VALUE.',
    ],
    reads: 'A word made of digits, then an integer, each on its own line.',
    prints: 'Four lines: the parsed sum, the joined String, n in binary, and the largest int Java can hold.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String digits = input.next();',
      '    int n = input.nextInt();',
      '',
      '    // Four library calls, four printed lines.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String digits = input.next();',
      '    int n = input.nextInt();',
      '',
      '    System.out.println(Integer.parseInt(digits) + n);',
      '    System.out.println(digits + String.valueOf(n));',
      '    System.out.println(Integer.toBinaryString(n));',
      '    System.out.println(Integer.MAX_VALUE);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Integer.parseInt("42") returns the int 42. The String "42" plus 1 would be "421", which is why the parse has to happen first.',
      'Integer.MAX_VALUE is a constant, not a method, so there are no parentheses after it.',
      'Every one of these is called on the class name, not on an object you made. That is what a class method looks like.',
    ],
    seo: 'AP CSA 1.7 coding exercise: call Integer.parseInt, String.valueOf, Integer.toBinaryString and Integer.MAX_VALUE from the Java library.',
    cases: [
      { stdin: '42\n8\n', hidden: 0 },
      { stdin: '7\n1\n', hidden: 0 },
      { stdin: '1000\n255\n', hidden: 1 },
      { stdin: '0\n16\n', hidden: 1 },
      { stdin: '99\n1023\n', hidden: 1 },
    ],
  },

  // ── 1.8 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.8', unit: U,
    handle: 'ap-csa-lesson-1-8-documentation-comments',
    title: 'Documentation with Comments',
    name: 'Precondition, Postcondition',
    mode: 'program',
    brief: 'The grader checks what your program prints, and a comment prints nothing. Write them anyway: the habit is what the exam rewards on the free response, where a stated precondition is the difference between a correct answer and a rejected one.',
    task: [
      'Read three integers: a starting balance in cents, a deposit in cents, and a number of equal withdrawals.',
      'Above your code, write a comment block stating the precondition (the number of withdrawals is at least 1) and the postcondition (what the program will have printed).',
      'Print the balance after the deposit.',
      'Print the size of one withdrawal, using integer division of the new balance by the number of withdrawals.',
      'Print the cents left over after those withdrawals.',
    ],
    reads: 'Three integers on separate lines: balance, deposit, withdrawals.',
    prints: 'Three lines: the balance after the deposit, the size of one withdrawal, and the remainder.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  /**',
      '   * Precondition:',
      '   * Postcondition:',
      '   */',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int balance = input.nextInt();',
      '    int deposit = input.nextInt();',
      '    int withdrawals = input.nextInt();',
      '',
      '    // Three printed lines.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  /**',
      '   * Precondition: withdrawals is at least 1.',
      '   * Postcondition: prints the balance after the deposit, one withdrawal, and the remainder.',
      '   */',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int balance = input.nextInt();',
      '    int deposit = input.nextInt();',
      '    int withdrawals = input.nextInt();',
      '',
      '    int after = balance + deposit;',
      '    System.out.println(after);',
      '    System.out.println(after / withdrawals);',
      '    System.out.println(after % withdrawals);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'A precondition is what has to be true before your code runs for it to be correct. Here it is the one that stops a divide by zero.',
      'The deposit lands before the withdrawals are worked out, so compute the new balance once and use it twice.',
      'Everything is in whole cents, so integer division and % are the right tools and nothing needs to be a double.',
    ],
    seo: 'AP CSA 1.8 coding exercise: document a precondition and postcondition, then split a balance with integer division and remainder.',
    cases: [
      { stdin: '500\n250\n4\n', hidden: 0 },
      { stdin: '0\n100\n3\n', hidden: 0 },
      { stdin: '1299\n1\n7\n', hidden: 1 },
      { stdin: '90\n10\n1\n', hidden: 1 },
      { stdin: '25\n75\n8\n', hidden: 1 },
    ],
  },

  // ── 1.9 ────────────────────────────────────────────────────────────────────
  {
    lesson: '1.9', unit: U,
    handle: 'ap-csa-lesson-1-9-method-signatures',
    title: 'Method Signatures',
    name: 'Match the Signature',
    mode: 'program',
    brief: 'A signature is a promise about what goes in and what comes out. Three of these four methods take a type you do not have yet, so each call needs the right value handed to it in the right form.',
    task: [
      'Read a decimal number d, then an integer n.',
      'Call Math.round(double), which returns a long, on d and print what it gives back.',
      'Call Math.abs(int) on n and print the result.',
      'Call Math.pow(double, double) with n and 2 and print the result. Notice it returns a double even when the answer is whole.',
      'Call String.valueOf(double) on d and print its length() instead of the String itself.',
    ],
    reads: 'A decimal number, then an integer, each on its own line.',
    prints: 'Four lines: the rounded value, the absolute value, n squared as a double, and how many characters d takes to write.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    double d = input.nextDouble();',
      '    int n = input.nextInt();',
      '',
      '    // Four calls. Check what each one returns before you print it.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    double d = input.nextDouble();',
      '    int n = input.nextInt();',
      '',
      '    System.out.println(Math.round(d));',
      '    System.out.println(Math.abs(n));',
      '    System.out.println(Math.pow(n, 2));',
      '    System.out.println(String.valueOf(d).length());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Math.pow always returns a double, so 4 squared prints as 16.0 and not 16. That is the signature telling you something.',
      'Math.round(double) returns a long. Printing it looks like an int, but the type is not the same thing as the printed form.',
      'String.valueOf(d) makes a String, and length() is called on that String. You can write it as one chained expression.',
    ],
    seo: 'AP CSA 1.9 coding exercise: call Math.round, Math.abs, Math.pow and String.valueOf and read what each signature returns.',
    cases: [
      { stdin: '3.5\n4\n', hidden: 0 },
      { stdin: '2.25\n-7\n', hidden: 0 },
      { stdin: '10.0\n0\n', hidden: 1 },
      { stdin: '0.5\n12\n', hidden: 1 },
      { stdin: '99.75\n-1\n', hidden: 1 },
    ],
  },

  // ── 1.10 ───────────────────────────────────────────────────────────────────
  {
    lesson: '1.10', unit: U,
    handle: 'ap-csa-lesson-1-10-calling-class-methods',
    title: 'Calling Class Methods',
    name: 'Called on the Class',
    mode: 'program',
    brief: 'A class method is called on the class name, with no object anywhere. Once you can spot that in the call, the difference from the next lesson stops being a memorisation problem.',
    task: [
      'Read two integers, a and b.',
      'Print Integer.compare(a, b), which is negative, zero or positive.',
      'Print Math.floorDiv(a, b), which rounds toward negative infinity instead of toward zero.',
      'Print Math.floorMod(a, b) and notice how it differs from a % b when a is negative.',
      'Print a % b on the last line so the two are next to each other.',
    ],
    reads: 'Two integers on separate lines: a, then b. b is never zero.',
    prints: 'Four lines: the comparison, the floor division, the floor remainder and the ordinary remainder.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '',
      '    // Four lines. Every call here is ClassName.method(...).',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int a = input.nextInt();',
      '    int b = input.nextInt();',
      '',
      '    System.out.println(Integer.compare(a, b));',
      '    System.out.println(Math.floorDiv(a, b));',
      '    System.out.println(Math.floorMod(a, b));',
      '    System.out.println(a % b);',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'You never write new Math() or new Integer(). These are class methods, so the class name is the whole receiver.',
      'Integer.compare returns -1, 0 or 1 rather than the difference, so do not expect a - b.',
      'For positive a and b, floorDiv and / agree and floorMod and % agree. The negative cases are the ones worth reading twice.',
    ],
    seo: 'AP CSA 1.10 coding exercise: call the class methods Integer.compare, Math.floorDiv and Math.floorMod and compare them to %.',
    cases: [
      { stdin: '17\n5\n', hidden: 0 },
      { stdin: '3\n8\n', hidden: 0 },
      { stdin: '-7\n3\n', hidden: 1 },
      { stdin: '9\n9\n', hidden: 1 },
      { stdin: '-20\n-6\n', hidden: 1 },
    ],
  },

  // ── 1.11 ───────────────────────────────────────────────────────────────────
  {
    lesson: '1.11', unit: U,
    handle: 'ap-csa-lesson-1-11-math-class',
    title: 'Math Class',
    name: 'Distance and Damage',
    mode: 'program',
    brief: 'Four Math methods in one expression each. The trap is not the maths, it is remembering which ones hand you back a double whether you wanted one or not.',
    task: [
      'Read four integers: x1, y1, x2, y2, the coordinates of two points.',
      'Print the horizontal distance using Math.abs.',
      'Print the vertical distance using Math.abs.',
      'Print the straight line distance using Math.sqrt and Math.pow.',
      'Print the larger of the two coordinates x1 and y2 using Math.max, and then the smaller of x2 and y1 using Math.min, on separate lines.',
    ],
    reads: 'Four integers on separate lines: x1, y1, x2, y2.',
    prints: 'Five lines: the horizontal distance, the vertical distance, the straight line distance, the max and the min.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int x1 = input.nextInt();',
      '    int y1 = input.nextInt();',
      '    int x2 = input.nextInt();',
      '    int y2 = input.nextInt();',
      '',
      '    // Five lines.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int x1 = input.nextInt();',
      '    int y1 = input.nextInt();',
      '    int x2 = input.nextInt();',
      '    int y2 = input.nextInt();',
      '',
      '    int dx = Math.abs(x2 - x1);',
      '    int dy = Math.abs(y2 - y1);',
      '    System.out.println(dx);',
      '    System.out.println(dy);',
      '    System.out.println(Math.sqrt(Math.pow(dx, 2) + Math.pow(dy, 2)));',
      '    System.out.println(Math.max(x1, y2));',
      '    System.out.println(Math.min(x2, y1));',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Math.abs(int) gives you an int back, so the first two lines have no decimal point.',
      'Math.sqrt always returns a double, so the third line always shows one. A distance of 5 prints as 5.0.',
      'Math.pow(dx, 2) works, and so does dx * dx. The exam accepts either, and dx * dx stays an int.',
    ],
    seo: 'AP CSA 1.11 coding exercise: use Math.abs, Math.sqrt, Math.pow, Math.max and Math.min to measure between two points.',
    cases: [
      { stdin: '0\n0\n3\n4\n', hidden: 0 },
      { stdin: '2\n2\n2\n2\n', hidden: 0 },
      { stdin: '-5\n7\n10\n-5\n', hidden: 1 },
      { stdin: '1\n1\n1\n13\n', hidden: 1 },
      { stdin: '8\n-3\n-4\n9\n', hidden: 1 },
    ],
  },

  // ── 1.12 ───────────────────────────────────────────────────────────────────
  {
    lesson: '1.12', unit: U,
    handle: 'ap-csa-lesson-1-12-objects-instances',
    title: 'Objects: Instances of Classes',
    name: 'Two Books, One Class',
    mode: 'program',
    brief: 'One class, two instances, two separate sets of values. The class is the blueprint and it holds no data of its own, which is the whole idea this lesson is built on.',
    task: [
      'The Book class is written for you. Do not change it.',
      'Read a title, a page count, and a second title and page count.',
      'Create two Book objects from those values.',
      'Print each book description on its own line by calling describe() on each object.',
      'Print the total number of pages across both books.',
    ],
    reads: 'A word, an integer, a word and an integer, each on its own line.',
    prints: 'Three lines: the first description, the second description, and the total page count.',
    starter: [
      'import java.util.Scanner;',
      '',
      'class Book {',
      '  private String title;',
      '  private int pages;',
      '',
      '  public Book(String title, int pages) {',
      '    this.title = title;',
      '    this.pages = pages;',
      '  }',
      '',
      '  public int getPages() { return pages; }',
      '',
      '  public String describe() { return title + " (" + pages + "p)"; }',
      '}',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String t1 = input.next();',
      '    int p1 = input.nextInt();',
      '    String t2 = input.next();',
      '    int p2 = input.nextInt();',
      '',
      '    // Create two Book objects and use them.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'class Book {',
      '  private String title;',
      '  private int pages;',
      '',
      '  public Book(String title, int pages) {',
      '    this.title = title;',
      '    this.pages = pages;',
      '  }',
      '',
      '  public int getPages() { return pages; }',
      '',
      '  public String describe() { return title + " (" + pages + "p)"; }',
      '}',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String t1 = input.next();',
      '    int p1 = input.nextInt();',
      '    String t2 = input.next();',
      '    int p2 = input.nextInt();',
      '',
      '    Book first = new Book(t1, p1);',
      '    Book second = new Book(t2, p2);',
      '    System.out.println(first.describe());',
      '    System.out.println(second.describe());',
      '    System.out.println(first.getPages() + second.getPages());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'new Book(t1, p1) makes one instance. Calling it twice makes two, and they do not share their title or page count.',
      'describe() is called on an object, not on the class: first.describe(), never Book.describe().',
      'The Book class already stores the values. You do not need to print the title yourself, and you must not edit the class.',
    ],
    seo: 'AP CSA 1.12 coding exercise: create two instances of a provided Book class and call their methods. Auto graded Java practice.',
    cases: [
      { stdin: 'Dune\n412\nHamlet\n160\n', hidden: 0 },
      { stdin: 'Emma\n1\nOdyssey\n2\n', hidden: 0 },
      { stdin: 'Beloved\n324\nBeloved\n324\n', hidden: 1 },
      { stdin: 'Ulysses\n730\nHaiku\n0\n', hidden: 1 },
      { stdin: 'Kindred\n287\nWatchmen\n416\n', hidden: 1 },
    ],
  },

  // ── 1.13 ───────────────────────────────────────────────────────────────────
  {
    lesson: '1.13', unit: U,
    handle: 'ap-csa-lesson-1-13-object-creation',
    title: 'Object Creation and Storage (Instantiation)',
    name: 'Two Names, One Object',
    mode: 'program',
    brief: 'A reference variable holds the address of an object, not the object. Copy the variable and you have two names for one thing, which is the single most useful fact in this unit and the one that surprises everybody.',
    task: [
      'The Counter class is written for you. Do not change it.',
      'Read an integer start and an integer bump.',
      'Create one Counter with the starting value, then create a SECOND variable that refers to the SAME object.',
      'Call add(bump) through the first variable, then print the value read through the second variable.',
      'Now create a genuinely new Counter from the same starting value, call add(bump) on the first variable again, and print the new object value.',
    ],
    reads: 'Two integers on separate lines: start, then bump.',
    prints: 'Two lines: the value seen through the alias, and the value in the separately created object.',
    starter: [
      'import java.util.Scanner;',
      '',
      'class Counter {',
      '  private int value;',
      '',
      '  public Counter(int value) { this.value = value; }',
      '',
      '  public void add(int n) { value += n; }',
      '',
      '  public int getValue() { return value; }',
      '}',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int start = input.nextInt();',
      '    int bump = input.nextInt();',
      '',
      '    // One object with two names, then a second, separate object.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'class Counter {',
      '  private int value;',
      '',
      '  public Counter(int value) { this.value = value; }',
      '',
      '  public void add(int n) { value += n; }',
      '',
      '  public int getValue() { return value; }',
      '}',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int start = input.nextInt();',
      '    int bump = input.nextInt();',
      '',
      '    Counter first = new Counter(start);',
      '    Counter alias = first;',
      '    first.add(bump);',
      '    System.out.println(alias.getValue());',
      '',
      '    Counter separate = new Counter(start);',
      '    first.add(bump);',
      '    System.out.println(separate.getValue());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'Counter alias = first; does not build anything. It copies a reference, so both names point at one object.',
      'Only the word new creates an object. Count the news in your answer: there should be exactly two.',
      'The second printed line should be the starting value untouched, because add was never called on that object.',
    ],
    seo: 'AP CSA 1.13 coding exercise: see the difference between copying a reference and creating a new object with new. Auto graded.',
    cases: [
      { stdin: '10\n5\n', hidden: 0 },
      { stdin: '0\n1\n', hidden: 0 },
      { stdin: '-4\n9\n', hidden: 1 },
      { stdin: '100\n0\n', hidden: 1 },
      { stdin: '7\n-3\n', hidden: 1 },
    ],
  },

  // ── 1.14 ───────────────────────────────────────────────────────────────────
  {
    lesson: '1.14', unit: U,
    handle: 'ap-csa-lesson-1-14-calling-instance-methods',
    title: 'Calling Instance Methods',
    name: 'Working the Account',
    mode: 'program',
    brief: 'Some methods change the object and return nothing. Some return a value and change nothing. Telling them apart from the call alone is what this exercise drills.',
    task: [
      'The Account class is written for you. Do not change it.',
      'Read an opening balance, a deposit and a withdrawal, all integers.',
      'Create one Account with the opening balance.',
      'Call deposit, then print the balance.',
      'Call withdraw, then print the balance.',
      'Print the number of transactions the account has recorded.',
    ],
    reads: 'Three integers on separate lines: opening, deposit, withdrawal.',
    prints: 'Three lines: the balance after the deposit, the balance after the withdrawal, and the transaction count.',
    starter: [
      'import java.util.Scanner;',
      '',
      'class Account {',
      '  private int balance;',
      '  private int transactions;',
      '',
      '  public Account(int balance) { this.balance = balance; }',
      '',
      '  public void deposit(int amount) { balance += amount; transactions++; }',
      '',
      '  public void withdraw(int amount) { balance -= amount; transactions++; }',
      '',
      '  public int getBalance() { return balance; }',
      '',
      '  public int getTransactions() { return transactions; }',
      '}',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int opening = input.nextInt();',
      '    int in = input.nextInt();',
      '    int out = input.nextInt();',
      '',
      '    // One account, two changes, three printed lines.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'class Account {',
      '  private int balance;',
      '  private int transactions;',
      '',
      '  public Account(int balance) { this.balance = balance; }',
      '',
      '  public void deposit(int amount) { balance += amount; transactions++; }',
      '',
      '  public void withdraw(int amount) { balance -= amount; transactions++; }',
      '',
      '  public int getBalance() { return balance; }',
      '',
      '  public int getTransactions() { return transactions; }',
      '}',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    int opening = input.nextInt();',
      '    int in = input.nextInt();',
      '    int out = input.nextInt();',
      '',
      '    Account acct = new Account(opening);',
      '    acct.deposit(in);',
      '    System.out.println(acct.getBalance());',
      '    acct.withdraw(out);',
      '    System.out.println(acct.getBalance());',
      '    System.out.println(acct.getTransactions());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'deposit returns void, so System.out.println(acct.deposit(in)) will not compile. Call it, then ask for the balance separately.',
      'getBalance returns an int and changes nothing, so calling it twice in a row gives the same answer twice.',
      'The account can go negative. Nothing in the class stops a withdrawal, and this exercise does not ask you to.',
    ],
    seo: 'AP CSA 1.14 coding exercise: call void and value returning instance methods on an Account object in the right order.',
    cases: [
      { stdin: '100\n50\n30\n', hidden: 0 },
      { stdin: '0\n0\n0\n', hidden: 0 },
      { stdin: '20\n5\n90\n', hidden: 1 },
      { stdin: '1500\n1200\n2700\n', hidden: 1 },
      { stdin: '-50\n100\n25\n', hidden: 1 },
    ],
  },

  // ── 1.15 ───────────────────────────────────────────────────────────────────
  {
    lesson: '1.15', unit: U,
    handle: 'ap-csa-lesson-1-15-string-manipulation',
    title: 'String Manipulation',
    name: 'Cut the String',
    mode: 'program',
    brief: 'substring takes the first index and stops BEFORE the second. Off by one here is the most reliable way to lose a point on the exam, so this exercise makes you use it four different ways.',
    task: [
      'Read one word.',
      'Print its length.',
      'Print the first three characters using substring.',
      'Print everything from index 2 onward using the one argument form of substring.',
      'Print the index of the letter e, or -1 when there is not one.',
      'Print the whole word in upper case.',
    ],
    reads: 'A single word of at least three characters.',
    prints: 'Five lines: the length, the first three characters, the tail from index 2, the index of e, and the word in upper case.',
    starter: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String word = input.next();',
      '',
      '    // Five lines.',
      '  }',
      '}',
    ].join('\n'),
    reference: [
      'import java.util.Scanner;',
      '',
      'public class Main {',
      '  public static void main(String[] args) {',
      '    Scanner input = new Scanner(System.in);',
      '    String word = input.next();',
      '',
      '    System.out.println(word.length());',
      '    System.out.println(word.substring(0, 3));',
      '    System.out.println(word.substring(2));',
      '    System.out.println(word.indexOf("e"));',
      '    System.out.println(word.toUpperCase());',
      '  }',
      '}',
    ].join('\n'),
    hints: [
      'substring(0, 3) gives you characters 0, 1 and 2. The second number is where it stops, not the last one it keeps.',
      'substring(2) with one argument runs to the end of the String.',
      'indexOf returns -1 when the letter is not there, which is a value you print rather than an error you handle.',
    ],
    seo: 'AP CSA 1.15 coding exercise: use length, substring with one and two arguments, indexOf and toUpperCase on a String.',
    cases: [
      { stdin: 'computer\n', hidden: 0 },
      { stdin: 'javascript\n', hidden: 0 },
      { stdin: 'chair\n', hidden: 1 },
      { stdin: 'algorithm\n', hidden: 1 },
      { stdin: 'eee\n', hidden: 1 },
    ],
  },
];

module.exports = { exercises };
