'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  CSA UNIT 3 EXERCISE 2 BANKS: APPLIED MCQ PRACTICE.
//
//  Six applied, scenario-based multiple choice questions per lesson, worth 6
//  points, matching the cross-course exercise-2 convention. See the header of
//  seed/csa-exercise-2/unit4.js for what an exercise 2 is and why every
//  rationale is written rather than only the correct one.
//
//  ALL NINE LESSONS. Unit 3 is class creation, and what authoring the FRQ bank
//  for these lessons surfaced is that its characteristic bugs are SILENT: a
//  shadowed field, a missing this, a constructor that assigns a parameter to
//  itself. None of them throw. They produce an object that looks constructed
//  and holds default values, so these questions lean on what the object
//  actually CONTAINS after a call rather than on whether the code runs.
//
//  ANSWER LETTERS SKEW TO B ON PURPOSE. The renderer shuffles options
//  deterministically per question, so rendered pages are balanced; smoke
//  assertion 5.3 asserts the SOURCE skew because that is what proves the
//  shuffle is doing real work.
//
//  Pure ASCII, no em-dashes. Zero PII: author content only.
// ─────────────────────────────────────────────────────────────────────────────

module.exports = [
  {
    lesson: '3.1', unit: 'unit-3',
    title: 'Abstraction and Program Design',
    blurb: 'Six scenarios on deciding what a class should hide and what it should expose.',
    brief: 'There is no tricky syntax in this topic, which is why it gets skipped. The exam asks it as judgement about a specific design, so these six are all judgement.',
    seo: 'Applied AP CSA 3.1 practice: six scenario questions on abstraction, encapsulation and program design.',
    questions: [
      {
        tag: 'Evaluate',
        scenario: 'A BankAccount class exposes its balance field as public so other classes can adjust it directly.',
        stem: 'What is the strongest objection?',
        options: [
          'Public fields use more memory',
          'Any class can now set the balance to an invalid value, because the rules about what a balance may be no longer have a single place to live',
          'Public fields are slower to access',
          'The field should be named differently',
        ],
        correct: 'B',
        why: {
          A: 'Visibility has no effect on memory use.',
          B: 'Correct. Encapsulation exists to keep the invariant enforceable in one place.',
          C: 'Access speed is unaffected by the modifier.',
          D: 'Naming is not the issue here.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A designer must decide whether a Student class should store a letter grade or compute it from stored scores on demand.',
        stem: 'What is the main argument for computing it?',
        options: [
          'Computing is always faster than storing',
          'A stored letter can fall out of sync with the scores it was derived from, while a computed one cannot',
          'Computed values use less memory in every case',
          'Stored values cannot be private',
        ],
        correct: 'B',
        why: {
          A: 'Reading a stored value is generally faster.',
          B: 'Correct. Deriving on demand removes an entire class of consistency bug.',
          C: 'Memory is a minor and situational consideration.',
          D: 'Both can be private.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A class has grown to handle student records, file input and report formatting.',
        stem: 'What design principle does this violate?',
        options: [
          'Classes should always be small',
          'A class should have one clear responsibility, and these three change for unrelated reasons so a change to one risks the others',
          'Classes cannot perform file input',
          'Formatting belongs in the constructor',
        ],
        correct: 'B',
        why: {
          A: 'Size is a symptom, not the principle. Some single-responsibility classes are large.',
          B: 'Correct, and the "changes for different reasons" test is the useful form of it.',
          C: 'File handling in a class is perfectly legal.',
          D: 'A constructor exists to initialize, not to format output.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A method signature is changed from taking three separate int parameters to taking one object.',
        stem: 'What is gained?',
        options: [
          'Nothing; it is strictly more complex',
          'The three values travel together as one meaningful unit, so they cannot be passed in the wrong order or get out of step',
          'The method becomes faster',
          'The method no longer needs a return type',
        ],
        correct: 'B',
        why: {
          A: 'It removes a real class of caller error.',
          B: 'Correct. Three ints of the same type are exactly the case where argument order is easy to get wrong.',
          C: 'Speed is unaffected or marginally worse.',
          D: 'The return type is independent of the parameters.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A programmer uses a class written by someone else, reading only its method signatures and documentation.',
        stem: 'What does this illustrate?',
        options: [
          'Poor practice, since the implementation should always be read',
          'Abstraction working as intended: the interface is sufficient to use the class correctly without knowing how it is built',
          'That the class has no private fields',
          'That the class must be in the same file',
        ],
        correct: 'B',
        why: {
          A: 'Needing to read the implementation to use a class is a sign the abstraction has failed.',
          B: 'Correct. This is the practical payoff of the whole topic.',
          C: 'Private fields are invisible precisely because they are private.',
          D: 'File location is unrelated.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A team must add a feature and can either modify an existing class or add a new one.',
        stem: 'Which consideration should dominate?',
        options: [
          'Whichever requires fewer lines of code',
          'Whether the new behavior is part of the existing class\'s responsibility, since forcing unrelated behavior into a class is what creates the tangle in the first place',
          'Whichever is faster to type',
          'New classes should always be avoided',
        ],
        correct: 'B',
        why: {
          A: 'Line count is a poor proxy for design quality.',
          B: 'Correct. Responsibility is the question; size follows from it.',
          C: 'Typing effort is not a design criterion.',
          D: 'Adding a class is often exactly the right move.',
        },
      },
    ],
  },
  {
    lesson: '3.2', unit: 'unit-3',
    title: 'Impact of Program Design',
    blurb: 'Six scenarios on what a design decision costs later, once other code depends on it.',
    brief: 'These six are about consequences: what breaks for callers, what a change ripples into, and why some decisions are much harder to reverse than others.',
    seo: 'Applied AP CSA 3.2 practice: six scenario questions on the downstream impact of program design decisions.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A public method\'s parameter list is changed after twenty other classes already call it.',
        stem: 'What is the consequence?',
        options: [
          'Nothing, since Java updates callers automatically',
          'Every caller must be found and updated, which is why a public signature is a commitment rather than a detail',
          'Only the class itself needs changing',
          'The program still compiles and fails at run time',
        ],
        correct: 'B',
        why: {
          A: 'No such automatic update exists.',
          B: 'Correct, and it is the practical reason to keep as much as possible private.',
          C: 'The callers are the ones that break.',
          D: 'A signature mismatch is caught at compile time, which is the good case.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A class stores a temperature in Fahrenheit but exposes only getCelsius and setCelsius.',
        stem: 'What flexibility does that preserve?',
        options: [
          'None; the storage unit is fixed forever',
          'The internal unit can change later without any caller noticing, because no caller depends on how the value is stored',
          'Callers can access the Fahrenheit value directly',
          'The class becomes faster',
        ],
        correct: 'B',
        why: {
          A: 'The opposite: hiding the field is what keeps it changeable.',
          B: 'Correct. This is why accessors beat public fields even when they look like pure overhead.',
          C: 'That is precisely what the design prevents.',
          D: 'Speed is unaffected.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method returns a reference to the class\'s internal ArrayList.',
        stem: 'What has been given away?',
        options: [
          'Nothing; the caller only gets to read it',
          'Full mutation rights, since the caller holds the same object the class does and can add or remove behind its back',
          'A copy, so the class is protected',
          'The list becomes immutable',
        ],
        correct: 'B',
        why: {
          A: 'A reference carries every method the object has, including the mutating ones.',
          B: 'Correct. This is the leak that makes encapsulation look present while being absent.',
          C: 'Returning the field returns the reference, not a copy.',
          D: 'Nothing about returning it restricts modification.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'Two classes each hold a reference to the other and call each other\'s methods freely.',
        stem: 'What is the design cost?',
        options: [
          'None; this is normal',
          'Neither class can be understood, tested or reused without the other, because the coupling runs both ways',
          'The program will not compile',
          'It doubles memory use',
        ],
        correct: 'B',
        why: {
          A: 'It is legal but it is a known design smell.',
          B: 'Correct. Tight bidirectional coupling is what makes a codebase hard to change.',
          C: 'Mutual references compile fine.',
          D: 'Two references are negligible.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A constructor performs heavy work such as reading files and contacting a network.',
        stem: 'Why is that a questionable design?',
        options: [
          'Constructors cannot contain logic',
          'Creating an object becomes slow and failure prone, and callers cannot get an instance at all without paying that cost',
          'Constructors cannot throw exceptions',
          'It uses too much memory',
        ],
        correct: 'B',
        why: {
          A: 'Constructors may contain logic; the question is how much.',
          B: 'Correct. Construction is expected to be cheap, and coupling it to I/O removes the caller\'s choice.',
          C: 'Constructors can throw.',
          D: 'Memory is not the concern.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A programmer wants to add a field to a class that is already used across a large project.',
        stem: 'Why is adding a private field usually low risk?',
        options: [
          'Because private fields are ignored by the compiler',
          'Because nothing outside the class can refer to it, so no existing caller can break',
          'Because fields cannot cause bugs',
          'Because the class must be recompiled anyway',
        ],
        correct: 'B',
        why: {
          A: 'It is compiled normally.',
          B: 'Correct, and the contrast with changing a PUBLIC signature is the point of the topic.',
          C: 'It can certainly introduce bugs inside the class.',
          D: 'Recompilation is not what makes it safe.',
        },
      },
    ],
  },
  {
    lesson: '3.3', unit: 'unit-3',
    title: 'Anatomy of a Class',
    blurb: 'Six scenarios on fields, methods and the difference between a class and one of its objects.',
    brief: 'The exercise-1 editor asks you to write a class. These six ask what exists once per class versus once per object, which is the distinction every later topic builds on.',
    seo: 'Applied AP CSA 3.3 practice: six scenario questions on class structure, instance variables and objects.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'Three Dog objects are created from one Dog class, each with a different name.',
        stem: 'How many copies of the name field exist?',
        options: [
          'One, shared by all three',
          'Three, because each object carries its own copy of every instance variable',
          'None until a method is called',
          'Three, but they must all hold the same value',
        ],
        correct: 'B',
        why: {
          A: 'That describes a static variable, which is 3.7.',
          B: 'Correct. The class is the blueprint; the objects are what hold data.',
          C: 'Fields exist and hold defaults from the moment the object is created.',
          D: 'Independent copies can hold entirely different values.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A class declares private int count; and never assigns it in the constructor.',
        stem: 'What does a new object hold in count?',
        options: [
          'An unpredictable leftover value',
          '0, because instance variables receive default values automatically',
          'null',
          'The class does not compile',
        ],
        correct: 'B',
        why: {
          A: 'Java does not expose uninitialized memory. Local variables, unlike fields, must be assigned before use.',
          B: 'Correct: 0 for numeric types, false for boolean, null for references.',
          C: 'An int is never null.',
          D: 'Unassigned fields are legal.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A method needs a temporary value used only while it runs.',
        stem: 'Should that be an instance variable or a local variable?',
        options: [
          'An instance variable, so it persists',
          'A local variable, because the value is part of one computation rather than part of the object\'s state',
          'Either; there is no difference',
          'An instance variable, since methods cannot declare variables',
        ],
        correct: 'B',
        why: {
          A: 'Persisting it makes it visible to every other method and turns a private detail into shared state.',
          B: 'Correct. A field should represent something the object IS, not scratch space.',
          C: 'The difference is lifetime and visibility, both significant.',
          D: 'Methods declare local variables routinely.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A class defines a method but the program never creates an instance of the class.',
        stem: 'Can that instance method be called?',
        options: [
          'Yes, by using the class name',
          'No, because an instance method needs an object to act on and none exists',
          'Yes, automatically at program start',
          'Only if the method is private',
        ],
        correct: 'B',
        why: {
          A: 'Calling through the class name is how STATIC methods work, which is 3.7.',
          B: 'Correct. The object supplies the field values the method operates on.',
          C: 'Only main runs automatically.',
          D: 'Visibility does not remove the need for an instance.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'Two objects of the same class are compared with == after being given identical field values.',
        stem: 'What does the comparison report?',
        options: [
          'true, since their contents match',
          'false, because == asks whether they are the SAME object and these are two distinct ones',
          'A compile error',
          'true only if the class has no fields',
        ],
        correct: 'B',
        why: {
          A: 'Content comparison requires an equals method the class defines.',
          B: 'Correct, and it is the same reference-versus-content distinction that bites with Strings.',
          C: 'Comparing two references of the same type is legal.',
          D: 'Field count is irrelevant to reference identity.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A class has fields, a constructor, and several methods.',
        stem: 'What determines the ORDER these must appear in the file?',
        options: [
          'Fields must come first, then the constructor, then methods',
          'Nothing; Java does not require any particular order, though a consistent convention aids readability',
          'Methods must precede fields',
          'The constructor must be last',
        ],
        correct: 'B',
        why: {
          A: 'A widespread convention, but not a rule the compiler enforces.',
          B: 'Correct. Members may reference each other regardless of declaration order.',
          C: 'No such requirement exists.',
          D: 'The constructor may appear anywhere among the members.',
        },
      },
    ],
  },
  {
    lesson: '3.4', unit: 'unit-3',
    title: 'Constructors',
    blurb: 'Six scenarios on what a constructor is for, and the one that silently disappears the moment you write your own.',
    brief: 'The exercise-1 editor asks you to write constructors. These six ask what an object holds afterward, since the classic constructor bug leaves every field at its default and throws nothing.',
    seo: 'Applied AP CSA 3.4 practice: six scenario questions on constructors, overloading and the default constructor.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A class previously had no constructor. A programmer adds one that takes two parameters.',
        stem: 'What happens to code that called new MyClass() with no arguments?',
        options: [
          'It still works',
          'It stops compiling, because the no-argument default constructor is provided only when the class declares no constructor at all',
          'It works but leaves fields null',
          'It works only inside the same file',
        ],
        correct: 'B',
        why: {
          A: 'The default is withdrawn as soon as any constructor is declared.',
          B: 'Correct, and the fix is to declare the no-argument constructor explicitly if it is still wanted.',
          C: 'There is no constructor left to call.',
          D: 'Location does not affect which constructors exist.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A constructor takes a parameter named name and the class has a field also named name. The constructor body reads name = name;',
        stem: 'What is stored in the field?',
        options: [
          'The parameter value, as intended',
          'Nothing changes: both sides refer to the PARAMETER, so the field keeps its default of null',
          'The field value is copied to the parameter',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'That requires this.name on the left.',
          B: 'Correct, and this is the silent constructor bug: it compiles, runs, and leaves the object empty.',
          C: 'The assignment is parameter to parameter and has no effect at all.',
          D: 'Self-assignment of a parameter is legal.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A class declares two constructors with different parameter lists.',
        stem: 'How does Java decide which one runs?',
        options: [
          'The first one declared',
          'By matching the number and types of the arguments at the call, which is overload resolution',
          'The one with the most parameters',
          'It is ambiguous and will not compile',
        ],
        correct: 'B',
        why: {
          A: 'Declaration order does not select an overload.',
          B: 'Correct, and it is why two constructors cannot differ by parameter NAMES alone.',
          C: 'Parameter count matters only insofar as it matches the call.',
          D: 'Distinct parameter lists are exactly what makes overloading legal.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A constructor must validate that an age parameter is not negative.',
        stem: 'Why is the constructor the right place for that check?',
        options: [
          'It is not; validation belongs in a separate method',
          'Because it is the single entry point through which every object is created, so a rejected value can never enter an object at all',
          'Because constructors run faster than methods',
          'Because constructors cannot call other methods',
        ],
        correct: 'B',
        why: {
          A: 'A separate method can be skipped; the constructor cannot.',
          B: 'Correct. Enforcing an invariant at construction is what keeps it true for the object\'s whole life.',
          C: 'Speed is not a factor.',
          D: 'Constructors may call methods freely.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A programmer writes a method named the same as the class but gives it a void return type.',
        stem: 'What have they written?',
        options: [
          'A constructor',
          'An ordinary method that merely shares the class\'s name, so the class still has only its default constructor',
          'A compile error',
          'A static initializer',
        ],
        correct: 'B',
        why: {
          A: 'A constructor has NO return type, not even void. Adding one demotes it to a method.',
          B: 'Correct, and it is confusing precisely because it compiles.',
          C: 'It is legal, if inadvisable.',
          D: 'A static initializer is a static block with no name.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'One constructor needs to do everything another constructor does, plus set one more field.',
        stem: 'What is the cleanest approach?',
        options: [
          'Copy the shared assignments into both constructors',
          'Call the other constructor with this(...) as the first statement, so the shared setup exists in exactly one place',
          'Make one constructor static',
          'Have the second constructor create an object with new and copy from it',
        ],
        correct: 'B',
        why: {
          A: 'Duplicated setup drifts apart the moment one copy is edited.',
          B: 'Correct, and this(...) must be the first statement in the constructor.',
          C: 'Constructors cannot be static.',
          D: 'That creates a second, wasted object and does not initialize this one.',
        },
      },
    ],
  },
  {
    lesson: '3.5', unit: 'unit-3',
    title: 'Methods: How to Write Them',
    blurb: 'Six scenarios on signatures, return types, and the difference between printing a value and returning one.',
    brief: 'The exercise-1 editor asks you to write methods. These six ask what the CALLER receives, because a method that prints instead of returning is the most common way a correct calculation becomes unusable.',
    seo: 'Applied AP CSA 3.5 practice: six scenario questions on method signatures, parameters, and return values.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A method computes a total and prints it, declaring a void return type. The caller needs the total for further arithmetic.',
        stem: 'What is the problem?',
        options: [
          'Nothing; the caller can read the printed value',
          'A printed value goes to the console and is unavailable to the program, so the caller has no way to obtain the number',
          'void methods cannot perform arithmetic',
          'The method should be static',
        ],
        correct: 'B',
        why: {
          A: 'Output is for humans. The program cannot recover it.',
          B: 'Correct, and this is the single most common shape error in student methods.',
          C: 'void restricts only what comes back, not what happens inside.',
          D: 'Staticness is unrelated to returning a value.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method is declared to return int but one path through its body reaches the end without a return.',
        stem: 'What happens?',
        options: [
          'It returns 0 by default',
          'It does not compile, because every path through a non-void method must return a value',
          'It returns null',
          'It compiles and throws at run time',
        ],
        correct: 'B',
        why: {
          A: 'Fields have defaults; return paths do not.',
          B: 'Correct, and it usually appears when a return is placed inside an if without a matching else.',
          C: 'An int cannot be null, and the code never compiles anyway.',
          D: 'The compiler rejects it first, which is the helpful outcome.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A method takes an int parameter and modifies it inside the body. The caller then prints its own variable.',
        stem: 'What does the caller see?',
        options: [
          'The modified value',
          'The original value, because a primitive argument is passed by value and the method received a copy',
          'Zero',
          'A compile error',
        ],
        correct: 'B',
        why: {
          A: 'That would require reference semantics, which primitives do not have.',
          B: 'Correct, and the contrast with objects, where the copied REFERENCE still points at the caller\'s object, is 3.6.',
          C: 'Nothing zeroes the caller\'s variable.',
          D: 'Modifying a parameter is legal.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'Two methods in one class are named the same but take different parameter types.',
        stem: 'Is that legal?',
        options: [
          'No, method names must be unique',
          'Yes, this is overloading, and the signature is the name together with the parameter list',
          'Yes, but only if the return types also differ',
          'Only for constructors',
        ],
        correct: 'B',
        why: {
          A: 'Names may repeat when the parameter lists differ.',
          B: 'Correct, and note the return type is NOT part of the signature.',
          C: 'Differing return types alone are not enough and will not compile.',
          D: 'Ordinary methods overload just as constructors do.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A method has eight parameters.',
        stem: 'What does that usually indicate?',
        options: [
          'Nothing; parameter count is arbitrary',
          'That the method is probably doing too much, or that several parameters belong together as one object',
          'That the method must be static',
          'That Java will refuse to compile it',
        ],
        correct: 'B',
        why: {
          A: 'A long list is a reliable signal worth heeding.',
          B: 'Correct, and it also makes call sites easy to get wrong when the types repeat.',
          C: 'Parameter count has no bearing on staticness.',
          D: 'Java permits it.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method must report both a result and whether the operation succeeded.',
        stem: 'Which approach fits Java?',
        options: [
          'Return two values separated by a comma',
          'Return an object that carries both, or use a sentinel such as -1 where the value range makes it unambiguous',
          'Declare the method with two return types',
          'Print one and return the other',
        ],
        correct: 'B',
        why: {
          A: 'Java methods return exactly one value.',
          B: 'Correct, and a sentinel only works when it cannot be confused with a legitimate result.',
          C: 'A method has one return type.',
          D: 'Printing makes half the answer unavailable to the caller.',
        },
      },
    ],
  },
  {
    lesson: '3.6', unit: 'unit-3',
    title: 'Methods: Passing and Returning Object References',
    blurb: 'Six scenarios on what actually travels when an object is passed, and why the answer differs from primitives.',
    brief: 'This is the topic where "Java is pass by value" stops sounding like a contradiction. These six ask what the CALLER observes after a method runs.',
    seo: 'Applied AP CSA 3.6 practice: six scenario questions on passing and returning object references in Java.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A method receives an ArrayList parameter and calls add on it. The caller then prints its own list size.',
        stem: 'What does the caller see?',
        options: [
          'The original size, since the list was copied',
          'A size larger by one, because the copied reference points at the caller\'s own list object',
          'Zero',
          'A compile error',
        ],
        correct: 'B',
        why: {
          A: 'The REFERENCE is copied; the object is not.',
          B: 'Correct, and it is why passing a mutable object hands out real modification rights.',
          C: 'Nothing clears the list.',
          D: 'This is ordinary legal code.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method receives an object parameter and REASSIGNS it to a brand new object.',
        stem: 'What does the caller observe?',
        options: [
          'The caller now points at the new object',
          'No change, because reassigning the parameter only repoints the method\'s own copy of the reference',
          'A NullPointerException',
          'Both objects merge',
        ],
        correct: 'B',
        why: {
          A: 'That would require Java to pass the reference itself by reference, which it does not.',
          B: 'Correct. This is the precise sense in which Java is pass by value: the VALUE copied is the reference.',
          C: 'Nothing becomes null.',
          D: 'Objects do not merge.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A method returns a reference to an object the class holds in a private field.',
        stem: 'What can the caller do with it?',
        options: [
          'Only read it',
          'Anything the object permits, including mutating it, because the caller now holds the very same object the class does',
          'Nothing; the reference is a copy of the data',
          'Only compare it',
        ],
        correct: 'B',
        why: {
          A: 'The reference carries every public method, mutators included.',
          B: 'Correct, and returning a defensive copy is the fix when that is not wanted.',
          C: 'A reference is not a data copy.',
          D: 'Comparison is one option among many.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'Two variables are assigned the same object, then a method is called on one of them that changes a field.',
        stem: 'What does the other variable show?',
        options: [
          'The unchanged value',
          'The changed value, because both names refer to a single object',
          'null',
          'A copy made at assignment time',
        ],
        correct: 'B',
        why: {
          A: 'There is only one object to change.',
          B: 'Correct. Assignment between object variables copies the reference, not the object.',
          C: 'Neither reference becomes null.',
          D: 'No copy is made on assignment.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A method takes a String parameter and calls replace on it without assigning the result.',
        stem: 'Does the caller\'s String change?',
        options: [
          'Yes, because objects are passed by reference',
          'No, because String is immutable, so replace returns a new String and the original object is untouched',
          'Yes, but only for the first character',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'Even with a shared reference, an immutable object offers no mutating operation to call.',
          B: 'Correct, and it is why String feels like it behaves as a primitive when passed.',
          C: 'No characters change in the original.',
          D: 'Discarding a return value is legal.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A class wants to hand out its internal list without letting callers modify it.',
        stem: 'What is the standard approach?',
        options: [
          'Return the field and document that callers should not modify it',
          'Return a NEW list containing the same elements, so callers mutate the copy rather than the class\'s own data',
          'Make the method private',
          'Return null when the caller should not modify it',
        ],
        correct: 'B',
        why: {
          A: 'Documentation does not prevent anything.',
          B: 'Correct: a defensive copy. Note the ELEMENTS are still shared, so this protects the list structure rather than the objects in it.',
          C: 'A private method cannot serve outside callers at all.',
          D: 'Returning null forces every caller into a null check and provides no data.',
        },
      },
    ],
  },
  {
    lesson: '3.7', unit: 'unit-3',
    title: 'Class Variables and Methods',
    blurb: 'Six scenarios on static: what belongs to the class rather than to any object, and what static code is forbidden from touching.',
    brief: 'The exercise-1 editor asks you to use static members. These six ask which things are shared, since a static field changed by one object is changed for every object.',
    seo: 'Applied AP CSA 3.7 practice: six scenario questions on static variables, static methods and shared state.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A class has a static int counter incremented in its constructor. Four objects are created.',
        stem: 'What does counter hold?',
        options: [
          '1, since each object has its own',
          '4, because a static field exists once for the whole class and every constructor call incremented that one copy',
          '0',
          'It is unpredictable',
        ],
        correct: 'B',
        why: {
          A: 'Per-object copies are what instance variables give.',
          B: 'Correct, and counting instances is the textbook use of a static field.',
          C: 'Four increments occurred.',
          D: 'The behavior is fully determined.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A static method tries to read an instance variable of its own class.',
        stem: 'What happens?',
        options: [
          'It reads the value from the most recently created object',
          'It does not compile, because a static method runs without any object and so has no instance variable to read',
          'It reads 0',
          'It compiles and throws NullPointerException',
        ],
        correct: 'B',
        why: {
          A: 'Java tracks no such "most recent" object.',
          B: 'Correct. A static method can access instance data only through an object it is given.',
          C: 'There is no field for it to read.',
          D: 'The compiler rejects it before it can run.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'An instance method calls a static method of the same class.',
        stem: 'Is that allowed?',
        options: [
          'No, the directions are symmetric and both are forbidden',
          'Yes, because a static member needs no object, so anything with or without an object can reach it',
          'Only if the instance method is also static',
          'Only from the constructor',
        ],
        correct: 'B',
        why: {
          A: 'The restriction runs one way only.',
          B: 'Correct: instance to static is fine; static to instance needs an object.',
          C: 'That would make it a different kind of method.',
          D: 'Any instance method may do it.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A value is the same for every object of a class and never changes, such as a maximum size.',
        stem: 'How should it be declared?',
        options: [
          'As a private instance variable',
          'As a static final field, since one shared copy is enough and final documents that it never changes',
          'As a local variable in the constructor',
          'As a public instance variable',
        ],
        correct: 'B',
        why: {
          A: 'That stores an identical copy in every object for no reason.',
          B: 'Correct. This is exactly the case static final exists for.',
          C: 'A local variable disappears when the constructor ends.',
          D: 'Public mutable state on every object is the worst of the options.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A static field is used to hold data specific to one particular object.',
        stem: 'What goes wrong?',
        options: [
          'Nothing, provided only one object exists',
          'Every object shares the one field, so creating a second object overwrites the first object\'s data',
          'It does not compile',
          'The field becomes read-only',
        ],
        correct: 'B',
        why: {
          A: 'True only by accident, and it fails the moment a second object appears.',
          B: 'Correct, and the bug is silent: the first object simply starts reporting the second one\'s data.',
          C: 'It is legal, merely wrong.',
          D: 'static has nothing to do with mutability.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'main is declared static.',
        stem: 'Why must it be?',
        options: [
          'So it runs faster',
          'Because the JVM must call it before any object exists, and only a static method can be called without one',
          'Because it returns void',
          'Because it takes an array parameter',
        ],
        correct: 'B',
        why: {
          A: 'Speed is not the reason.',
          B: 'Correct, and it explains why calling an instance method directly from main fails.',
          C: 'The return type is unrelated to staticness.',
          D: 'The parameter type is unrelated too.',
        },
      },
    ],
  },
  {
    lesson: '3.8', unit: 'unit-3',
    title: 'Scope and Access',
    blurb: 'Six scenarios on where a name is visible, and what happens when a local variable hides a field.',
    brief: 'The exercise-1 editor asks you to apply access modifiers. These six ask which declaration a name actually refers to, because shadowing compiles cleanly and does the wrong thing.',
    seo: 'Applied AP CSA 3.8 practice: six scenario questions on variable scope, shadowing, and public versus private access.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A method declares a local variable with the same name as an instance variable, then assigns to that name.',
        stem: 'Which one is assigned?',
        options: [
          'The instance variable',
          'The local variable, because the innermost declaration shadows the field for the rest of that block',
          'Both',
          'Neither; it does not compile',
        ],
        correct: 'B',
        why: {
          A: 'Reaching the field then requires this.name.',
          B: 'Correct, and the field silently keeps its old value, which is the shadowing bug.',
          C: 'One name refers to exactly one declaration at a time.',
          D: 'Shadowing is legal.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A variable is declared inside a for loop body and used after the loop.',
        stem: 'What happens?',
        options: [
          'It holds its last value',
          'It does not compile, because the variable\'s scope ends with the block it was declared in',
          'It is null',
          'It is 0',
        ],
        correct: 'B',
        why: {
          A: 'The name no longer exists after the block.',
          B: 'Correct. Declaring it before the loop is the fix when the value must survive.',
          C: 'There is no variable left to hold anything.',
          D: 'Same reason.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A field is declared private and another class tries to read it directly.',
        stem: 'What is the result?',
        options: [
          'It reads successfully',
          'A compile error, because private restricts access to the declaring class',
          'It reads the default value',
          'It works only if the classes are in the same file',
        ],
        correct: 'B',
        why: {
          A: 'private is enforced by the compiler.',
          B: 'Correct, and a public accessor method is the intended route.',
          C: 'No read occurs at all.',
          D: 'Sharing a file does not grant private access across classes.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A helper method is used only inside its own class.',
        stem: 'What access modifier is appropriate?',
        options: [
          'public, so it can be tested',
          'private, because narrowing access keeps it free to change without affecting any outside caller',
          'It must have no modifier',
          'static, which controls access',
        ],
        correct: 'B',
        why: {
          A: 'Widening access to ease testing turns an internal detail into a commitment.',
          B: 'Correct. Default to the narrowest access that works.',
          C: 'No modifier means package access, which is broader than private.',
          D: 'static concerns object association, not visibility.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A constructor parameter shadows a field and the programmer wants to assign the parameter to the field.',
        stem: 'What is required?',
        options: [
          'Rename the parameter; there is no other way',
          'Qualify the field with this, as in this.name = name, which disambiguates the shadowed name',
          'Declare the field static',
          'Nothing; the assignment already works',
        ],
        correct: 'B',
        why: {
          A: 'Renaming works but is not required, and matching names are the convention.',
          B: 'Correct, and this is exactly why 3.9 exists as its own topic.',
          C: 'Making it static changes the design to solve a naming problem.',
          D: 'Unqualified, both sides are the parameter and the field is never touched.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'Two different methods each declare a local variable named temp.',
        stem: 'Do they conflict?',
        options: [
          'Yes, names must be unique within a class',
          'No, because each local variable exists only within its own method and the two never coexist',
          'Yes, unless one is static',
          'Only if they have the same type',
        ],
        correct: 'B',
        why: {
          A: 'Uniqueness is required within a scope, not across a class.',
          B: 'Correct. Independent scopes are what make short local names safe.',
          C: 'Locals cannot be static.',
          D: 'Type does not create or prevent a conflict.',
        },
      },
    ],
  },
  {
    lesson: '3.9', unit: 'unit-3',
    title: 'The this Keyword',
    blurb: 'Six scenarios on what this refers to and the one place it is mandatory rather than optional.',
    brief: 'The exercise-1 editor asks you to use this. These six ask when leaving it out changes the behavior, which is precisely when a name is shadowed.',
    seo: 'Applied AP CSA 3.9 practice: six scenario questions on the this keyword, shadowing, and constructor chaining.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'Inside an instance method, this is evaluated.',
        stem: 'What does it refer to?',
        options: [
          'The class itself',
          'The particular object the method was called on',
          'The most recently created object of the class',
          'The superclass',
        ],
        correct: 'B',
        why: {
          A: 'The class is not an object, and static members belong to it.',
          B: 'Correct. Two calls on two different objects see two different values of this.',
          C: 'Creation order plays no part.',
          D: 'That would be super.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method has no parameter or local sharing a name with a field, and it refers to that field without this.',
        stem: 'Is the code correct?',
        options: [
          'No, this is always required for fields',
          'Yes, because with nothing shadowing the name it resolves to the field anyway; this is optional there',
          'No, it will not compile',
          'Yes, but only in constructors',
        ],
        correct: 'B',
        why: {
          A: 'It is required only to break a shadow.',
          B: 'Correct, and some codebases still use it everywhere for consistency, which is a style choice.',
          C: 'It compiles and works.',
          D: 'The rule is the same in any instance method.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A setter is written as public void setAge(int age) { age = age; }',
        stem: 'What is the effect on the object?',
        options: [
          'The field is updated',
          'Nothing at all: both names refer to the parameter, so the field keeps its previous value',
          'The field is set to 0',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'That needs this.age on the left.',
          B: 'Correct, and it is silent. The setter appears to work and the getter keeps returning the old value.',
          C: 'The field is not touched, so it keeps whatever it held.',
          D: 'Self-assignment compiles, though many tools warn about it.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A constructor needs to invoke another constructor of the same class.',
        stem: 'What is the syntax and constraint?',
        options: [
          'new MyClass(...) anywhere in the body',
          'this(...) and it must be the first statement in the constructor',
          'super(...) at the end of the body',
          'It is not possible',
        ],
        correct: 'B',
        why: {
          A: 'That builds a separate object rather than initializing this one.',
          B: 'Correct. The first-statement rule ensures initialization happens exactly once and in order.',
          C: 'super calls a superclass constructor, and it too must come first.',
          D: 'Constructor chaining is standard.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A method returns this.',
        stem: 'What does that enable?',
        options: [
          'Nothing useful',
          'Chained calls, since the returned object is the same one the method was called on and another call can follow immediately',
          'Automatic copying of the object',
          'Static access to the method',
        ],
        correct: 'B',
        why: {
          A: 'It is a deliberate and common pattern.',
          B: 'Correct: returning this is what makes a fluent builder style possible.',
          C: 'No copy is made; it is the same object.',
          D: 'this is unavailable in static contexts entirely.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A programmer uses this inside a static method.',
        stem: 'What happens?',
        options: [
          'It refers to the class',
          'It does not compile, because a static method has no object for this to refer to',
          'It is null',
          'It refers to the first object created',
        ],
        correct: 'B',
        why: {
          A: 'There is no reference to the class available under that name.',
          B: 'Correct, and it is the same underlying reason a static method cannot read instance fields.',
          C: 'It has no value at all rather than a null one.',
          D: 'No such association exists.',
        },
      },
    ],
  },
];
