'use strict';
// ─────────────────────────────────────────────────────────────────────────────
//  CSA UNIT 2 EXERCISE 2 BANKS: APPLIED MCQ PRACTICE.
//
//  Six applied, scenario-based multiple choice questions per lesson, worth 6
//  points, matching the cross-course exercise-2 convention. See the header of
//  seed/csa-exercise-2/unit4.js for what an exercise 2 is and why every
//  rationale is written rather than only the correct one.
//
//  ALL TWELVE LESSONS. Unit 2 is the heaviest MCQ unit on the exam at roughly
//  30 percent, and it is where the silent wrong answer lives: a boolean or loop
//  bound that is off by one produces a plausible number rather than a crash, so
//  these questions lean on tracing and on what DISTINGUISHES two nearly
//  identical versions.
//
//  ANSWER LETTERS SKEW TO B ON PURPOSE. The renderer shuffles options
//  deterministically per question, so rendered pages are balanced; smoke
//  assertion 5.3 asserts the SOURCE skew because that is what proves the
//  shuffle is doing real work. Authoring varied letters here would turn 5.3
//  red while changing nothing a student sees.
//
//  Pure ASCII, no em-dashes. Zero PII: author content only.
// ─────────────────────────────────────────────────────────────────────────────

module.exports = [
  {
    lesson: '2.1', unit: 'unit-2',
    title: 'Algorithms with Selection and Repetition',
    blurb: 'Six scenarios on recognizing which control structure a problem actually needs before any code is written.',
    brief: 'The exercise-1 editor asks you to build an algorithm. These six ask you to pick the shape first, which is the decision that makes the rest either easy or impossible.',
    seo: 'Applied AP CSA 2.1 practice: six scenario questions on choosing selection and repetition for an algorithm.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A program must apply a discount only to orders over 50 dollars, and each order is processed once.',
        stem: 'Which control structure does this require?',
        options: [
          'Repetition, because a discount is applied repeatedly',
          'Selection, because the discount either applies or it does not and the order is handled once',
          'Both selection and repetition nested together',
          'Neither; sequence alone is enough',
        ],
        correct: 'B',
        why: {
          A: 'Nothing repeats. One order is examined one time.',
          B: 'Correct. A decision with no repeated work is exactly what selection is for.',
          C: 'Nesting solves a problem this scenario does not have.',
          D: 'Plain sequence cannot skip the discount for small orders.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program must keep prompting a user until they enter a valid password, with no fixed limit on attempts.',
        stem: 'Which structure fits?',
        options: [
          'A for loop, because the number of attempts is known',
          'A while loop, because the repetition continues on a condition rather than a known count',
          'An if statement, because the password is either valid or not',
          'A nested loop, one for characters and one for attempts',
        ],
        correct: 'B',
        why: {
          A: 'The attempt count is not known in advance, which is what a for loop assumes.',
          B: 'Correct. Condition-controlled repetition is the defining case for while.',
          C: 'An if checks once. It cannot re-prompt.',
          D: 'Nothing here iterates over characters.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'An algorithm must print a grade letter for each of exactly 30 students.',
        stem: 'What combination is needed?',
        options: [
          'Selection only, applied 30 times by hand',
          'Repetition over the 30 students with selection inside it to choose each letter',
          'Repetition only, since the letter follows from the score',
          'Neither, since 30 is a fixed number',
        ],
        correct: 'B',
        why: {
          A: 'Writing the decision out 30 times is what the loop exists to avoid.',
          B: 'Correct. A per-item decision inside a traversal is the most common structure in the course.',
          C: 'Choosing among letters is itself a decision and needs selection.',
          D: 'A fixed count is exactly when a for loop applies, not when repetition becomes unnecessary.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student claims that any algorithm using a while loop can be rewritten with a for loop.',
        stem: 'Is that accurate?',
        options: [
          'No, the two are fundamentally different in power',
          'Yes mechanically, since a for loop is a while loop with its three parts gathered into the header, but the for is only CLEARER when a count governs the repetition',
          'No, for loops cannot use a condition',
          'Yes, and the for loop is always preferable',
        ],
        correct: 'B',
        why: {
          A: 'They are interchangeable in capability.',
          B: 'Correct. The real distinction is which one states the intent, not which one can do the job.',
          C: 'The middle part of a for header IS a condition.',
          D: 'For an unknown number of attempts, a for loop obscures the intent.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'An algorithm must find whether ANY value in a list is negative.',
        stem: 'What is the minimum work required?',
        options: [
          'Examine every element, always',
          'Examine elements until a negative is found, then stop, because one example settles an existential claim',
          'Sort the list first, then check the front',
          'Count all the negatives and compare to zero',
        ],
        correct: 'B',
        why: {
          A: 'Only necessary when no negative exists.',
          B: 'Correct, and the mirror image is a universal claim, which is settled by one counterexample.',
          C: 'Sorting is far more work than a single scan.',
          D: 'Counting every negative computes more than the question asked.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'Two algorithms solve the same problem. One uses a single loop; the other uses a loop nested inside a loop.',
        stem: 'What does that structural difference usually signal?',
        options: [
          'The nested version is always wrong',
          'The nested version does substantially more work as the input grows, since its passes multiply rather than add',
          'The nested version uses more memory',
          'They perform identically',
        ],
        correct: 'B',
        why: {
          A: 'Nesting is required for genuinely two-dimensional problems.',
          B: 'Correct, and this is the intuition 2.12 formalizes as informal run-time analysis.',
          C: 'Nesting adds passes, not storage.',
          D: 'The difference grows with input size and can be dramatic.',
        },
      },
    ],
  },
  {
    lesson: '2.2', unit: 'unit-2',
    title: 'Boolean Expressions',
    blurb: 'Six scenarios on expressions that evaluate to true or false, and the operator that is not the one students reach for.',
    brief: 'The exercise-1 editor asks you to write conditions. These six ask what a condition actually evaluates to, and which comparison is legal for which type.',
    seo: 'Applied AP CSA 2.2 practice: six scenario questions on boolean expressions, relational operators, and equality.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A student writes if (x = 5) intending to test whether x equals 5.',
        stem: 'What happens?',
        options: [
          'It tests equality correctly',
          'It does not compile, because = assigns and an int assignment is not a boolean condition',
          'It compiles and is always true',
          'It compiles and is always false',
        ],
        correct: 'B',
        why: {
          A: 'Equality is ==. A single = is assignment.',
          B: 'Correct in Java specifically. In C this would compile and mislead; Java\'s type rule catches it.',
          C: 'There is no boolean value for the if to consume, so it never reaches a truth value.',
          D: 'Same reason: it fails at compile time rather than evaluating.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'Two String variables both hold the text "hello" but were built separately at run time.',
        stem: 'What does s1 == s2 report?',
        options: [
          'true, because the contents match',
          'Possibly false, because == compares references rather than contents, which is why .equals is required for Strings',
          'It does not compile',
          'Always false for any two Strings',
        ],
        correct: 'B',
        why: {
          A: 'Content matching is what .equals tests, not ==.',
          B: 'Correct, and "possibly" is the honest word: literals may be interned and compare true, which is what makes the bug intermittent.',
          C: '== is legal between two references; it just answers a different question.',
          D: 'Two references to the same object compare true.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A condition must be true when a value is outside the range 10 to 20 inclusive.',
        stem: 'Which expression is correct?',
        options: [
          'x < 10 && x > 20',
          'x < 10 || x > 20',
          '10 < x < 20',
          '!(x < 10 || x > 20)',
        ],
        correct: 'B',
        why: {
          A: 'No number is both below 10 and above 20, so this is always false.',
          B: 'Correct. "Outside" is a union of two regions, which is or.',
          C: 'Chained comparison does not compile in Java; the first comparison yields a boolean that cannot be compared to 20.',
          D: 'That is the negation, so it is true INSIDE the range.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A method returns a boolean and a student writes if (isReady() == true).',
        stem: 'What is the assessment?',
        options: [
          'It is required for correctness',
          'It is correct but redundant, since the method already produces the boolean the if needs',
          'It does not compile',
          'It inverts the result',
        ],
        correct: 'B',
        why: {
          A: 'The comparison adds nothing the if did not already have.',
          B: 'Correct, and the danger is the neighbouring typo: == true is harmless, while = true would be an assignment.',
          C: 'Comparing a boolean to a boolean literal is legal.',
          D: 'Comparing to true preserves the value.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A program compares two double values for exact equality with ==.',
        stem: 'Why is that risky?',
        options: [
          'Doubles cannot be compared at all',
          'Values computed by different routes can differ by a tiny rounding amount, so two logically equal results can compare unequal',
          '== always returns false for doubles',
          'Doubles must use .equals like Strings',
        ],
        correct: 'B',
        why: {
          A: 'Comparison is legal; exactness is what is unreliable.',
          B: 'Correct, and the usual fix is testing whether the difference is smaller than a small tolerance.',
          C: 'It returns true whenever the bit patterns match, which does happen.',
          D: 'double is a primitive and has no methods.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A condition must be true only when a number is even.',
        stem: 'Which test does that?',
        options: [
          'n / 2 == 0',
          'n % 2 == 0',
          'n % 2 == 1',
          'n * 2 == 0',
        ],
        correct: 'B',
        why: {
          A: 'Integer division by 2 is 0 only for n equal to 0 or 1, not for even numbers generally.',
          B: 'Correct. A remainder of 0 on division by 2 is the definition of even.',
          C: 'That tests odd, and it also fails for negative odd numbers, where the remainder is -1.',
          D: 'True only when n is 0.',
        },
      },
    ],
  },
  {
    lesson: '2.3', unit: 'unit-2',
    title: 'if Statements',
    blurb: 'Six scenarios on which branch actually runs, and the two punctuation habits that silently detach a body from its condition.',
    brief: 'The exercise-1 editor asks you to write branches. These six ask what runs when, because an if that compiles and does the wrong thing never announces itself.',
    seo: 'Applied AP CSA 2.3 practice: six scenario questions on if, else, else if and branch selection.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A student writes if (score > 90); then a print statement on the next line, indented.',
        stem: 'What does the print statement do?',
        options: [
          'It runs only when score is above 90',
          'It runs every time, because the semicolon ends the if with an empty body and the indented line is simply the next statement',
          'It never runs',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'The empty statement is the entire body of the if.',
          B: 'Correct, and indentation is the trap: it shows the intent while the semicolon decides the behavior.',
          C: 'It runs unconditionally, not never.',
          D: 'An empty statement is legal, which is exactly why this is dangerous.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A grading chain is written as three separate if statements: if (s >= 90) A, if (s >= 80) B, if (s >= 70) C.',
        stem: 'What does a score of 95 print?',
        options: [
          'Only A',
          'A, B and C, because each independent if is evaluated and 95 satisfies all three',
          'Only C',
          'Nothing',
        ],
        correct: 'B',
        why: {
          A: 'That would require else if, which makes the tests mutually exclusive.',
          B: 'Correct. Independent ifs do not know about each other.',
          C: 'All three run, not just the last.',
          D: 'All three conditions are true for 95.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'The same grading chain is rewritten with else if, but ordered lowest threshold first: if (s >= 70) C, else if (s >= 80) B, else if (s >= 90) A.',
        stem: 'What does a score of 95 print?',
        options: [
          'A, the correct grade',
          'C, because the first true test wins and 95 satisfies the 70 test before the others are ever considered',
          'Nothing, since the order is invalid',
          'B',
        ],
        correct: 'B',
        why: {
          A: 'The A branch is never reached.',
          B: 'Correct. An else if chain must run from most restrictive to least, and this is the bug that ordering causes.',
          C: 'The code is perfectly legal; it is just wrong.',
          D: 'The chain stops at the first true test, which is C.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A student omits braces and writes an if followed by two indented statements.',
        stem: 'What is the effect?',
        options: [
          'Both statements are conditional',
          'Only the first statement is conditional; the second runs unconditionally',
          'Neither statement runs',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'Without braces, the body is exactly one statement.',
          B: 'Correct, and this is the second silent detachment after the stray semicolon.',
          C: 'The first still runs when the condition holds.',
          D: 'A braceless single-statement body is legal.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'Two versions of a method differ only in that one uses if/else and the other uses two independent ifs with opposite conditions.',
        stem: 'When do they behave differently?',
        options: [
          'Never; they are equivalent',
          'When the first branch MODIFIES the value being tested, since the second if re-evaluates the changed value while else does not',
          'Only when the conditions are compound',
          'Only on negative inputs',
        ],
        correct: 'B',
        why: {
          A: 'They are equivalent only while the tested value is untouched.',
          B: 'Correct. This is the real distinction and it is easy to miss when reading quickly.',
          C: 'Compound conditions behave the same way in both forms.',
          D: 'Sign has nothing to do with it.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method must return "positive", "negative" or "zero" for an int.',
        stem: 'How many conditions are strictly required?',
        options: [
          'Three, one per outcome',
          'Two, because the third case is whatever remains after both tests fail and belongs in the else',
          'One, using a compound expression',
          'Four, to include a default',
        ],
        correct: 'B',
        why: {
          A: 'Testing the third case is redundant work that also risks a gap if the tests disagree.',
          B: 'Correct. A final else is exhaustive by construction and cannot leave a value unhandled.',
          C: 'One condition can only split the values two ways.',
          D: 'Three outcomes need at most two tests.',
        },
      },
    ],
  },
  {
    lesson: '2.4', unit: 'unit-2',
    title: 'Nested if Statements',
    blurb: 'Six scenarios on which if an else belongs to, and when nesting is the same as an and.',
    brief: 'The exercise-1 editor asks you to nest. These six ask what the nesting means, since a dangling else attaches by rule rather than by indentation.',
    seo: 'Applied AP CSA 2.4 practice: six scenario questions on nested if statements and the dangling else.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'Code reads: if (a) if (b) doX(); else doY(); with no braces.',
        stem: 'Which if owns the else?',
        options: [
          'The outer if, matching the indentation a student would write',
          'The inner if, because an else always binds to the nearest unmatched if regardless of layout',
          'Neither; this does not compile',
          'Both, in sequence',
        ],
        correct: 'B',
        why: {
          A: 'Indentation carries no meaning to the compiler.',
          B: 'Correct. This is the dangling else, and braces are the only reliable fix.',
          C: 'It compiles cleanly, which is what makes it a trap.',
          D: 'An else belongs to exactly one if.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A program must act only when a user is both logged in AND an administrator, with no other branches.',
        stem: 'What is true of nesting versus a compound condition?',
        options: [
          'Only nesting can express this',
          'They are equivalent here, so the compound && version is preferable for being flatter and reading as one requirement',
          'Only the compound version can express this',
          'They differ in result',
        ],
        correct: 'B',
        why: {
          A: 'A single && expresses the same requirement.',
          B: 'Correct. Nesting earns its place when the two levels need DIFFERENT else branches.',
          C: 'Nesting expresses it too; it is just wordier.',
          D: 'With no else branches, the outcomes are identical.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'An outer if tests age >= 18 and an inner if tests hasLicense, with an else on the inner if printing "needs a license".',
        stem: 'What does a 15 year old with a license see?',
        options: [
          '"needs a license"',
          'Nothing, because the outer condition fails and nothing inside it, including its else, is ever reached',
          'An error',
          'Both branches',
        ],
        correct: 'B',
        why: {
          A: 'That else lives inside the outer if and is unreachable when the outer test fails.',
          B: 'Correct, and it is the usual cause of "why does my program print nothing".',
          C: 'No error occurs; the block is simply skipped.',
          D: 'Neither inner branch is reached.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A decision has three levels of nesting and the deepest branch is the common case.',
        stem: 'What restructuring usually helps?',
        options: [
          'Add more nesting for clarity',
          'Invert the outer tests and return early on the exceptional cases, so the common path ends up unindented',
          'Combine every level into one compound condition regardless of the else branches',
          'Replace the ifs with a loop',
        ],
        correct: 'B',
        why: {
          A: 'Depth is the problem, not the solution.',
          B: 'Correct. Guard clauses trade nesting depth for a flat main path.',
          C: 'Flattening is right in spirit but loses behavior when the levels have distinct elses.',
          D: 'Repetition is unrelated to a decision.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student adds braces to a nested if/else without changing any condition, and the program\'s output changes.',
        stem: 'What does that prove?',
        options: [
          'Braces alter how conditions are evaluated',
          'The else had been binding to a different if than intended, and the braces corrected the association',
          'The program was not compiled before',
          'Braces introduced a bug',
        ],
        correct: 'B',
        why: {
          A: 'Braces group statements; they do not change evaluation.',
          B: 'Correct, and a behavior change on adding braces is the definitive symptom of a dangling else.',
          C: 'It compiled and ran both times.',
          D: 'The braces revealed the bug rather than causing it.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A nested structure must classify a number as positive-even, positive-odd, or non-positive.',
        stem: 'What is the cleanest arrangement?',
        options: [
          'Three independent ifs testing all three conditions',
          'An outer if on positivity, with an inner if/else on evenness, and an outer else for non-positive',
          'One compound condition with three ands',
          'A loop over the three cases',
        ],
        correct: 'B',
        why: {
          A: 'Independent tests repeat the positivity check and can disagree after an edit.',
          B: 'Correct. The nesting mirrors the structure of the classification itself.',
          C: 'A single expression cannot produce three distinct outcomes.',
          D: 'There is nothing to repeat.',
        },
      },
    ],
  },
  {
    lesson: '2.5', unit: 'unit-2',
    title: 'Compound Boolean Expressions',
    blurb: 'Six scenarios on and, or, not, and the short circuit that is doing more work than students think.',
    brief: 'The exercise-1 editor asks you to combine conditions. These six ask what gets evaluated and what deliberately does not, because short circuiting is a correctness feature and not just a speed one.',
    seo: 'Applied AP CSA 2.5 practice: six scenario questions on compound boolean expressions, short circuit evaluation and De Morgan.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A condition reads: if (s != null && s.length() > 0).',
        stem: 'Why does the order of the two tests matter?',
        options: [
          'It does not matter; && is commutative',
          'If the null check came second, calling length() on a null reference would throw before the null check ever ran; && stops as soon as the left side is false',
          'Because length() is slower than a null check',
          'Because != binds tighter than &&',
        ],
        correct: 'B',
        why: {
          A: 'The VALUES commute but the evaluation does not, which is the whole point.',
          B: 'Correct. Short circuiting is what makes this idiom safe, not merely fast.',
          C: 'Speed is irrelevant; the concern is an exception.',
          D: 'Precedence is real but is not what protects against the null.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method with a side effect is called on the right side of a || whose left side is true.',
        stem: 'Does the side effect happen?',
        options: [
          'Yes, both sides always evaluate',
          'No, because || stops once the left side is true and the right side is never evaluated',
          'Yes, but only after the if body runs',
          'It depends on the compiler',
        ],
        correct: 'B',
        why: {
          A: 'That would be true of the non-short-circuit operator |, which is not what is used here.',
          B: 'Correct, and hiding a needed side effect inside a condition is how this becomes a real bug.',
          C: 'The condition is fully resolved before the body runs.',
          D: 'Short circuiting is guaranteed by the language, not left to the implementation.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A student needs the negation of (x > 5 && y < 10).',
        stem: 'Which expression is equivalent?',
        options: [
          'x < 5 && y > 10',
          'x <= 5 || y >= 10',
          'x < 5 || y > 10',
          'x <= 5 && y >= 10',
        ],
        correct: 'B',
        why: {
          A: 'Both errors at once: the and should become or, and the negations drop the equality boundary.',
          B: 'Correct. De Morgan flips the connective and negates each side, and the negation of > is <=.',
          C: 'Right connective, but < 5 and > 10 miss the boundary values 5 and 10.',
          D: 'Correct negations, wrong connective.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A condition must be true when exactly one of two booleans is true, never both.',
        stem: 'Which expression works?',
        options: [
          'a && b',
          '(a || b) && !(a && b)',
          'a || b',
          '!(a || b)',
        ],
        correct: 'B',
        why: {
          A: 'True only when both hold, the opposite of what is wanted.',
          B: 'Correct: at least one, and not both. The != operator on booleans expresses the same thing.',
          C: 'Also true when both are true.',
          D: 'True only when neither holds.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student writes if (day == "Sat" || "Sun") intending to test for a weekend.',
        stem: 'What is wrong?',
        options: [
          'Nothing; this is valid',
          'The right side of || must itself be a boolean, but "Sun" is a String, so it does not compile; the comparison has to be repeated in full',
          'It compiles but is always true',
          'It should use && instead',
        ],
        correct: 'B',
        why: {
          A: 'The operand types are wrong.',
          B: 'Correct. Each side of a logical operator must be a complete boolean expression.',
          C: 'It never reaches a truth value.',
          D: 'Requiring both days at once would be worse, and it still would not compile.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A compound condition mixes && and || without parentheses: a || b && c.',
        stem: 'How is it grouped?',
        options: [
          'Left to right, as (a || b) && c',
          'As a || (b && c), because && has higher precedence than ||',
          'It does not compile without parentheses',
          'The grouping is undefined',
        ],
        correct: 'B',
        why: {
          A: 'Precedence, not left-to-right order, decides the grouping here.',
          B: 'Correct, and parenthesizing anyway is the habit worth having since the reader should not need the table.',
          C: 'It compiles; precedence resolves it.',
          D: 'It is fully specified by the language.',
        },
      },
    ],
  },
  {
    lesson: '2.6', unit: 'unit-2',
    title: 'Comparing Boolean Expressions',
    blurb: 'Six scenarios on proving two conditions are the same, and the single input that shows they are not.',
    brief: 'The exercise-1 editor asks you to simplify conditions. These six ask how you KNOW a simplification is safe, which is a truth table or a counterexample and never an impression.',
    seo: 'Applied AP CSA 2.6 practice: six scenario questions on equivalent boolean expressions and truth tables.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A student claims !(a && b) is the same as !a && !b.',
        stem: 'What settles the claim fastest?',
        options: [
          'Testing with a true and b true',
          'Testing with a true and b false, where the first is true and the second is false',
          'Reading the expressions aloud',
          'Testing with a false and b false',
        ],
        correct: 'B',
        why: {
          A: 'Both are false there, so it agrees and proves nothing.',
          B: 'Correct. One disagreeing row refutes an equivalence, and mixed inputs are where these two diverge.',
          C: 'Intuition is what produced the wrong claim.',
          D: 'Both are true there; another agreeing row.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'Two conditions agree on three of the four rows of a two-variable truth table.',
        stem: 'What follows?',
        options: [
          'They are equivalent, since they mostly agree',
          'They are not equivalent, because equivalence requires agreement on every row without exception',
          'They are equivalent for practical purposes',
          'More variables are needed to decide',
        ],
        correct: 'B',
        why: {
          A: 'Equivalence is not a majority vote.',
          B: 'Correct, and the disagreeing row is exactly the input that will eventually reach production.',
          C: '"Practical purposes" is how the disagreeing case ships.',
          D: 'Four rows fully cover two booleans.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A condition reads if (x) { return true; } else { return false; }',
        stem: 'What is the simplification?',
        options: [
          'return !x;',
          'return x;',
          'return x == true;',
          'It cannot be simplified',
        ],
        correct: 'B',
        why: {
          A: 'That inverts the result.',
          B: 'Correct. The if is doing nothing but restating the boolean it was handed.',
          C: 'Equivalent but still redundant.',
          D: 'It reduces to a single expression.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A three-variable condition is claimed equivalent to a shorter one.',
        stem: 'How many rows must a complete truth table check?',
        options: [
          'Three, one per variable',
          'Eight, since each of three independent booleans doubles the number of combinations',
          'Six',
          'Four',
        ],
        correct: 'B',
        why: {
          A: 'Rows enumerate combinations, not variables.',
          B: 'Correct: two to the third power.',
          C: 'Six matches no power of two.',
          D: 'Four covers two variables, not three.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'Two expressions are equivalent in truth value, but one calls a method with a side effect that the other short circuits away.',
        stem: 'Are they interchangeable in a program?',
        options: [
          'Yes, equivalent truth values make them interchangeable',
          'No, because a program is affected by what actually executes, not only by the value the condition produces',
          'Yes, provided the method is fast',
          'No, because they cannot be truth-equivalent at all',
        ],
        correct: 'B',
        why: {
          A: 'This is the trap: logical equivalence does not imply behavioral equivalence.',
          B: 'Correct, and it is why side effects belong outside conditions.',
          C: 'Speed does not restore a skipped side effect.',
          D: 'They genuinely can be truth-equivalent; that is the premise.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A condition reads !(x <= 10).',
        stem: 'What is the direct equivalent?',
        options: [
          'x < 10',
          'x > 10',
          'x >= 10',
          'x != 10',
        ],
        correct: 'B',
        why: {
          A: 'Excludes values above 10, which the original includes.',
          B: 'Correct. The negation of "at most 10" is "more than 10".',
          C: 'Wrongly includes 10 itself, which the original excludes.',
          D: 'Would include values below 10.',
        },
      },
    ],
  },
  {
    lesson: '2.7', unit: 'unit-2',
    title: 'while Loops',
    blurb: 'Six scenarios on what makes a loop stop, and the three separate ways one fails to.',
    brief: 'The exercise-1 editor asks you to write a while loop. These six ask what advances it toward termination, since a loop that never ends produces no output to debug from.',
    seo: 'Applied AP CSA 2.7 practice: six scenario questions on while loops, termination and infinite loops.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A while loop reads a value from input and never modifies its own counter inside the body.',
        stem: 'Under what condition does it still terminate?',
        options: [
          'It never terminates',
          'It terminates if the condition depends on the input rather than the counter, since something the loop reads can still change',
          'It terminates only after 100 iterations',
          'It terminates immediately',
        ],
        correct: 'B',
        why: {
          A: 'Too strong. Progress can come from outside the loop body.',
          B: 'Correct. What matters is that SOMETHING in the condition changes, not specifically a counter.',
          C: 'Java imposes no iteration limit.',
          D: 'It runs as long as the condition holds.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A sentinel loop should stop when the user enters -1, written as while (input != -1).',
        stem: 'Where must the next read happen?',
        options: [
          'Only before the loop, so the condition has a value',
          'Before the loop AND at the end of each iteration, so the condition tests a fresh value every time',
          'Only at the end of the body',
          'Inside the condition itself',
        ],
        correct: 'B',
        why: {
          A: 'Then the condition tests the same value forever.',
          B: 'Correct. The priming read plus the update read is the standard sentinel shape.',
          C: 'The first test would run against an uninitialized or stale value.',
          D: 'Reading inside a condition is legal in some languages but obscures the flow and is not the taught pattern.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A loop is written while (i < 10) with i incremented by 2 starting from 1.',
        stem: 'How many times does the body run?',
        options: [
          'Ten',
          'Five, for i equal to 1, 3, 5, 7 and 9',
          'Four',
          'Nine',
        ],
        correct: 'B',
        why: {
          A: 'Ten would require a step of 1 from 0.',
          B: 'Correct: the odd values below 10.',
          C: 'Undercounts by one; 9 is still less than 10.',
          D: 'That counts every value, not every other one.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A loop must run at least once before its condition is checked.',
        stem: 'Which structure fits?',
        options: [
          'A while loop with the condition set to true',
          'A do-while loop, which places the test after the body',
          'A for loop with no initializer',
          'An if statement inside a while',
        ],
        correct: 'B',
        why: {
          A: 'That never stops without an added break.',
          B: 'Correct. Guaranteed first execution is exactly what do-while provides.',
          C: 'A for loop still tests before the first pass.',
          D: 'That adds a decision without changing when the loop tests.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A while loop\'s condition compares a double accumulated by repeated addition against an exact value.',
        stem: 'Why might it fail to terminate?',
        options: [
          'Doubles cannot be used in conditions',
          'Accumulated rounding can make the value step over the target without ever equalling it, so an equality test never becomes false',
          'The loop runs too fast',
          'Doubles are always exact',
        ],
        correct: 'B',
        why: {
          A: 'They can; exact equality is the unreliable part.',
          B: 'Correct, and the fix is a relational test rather than an equality test.',
          C: 'Speed has no bearing on termination.',
          D: 'Binary floating point cannot represent many decimal values exactly.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A loop should stop early when a condition is met, but the surrounding method must still run cleanup afterward.',
        stem: 'What is the appropriate mechanism?',
        options: [
          'return, exiting the method immediately',
          'break, which leaves the loop but continues with the statements after it',
          'continue, which skips to the next iteration',
          'System.exit',
        ],
        correct: 'B',
        why: {
          A: 'Returning skips the cleanup the method still owes.',
          B: 'Correct. break exits the loop only.',
          C: 'continue keeps looping rather than leaving.',
          D: 'That terminates the whole program.',
        },
      },
    ],
  },
  {
    lesson: '2.8', unit: 'unit-2',
    title: 'for Loops',
    blurb: 'Six scenarios on the three parts of a for header and exactly how many times the body runs.',
    brief: 'The exercise-1 editor asks you to write for loops. These six are mostly counting, because off-by-one is the error that survives testing on the happy path.',
    seo: 'Applied AP CSA 2.8 practice: six scenario questions on for loop headers, iteration counts and off-by-one errors.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A loop reads for (int i = 1; i <= n; i++).',
        stem: 'How many times does the body execute?',
        options: [
          'n - 1',
          'n, for i taking every value from 1 through n inclusive',
          'n + 1',
          'It depends on the body',
        ],
        correct: 'B',
        why: {
          A: 'That would be the count for i < n.',
          B: 'Correct. Starting at 1 with <= n gives exactly n passes.',
          C: 'That would need starting at 0 with <= n.',
          D: 'The body cannot change the count unless it alters i or breaks.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A loop reads for (int i = 0; i < n; i++) and a student changes < to <=.',
        stem: 'What is the consequence when the body indexes an array of length n?',
        options: [
          'One fewer iteration',
          'One extra iteration that accesses index n and throws ArrayIndexOutOfBoundsException',
          'No change',
          'The loop becomes infinite',
        ],
        correct: 'B',
        why: {
          A: 'The change adds a pass rather than removing one.',
          B: 'Correct, and it is the single most common runtime error in the course.',
          C: 'The iteration count changes by one.',
          D: 'It still terminates, just one pass too late.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A for loop declares its counter in the header: for (int i = 0; ...).',
        stem: 'What is true after the loop finishes?',
        options: [
          'i holds the final value and is usable',
          'i is out of scope, because a counter declared in the header exists only within the loop',
          'i is automatically reset to 0',
          'i becomes null',
        ],
        correct: 'B',
        why: {
          A: 'That requires declaring i before the loop.',
          B: 'Correct, and needing the final value is the usual reason to declare it outside.',
          C: 'Nothing resets it; it simply ceases to exist.',
          D: 'An int is never null.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A for loop is written with an empty condition: for (int i = 0; ; i++).',
        stem: 'What happens?',
        options: [
          'It does not compile',
          'It compiles and loops forever, since an omitted condition is treated as true',
          'It runs exactly once',
          'It runs zero times',
        ],
        correct: 'B',
        why: {
          A: 'All three header parts are optional.',
          B: 'Correct, and it is only useful with a break inside.',
          C: 'Nothing stops it after one pass.',
          D: 'A missing condition never blocks entry.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A loop counts down: for (int i = n; i > 0; i--).',
        stem: 'Which values does i take in the body?',
        options: [
          'n through 0 inclusive',
          'n down to 1, stopping before 0',
          'n - 1 down to 0',
          'Only n',
        ],
        correct: 'B',
        why: {
          A: 'The condition i > 0 excludes 0.',
          B: 'Correct: n passes, ending at 1.',
          C: 'The loop starts at n, not n - 1.',
          D: 'It decrements through the whole range.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A student modifies the loop counter inside the body of a for loop as well as in the header.',
        stem: 'What is the risk?',
        options: [
          'It does not compile',
          'The iteration count no longer follows from the header, so the loop can skip values or fail to terminate',
          'The header increment is ignored',
          'The loop always runs twice as often',
        ],
        correct: 'B',
        why: {
          A: 'It is legal, which is why it is a hazard rather than an error.',
          B: 'Correct. The header stops being a reliable summary of what the loop does.',
          C: 'Both updates apply, compounding each other.',
          D: 'The effect depends entirely on what the body does.',
        },
      },
    ],
  },
  {
    lesson: '2.9', unit: 'unit-2',
    title: 'Implementing Selection and Iteration Algorithms',
    blurb: 'Six scenarios on the standard accumulate-and-decide algorithms, and where the accumulator has to live.',
    brief: 'The exercise-1 editor asks you to implement these. These six ask what breaks when a variable is declared one level too deep or seeded with the wrong constant.',
    seo: 'Applied AP CSA 2.9 practice: six scenario questions on counting, summing, and min-max algorithms with loops.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A counting loop declares int count = 0; INSIDE the loop body.',
        stem: 'What does it report?',
        options: [
          'The correct total',
          'At most 1, because the counter is recreated and reset on every iteration',
          'Zero always',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'A total requires the variable to survive the iteration.',
          B: 'Correct: it can be incremented once within a pass but never carries forward.',
          C: 'It reaches 1 whenever a match occurs on the final pass.',
          D: 'Declaring inside a loop is legal.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A loop must report the smallest value in a list of temperatures that can be below zero.',
        stem: 'How should the running minimum be seeded?',
        options: [
          'With 0',
          'With the first element, so no assumption is made about the range of the data',
          'With -1',
          'With the length of the list',
        ],
        correct: 'B',
        why: {
          A: 'Any all-positive list then wrongly reports 0.',
          B: 'Correct, and it requires the list to be non-empty, which is a check worth making explicit.',
          C: 'Same defect as 0, shifted by one.',
          D: 'A count is not a temperature.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A loop computes a running average by dividing the sum by the count INSIDE the loop.',
        stem: 'What is the effect?',
        options: [
          'The final answer is wrong',
          'The final answer is right but the division is repeated needlessly on every pass',
          'The loop does not terminate',
          'The sum is corrupted',
        ],
        correct: 'B',
        why: {
          A: 'The last computed value is the correct overall average.',
          B: 'Correct, assuming the division result is not fed back into the sum. It is wasteful rather than wrong.',
          C: 'Division does not affect the loop bound.',
          D: 'Dividing into a separate variable leaves the sum untouched.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method must count values that satisfy a condition AND report their total.',
        stem: 'How many passes over the data are needed?',
        options: [
          'Two, one for each result',
          'One, since both accumulators can be updated in the same iteration',
          'As many as there are matches',
          'Three',
        ],
        correct: 'B',
        why: {
          A: 'A second pass repeats work already available in the first.',
          B: 'Correct. Independent accumulators share a traversal freely.',
          C: 'The pass count does not depend on how many match.',
          D: 'Two results do not require three passes.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A loop sets a boolean flag when it finds a match, then checks the flag after the loop.',
        stem: 'When is that preferable to returning immediately?',
        options: [
          'Always; flags are cleaner',
          'When work still has to happen after the search, such as counting every match or running cleanup',
          'Never; returning is always better',
          'Only when the list is sorted',
        ],
        correct: 'B',
        why: {
          A: 'For a pure existence check, an immediate return is simpler and stops early.',
          B: 'Correct. The flag earns its place when the traversal must complete anyway.',
          C: 'Returning early cannot finish work the method still owes.',
          D: 'Ordering is irrelevant to the choice.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method must return the index of the first match, or -1 when nothing matches.',
        stem: 'Where does the -1 belong?',
        options: [
          'Inside the loop, in an else branch',
          'After the loop, since reaching that point means every element was examined without a match',
          'Before the loop, as the initial return',
          'It is not needed',
        ],
        correct: 'B',
        why: {
          A: 'An else inside the loop returns -1 on the very first non-match, ending the search prematurely.',
          B: 'Correct. Loop completion is itself the proof that nothing matched.',
          C: 'Returning before the loop means it never runs.',
          D: 'Without it the method has no value to return on the no-match path and will not compile.',
        },
      },
    ],
  },
  {
    lesson: '2.10', unit: 'unit-2',
    title: 'Implementing String Algorithms',
    blurb: 'Six scenarios on traversing text, and the fact that a String cannot be changed no matter what a method appears to do to it.',
    brief: 'The exercise-1 editor asks you to process Strings. These six ask what substring actually returns and why an unassigned String method call accomplishes nothing.',
    seo: 'Applied AP CSA 2.10 practice: six scenario questions on String traversal, substring, indexOf and immutability.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A program calls s.toUpperCase(); on its own line and then prints s.',
        stem: 'What is printed?',
        options: [
          'The uppercase version',
          'The original text unchanged, because Strings are immutable and the method returns a NEW String that was discarded',
          'An empty string',
          'A compile error',
        ],
        correct: 'B',
        why: {
          A: 'That requires assigning the result back to s.',
          B: 'Correct. Every String method returns a new object and never modifies the receiver.',
          C: 'Nothing empties the original.',
          D: 'Discarding a return value is legal.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'Given String s = "computer", evaluate s.substring(2, 5).',
        stem: 'What is the result?',
        options: [
          '"ompu"',
          '"mpu"',
          '"mput"',
          '"omp"',
        ],
        correct: 'B',
        why: {
          A: 'That starts at index 1 rather than 2.',
          B: 'Correct: begins at index 2 inclusive, ends at index 5 exclusive, giving indices 2, 3 and 4.',
          C: 'That would be substring(2, 6), treating the end as inclusive.',
          D: 'That starts at index 1 and takes three characters.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A loop traverses a String with for (int i = 0; i <= s.length(); i++) and calls s.charAt(i).',
        stem: 'What happens?',
        options: [
          'It works correctly',
          'It throws StringIndexOutOfBoundsException on the final pass, since valid indices stop at length() - 1',
          'It skips the last character',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'It runs one pass too many.',
          B: 'Correct. Same off-by-one as arrays, with a String-specific exception name.',
          C: 'Every character is visited and then one more position that does not exist.',
          D: 'The bounds are checked at run time.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method must report whether a String contains a given character.',
        stem: 'What does indexOf return when the character is absent?',
        options: [
          '0',
          '-1, which is why the result must be compared against -1 rather than treated as a boolean',
          'null',
          'The length of the String',
        ],
        correct: 'B',
        why: {
          A: '0 is a valid position, meaning found at the very start.',
          B: 'Correct, and confusing 0 with "not found" is the classic error here.',
          C: 'It returns an int, which is never null.',
          D: 'Length is not used as a sentinel.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A loop builds a result by repeatedly doing result = result + ch; over a long String.',
        stem: 'What is the hidden cost?',
        options: [
          'None; concatenation is free',
          'Each concatenation creates a whole new String and copies the old contents, so the work grows sharply with length',
          'The result is incorrect',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'Immutability means every step allocates.',
          B: 'Correct, and it is why StringBuilder exists, though the pattern is still fine for short strings.',
          C: 'The output is right; only the cost is a problem.',
          D: 'It is ordinary legal code.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A method must compare two Strings for identical contents.',
        stem: 'Which comparison is correct?',
        options: [
          's1 == s2',
          's1.equals(s2)',
          's1 > s2',
          's1.substring(s2)',
        ],
        correct: 'B',
        why: {
          A: 'Compares references, so it can be false for equal contents.',
          B: 'Correct. compareTo serves when an ORDERING rather than equality is needed.',
          C: 'Relational operators do not apply to objects.',
          D: 'substring takes indices, not a String, and does not compare.',
        },
      },
    ],
  },
  {
    lesson: '2.11', unit: 'unit-2',
    title: 'Nested Iteration',
    blurb: 'Six scenarios on loops inside loops: how many times the inner body runs, and which variable controls what.',
    brief: 'The exercise-1 editor asks you to nest loops. These six ask you to count total iterations and to spot the initialization that belongs inside rather than outside.',
    seo: 'Applied AP CSA 2.11 practice: six scenario questions on nested loops, iteration counts and triangular patterns.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'An outer loop runs 4 times and an inner loop runs 5 times per outer pass.',
        stem: 'How many times does the inner body execute in total?',
        options: [
          '9',
          '20, because the counts multiply rather than add',
          '5',
          '4',
        ],
        correct: 'B',
        why: {
          A: 'Adding them describes two sequential loops, not nested ones.',
          B: 'Correct, and this multiplication is why nesting dominates run time.',
          C: 'That is one outer pass only.',
          D: 'That is the outer count alone.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'An inner loop is written for (int j = 0; j <= i; j++) inside an outer loop over i from 0 to n-1.',
        stem: 'What pattern of counts does the inner loop produce?',
        options: [
          'The same count every pass',
          'A growing count: 1, then 2, then 3 and so on, which produces a triangular total rather than a rectangular one',
          'A shrinking count',
          'Always zero',
        ],
        correct: 'B',
        why: {
          A: 'The bound depends on i, so it changes each pass.',
          B: 'Correct. Triangular nesting is roughly half the work of the full rectangle.',
          C: 'It grows because i increases.',
          D: 'When i is 0 the inner loop still runs once, since 0 <= 0.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A student declares the inner loop counter OUTSIDE both loops and never resets it.',
        stem: 'What happens on the second outer pass?',
        options: [
          'It behaves identically to declaring it inside',
          'The inner loop does not run, because the counter is already past its bound from the first pass',
          'The inner loop runs twice as long',
          'It does not compile',
        ],
        correct: 'B',
        why: {
          A: 'Declaring inside the header resets it on every outer pass, which is the difference.',
          B: 'Correct. The missing reset is the classic nested loop bug.',
          C: 'It runs zero more times rather than more.',
          D: 'The code is legal.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A nested loop must compare every element of a list to every OTHER element without comparing a pair twice.',
        stem: 'How should the inner loop start?',
        options: [
          'At 0, the same as the outer loop',
          'At i + 1, so each unordered pair is considered exactly once',
          'At the end of the list',
          'At i, including the element with itself',
        ],
        correct: 'B',
        why: {
          A: 'That visits every ordered pair, covering each unordered pair twice.',
          B: 'Correct, and it halves the work as a side effect.',
          C: 'A backward inner loop still needs a bound tied to i.',
          D: 'That adds the pointless self comparison.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'Two programs process the same n items. One uses a single loop; the other nests two loops over all n.',
        stem: 'How does the work compare as n doubles?',
        options: [
          'Both double',
          'The single loop doubles while the nested one quadruples, since its work grows with n squared',
          'Both quadruple',
          'Neither changes',
        ],
        correct: 'B',
        why: {
          A: 'Only the single loop scales linearly.',
          B: 'Correct, and this is the intuition 2.12 makes explicit.',
          C: 'The single loop grows linearly, not quadratically.',
          D: 'Both depend on n.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A nested loop prints a rectangle of stars, and the newline is printed inside the inner loop.',
        stem: 'What does the output look like?',
        options: [
          'A correct rectangle',
          'One star per line, because the newline follows every star rather than every row',
          'A single long line',
          'Nothing',
        ],
        correct: 'B',
        why: {
          A: 'That needs the newline after the inner loop finishes.',
          B: 'Correct: the placement of the newline is what separates rows from characters.',
          C: 'That is the result of omitting the newline entirely.',
          D: 'Both loops still run and print.',
        },
      },
    ],
  },
  {
    lesson: '2.12', unit: 'unit-2',
    title: 'Informal Run-Time Analysis',
    blurb: 'Six scenarios on counting operations rather than seconds, and why the input size is what matters.',
    brief: 'The exercise-1 editor asks you to compare implementations. These six ask how the work GROWS, which is the only comparison that survives changing computers.',
    seo: 'Applied AP CSA 2.12 practice: six scenario questions on informal run-time analysis and counting statement executions.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A single loop over n elements performs one comparison per element.',
        stem: 'How does the number of comparisons grow with n?',
        options: [
          'It stays constant',
          'It grows in direct proportion to n, so doubling the input doubles the comparisons',
          'It grows with n squared',
          'It shrinks as n grows',
        ],
        correct: 'B',
        why: {
          A: 'Constant work would mean the loop does not depend on n.',
          B: 'Correct. This is linear growth.',
          C: 'Quadratic growth requires nesting.',
          D: 'More data means more comparisons.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'One algorithm takes 3n + 100 steps and another takes n squared steps.',
        stem: 'Which is preferable for very large n?',
        options: [
          'The n squared one, since it has no constant',
          'The 3n + 100 one, because linear growth eventually beats quadratic no matter how large the constants are',
          'They are the same',
          'It cannot be determined',
        ],
        correct: 'B',
        why: {
          A: 'The constant is irrelevant once n is large.',
          B: 'Correct, and note the quadratic one can genuinely win for SMALL n, which is why it is not simply worse.',
          C: 'They diverge sharply as n grows.',
          D: 'The growth rates settle it decisively.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A search examines elements until it finds a match, and the match happens to be the first element.',
        stem: 'What does that tell you about the algorithm?',
        options: [
          'It is always constant time',
          'Only that its BEST case is fast; the growth rate is judged by the worst case, where no match is found',
          'It is quadratic',
          'It never terminates',
        ],
        correct: 'B',
        why: {
          A: 'One lucky input does not characterize the algorithm.',
          B: 'Correct. Best case, worst case and average case are separate claims.',
          C: 'A single loop is not quadratic.',
          D: 'It terminates at the match.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A loop halves the remaining search space on every pass.',
        stem: 'How many passes does it need for n items?',
        options: [
          'About n',
          'About the number of times n can be halved before reaching 1, which grows very slowly',
          'About n squared',
          'Exactly 2',
        ],
        correct: 'B',
        why: {
          A: 'Linear growth means examining every item, which halving avoids.',
          B: 'Correct: this is logarithmic growth, and it is why binary search scales so well.',
          C: 'Halving reduces work rather than multiplying it.',
          D: 'The count depends on n.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student times two algorithms on their laptop and concludes one is better.',
        stem: 'What is the weakness of that evidence?',
        options: [
          'Timing is always meaningless',
          'A single input size on one machine measures constants and conditions rather than how the work grows, so it may reverse at a different scale',
          'Laptops cannot run Java',
          'The algorithms must be identical',
        ],
        correct: 'B',
        why: {
          A: 'Timing is useful evidence, just not sufficient on its own.',
          B: 'Correct. Growth rate is a claim about scaling and needs more than one point to observe.',
          C: 'Irrelevant to the reasoning.',
          D: 'They can be genuinely different algorithms.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'Two nested loops each run n times, and the inner body contains 5 statements.',
        stem: 'How is the total work described?',
        options: [
          '5 times n statements',
          'Proportional to n squared, since the constant 5 does not affect how the work GROWS',
          '25 times n statements',
          'Constant',
        ],
        correct: 'B',
        why: {
          A: 'That accounts for only one loop.',
          B: 'Correct, and dropping constants is what makes growth rates comparable across implementations.',
          C: 'The 5 is not squared; only the loop counts multiply.',
          D: 'The work clearly depends on n.',
        },
      },
    ],
  },
];
