'use strict';
// Big Idea 1: Creative Development. Exercise 2 banks, 4 topics.
// Applied challenge: every stem puts the student inside a development scenario
// and asks what to DO, rather than what a term means. The lesson quiz already
// tests the definition; this tests the transfer.
// Pure ASCII, no em-dashes. Zero PII: author content only.

module.exports = [
  {
    slug: 'collaboration',
    title: 'Collaboration',
    blurb: 'Six development-team scenarios. Decide what collaboration actually calls for, not what sounds polite.',
    brief: 'The lesson quiz asks what pair programming is. These ask you to sit inside a team that is going wrong and pick the move that fixes it.',
    seo: 'Applied AP CSP 1.1 practice: six scenario questions on pair programming, consensus building, and how collaboration changes a computing innovation.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'Two students build a fitness app. One writes every line while the other watches, and they never swap.',
        stem: 'They call this pair programming. What is the strongest reason it is not?',
        options: [
          'Pair programming requires more than two people on a team',
          'The navigator role is doing no reviewing, and the roles never rotate, so the second person contributes nothing to the code',
          'Pair programming is only valid when both students type on separate machines',
          'Pair programming must happen online rather than in person',
        ],
        correct: 'B',
        why: {
          A: 'Pair programming is specifically two people. Team size is not the defect here.',
          B: 'Pair programming is a driver who types and a navigator who reviews, questions, and catches errors, with the roles rotating. Watching passively is neither role.',
          C: 'Two people on one machine is the normal form of pair programming, not a violation of it.',
          D: 'Pair programming works in person or online. The medium is not what makes it collaboration.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A team of four ships a campus map app. Every tester was a member of the team.',
        stem: 'Which consequence is the most likely and the most specific to that testing choice?',
        options: [
          'The program will run more slowly than one tested by outsiders',
          'The program will contain more syntax errors',
          'The team will miss needs and failure cases they do not personally have, because everyone testing shares their assumptions',
          'The program will violate copyright law',
        ],
        correct: 'C',
        why: {
          A: 'Who tests a program has no bearing on its running speed.',
          B: 'Syntax errors are caught by the language, not by the diversity of the test group.',
          C: 'This is the core argument for collaboration in CSP. A group that shares a perspective shares its blind spots, so unmet needs and untested situations survive testing.',
          D: 'Testing practices and copyright are unrelated concerns.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'Two teammates disagree about whether the app should open on a map or on a search box.',
        stem: 'Which response best demonstrates consensus building rather than simply winning?',
        options: [
          'The teammate with more programming experience decides, since they will write the code',
          'They flip a coin so neither person feels overruled',
          'They state the user need each design serves, agree on which need is more common for their users, and choose from that',
          'They build both and let the codebase carry two versions indefinitely',
        ],
        correct: 'C',
        why: {
          A: 'Deferring to seniority ends the disagreement without ever examining the reasons, which is not consensus.',
          B: 'A coin flip discards both arguments. It is fast, not collaborative.',
          C: 'Consensus building means surfacing the reasons, finding shared criteria, and deciding against those criteria. The user need is the shared criterion here.',
          D: 'Carrying both designs defers the decision and doubles the maintenance rather than resolving anything.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A student says a wooden chair with a QR code sticker is a computing innovation.',
        stem: 'What is the correct classification, and why?',
        options: [
          'It is a computing innovation, because a QR code is scanned by a computer',
          'It is not a computing innovation, because a program is not an integral part of the chair itself',
          'It is a nonphysical computing innovation, because the sticker holds data',
          'It is a computing innovation only if the chair was designed on a computer',
        ],
        correct: 'B',
        why: {
          A: 'Something being scannable by a computer does not make a program integral to the object. The chair is a chair with or without the sticker.',
          B: 'A computing innovation requires a program as an integral part of its function. Remove the code from the chair and it still works exactly as a chair.',
          C: 'Nonphysical computing innovations are things like e-commerce or social media. A sticker on furniture is neither.',
          D: 'Being designed with computer assistance does not make the product itself a computing innovation.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A team keeps their program notes, decisions, and open questions in a shared online document.',
        stem: 'Which benefit of that practice is the one AP CSP specifically credits?',
        options: [
          'It makes the program execute with fewer errors at runtime',
          'It guarantees the program will be accessible to users with disabilities',
          'It preserves the reasoning behind decisions so any collaborator, including a future one, can understand and build on the work',
          'It replaces the need to comment the code',
        ],
        correct: 'C',
        why: {
          A: 'Documentation is written for people. It does not change what the machine does at runtime.',
          B: 'Accessibility comes from deliberate design choices in the program, not from keeping notes.',
          C: 'Collaboration tools carry the reasoning, not just the result, which is what lets a teammate or a later developer pick the work up without redoing the thinking.',
          D: 'Program documentation and in-code comments serve overlapping but different purposes, and neither removes the need for the other.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'During a conflict, one teammate goes quiet and stops contributing for two work sessions.',
        stem: 'Which action best applies the interpersonal skills the CED names for collaboration?',
        options: [
          'Reassign all of that teammate\'s work to the others so the project stays on schedule',
          'Ask the teammate directly what changed, listen to the answer, and renegotiate the split of work from there',
          'Wait for the teammate to raise it themselves, since forcing a conversation could make it worse',
          'Log the lapse so the teacher can factor it into the grade',
        ],
        correct: 'B',
        why: {
          A: 'Routing around a person keeps the project moving and leaves the conflict entirely unaddressed.',
          B: 'Communication, conflict resolution, and negotiation are the named skills. Asking, listening, then renegotiating uses all three.',
          C: 'Waiting is not conflict resolution. The behavior is already the signal that something needs a conversation.',
          D: 'Escalating to a grade is neither communication nor negotiation, and it does not restore the collaboration.',
        },
      },
    ],
  },

  {
    slug: 'program-function-purpose',
    title: 'Program Function and Purpose',
    blurb: 'Six scenarios that separate what a program is FOR from what it DOES, which is where most exam points are lost.',
    brief: 'Purpose, function, input, output, and behavior get used loosely in conversation and precisely on the exam. These force the precise reading.',
    seo: 'Applied AP CSP 1.2 practice: six scenario questions separating program purpose from function, and identifying inputs, outputs, and program behavior.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'An app takes a photo of a plant and names the species.',
        stem: 'Which statement describes the program\'s PURPOSE rather than its function?',
        options: [
          'It compares image features against a reference database and returns the closest match',
          'It helps a gardener identify a plant without needing an expert on hand',
          'It accepts an image file as input',
          'It displays a species name as output',
        ],
        correct: 'B',
        why: {
          A: 'That is the function: the how. Purpose is the why.',
          B: 'Purpose answers why the program exists and what problem it solves for a person. The mechanism is not mentioned.',
          C: 'An input is a component of the function, not the purpose.',
          D: 'An output is a component of the function, not the purpose.',
        },
      },
      {
        tag: 'Analyze',
        stem: 'A program asks for a temperature in Celsius and displays it in Fahrenheit. Which pair correctly identifies its input and output?',
        options: [
          'Input: the conversion formula. Output: the Celsius value',
          'Input: the Celsius value. Output: the Fahrenheit value',
          'Input: the Fahrenheit value. Output: the Celsius value',
          'Input: the user\'s keyboard. Output: the screen',
        ],
        correct: 'B',
        why: {
          A: 'The formula is part of how the program works, not data supplied to it.',
          B: 'Input is data the program receives, output is data it produces. The user supplies Celsius, the program produces Fahrenheit.',
          C: 'This reverses the flow described in the prompt.',
          D: 'Keyboard and screen are devices. Input and output name the DATA, not the hardware carrying it.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'Two students describe the same quiz program.',
        stem: 'Student 1 says it teaches vocabulary. Student 2 says it displays a word, reads a typed answer, and keeps a running score. What is the correct characterization?',
        options: [
          'Student 1 gave the function, Student 2 gave the purpose',
          'Student 1 gave the purpose, Student 2 gave the function',
          'Both gave the purpose, stated at different levels of detail',
          'Both gave the function, since both describe the same program',
        ],
        correct: 'B',
        why: {
          A: 'This reverses the two. Teaching vocabulary is the goal, not the mechanism.',
          B: 'Purpose is the problem being solved for the user. Function is the input, process, and output that solve it.',
          C: 'Only one of the two describes purpose. The other is a step by step account of behavior.',
          D: 'Describing the same program does not make both descriptions the same kind of description.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A weather app shows a different home screen in the morning than in the evening.',
        stem: 'Which term best describes that difference?',
        options: [
          'The program\'s purpose changes with the time of day',
          'The program\'s behavior differs because its input differs',
          'The program has two separate functions running at once',
          'The program produces no output in the evening',
        ],
        correct: 'B',
        why: {
          A: 'The purpose, helping a user plan around weather, is unchanged. Only what it shows changes.',
          B: 'Behavior is what the program does for a given input. Time of day is an input, so different input yields different behavior.',
          C: 'One program responding differently to different input is not two functions.',
          D: 'It produces output at both times. The output is simply different.',
        },
      },
      {
        tag: 'Debug',
        scenario: 'A tip calculator returns 0 whenever the bill total is left blank.',
        stem: 'Which description of the situation is most accurate?',
        options: [
          'The program has no purpose when input is missing',
          'The program\'s behavior for that input is defined but undesirable, so the input handling should change',
          'The program has a syntax error that appears only for blank input',
          'The program produces no output for that input',
        ],
        correct: 'B',
        why: {
          A: 'Purpose is a property of the program, not of one input. It does not disappear on an empty field.',
          B: 'The program does something specific and predictable for blank input. That is defined behavior, and the fix is to handle the input rather than to call it a crash.',
          C: 'A syntax error prevents the program from running at all, not just for one input.',
          D: 'It produces output. The output is 0, which is exactly the problem.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which of these is the clearest statement of a program\'s purpose for the Create Task written response?',
        options: [
          'The program uses a list, a loop, and a conditional',
          'The program lets a user log the books they have read and see how many they finished this month',
          'The program was written in Python over three weeks',
          'The program contains a procedure with two parameters',
        ],
        correct: 'B',
        why: {
          A: 'These are language features, which belong in a different part of the response.',
          B: 'A purpose statement names the user and the problem solved, in terms someone outside the class could follow.',
          C: 'The language and timeline describe the development process, not the purpose.',
          D: 'A procedure signature is an implementation detail.',
        },
      },
    ],
  },

  {
    slug: 'program-design-development',
    title: 'Program Design and Development',
    blurb: 'Six scenarios inside an iterative development cycle. Pick the next move, not the ideal one in hindsight.',
    brief: 'Development is investigate, design, prototype, test, and repeat. These questions drop you at a specific point in that cycle and ask what comes next.',
    seo: 'Applied AP CSP 1.3 practice: six scenario questions on iterative development, prototyping, user investigation, and program requirements.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A team has an idea for a study timer and starts by writing the full final version.',
        stem: 'Which criticism of that approach is the one the development process in CSP is built to prevent?',
        options: [
          'Writing the full version takes more lines of code',
          'They will not discover a wrong assumption about what users need until the whole thing is built',
          'The program will run more slowly than a prototype would',
          'They cannot use a loop until they have a prototype',
        ],
        correct: 'B',
        why: {
          A: 'Line count is not the concern. Discovering a design mistake late is.',
          B: 'Iterative development exists so that a wrong assumption surfaces after a small investment rather than a large one.',
          C: 'Prototypes are not faster at runtime than finished programs.',
          D: 'Language features are available at every stage of development.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'Testing reveals users want a pause button nobody planned for.',
        stem: 'Where does that discovery belong in the development process?',
        options: [
          'It is a defect and should be logged as a bug',
          'It is a new requirement, so the team returns to design with it and iterates',
          'It should be deferred until after the program is complete, since it was not in the original plan',
          'It means the original purpose statement was invalid',
        ],
        correct: 'B',
        why: {
          A: 'A bug is a program not doing what it was designed to do. This is the design itself being incomplete.',
          B: 'Iteration means testing feeds back into design. An unmet user need discovered in testing is exactly what that feedback loop is for.',
          C: 'Deferring every unplanned need until the end defeats the purpose of iterating.',
          D: 'The purpose, helping users manage study time, still holds. Only the requirements grew.',
        },
      },
      {
        tag: 'Evaluate',
        stem: 'Which pair of program requirements is stated most usefully for development?',
        options: [
          'The program should be fast and easy to use',
          'The program should accept a study length in minutes and display the remaining time each second',
          'The program should be better than existing timer apps',
          'The program should use good variable names and clear comments',
        ],
        correct: 'B',
        why: {
          A: 'Fast and easy are goals without a test. Nothing here says when they are met.',
          B: 'Each clause names an observable behavior, so a tester can determine whether it happens.',
          C: 'Better is a comparison with no criterion attached.',
          D: 'These are code quality practices, not requirements about what the program does.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A developer keeps a development log noting what was tried, what failed, and why.',
        stem: 'Which is the strongest argument for that log in a collaborative project?',
        options: [
          'It proves to the teacher that the student did their own work',
          'It prevents a teammate from repeating an approach that has already been ruled out, and preserves the reason it was ruled out',
          'It makes the final program shorter',
          'It is required before a program can be tested',
        ],
        correct: 'B',
        why: {
          A: 'Attribution is a real use of a log, but it is not what makes it valuable to development.',
          B: 'A record of dead ends is the part of the reasoning that is otherwise lost, and it is exactly what a collaborator needs to avoid repeating the work.',
          C: 'Documentation is written alongside the program and does not change its length.',
          D: 'Testing has no such prerequisite.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A team is deciding what to build first for a school event app.',
        stem: 'Which approach best matches the design phase as CSP describes it?',
        options: [
          'Start with whichever feature is easiest to code',
          'Investigate what students actually need from the app, then design around the most common needs',
          'Copy the feature list from a similar published app',
          'Build every feature at a low quality, then improve them all at the end',
        ],
        correct: 'B',
        why: {
          A: 'Ease of implementation is a real consideration, but it does not tell you whether anyone needs the feature.',
          B: 'Investigating user needs before designing is the step that keeps development anchored to a purpose.',
          C: 'Another app was designed for another set of users, whose needs may not match.',
          D: 'Building everything badly first spreads effort thin and delays discovering which features matter.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'Two teammates each wrote a version of the same procedure without knowing the other had.',
        stem: 'Which practice would most directly have prevented this?',
        options: [
          'Testing each version more thoroughly',
          'Agreeing on a division of the program and recording who owns which part before coding began',
          'Writing more comments inside each version',
          'Using a faster algorithm in both versions',
        ],
        correct: 'B',
        why: {
          A: 'Testing finds defects in code that exists. It does not prevent duplicate work.',
          B: 'Duplicated effort is a collaboration failure, and an agreed division of responsibility recorded up front is the specific practice that prevents it.',
          C: 'Comments explain code after it is written, which is too late here.',
          D: 'Algorithm choice has nothing to do with two people writing the same thing.',
        },
      },
    ],
  },

  {
    slug: 'identifying-correcting-errors',
    title: 'Identifying and Correcting Errors',
    blurb: 'Six broken programs. Name the error type, then pick the fix that actually addresses it.',
    brief: 'Naming an error is half the skill. These pair each error with candidate fixes, most of which change something real and still leave the bug in place.',
    seo: 'Applied AP CSP 1.4 practice: six scenario questions classifying logic, syntax, runtime, and overflow errors, and choosing the correct debugging move.',
    questions: [
      {
        tag: 'Debug',
        stem: 'A program is meant to display the average of three numbers but always displays a value near the first number. Which error type is this?',
        code: 'avg <- a + b + c / 3\nDISPLAY avg',
        options: [
          'A syntax error, because the expression is malformed',
          'A logic error, because the program runs and produces a defined but wrong result',
          'A runtime error, because division happens before addition',
          'An overflow error, because the sum is too large',
        ],
        correct: 'B',
        why: {
          A: 'The expression is valid. Nothing prevents it from being parsed or run.',
          B: 'The program runs to completion and produces a wrong answer, which is the definition of a logic error. Only c is divided by 3.',
          C: 'Runtime errors stop execution. This finishes and prints something.',
          D: 'Overflow is about values exceeding what can be stored, which is not happening here.',
        },
      },
      {
        tag: 'Debug',
        scenario: 'A program crashes with a message about an invalid index whenever the list is empty.',
        stem: 'Which classification and fix pair is correct?',
        options: [
          'Logic error, fixed by renaming the list variable',
          'Runtime error, fixed by checking the list length before accessing an element',
          'Syntax error, fixed by adding a missing bracket',
          'Overflow error, fixed by using a smaller list',
        ],
        correct: 'B',
        why: {
          A: 'A logic error produces a wrong result without stopping. This stops.',
          B: 'The program halts during execution on certain input, which is a runtime error, and guarding the access before it happens is the direct fix.',
          C: 'A syntax error would prevent the program from running at all, including on non empty lists.',
          D: 'Overflow concerns value size, not an access past the end of a list.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A student adds a DISPLAY statement inside a loop to see what a variable holds on each pass.',
        stem: 'Which best describes what that technique accomplishes?',
        options: [
          'It fixes the logic error by forcing the variable to update',
          'It exposes the program\'s intermediate state so the point where the value first goes wrong can be located',
          'It converts a runtime error into a logic error',
          'It confirms the program has no syntax errors',
        ],
        correct: 'B',
        why: {
          A: 'Displaying a value never changes it. The bug is untouched.',
          B: 'Debugging by inspecting intermediate values narrows a wrong final answer down to the specific step where it first diverged.',
          C: 'Adding output does not change what kind of error is present.',
          D: 'A program with a syntax error would not have run far enough to print anything, but printing is not how you check for one.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A team fixes a bug by adding a special case that returns the right answer for the one input they tested.',
        stem: 'What is the strongest objection?',
        options: [
          'The special case makes the program longer',
          'The underlying error is still present for every other input that triggers it',
          'Special cases are not allowed in AP CSP pseudocode',
          'The fix introduces a syntax error',
        ],
        correct: 'B',
        why: {
          A: 'Length is a minor cost compared to a bug that still exists.',
          B: 'Patching the symptom for one observed input leaves the cause in place, so the same defect reappears for every other input that reaches it.',
          C: 'Conditionals for special cases are perfectly valid. The problem is what this one hides.',
          D: 'Nothing in the described fix creates a syntax error.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display?',
        code: 'count <- 0\nREPEAT 4 TIMES\n{\n  count <- count + 2\n}\nDISPLAY count',
        options: ['2', '4', '6', '8'],
        correct: 'D',
        why: {
          A: '2 is the value after one pass. The loop runs four times.',
          B: '4 is the number of iterations, not the accumulated total.',
          C: '6 is the value after three passes, one short.',
          D: 'Four passes each add 2 to a variable starting at 0, giving 8.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A program works on the developer\'s test data and fails for a classmate.',
        stem: 'Which is the most productive first step?',
        options: [
          'Rewrite the program from the beginning',
          'Find out exactly what input the classmate used, then run the program on that input',
          'Add comments explaining the intended behavior',
          'Assume the classmate made a mistake, since the program works',
        ],
        correct: 'B',
        why: {
          A: 'Rewriting discards working code before anyone knows what is wrong.',
          B: 'A bug that appears for one person and not another is a difference in input or environment, so reproducing it on the failing input is the step that turns a report into something debuggable.',
          C: 'Comments describe intent and do not locate the defect.',
          D: 'Working on one set of inputs is exactly the situation in which a real bug hides.',
        },
      },
    ],
  },
];
