'use strict';
// Big Idea 2: Data. Exercise 2 banks, 4 topics.
// Applied challenge: binary and compression questions that require a computation
// or a judgement call, not a recalled definition.
// Pure ASCII, no em-dashes. Zero PII: author content only.

module.exports = [
  {
    slug: 'binary-numbers',
    title: 'Binary Numbers',
    blurb: 'Six questions that make you convert, count, and reason about what a fixed number of bits can and cannot hold.',
    brief: 'The quiz checks that you can convert. These check that you know what happens at the edges: overflow, rounding, and how many values a bit width buys you.',
    seo: 'Applied AP CSP 2.1 practice: six scenario questions on binary conversion, bit width, overflow, and round-off error in fixed size representations.',
    questions: [
      {
        tag: 'Apply',
        stem: 'A system stores a value in 6 bits, unsigned. How many distinct values can it represent, and what is the largest?',
        options: [
          '6 values, largest 6',
          '32 values, largest 32',
          '64 values, largest 63',
          '64 values, largest 64',
        ],
        correct: 'C',
        why: {
          A: 'The number of bits is not the number of values. Each bit doubles the count.',
          B: '32 is 2 to the fifth, which is 5 bits. Six bits is double that.',
          C: 'n bits give 2 to the n values. 2 to the sixth is 64 values, running from 0 to 63.',
          D: 'The count is 64, but counting from 0 means the largest is 63, not 64.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What is the decimal value of the binary number 10110?',
        options: ['16', '22', '26', '44'],
        correct: 'B',
        why: {
          A: '16 accounts only for the leading 1 and ignores the rest.',
          B: 'The place values are 16, 8, 4, 2, 1. The set bits are 16, 4, and 2, giving 22.',
          C: '26 would be 11010, which reverses two of the middle digits.',
          D: '44 is 10110 shifted one place left, which is double the correct value.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A counter stored in 4 unsigned bits currently holds 15. The program adds 1.',
        stem: 'Which outcome and error type is correct?',
        options: [
          'The value becomes 16, with no error, since 16 fits in 4 bits',
          'The value cannot be represented in 4 bits, which is an overflow error',
          'The value becomes 15.5, which is a round-off error',
          'The program halts with a syntax error',
        ],
        correct: 'B',
        why: {
          A: '4 bits hold 0 through 15. 16 is one past the maximum.',
          B: 'Overflow is exactly this: a computation whose result needs more bits than the representation provides.',
          C: 'Round-off applies to values with fractional parts that cannot be represented exactly. This is an integer past its maximum.',
          D: 'Syntax errors are detected before running and are unrelated to values.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student says any decimal number can be stored exactly if you use enough bits.',
        stem: 'What is the correct response?',
        options: [
          'True, since binary can represent any value with sufficient bits',
          'False, because some values such as one third have no exact finite representation, so a fixed number of bits forces round-off',
          'True, but only for numbers less than 1',
          'False, because binary cannot represent fractions at all',
        ],
        correct: 'B',
        why: {
          A: 'Adding bits improves precision but never reaches exactness for a value with no finite representation.',
          B: 'Any fixed size representation stores a finite set of values, so values outside that set are approximated. That approximation is round-off error.',
          C: 'Being less than 1 makes no difference. One third is a problem at any scale.',
          D: 'Binary represents fractions routinely. Exactness for every fraction is the part that fails.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'An image is stored with 8 bits per color channel and three channels per pixel.',
        stem: 'How many distinct colors can one pixel take?',
        options: [
          '24, since 8 times 3 is 24',
          '256, since each channel holds 256 levels',
          '768, since 256 times 3 is 768',
          'About 16.7 million, since 256 levels in each of three channels combine',
        ],
        correct: 'D',
        why: {
          A: '24 is the total bit count, not the number of colors those bits encode.',
          B: '256 is the range of one channel. Three channels combine rather than replace one another.',
          C: 'Adding the channel ranges undercounts. Independent channels multiply.',
          D: 'Each channel independently takes 256 values, so 256 cubed is 16,777,216 combinations.',
        },
      },
      {
        tag: 'Apply',
        stem: 'A sensor reports a reading every second and each reading is stored in 2 bytes. About how much storage does one hour of readings need?',
        options: [
          'About 3,600 bits',
          'About 7,200 bytes',
          'About 3,600 bytes',
          'About 120 bytes',
        ],
        correct: 'B',
        why: {
          A: 'This counts one bit per reading rather than two bytes.',
          B: 'One hour is 3,600 seconds, so 3,600 readings at 2 bytes each is 7,200 bytes.',
          C: '3,600 bytes assumes one byte per reading, which is half the stated size.',
          D: '120 counts minutes rather than seconds.',
        },
      },
    ],
  },

  {
    slug: 'data-compression',
    title: 'Data Compression',
    blurb: 'Six scenarios where you must choose lossy or lossless, and defend the choice against the actual use.',
    brief: 'The exam rarely asks what lossless means. It asks which one you would use here, and why the other one would be wrong.',
    seo: 'Applied AP CSP 2.2 practice: six scenario questions choosing between lossy and lossless compression and reasoning about size and fidelity tradeoffs.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A hospital archives patient scan images for later diagnosis.',
        stem: 'Which compression choice is correct, and why?',
        options: [
          'Lossy, because the files are large and storage costs matter most',
          'Lossless, because a detail discarded during compression could be the detail a diagnosis depends on',
          'Lossy, because medical images are viewed on screens that cannot show full detail anyway',
          'Neither, because medical data cannot be compressed',
        ],
        correct: 'B',
        why: {
          A: 'Storage savings do not justify discarding information that cannot be recovered when the stakes are a diagnosis.',
          B: 'Lossless compression reconstructs the original exactly. When any discarded detail could matter, that guarantee is the requirement.',
          C: 'The display is not the only consumer. The image may be enlarged, reprocessed, or re-examined later.',
          D: 'Medical data compresses like any other data. The question is only which kind.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student compresses a text file with a lossless method, then compresses the result again with the same method.',
        stem: 'What is the most likely outcome of the second pass?',
        options: [
          'The file halves in size again',
          'Little or no further reduction, because the redundancy the method exploits has already been removed',
          'The file is corrupted and cannot be restored',
          'The file becomes lossy after two passes',
        ],
        correct: 'B',
        why: {
          A: 'Compression is not a repeatable halving. The first pass consumed the pattern the method depends on.',
          B: 'Lossless methods shrink data by encoding redundancy compactly. Once removed, there is little left for a second pass to find.',
          C: 'Lossless compression is reversible by definition, and applying it twice does not destroy the data.',
          D: 'The method does not change character based on how many times it is applied.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A song is compressed from 40 MB to 4 MB and listeners cannot hear a difference.',
        stem: 'Which statement is accurate?',
        options: [
          'The compression was lossless, since nothing audible was lost',
          'The compression was lossy, and the discarded data cannot be recovered from the 4 MB file even though the loss is not noticeable',
          'The original can be reconstructed exactly from the 4 MB file',
          'The file will sound worse each time it is played',
        ],
        correct: 'B',
        why: {
          A: 'Lossless is about whether the original can be reconstructed, not about whether a person notices.',
          B: 'A tenfold reduction on audio comes from discarding data. Imperceptible loss is still loss, and it is permanent.',
          C: 'Exact reconstruction is precisely what lossy compression gives up.',
          D: 'Playback does not degrade a file. Repeated re-compression would.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A program\'s source code is emailed as a compressed archive.',
        stem: 'Why must this compression be lossless?',
        options: [
          'Because source code files are small enough that compression is optional',
          'Because a single altered character can change or break the program, so exact reconstruction is required',
          'Because text cannot be compressed with a lossy method',
          'Because email attachments must be lossless by protocol',
        ],
        correct: 'B',
        why: {
          A: 'File size does not determine which compression is safe.',
          B: 'Code has no tolerance for approximation. One changed character is a different program, so the reconstruction must be exact.',
          C: 'Lossy methods can be applied to text. The result is simply useless, which is the point.',
          D: 'Email carries whatever bytes it is given. There is no such protocol rule.',
        },
      },
      {
        tag: 'Apply',
        stem: 'A 12 MB file is compressed to 3 MB. What fraction of the original size remains, and what is the reduction?',
        options: [
          'One quarter remains, a 75 percent reduction',
          'One third remains, a 67 percent reduction',
          'Three quarters remain, a 25 percent reduction',
          'One quarter remains, a 25 percent reduction',
        ],
        correct: 'A',
        why: {
          A: '3 of 12 is one quarter remaining, so 9 of the 12 MB were removed, which is a 75 percent reduction.',
          B: 'One third of 12 is 4, not 3.',
          C: 'This reverses what remains and what was removed.',
          D: 'The remaining fraction is right but the reduction is its complement, not the same number.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A team must send video over a slow connection during a live stream.',
        stem: 'Which reasoning best supports lossy compression here?',
        options: [
          'Lossy compression is always faster to compute than lossless',
          'A smaller file that arrives in time is more useful than a perfect file that arrives late, and viewers tolerate small quality loss in live video',
          'Live video cannot be compressed losslessly',
          'Lossy compression removes the need for a fast connection entirely',
        ],
        correct: 'B',
        why: {
          A: 'Computation speed varies by method and is not the deciding argument here.',
          B: 'The tradeoff is fidelity against size, and in a live stream timely delivery is the requirement that fidelity is traded for.',
          C: 'Lossless video compression exists. It simply does not shrink the data enough for this constraint.',
          D: 'Compression reduces the bandwidth needed. It does not eliminate the need for bandwidth.',
        },
      },
    ],
  },

  {
    slug: 'extracting-information',
    title: 'Extracting Information from Data',
    blurb: 'Six scenarios about what a dataset can honestly support, and where a conclusion outruns the evidence.',
    brief: 'Every question here has a tempting answer that the data almost supports. Finding the gap between correlation, sample, and claim is the skill.',
    seo: 'Applied AP CSP 2.3 practice: six scenario questions on filtering data, correlation versus causation, metadata, and the limits of a dataset.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A dataset shows that months with higher ice cream sales also have more swimming pool injuries.',
        stem: 'What can be concluded?',
        options: [
          'Ice cream consumption causes swimming injuries',
          'The two are correlated, and a third factor such as warm weather plausibly drives both',
          'Swimming injuries cause people to buy ice cream',
          'The dataset contains an error, since unrelated values should not move together',
        ],
        correct: 'B',
        why: {
          A: 'A correlation alone never establishes which variable causes which, or that either does.',
          B: 'Correlation is a real pattern in the data. Attributing it to a shared cause is the standard and correct reading here.',
          C: 'This is the same causal overreach in the other direction.',
          D: 'Unrelated variables moving together is common and expected, not evidence of a data error.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A school surveys students about lunch preferences using a form linked from the yearbook club page.',
        stem: 'Which limitation most affects conclusions drawn from the results?',
        options: [
          'The sample is drawn from students who visit that page, so it may not represent the whole school',
          'The survey collects too much data to analyze',
          'Surveys cannot produce numeric data',
          'The results will be correlated rather than causal',
        ],
        correct: 'A',
        why: {
          A: 'Who could reach the survey determines who answered, and a conclusion about all students needs a sample that reflects all students.',
          B: 'Volume is a processing concern, not a validity concern, and nothing suggests the volume is a problem.',
          C: 'Surveys produce numeric data routinely.',
          D: 'The correlation and causation distinction is real but is not what the sampling flaw affects here.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A photo file carries the date, camera model, and location where it was taken.',
        stem: 'What is this information called, and why does it matter for analysis?',
        options: [
          'It is the payload, and it is what the file is for',
          'It is metadata, and it allows photos to be searched, sorted, and grouped without opening each image',
          'It is compression data, and it is used to restore the file',
          'It is a checksum, and it verifies the file is undamaged',
        ],
        correct: 'B',
        why: {
          A: 'The payload is the image itself. This is data describing that image.',
          B: 'Metadata is data about data, and it is what makes a large collection searchable and groupable at scale.',
          C: 'Compression details are separate and are not what date and location are.',
          D: 'A checksum verifies integrity and carries no descriptive meaning.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student filters a sales dataset to rows where the region is North, then reports the average sale.',
        stem: 'What does that average describe?',
        options: [
          'The average sale across the whole company',
          'The average sale among North region rows only, which says nothing directly about other regions',
          'The most common sale amount in the North region',
          'The total sales in the North region',
        ],
        correct: 'B',
        why: {
          A: 'Filtering removed every other region from the calculation.',
          B: 'A statistic computed after filtering describes only the filtered subset. Extending it to the whole dataset is the common error.',
          C: 'The most common value is the mode, which is a different statistic from the average.',
          D: 'A total and an average are different summaries of the same rows.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A dataset of 500 rows has a blank value in the age column for 60 rows.',
        stem: 'Which approach is most defensible when computing an average age?',
        options: [
          'Treat the blanks as zero, since a blank means no value',
          'Compute the average over the 440 rows that have an age, and report that the other 60 were excluded',
          'Delete the entire dataset and collect it again',
          'Fill the blanks with the highest age in the dataset',
        ],
        correct: 'B',
        why: {
          A: 'Zero is a real age value, so treating missing data as zero drags the average down and misrepresents the data.',
          B: 'Excluding incomplete rows and stating that you did so keeps the statistic honest and lets a reader judge it.',
          C: 'Discarding 440 usable rows over 60 incomplete ones destroys far more information than it protects.',
          D: 'Inventing values, especially extreme ones, biases the result in a way no reader can detect.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A city wants to know which streets need repaving and uses reports submitted through a smartphone app.',
        stem: 'Which bias is most likely in the resulting data?',
        options: [
          'Streets in areas with lower smartphone use will be underreported regardless of their condition',
          'The app will report streets that do not exist',
          'The data will be lossy compressed and lose detail',
          'The reports will all be duplicates',
        ],
        correct: 'A',
        why: {
          A: 'Data collected through a device reflects who owns and uses that device, so need and reporting come apart in exactly the places least able to report.',
          B: 'Nothing about app-based reporting invents streets.',
          C: 'Compression is unrelated to how the reports were gathered.',
          D: 'Duplicates are possible but are a cleaning problem, not the structural bias here.',
        },
      },
    ],
  },

  {
    slug: 'using-programs-with-data',
    title: 'Using Programs with Data',
    blurb: 'Six scenarios about cleaning, transforming, and scaling data processing beyond what a person could do by hand.',
    brief: 'This topic is about the moment a dataset gets too big for a human. These questions ask what the program must do that the person no longer can.',
    seo: 'Applied AP CSP 2.4 practice: six scenario questions on cleaning data, transforming values, filtering, and processing datasets at scale with programs.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A dataset lists states as NY, N.Y., and New York across different rows.',
        stem: 'What must happen before the rows can be grouped by state, and what is that step called?',
        options: [
          'The rows must be compressed, which is called encoding',
          'The variations must be standardized to one form, which is called cleaning the data',
          'The rows must be sorted, which is called filtering',
          'The state column must be deleted, which is called reduction',
        ],
        correct: 'B',
        why: {
          A: 'Compression changes the size of the data, not the consistency of its values.',
          B: 'Cleaning resolves inconsistent representations of the same value so a grouping operation can see them as one thing.',
          C: 'Sorting arranges rows and does not merge different spellings, and it is not what filtering means.',
          D: 'Deleting the column removes the ability to group by state entirely.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student processes 3 million rows by hand in a spreadsheet and gives up after a week.',
        stem: 'Which statement best captures why a program is the right tool?',
        options: [
          'A program is more accurate than a person on any single row',
          'A program applies the same operation to every row at a scale and speed that makes the analysis possible at all',
          'A program will find patterns a person could never think of',
          'A program removes the need to clean the data',
        ],
        correct: 'B',
        why: {
          A: 'On one row a careful person is just as accurate. Scale is the difference, not per row accuracy.',
          B: 'The argument for programs on large datasets is that they make an otherwise impossible amount of repeated work feasible.',
          C: 'Programs execute the analysis a person specifies. They do not supply the questions.',
          D: 'Cleaning is work a program does, not work a program removes.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'Temperatures are stored in Celsius and a report needs Fahrenheit.',
        stem: 'What kind of operation is applied to the column, and what happens to the row count?',
        options: [
          'A filter, and the row count decreases',
          'A transformation, and the row count is unchanged',
          'A compression, and the row count decreases',
          'A sort, and the row count is unchanged',
        ],
        correct: 'B',
        why: {
          A: 'A filter selects rows. Converting units selects nothing.',
          B: 'Transforming a column computes a new value for each row, so every row survives with a changed value.',
          C: 'Compression is about storage size, not unit conversion.',
          D: 'Sorting reorders rows without changing any value.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program filters a 100,000 row dataset to the 2,000 rows from last month, then computes a total.',
        stem: 'Which describes the result correctly?',
        options: [
          'The total covers all 100,000 rows, since filtering only hides rows',
          'The total covers the 2,000 filtered rows, and applies to last month only',
          'The total is invalid because filtering loses data permanently',
          'The total covers 98,000 rows, since filtering removes the matching rows',
        ],
        correct: 'B',
        why: {
          A: 'Filtering determines what the computation sees, so hidden rows are excluded from the total.',
          B: 'A computation after a filter describes exactly the filtered subset, which here is last month.',
          C: 'Filtering produces a subset for analysis and does not destroy the source data.',
          D: 'Filtering keeps matching rows rather than removing them.',
        },
      },
      {
        tag: 'Apply',
        stem: 'A program must find every row where the score is above 90 AND the region is West. Which describes what it does per row?',
        options: [
          'It keeps the row if either condition is true',
          'It keeps the row only when both conditions are true',
          'It keeps the row if the first condition is true and ignores the second',
          'It keeps every row and marks the ones that match',
        ],
        correct: 'B',
        why: {
          A: 'That describes OR, which would keep far more rows than intended.',
          B: 'A filter combining conditions with AND keeps a row only when every condition holds for it.',
          C: 'Ignoring the second condition would return West and non West rows alike.',
          D: 'Marking is not filtering. A filter narrows the set the later computation sees.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A visualization shows sales rising steeply, but the vertical axis starts at 90 rather than 0.',
        stem: 'What is the most accurate criticism?',
        options: [
          'The chart uses the wrong colors for the data',
          'The truncated axis exaggerates the apparent change, so the visual impression overstates what the numbers show',
          'The chart cannot be produced by a program',
          'The underlying data must have been cleaned incorrectly',
        ],
        correct: 'B',
        why: {
          A: 'Color choice is a real design concern but is not what distorts the magnitude here.',
          B: 'Starting an axis above zero stretches small differences across the full height of the chart, which misleads without any number being wrong.',
          C: 'Programs produce charts like this routinely, which is part of why the critique matters.',
          D: 'The data may be perfectly clean. The presentation is what misleads.',
        },
      },
    ],
  },
];
