'use strict';
// Big Idea 3: Algorithms and Programming, topics 3.1 to 3.6.
// Applied challenge: the only Big Idea whose lesson pages already carry a code
// exercise (exercise-1, eight Python problems). Exercise 2 is deliberately NOT
// more coding. It is the reading and reasoning half: trace it, predict it, and
// say why the tempting wrong answer is wrong.
// AP pseudocode throughout, matching the exam reference sheet.
// Pure ASCII, no em-dashes. Zero PII: author content only.

module.exports = [
  {
    slug: 'variables',
    title: 'Variables and Assignments',
    blurb: 'Six traces where the answer depends on remembering that assignment replaces rather than relates.',
    brief: 'Nearly every wrong answer here comes from reading assignment as a permanent relationship instead of a one time copy. Trace the values in order.',
    seo: 'Applied AP CSP 3.1 practice: six trace questions on variable assignment, value replacement, and swapping values with a temporary variable.',
    questions: [
      {
        tag: 'Trace',
        predict: 'what is stored in b when the last line runs?',
        stem: 'What does this segment display?',
        code: 'a <- 5\nb <- a\na <- 9\nDISPLAY b',
        options: ['5', '9', '14', 'a'],
        correct: 'A',
        why: {
          A: 'The second line copies the value of a at that moment, which is 5. Changing a afterwards does not reach back into b.',
          B: '9 assumes b tracks a. Assignment copies a value once, it does not link the variables.',
          C: '14 adds the two values, but no addition appears in the segment.',
          D: 'DISPLAY b shows the value stored in b, not the name of another variable.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display?',
        code: 'x <- 3\ny <- 4\nx <- y\ny <- x\nDISPLAY x + y',
        options: ['7', '8', '6', '3'],
        correct: 'B',
        why: {
          A: '7 is the sum of the original values, but both variables changed before the display.',
          B: 'x becomes 4, then y is set from the new x, which is also 4. The sum is 8.',
          C: '6 would require both to end at 3, but the first swap step moved x to 4.',
          D: '3 is the original x, which was overwritten on the third line.',
        },
      },
      {
        tag: 'Debug',
        scenario: 'A student wants to swap the values in p and q.',
        stem: 'Why does this segment fail, and what is missing?',
        code: 'p <- q\nq <- p',
        options: [
          'It fails because the lines are in the wrong order, and reversing them fixes it',
          'It fails because p is overwritten before its original value is saved, so a temporary variable is needed',
          'It fails because a variable cannot appear on both sides of an assignment',
          'It does not fail, and the values are swapped correctly',
        ],
        correct: 'B',
        why: {
          A: 'Reversing the lines loses q instead of p. The order is not the defect.',
          B: 'The first line destroys the original p, so the second line copies the new value back. A temp holding one original value first is the standard fix.',
          C: 'A variable on both sides is entirely legal, and it is how accumulation works.',
          D: 'It runs without error and leaves both variables holding the original q, which is not a swap.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which sequence correctly swaps the values of m and n?',
        options: [
          'm <- n, then n <- m',
          'temp <- m, then m <- n, then n <- temp',
          'temp <- m, then n <- temp, then m <- n',
          'm <- n + m, then n <- m',
        ],
        correct: 'B',
        why: {
          A: 'This is the failed swap. The original m is gone after the first line.',
          B: 'Saving one value before overwriting it is the whole point of the temporary variable, and this order preserves both.',
          C: 'This copies m into n, then copies the new n back into m, leaving both holding the original m.',
          D: 'The second line copies the combined sum rather than the original m.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display?',
        code: 'total <- 0\ntotal <- total + 5\ntotal <- total + 5\nDISPLAY total',
        options: ['0', '5', '10', '55'],
        correct: 'C',
        why: {
          A: '0 is the starting value, before either update runs.',
          B: '5 is the value after the first update only.',
          C: 'Each line reads the current total, adds 5, and stores the result back, so two updates give 10.',
          D: '55 would come from joining the digits as text rather than adding numbers.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program uses a variable named x for a student count, a temperature, and a list index in different sections.',
        stem: 'Which is the strongest specific objection?',
        options: [
          'Reusing a variable name makes the program run more slowly',
          'A reader cannot tell what x holds at any point, which makes both debugging and collaboration harder',
          'A variable name may only be used once in a program',
          'The program will produce a runtime error',
        ],
        correct: 'B',
        why: {
          A: 'Variable naming has no effect on execution speed.',
          B: 'Names are how a reader tracks meaning. One name carrying three unrelated meanings destroys that, and the cost lands on whoever debugs it.',
          C: 'Reusing a name is legal. It is a clarity problem, not a rule violation.',
          D: 'Nothing here causes an error. That is what makes it easy to leave in place.',
        },
      },
    ],
  },

  {
    slug: 'data-abstraction',
    title: 'Data Abstraction',
    blurb: 'Six scenarios about lists as abstractions, and what changes when data gets a name instead of a set of numbered variables.',
    brief: 'Data abstraction is easy to define and hard to argue for. These questions ask you to make the argument concretely, on real programs.',
    seo: 'Applied AP CSP 3.2 practice: six scenario questions on data abstraction, using lists instead of separate variables, and managing complexity.',
    questions: [
      {
        tag: 'Evaluate',
        scenario: 'A program tracks 40 test scores using 40 separate variables named score1 through score40.',
        stem: 'What does replacing them with a single list most directly improve?',
        options: [
          'The program will run 40 times faster',
          'The program can process all scores with one loop, and adding a 41st score no longer requires editing the code in many places',
          'The scores will require less storage in memory',
          'The scores will be automatically sorted',
        ],
        correct: 'B',
        why: {
          A: 'Using a list does not multiply execution speed. The gain is in how the code is written and maintained.',
          B: 'A list makes the count a property of the data rather than of the source code, so one loop handles any number of scores.',
          C: 'Forty values occupy roughly the same space whether named separately or held in a list.',
          D: 'A list preserves the order given. Sorting is a separate operation.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which best describes what data abstraction provides?',
        options: [
          'A way to make a program shorter by removing features',
          'A way to refer to a collection of related values by one name, so the program can work with the collection without tracking each element separately',
          'A way to hide errors from the user',
          'A way to convert data between binary and decimal',
        ],
        correct: 'B',
        why: {
          A: 'Abstraction manages complexity without removing capability.',
          B: 'Naming a collection lets the rest of the program reason about the whole rather than about every individual value.',
          C: 'Hiding errors is a defect, not an abstraction.',
          D: 'Number base conversion is unrelated to data abstraction.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program stores each student as a list holding a name, a grade level, and a score.',
        stem: 'What is the main benefit over three parallel lists, one per attribute?',
        options: [
          'It uses fewer total values',
          'The attributes belonging to one student stay together, so they cannot drift out of alignment when the data is sorted or filtered',
          'It allows the program to run without loops',
          'It makes the score field impossible to change',
        ],
        correct: 'B',
        why: {
          A: 'The same values are stored either way. Only the grouping differs.',
          B: 'Parallel lists rely on matching positions, and any operation that reorders one and not the others silently corrupts every record. Grouping removes that risk.',
          C: 'Loops are still needed to visit each student.',
          D: 'Grouping data does not make any part of it read only.',
        },
      },
      {
        tag: 'Trace',
        stem: 'The list scores holds [4, 8, 15, 16]. What does LENGTH(scores) return, and what does scores[2] hold in AP pseudocode?',
        options: [
          '4 and 8',
          '3 and 15',
          '4 and 15',
          '5 and 8',
        ],
        correct: 'A',
        why: {
          A: 'The list has 4 elements, and AP pseudocode indexes from 1, so scores[2] is the second element, 8.',
          B: 'The length is 4, not 3, and index 2 is not the third element.',
          C: 'The length is right but 15 is scores[3] under 1 based indexing.',
          D: 'The length is 4. There is no fifth element.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A team wants to add a fourth attribute to every student record.',
        stem: 'Which storage design makes that change least disruptive?',
        options: [
          'Four parallel lists, one per attribute',
          'One list of student records, each record holding the attributes together',
          'Separate variables for every attribute of every student',
          'A single string containing all data for all students',
        ],
        correct: 'B',
        why: {
          A: 'Adding an attribute means adding a whole new list and updating every operation that must keep all of them aligned.',
          B: 'When a record is the unit, adding an attribute extends the record shape in one place rather than adding a parallel structure to maintain.',
          C: 'Separate variables per student per attribute is the design that scales worst to any change.',
          D: 'Packing everything into one string forces the program to parse text before it can do anything.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student says abstraction always makes a program easier to understand.',
        stem: 'What is the most accurate refinement?',
        options: [
          'True without exception, since abstraction is a best practice',
          'Abstraction manages complexity by hiding detail, which helps when the hidden detail is not needed and hurts when a reader must understand it and cannot see it',
          'False, since abstraction always makes programs harder to read',
          'True, but only for programs longer than 100 lines',
        ],
        correct: 'B',
        why: {
          A: 'Treating any technique as unconditionally good is what produces layers nobody can see through.',
          B: 'Abstraction trades visible detail for a simpler surface. That is a benefit exactly when the detail is irrelevant to the reader at that level.',
          C: 'The common case is a real improvement. Blanket rejection is as wrong as blanket endorsement.',
          D: 'Program length is not what determines whether hiding a detail helps.',
        },
      },
    ],
  },

  {
    slug: 'mathematical-expressions',
    title: 'Mathematical Expressions',
    blurb: 'Six expressions where order of operations and MOD decide the answer.',
    brief: 'MOD is the operator the exam leans on hardest and students practice least. Half of these turn on it.',
    seo: 'Applied AP CSP 3.3 practice: six evaluation questions on arithmetic order of operations, the MOD operator, and integer expression results.',
    questions: [
      {
        tag: 'Trace',
        stem: 'What is the value of the expression 17 MOD 5?',
        options: ['2', '3', '3.4', '85'],
        correct: 'A',
        why: {
          A: 'MOD gives the remainder. 17 divided by 5 is 3 with 2 left over.',
          B: '3 is the whole number quotient, not the remainder.',
          C: '3.4 is the exact division result. MOD returns only what is left over.',
          D: '85 is the product, not a division result.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display?',
        code: 'n <- 2 + 3 * 4\nDISPLAY n',
        options: ['20', '14', '24', '9'],
        correct: 'B',
        why: {
          A: '20 comes from adding first, which ignores that multiplication binds tighter.',
          B: 'Multiplication happens before addition, so it is 2 + 12, which is 14.',
          C: '24 is the product of all three values.',
          D: '9 does not follow from any reading of the expression.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which expression is true exactly when the value in num is even?',
        options: [
          'num MOD 2 = 1',
          'num MOD 2 = 0',
          'num / 2 = 0',
          'num MOD 0 = 2',
        ],
        correct: 'B',
        why: {
          A: 'A remainder of 1 identifies odd numbers.',
          B: 'An even number divides by 2 with nothing left over, so its remainder is 0.',
          C: 'This is true only when num itself is 0.',
          D: 'MOD 0 is undefined, and the comparison is backwards besides.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A program must wrap a position around a circular track of 12 slots.',
        stem: 'If pos may exceed 12, which expression keeps it within 0 to 11?',
        options: [
          'pos - 12',
          'pos MOD 12',
          'pos / 12',
          '12 MOD pos',
        ],
        correct: 'B',
        why: {
          A: 'Subtracting once fails for any value more than 24, and it needs repeating.',
          B: 'MOD is exactly the wraparound operator. Any value maps into 0 through 11 in one step.',
          C: 'Division gives how many full laps, not the position within a lap.',
          D: 'This reverses the operands and asks the remainder of 12 divided by the position.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display?',
        code: 'a <- 10\nb <- 4\nDISPLAY (a + b) MOD 7',
        options: ['0', '1', '2', '7'],
        correct: 'A',
        why: {
          A: 'The parentheses force the addition first, giving 14, and 14 divides by 7 exactly, leaving 0.',
          B: '1 would be the remainder of 15 divided by 7.',
          C: '2 would be the remainder of 16 divided by 7.',
          D: '7 is the divisor and can never be the remainder when dividing by 7.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program computes an average with total / count and count can be zero.',
        stem: 'What kind of error is possible, and what is the fix?',
        options: [
          'A logic error, fixed by using MOD instead of division',
          'A runtime error from dividing by zero, fixed by checking count before dividing',
          'A syntax error, fixed by adding parentheses',
          'An overflow error, fixed by using fewer bits',
        ],
        correct: 'B',
        why: {
          A: 'MOD by zero is undefined too, so it fixes nothing.',
          B: 'Division by zero stops execution when it happens, which is a runtime error, and the standard guard is a conditional around the division.',
          C: 'The expression parses fine. Parentheses change grouping, not this failure.',
          D: 'Overflow concerns values too large to store, not division by zero.',
        },
      },
    ],
  },

  {
    slug: 'strings',
    title: 'Strings',
    blurb: 'Six questions on building, joining, and reading strings, including where a number stops being a number.',
    brief: 'The trap in every one of these is the moment a value crosses between number and text. Watch for it.',
    seo: 'Applied AP CSP 3.4 practice: six questions on string concatenation, substrings, length, and the difference between numeric and text values.',
    questions: [
      {
        tag: 'Trace',
        stem: 'If first holds "Ada" and last holds "Lovelace", what does concatenating first, a space, and last produce?',
        options: ['AdaLovelace', 'Ada Lovelace', 'Lovelace Ada', 'Ada, Lovelace'],
        correct: 'B',
        why: {
          A: 'This omits the space that was explicitly included.',
          B: 'Concatenation joins the pieces in the order given, producing the two names separated by the space.',
          C: 'The order given puts first before last.',
          D: 'No comma appears among the pieces being joined.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program joins the text "5" and the text "3".',
        stem: 'What is the result, and why is it not 8?',
        options: [
          'The result is 8, because the values are numbers',
          'The result is the text "53", because concatenation joins characters rather than adding numeric values',
          'The result is 15, because joining multiplies',
          'The result is an error, because text cannot be joined',
        ],
        correct: 'B',
        why: {
          A: 'The values are text. Their appearance as digits does not make them numbers.',
          B: 'Concatenation places one sequence of characters after another, so two single character strings become a two character string.',
          C: 'Nothing about concatenation multiplies.',
          D: 'Joining text is the ordinary operation on strings.',
        },
      },
      {
        tag: 'Apply',
        stem: 'A username must be built from a first name, an underscore, and a graduation year. Which order of operations produces alex_2028 from "alex" and 2028?',
        options: [
          'Add the year to the name, then insert the underscore',
          'Convert the year to text, then concatenate the name, the underscore, and that text',
          'Concatenate the name and the year, then convert the result to a number',
          'Take the substring of the year, then add it to the name',
        ],
        correct: 'B',
        why: {
          A: 'Adding a number to a name is not a defined operation and would not produce text.',
          B: 'Concatenation needs text on both sides, so the numeric year is converted first and then joined.',
          C: 'Converting the finished username to a number destroys it, since it contains letters.',
          D: 'A substring of the year would drop digits that the username needs.',
        },
      },
      {
        tag: 'Trace',
        stem: 'The string word holds "COMPUTER". What is its length, and what is the substring of 4 characters starting at position 1?',
        options: [
          'Length 8, substring "COMP"',
          'Length 7, substring "COMP"',
          'Length 8, substring "OMPU"',
          'Length 8, substring "TER"',
        ],
        correct: 'A',
        why: {
          A: 'C, O, M, P, U, T, E, R is eight characters, and four characters from position 1 is COMP.',
          B: 'Counting seven drops a letter.',
          C: 'OMPU starts at position 2 rather than 1.',
          D: 'TER is the tail of the string and is only three characters.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A program must check whether a password is at least 8 characters.',
        stem: 'Which check is correct?',
        options: [
          'LENGTH(password) = 8',
          'LENGTH(password) >= 8',
          'password >= 8',
          'LENGTH(password) > 8',
        ],
        correct: 'B',
        why: {
          A: 'This accepts only passwords of exactly 8 characters and rejects longer ones.',
          B: 'At least 8 means 8 or more, which is what the greater than or equal comparison expresses.',
          C: 'Comparing the text itself to a number does not measure its length.',
          D: 'Strictly greater than 8 rejects a valid 8 character password.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student stores phone numbers as numbers rather than text.',
        stem: 'Which consequence is real and specific?',
        options: [
          'Phone numbers cannot be stored in a program at all',
          'A leading zero is lost, because a numeric value has no way to represent it',
          'The numbers will be automatically sorted',
          'The program will fail to compile',
        ],
        correct: 'B',
        why: {
          A: 'They can be stored either way. The question is which representation preserves the data.',
          B: 'Numbers carry value, not formatting, so a leading zero has nowhere to live and disappears. That is why identifiers are stored as text.',
          C: 'Storing a value as a number does not sort anything.',
          D: 'Nothing about the choice prevents the program from running.',
        },
      },
    ],
  },

  {
    slug: 'boolean-expressions',
    title: 'Boolean Expressions',
    blurb: 'Six expressions to evaluate, including the two De Morgan style rewrites the exam reuses every year.',
    brief: 'Every question here can be answered by building the truth table in your head. The distractors are the answers you get by skipping that step.',
    seo: 'Applied AP CSP 3.5 practice: six questions evaluating boolean expressions with AND, OR, and NOT, including equivalent rewrites of compound conditions.',
    questions: [
      {
        tag: 'Trace',
        stem: 'If a is 5 and b is 10, what is the value of (a > 3) AND (b < 10)?',
        options: ['true', 'false', '5', 'It cannot be determined'],
        correct: 'B',
        why: {
          A: 'AND requires both sides to be true, and the second is not.',
          B: 'a > 3 is true, but b < 10 is false because b equals 10, and true AND false is false.',
          C: 'A boolean expression evaluates to true or false, not to a number.',
          D: 'Both values are given, so the expression is fully determined.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which expression is equivalent to NOT (x > 5)?',
        options: ['x < 5', 'x <= 5', 'x >= 5', 'x = 5'],
        correct: 'B',
        why: {
          A: 'This excludes 5 itself, which the original includes.',
          B: 'The negation of greater than is less than or equal to, because it must cover every value the original excluded, including 5.',
          C: 'This is the wrong direction entirely and overlaps the original.',
          D: 'Equality covers only one value out of the whole range.',
        },
      },
      {
        tag: 'Analyze',
        stem: 'Which expression is equivalent to NOT (p AND q)?',
        options: [
          'NOT p AND NOT q',
          'NOT p OR NOT q',
          'p OR q',
          'NOT p AND q',
        ],
        correct: 'B',
        why: {
          A: 'This is true only when both are false, which is narrower than the original.',
          B: 'The original is false only when both are true, so it is true whenever at least one is false, which is exactly NOT p OR NOT q.',
          C: 'This drops the negation entirely and is true in the wrong cases.',
          D: 'Negating only one operand changes the meaning completely.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display?',
        code: 'age <- 16\nhasPass <- false\nIF ((age >= 16) OR hasPass)\n{\n  DISPLAY "allowed"\n}\nELSE\n{\n  DISPLAY "denied"\n}',
        options: ['allowed', 'denied', 'true', 'Nothing is displayed'],
        correct: 'A',
        why: {
          A: 'OR needs only one true operand. age >= 16 is true, so the condition holds regardless of hasPass.',
          B: 'This would require both operands to be false.',
          C: 'The program displays the string in the branch, not the value of the condition.',
          D: 'Every path through this IF and ELSE displays something.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A program should admit anyone who is NOT both under 13 and unaccompanied.',
        stem: 'Which condition correctly admits a visitor?',
        options: [
          'NOT (age < 13) AND NOT accompanied',
          'NOT (age < 13 AND NOT accompanied)',
          'age < 13 OR accompanied',
          'NOT age < 13 OR NOT accompanied',
        ],
        correct: 'B',
        why: {
          A: 'This requires both that the visitor is 13 or older and that they are unaccompanied, which turns away accompanied adults.',
          B: 'The rule negates the whole compound condition, so the NOT wraps the entire AND expression exactly as written.',
          C: 'This admits every child, which is the opposite of the rule.',
          D: 'Without parentheses this negates only the first comparison and changes the meaning.',
        },
      },
      {
        tag: 'Transfer',
        stem: 'A condition is written as (score > 90) AND (score > 50). Which simpler expression is equivalent?',
        options: ['score > 50', 'score > 90', 'score > 140', 'score = 90'],
        correct: 'B',
        why: {
          A: 'Values between 51 and 90 satisfy this but fail the original.',
          B: 'Any score above 90 is already above 50, so the second test never rejects anything the first accepted. The stricter condition absorbs the looser one.',
          C: 'Thresholds are not added together when conditions are combined.',
          D: 'The original excludes exactly 90 rather than selecting it.',
        },
      },
    ],
  },

  {
    slug: 'conditionals',
    title: 'Conditionals',
    blurb: 'Six traces where the branch taken depends on a boundary value.',
    brief: 'Boundary values are where conditionals break and where the exam aims. Every question here puts a value on or next to a boundary.',
    seo: 'Applied AP CSP 3.6 practice: six trace questions on IF and ELSE branching, boundary values, and which branch of a conditional actually executes.',
    questions: [
      {
        tag: 'Trace',
        predict: 'which branch runs when the value sits exactly on the boundary?',
        stem: 'What does this segment display when temp is 32?',
        code: 'IF (temp > 32)\n{\n  DISPLAY "above"\n}\nELSE\n{\n  DISPLAY "at or below"\n}',
        options: ['above', 'at or below', 'Both are displayed', 'Nothing is displayed'],
        correct: 'B',
        why: {
          A: 'Strict greater than excludes 32 itself, so the condition is false.',
          B: '32 is not greater than 32, so the condition is false and the ELSE branch runs.',
          C: 'IF and ELSE are mutually exclusive. Exactly one runs.',
          D: 'One of the two branches always runs when an ELSE is present.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display when n is 7?',
        code: 'IF (n MOD 2 = 0)\n{\n  DISPLAY "even"\n}\nELSE\n{\n  DISPLAY "odd"\n}',
        options: ['even', 'odd', '1', '7'],
        correct: 'B',
        why: {
          A: '7 divided by 2 leaves a remainder of 1, so the condition is false.',
          B: 'The remainder is 1, not 0, so the ELSE branch runs and displays odd.',
          C: 'The remainder is computed but is not what gets displayed.',
          D: 'The value of n is not displayed by either branch.',
        },
      },
      {
        tag: 'Debug',
        scenario: 'A grading program gives an A for 90 and above, but a student scoring exactly 90 receives a B.',
        stem: 'Which condition most likely appears in the code?',
        options: [
          'IF (score >= 90)',
          'IF (score > 90)',
          'IF (score = 90)',
          'IF (score < 90)',
        ],
        correct: 'B',
        why: {
          A: 'This is the correct condition and would award the A.',
          B: 'Strictly greater than excludes the boundary, which is exactly the reported symptom: 90 falls through to the next branch.',
          C: 'This would award an A only for exactly 90, which is the opposite failure.',
          D: 'This reverses the comparison and would give an A to every failing score.',
        },
      },
      {
        tag: 'Apply',
        stem: 'A program charges 0 dollars under 5 years old, 8 dollars from 5 to 64, and 5 dollars at 65 and above. Which set of conditions is correct and non overlapping?',
        options: [
          'IF age < 5, ELSE IF age < 65, ELSE',
          'IF age < 5, ELSE IF age > 65, ELSE',
          'IF age <= 5, ELSE IF age <= 65, ELSE',
          'IF age < 5, ELSE IF age >= 5, ELSE IF age >= 65',
        ],
        correct: 'A',
        why: {
          A: 'Each test runs only when the previous ones failed, so the second covers 5 through 64 and the final ELSE covers 65 and up exactly.',
          B: 'This sends a 65 year old to the final branch by accident and mislabels the boundary.',
          C: 'The first test captures 5 year olds, who should pay 8, and the second captures 65 year olds, who should pay 5.',
          D: 'The second condition is always true once the first fails, so the third branch can never run.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display when x is 4?',
        code: 'IF (x > 10)\n{\n  DISPLAY "big"\n}\nIF (x > 2)\n{\n  DISPLAY "medium"\n}',
        options: ['big', 'medium', 'big and medium', 'Nothing is displayed'],
        correct: 'B',
        why: {
          A: '4 is not greater than 10, so the first condition is false.',
          B: 'These are two independent IF statements. The first is false and the second is true, so only medium is displayed.',
          C: 'Both would display only if both conditions were true.',
          D: 'The second condition holds for 4, so something is displayed.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program has an IF with no ELSE, and testing shows nothing happens for certain inputs.',
        stem: 'Which statement is accurate?',
        options: [
          'This is a syntax error, since every IF requires an ELSE',
          'This is defined behavior: when the condition is false, the block is skipped and execution continues, which may or may not be what was intended',
          'This is a runtime error that halts the program',
          'The IF will run anyway to guarantee output',
        ],
        correct: 'B',
        why: {
          A: 'An ELSE is optional in every language the course covers.',
          B: 'Skipping the block is exactly what a false condition means. Whether that is a bug depends on the requirement, not on the language.',
          C: 'Nothing halts. The program continues past the IF.',
          D: 'A false condition means the block does not run. There is no fallback.',
        },
      },
    ],
  },
];
