'use strict';
// Big Idea 3: Algorithms and Programming, topics 3.7 to 3.12.
// Applied challenge: tracing, loop bounds, and the two places students lose the
// most points on the exam, nested conditional order and off by one loop counts.
// Pure ASCII, no em-dashes. Zero PII: author content only.

module.exports = [
  {
    slug: 'nested-conditionals',
    title: 'Nested Conditionals',
    blurb: 'Six traces where the ORDER of the tests, not the tests themselves, decides the answer.',
    brief: 'A nested conditional whose branches are all individually correct can still be wrong overall. Order is the whole subject here.',
    seo: 'Applied AP CSP 3.7 practice: six trace questions on nested conditionals, branch ordering, and unreachable branches in multi-way decisions.',
    questions: [
      {
        tag: 'Debug',
        scenario: 'A grading program always reports C for every passing score.',
        stem: 'What is wrong with this segment?',
        code: 'IF (score >= 70)\n{\n  DISPLAY "C"\n}\nELSE IF (score >= 80)\n{\n  DISPLAY "B"\n}\nELSE IF (score >= 90)\n{\n  DISPLAY "A"\n}',
        options: [
          'The comparisons should use greater than rather than greater than or equal',
          'The branches are ordered from lowest threshold to highest, so the first test captures every score that any later test would have matched',
          'ELSE IF is not valid after an IF',
          'The DISPLAY statements are in the wrong branches',
        ],
        correct: 'B',
        why: {
          A: 'The comparison operators are correct. The sequence they appear in is not.',
          B: 'ELSE IF only runs when every earlier test failed, so a broad first test makes the stricter later tests unreachable. Ordering from highest threshold down fixes it.',
          C: 'ELSE IF chains are entirely valid.',
          D: 'Each label matches its own threshold. The problem is which threshold is tested first.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display when age is 20 and hasTicket is false?',
        code: 'IF (age >= 18)\n{\n  IF (hasTicket)\n  {\n    DISPLAY "enter"\n  }\n  ELSE\n  {\n    DISPLAY "buy ticket"\n  }\n}\nELSE\n{\n  DISPLAY "too young"\n}',
        options: ['enter', 'buy ticket', 'too young', 'Nothing is displayed'],
        correct: 'B',
        why: {
          A: 'Entering requires the inner condition to be true, and hasTicket is false.',
          B: 'The outer test passes because 20 is at least 18, so control moves inside, where the false inner test selects the ELSE.',
          C: 'This branch runs only when the outer test fails, which it does not.',
          D: 'Every path here reaches a DISPLAY.',
        },
      },
      {
        tag: 'Analyze',
        stem: 'In an ELSE IF chain, when does the third branch execute?',
        options: [
          'Whenever its own condition is true, regardless of the earlier ones',
          'Only when the first two conditions were false AND its own condition is true',
          'Always, after the first matching branch runs',
          'Only when all three conditions are true',
        ],
        correct: 'B',
        why: {
          A: 'This describes separate IF statements, not a chain.',
          B: 'A chain is exclusive. Reaching a later branch means every earlier test already failed, and then its own test must still pass.',
          C: 'Once a branch runs, the rest of the chain is skipped entirely.',
          D: 'A chain never requires multiple conditions to hold at once.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which ordering correctly assigns A for 90 and above, B for 80 to 89, and C for 70 to 79?',
        options: [
          'Test >= 70 first, then >= 80, then >= 90',
          'Test >= 90 first, then >= 80, then >= 70',
          'Test = 90 first, then = 80, then = 70',
          'Test >= 80 first, then >= 90, then >= 70',
        ],
        correct: 'B',
        why: {
          A: 'The broadest test first swallows every score, which is the classic bug.',
          B: 'Starting from the strictest threshold means each later branch is only reached by scores the earlier ones already excluded.',
          C: 'Equality matches three individual scores and nothing else.',
          D: 'The 80 test runs before the 90 test, so a 95 is labeled B.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display when n is 12?',
        code: 'IF (n MOD 3 = 0)\n{\n  IF (n MOD 4 = 0)\n  {\n    DISPLAY "both"\n  }\n  ELSE\n  {\n    DISPLAY "three only"\n  }\n}\nELSE\n{\n  DISPLAY "neither"\n}',
        options: ['both', 'three only', 'neither', 'four only'],
        correct: 'A',
        why: {
          A: '12 divides evenly by 3 and by 4, so the outer test passes and the inner test passes too.',
          B: 'This runs only when the inner test fails, and 12 MOD 4 is 0.',
          C: 'This requires the outer test to fail, and 12 MOD 3 is 0.',
          D: 'The structure never reaches a four only case, since the outer test gates everything.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student replaces a nested conditional with a single condition using AND.',
        stem: 'When is that rewrite safe?',
        options: [
          'Always, since AND and nesting are interchangeable',
          'When the inner conditional has no ELSE, so the only outcome that matters is both conditions being true',
          'Only when the two conditions test the same variable',
          'Never, since nesting and AND behave differently',
        ],
        correct: 'B',
        why: {
          A: 'An inner ELSE has no equivalent in a flattened AND, so the rewrite loses a case.',
          B: 'With no inner ELSE, the only path that produces an action is both tests passing, which is exactly what AND expresses.',
          C: 'Which variables are tested does not affect whether the rewrite preserves behavior.',
          D: 'The rewrite is safe in the common no ELSE case, so a blanket never is wrong.',
        },
      },
    ],
  },

  {
    slug: 'iteration',
    title: 'Iteration',
    blurb: 'Six loops. Count the iterations before you count anything else.',
    brief: 'Off by one is the single most common loop error on the exam. Every question here can be settled by counting passes carefully.',
    seo: 'Applied AP CSP 3.8 practice: six trace questions on REPEAT and REPEAT UNTIL loops, iteration counts, accumulation, and infinite loop conditions.',
    questions: [
      {
        tag: 'Trace',
        stem: 'What does this segment display?',
        code: 'i <- 1\ntotal <- 0\nREPEAT UNTIL (i > 4)\n{\n  total <- total + i\n  i <- i + 1\n}\nDISPLAY total',
        options: ['4', '10', '15', '6'],
        correct: 'B',
        why: {
          A: '4 is the last value added, not the running total.',
          B: 'The loop adds 1, 2, 3, and 4 before i reaches 5 and the condition stops it, giving 10.',
          C: '15 would include 5, but the loop exits before adding it.',
          D: '6 stops one iteration early, at 1 plus 2 plus 3.',
        },
      },
      {
        tag: 'Trace',
        stem: 'How many times does the body of this loop execute?',
        code: 'count <- 0\nREPEAT 5 TIMES\n{\n  count <- count + 1\n}',
        options: ['4', '5', '6', 'It depends on count'],
        correct: 'B',
        why: {
          A: '4 undercounts. REPEAT n TIMES runs exactly n passes.',
          B: 'REPEAT 5 TIMES is an exact count, independent of anything in the body.',
          C: '6 overcounts by one, which is the usual result of counting the check that ends the loop as a pass.',
          D: 'The body changing count has no effect on how many times a REPEAT n TIMES loop runs.',
        },
      },
      {
        tag: 'Debug',
        scenario: 'A loop never ends.',
        stem: 'Which change fixes it?',
        code: 'i <- 1\nREPEAT UNTIL (i > 3)\n{\n  DISPLAY i\n}',
        options: [
          'Change the condition to i >= 3',
          'Add i <- i + 1 inside the loop body so the condition can eventually become true',
          'Move the DISPLAY outside the loop',
          'Change REPEAT UNTIL to REPEAT 3 TIMES and leave the body alone',
        ],
        correct: 'B',
        why: {
          A: 'The condition is fine. Nothing in the body ever changes i, so no comparison would ever become true.',
          B: 'A condition based loop needs the body to make progress toward the exit condition. Incrementing i is that progress.',
          C: 'Removing the display leaves an empty loop that still never ends.',
          D: 'This does terminate, but it is a different loop rather than a fix to the described bug, and it still never advances i.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which loop displays exactly the values 1, 2, and 3?',
        options: [
          'i <- 0, REPEAT UNTIL (i > 3), display i then add 1',
          'i <- 1, REPEAT UNTIL (i > 3), display i then add 1',
          'i <- 1, REPEAT UNTIL (i >= 3), display i then add 1',
          'i <- 1, REPEAT UNTIL (i > 4), display i then add 1',
        ],
        correct: 'B',
        why: {
          A: 'Starting at 0 displays 0, 1, 2, and 3.',
          B: 'Starting at 1 and stopping once i passes 3 displays exactly 1, 2, and 3.',
          C: 'The loop exits as soon as i reaches 3, so 3 is never displayed.',
          D: 'This continues through 4.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this segment display?',
        code: 'n <- 16\nsteps <- 0\nREPEAT UNTIL (n = 1)\n{\n  n <- n / 2\n  steps <- steps + 1\n}\nDISPLAY steps',
        options: ['2', '4', '8', '16'],
        correct: 'B',
        why: {
          A: '2 stops after reaching 4.',
          B: '16 halves to 8, 4, 2, and 1, which is four steps.',
          C: '8 is the value after one halving, not the step count.',
          D: '16 is the starting value.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A loop processes every element of a list whose length changes at runtime.',
        stem: 'Which loop form is appropriate, and why?',
        options: [
          'REPEAT 100 TIMES, because 100 is a safe upper bound',
          'A FOR EACH loop over the list, because it visits exactly the elements present without needing the count in advance',
          'A REPEAT UNTIL loop with no condition, because the list length is unknown',
          'No loop, because loops require a known count',
        ],
        correct: 'B',
        why: {
          A: 'A fixed count either runs past the end of a short list or misses part of a long one.',
          B: 'FOR EACH is defined in terms of the list itself, so the iteration count follows the data rather than a constant written in the code.',
          C: 'A loop with no exit condition never terminates.',
          D: 'Loops handle unknown counts routinely, which is much of what they are for.',
        },
      },
    ],
  },

  {
    slug: 'developing-algorithms',
    title: 'Developing Algorithms',
    blurb: 'Six algorithm designs where two versions produce different results and you must say which and why.',
    brief: 'These stop being trace questions and start being design questions. The answer is usually about what happens on the empty or single element case.',
    seo: 'Applied AP CSP 3.9 practice: six questions on algorithm design, combining sequencing, selection, and iteration, and comparing algorithm outcomes.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'An algorithm finds the largest value in a list by setting max to 0 and comparing each element.',
        stem: 'On which input does it fail, and why?',
        options: [
          'A list of all positive numbers, because 0 is smaller than all of them',
          'A list of all negative numbers, because no element is greater than the starting value of 0, so it reports 0, which is not in the list',
          'A list with exactly one element, because a loop cannot run once',
          'A sorted list, because the maximum is already at the end',
        ],
        correct: 'B',
        why: {
          A: 'Positive lists work correctly, since some element exceeds 0.',
          B: 'Seeding with a constant assumes something in the list beats it. Initializing max to the first element instead removes the assumption.',
          C: 'A loop runs once over a one element list without difficulty.',
          D: 'Sorted input is the easy case, not a failure case.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this algorithm display for the list [3, 9, 2]?',
        code: 'best <- list[1]\nFOR EACH v IN list\n{\n  IF (v > best)\n  {\n    best <- v\n  }\n}\nDISPLAY best',
        options: ['3', '9', '2', '14'],
        correct: 'B',
        why: {
          A: '3 is the seed value, which is replaced when a larger element appears.',
          B: 'Seeding with the first element and replacing it whenever a larger one appears leaves 9, the maximum.',
          C: '2 is the smallest element and never becomes best.',
          D: '14 is the sum, which this algorithm never computes.',
        },
      },
      {
        tag: 'Apply',
        stem: 'An algorithm must count how many values in a list are above 10. Which structure is correct?',
        options: [
          'Set count to 0, then for each value add the value to count if it is above 10',
          'Set count to 0, then for each value add 1 to count if it is above 10',
          'Set count to the list length, then subtract 1 for each value above 10',
          'Set count to 0, then add 1 to count for every value in the list',
        ],
        correct: 'B',
        why: {
          A: 'Adding the values produces a sum of the qualifying values rather than a count of them.',
          B: 'A counter increments by one per qualifying element, which is exactly what counting means.',
          C: 'This counts the values that are NOT above 10.',
          D: 'This counts every element and ignores the condition.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'Two algorithms both compute the sum of a list. One uses a loop, the other adds the elements by index in fixed statements.',
        stem: 'Which comparison is accurate?',
        options: [
          'They produce different results',
          'They produce the same result, but only the loop works for a list whose length is not known when the code is written',
          'The fixed statement version is always faster',
          'Only the loop version can be written in AP pseudocode',
        ],
        correct: 'B',
        why: {
          A: 'For a list of the length the fixed version was written for, both compute the same sum.',
          B: 'Generality is the difference. A loop expresses the algorithm for any length, while fixed statements encode one specific length.',
          C: 'Speed is essentially the same, and it is not the meaningful difference.',
          D: 'Both can be expressed in AP pseudocode.',
        },
      },
      {
        tag: 'Trace',
        stem: 'What does this algorithm display for the list [5, 5, 5]?',
        code: 'count <- 0\nFOR EACH v IN list\n{\n  IF (v = 5)\n  {\n    count <- count + 1\n  }\n}\nDISPLAY count',
        options: ['1', '3', '5', '15'],
        correct: 'B',
        why: {
          A: '1 would result if the loop stopped after the first match.',
          B: 'Every element matches, and there are three of them, so the counter reaches 3.',
          C: '5 is the element value rather than how many there are.',
          D: '15 is the sum of the elements, not a count.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'An algorithm must return the average of a list that may be empty.',
        stem: 'Which design handles the empty case correctly?',
        options: [
          'Divide the sum by the length in every case',
          'If the length is 0, return a defined result such as 0 or a no data indicator, otherwise divide the sum by the length',
          'Add 1 to the length before dividing so the divisor is never 0',
          'Skip the empty case, since an empty list will not occur in practice',
        ],
        correct: 'B',
        why: {
          A: 'An empty list makes the divisor 0, which stops the program.',
          B: 'Guarding the degenerate case before the division is the standard fix, and it makes the empty result an explicit decision rather than a crash.',
          C: 'Adding 1 avoids the crash by computing a wrong average for every non empty list.',
          D: 'Assuming an input cannot occur is how the crash gets shipped.',
        },
      },
    ],
  },

  {
    slug: 'lists',
    title: 'Lists',
    blurb: 'Six list operations where the index, not the value, is what the question turns on.',
    brief: 'AP pseudocode indexes from 1. Every distractor in this bank is what you get from indexing from 0 or from forgetting that the list shifts.',
    seo: 'Applied AP CSP 3.10 practice: six questions on list indexing from 1, APPEND, INSERT, REMOVE, LENGTH, and how lists shift after removal.',
    questions: [
      {
        tag: 'Trace',
        stem: 'The list nums holds [10, 20, 30, 40]. What is nums[3]?',
        options: ['20', '30', '40', '3'],
        correct: 'B',
        why: {
          A: '20 is nums[2] under AP pseudocode indexing.',
          B: 'AP pseudocode indexes from 1, so the third element is 30.',
          C: '40 is nums[4], the fourth element, which is what index 3 would give in a language that counts from 0.',
          D: 'The index itself is not the value stored there.',
        },
      },
      {
        tag: 'Trace',
        stem: 'The list L holds [7, 8, 9]. After REMOVE(L, 1), what does L hold and what is LENGTH(L)?',
        options: [
          '[8, 9] and 2',
          '[7, 9] and 2',
          '[7, 8] and 2',
          '[7, 8, 9] and 3',
        ],
        correct: 'A',
        why: {
          A: 'Removing at index 1 takes out the first element, and the remaining elements shift down to fill positions 1 and 2.',
          B: 'This removes the middle element, which would be index 2.',
          C: 'This removes the last element, which would be index 3.',
          D: 'REMOVE changes the list rather than leaving it alone.',
        },
      },
      {
        tag: 'Apply',
        stem: 'The list L holds [1, 2, 3]. What does L hold after APPEND(L, 4) followed by INSERT(L, 1, 0)?',
        options: [
          '[0, 1, 2, 3, 4]',
          '[1, 2, 3, 4, 0]',
          '[0, 1, 2, 3]',
          '[1, 0, 2, 3, 4]',
        ],
        correct: 'A',
        why: {
          A: 'APPEND puts 4 at the end, then INSERT at index 1 places 0 at the front and shifts everything else right.',
          B: 'This appends both values instead of inserting the second at index 1.',
          C: 'This drops the appended 4.',
          D: 'Inserting at index 1 places the value before the current first element, not after it.',
        },
      },
      {
        tag: 'Debug',
        scenario: 'A loop over a list of length 5 crashes on its last pass.',
        stem: 'Which loop bound is the likely cause?',
        options: [
          'Iterating i from 1 to LENGTH(list)',
          'Iterating i from 1 to LENGTH(list) + 1, which accesses an index past the end',
          'Iterating i from 1 to LENGTH(list) - 1',
          'Using FOR EACH over the list',
        ],
        correct: 'B',
        why: {
          A: 'This is the correct bound for 1 based indexing and does not crash.',
          B: 'Reaching index 6 on a 5 element list is an access past the end, which is the crash described.',
          C: 'This stops one element early, which silently skips the last element rather than crashing.',
          D: 'FOR EACH cannot run past the end, since it is defined by the list itself.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program removes elements from a list while looping over it by index from 1 upward.',
        stem: 'What goes wrong?',
        options: [
          'Nothing, since removal and iteration are independent',
          'Each removal shifts later elements down, so the index advances past an element that moved into the position just processed, and elements get skipped',
          'The list becomes read only after the first removal',
          'The loop runs forever',
        ],
        correct: 'B',
        why: {
          A: 'Removal changes the positions the loop is indexing into, so they are not independent at all.',
          B: 'When an element is removed, the next element slides into the current index while the loop moves to the next index, so that element is never examined.',
          C: 'Removal does not lock the list.',
          D: 'The loop terminates. It simply skips elements on the way.',
        },
      },
      {
        tag: 'Transfer',
        stem: 'Which expression accesses the LAST element of a list named L, regardless of its length?',
        options: ['L[0]', 'L[1]', 'L[LENGTH(L)]', 'L[LENGTH(L) - 1]'],
        correct: 'C',
        why: {
          A: 'AP pseudocode has no index 0.',
          B: 'Index 1 is the first element.',
          C: 'With 1 based indexing, the number of elements is also the index of the last one.',
          D: 'This is the correct form for 0 based languages, where it lands one short here.',
        },
      },
    ],
  },

  {
    slug: 'binary-search',
    title: 'Binary Search',
    blurb: 'Six questions on when binary search applies, and how few steps it actually needs.',
    brief: 'The first thing the exam checks is whether you noticed the list was unsorted. The second is whether you can count halvings.',
    seo: 'Applied AP CSP 3.11 practice: six questions on binary search prerequisites, step counts, and comparing binary search to sequential search.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A student applies binary search to the list [9, 2, 7, 4, 1].',
        stem: 'What is the problem?',
        options: [
          'The list is too short for binary search',
          'The list is not sorted, and binary search depends on order to decide which half to discard',
          'Binary search cannot handle five elements',
          'Binary search requires an even number of elements',
        ],
        correct: 'B',
        why: {
          A: 'Length is not the requirement, and five elements are plenty.',
          B: 'Discarding half the list is only valid if order guarantees the target cannot be in the discarded half. Without sorting, that guarantee is gone.',
          C: 'Any length works on a sorted list.',
          D: 'Odd and even lengths are both fine.',
        },
      },
      {
        tag: 'Apply',
        stem: 'About how many comparisons does binary search need in the worst case on a sorted list of 1,000 elements?',
        options: ['About 10', 'About 100', 'About 500', 'About 1,000'],
        correct: 'A',
        why: {
          A: 'Each comparison halves the range, and roughly ten halvings reduce 1,000 to 1.',
          B: '100 would apply if each step removed a fixed tenth rather than half.',
          C: '500 is one halving, not the whole search.',
          D: '1,000 is the worst case for sequential search.',
        },
      },
      {
        tag: 'Trace',
        scenario: 'Binary search runs on [2, 5, 8, 12, 16, 23, 38] looking for 23.',
        stem: 'Which element is examined first, and which half survives?',
        options: [
          '2 is examined first, and the right half survives',
          '12 is examined first, and the right half survives',
          '12 is examined first, and the left half survives',
          '38 is examined first, and the left half survives',
        ],
        correct: 'B',
        why: {
          A: 'Binary search starts at the middle, not at the first element.',
          B: 'The middle of seven elements is the fourth, which is 12. Since 23 is larger, everything at or below 12 is discarded.',
          C: 'The target is larger than the middle, so the left half is the half discarded.',
          D: 'The last element is not the starting point.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A list of 20 elements will be searched once, and it is unsorted.',
        stem: 'Which approach is more sensible, and why?',
        options: [
          'Sort it, then binary search, because binary search is always faster',
          'Sequential search, because sorting to enable one binary search costs more work than simply scanning 20 elements',
          'Binary search without sorting, since 20 elements is small enough for the order not to matter',
          'Neither, since a list this small cannot be searched',
        ],
        correct: 'B',
        why: {
          A: 'Binary search is faster per search, but the sort has to be paid for first, and one search does not repay it.',
          B: 'The comparison is total work, not per search speed. Sorting to run a single search on a short list is a net loss.',
          C: 'Running binary search on unsorted data produces wrong answers regardless of size.',
          D: 'A 20 element list is trivially searchable.',
        },
      },
      {
        tag: 'Transfer',
        stem: 'Doubling the size of a sorted list adds how many comparisons to a worst case binary search?',
        options: [
          'It doubles the number of comparisons',
          'It adds about one comparison',
          'It adds no comparisons',
          'It squares the number of comparisons',
        ],
        correct: 'B',
        why: {
          A: 'Doubling the comparisons is what happens to sequential search, not binary search.',
          B: 'One extra halving is enough to cut a doubled list back to the previous size, so the cost grows by about one step.',
          C: 'The cost does grow, just very slowly.',
          D: 'Nothing here squares. Squaring would mean the cost grew far faster than the list, which is the opposite of what halving does.',
        },
      },
      {
        tag: 'Apply',
        stem: 'What must be true of a list before binary search will return correct results?',
        options: [
          'It must contain only numbers',
          'It must be sorted in a known order',
          'It must have an even number of elements',
          'It must contain no duplicate values',
        ],
        correct: 'B',
        why: {
          A: 'Any ordered data type works, including text.',
          B: 'Sorted order is the single prerequisite, because it is what makes discarding half the list safe.',
          C: 'Element count parity is irrelevant.',
          D: 'Duplicates are fine. The search still finds a matching value.',
        },
      },
    ],
  },

  {
    slug: 'calling-procedures',
    title: 'Calling Procedures',
    blurb: 'Six calls where the argument order, the return value, or the scope decides the answer.',
    brief: 'Calling a procedure is easy. Knowing what comes back, and what the caller can see afterwards, is where the points are.',
    seo: 'Applied AP CSP 3.12 practice: six questions on calling procedures, passing arguments in order, using return values, and variable scope.',
    questions: [
      {
        tag: 'Trace',
        stem: 'Given PROCEDURE divide(a, b) that returns a / b, what does DISPLAY divide(20, 4) show?',
        options: ['5', '0.2', '80', '24'],
        correct: 'A',
        why: {
          A: 'Arguments bind in order, so a is 20 and b is 4, giving 5.',
          B: '0.2 comes from reversing the arguments.',
          C: '80 is the product rather than the quotient.',
          D: '24 is the sum of the two arguments, and the procedure body divides rather than adds.',
        },
      },
      {
        tag: 'Debug',
        scenario: 'A student calls a procedure that returns a value but nothing appears on screen.',
        stem: 'What is most likely missing?',
        code: 'PROCEDURE doubleIt(n)\n{\n  RETURN n * 2\n}\n\ndoubleIt(5)',
        options: [
          'The procedure needs a DISPLAY inside it, since RETURN does not print',
          'The call result is never used, so it should be displayed or stored, for example DISPLAY doubleIt(5)',
          'The procedure must be called twice',
          'RETURN cannot be used with a parameter',
        ],
        correct: 'B',
        why: {
          A: 'Adding a DISPLAY inside works, but it changes the procedure into one that can only print, which is a worse design than using the value the caller already receives.',
          B: 'A returned value goes back to the caller and is discarded unless the caller does something with it. Displaying or storing it is the fix.',
          C: 'Calling twice discards the result twice.',
          D: 'Returning an expression built from a parameter is the normal case.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A procedure declares a variable inside its body, and the caller tries to display it afterwards.',
        stem: 'What happens and why?',
        options: [
          'The value displays normally, since all variables are shared',
          'The caller cannot see it, because a variable declared inside a procedure exists only within that procedure',
          'The procedure automatically returns it',
          'The program displays 0',
        ],
        correct: 'B',
        why: {
          A: 'Variables are not globally shared by default, and relying on that is what scope rules prevent.',
          B: 'Scope limits a local variable to the procedure that declared it, which is what makes procedures safe to reuse without collisions.',
          C: 'A procedure returns only what its RETURN statement names.',
          D: 'There is no value to display, which is a different situation from displaying zero.',
        },
      },
      {
        tag: 'Apply',
        stem: 'A procedure is defined as PROCEDURE rectArea(width, height). Which call computes the area of a rectangle 3 wide and 8 tall?',
        options: ['rectArea(8, 3)', 'rectArea(3, 8)', 'rectArea(24)', 'rectArea(width, height)'],
        correct: 'B',
        why: {
          A: 'This passes the height first, which binds it to width.',
          B: 'Arguments bind to parameters in the order written, so width receives 3 and height receives 8.',
          C: 'The procedure takes two arguments, not a precomputed result.',
          D: 'Passing the parameter names is not how a call supplies values.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'The same twelve lines appear in four places in a program.',
        stem: 'What is the strongest argument for moving them into a procedure?',
        options: [
          'The program will execute more quickly',
          'A change to that logic then happens in one place instead of four, which removes the chance that three copies get updated and one does not',
          'Procedures use less memory than repeated lines',
          'The program will have fewer variables',
        ],
        correct: 'B',
        why: {
          A: 'A procedure call is not faster than inline code, and may be marginally slower.',
          B: 'Duplication makes divergence possible. One definition means a fix cannot be applied partially.',
          C: 'Memory use is not the argument, and the difference is negligible.',
          D: 'The variable count is not what changes.',
        },
      },
      {
        tag: 'Transfer',
        stem: 'What is the difference between a procedure that returns a value and one that does not?',
        options: [
          'A procedure that returns a value cannot take parameters',
          'A returning procedure produces a result the caller can use in an expression, while a non returning one performs an action and yields nothing to use',
          'A procedure that returns a value can only be called once',
          'There is no difference in how they are called',
        ],
        correct: 'B',
        why: {
          A: 'Returning procedures take parameters routinely.',
          B: 'A return value flows back into the expression at the call site. Without one, the call is a statement performed for its effect.',
          C: 'Either kind can be called any number of times.',
          D: 'The difference shows up exactly in whether the call can appear inside a larger expression.',
        },
      },
    ],
  },
];
