'use strict';
// Big Idea 3: Algorithms and Programming, topics 3.13 to 3.18.
// Applied challenge: abstraction, randomness, simulation, efficiency, and the
// two categories of hard problem. These are the topics students recognize and
// cannot apply, so every stem is a judgement call rather than a definition.
// Pure ASCII, no em-dashes. Zero PII: author content only.

module.exports = [
  {
    slug: 'developing-procedures',
    title: 'Developing Procedures',
    blurb: 'Six design decisions about what belongs in a procedure and what belongs in its parameters.',
    brief: 'Writing a procedure is not the hard part. Deciding its boundary, what it takes in and what it hands back, is what the Create Task is graded on.',
    seo: 'Applied AP CSP 3.13 practice: six questions on designing procedures, choosing parameters, return values, and using abstraction to manage complexity.',
    questions: [
      {
        tag: 'Evaluate',
        scenario: 'A procedure computes sales tax but reads the rate from a variable defined outside it.',
        stem: 'Why is passing the rate as a parameter usually better?',
        options: [
          'Parameters make the procedure execute faster',
          'The procedure becomes usable anywhere, including with a different rate, instead of depending on one specific outside variable existing',
          'Procedures are not allowed to read outside variables',
          'Parameters reduce the number of lines of code',
        ],
        correct: 'B',
        why: {
          A: 'Parameter passing is not a speed optimization.',
          B: 'A procedure that depends on outside state can only be reused where that state exists. Parameters make the dependency explicit and the procedure portable.',
          C: 'Reading outside variables is generally permitted. It is a design weakness, not a rule violation.',
          D: 'The line count is about the same either way.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A program repeatedly converts a letter grade to grade points.',
        stem: 'What is the best procedure signature for that work?',
        options: [
          'A procedure with no parameters that returns nothing',
          'A procedure that takes a letter grade and returns the matching grade points',
          'A procedure that takes no parameters and displays the grade points',
          'A procedure that takes a letter grade and displays the points without returning them',
        ],
        correct: 'B',
        why: {
          A: 'With no input and no output the procedure cannot do the job at all.',
          B: 'The conversion has one input and one result, so it maps cleanly onto one parameter and one return value, which lets callers use the result however they need.',
          C: 'Without a parameter there is nothing to convert.',
          D: 'Displaying instead of returning forces every caller to want printed output, which most will not.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A single procedure validates input, computes a total, formats a receipt, and sends an email.',
        stem: 'What is the strongest specific objection?',
        options: [
          'The procedure has too many lines to compile',
          'It does four separable jobs, so no caller can reuse one of them, and a change to any one job risks the other three',
          'Procedures may perform at most two operations',
          'It will run more slowly than four separate procedures',
        ],
        correct: 'B',
        why: {
          A: 'Length has no compilation limit here.',
          B: 'Bundling independent responsibilities destroys reuse and couples unrelated changes, which is the practical cost of a missing abstraction boundary.',
          C: 'No such rule exists. This is a design principle, not a limit.',
          D: 'Splitting it does not make it faster. The gain is in reuse and maintainability.',
        },
      },
      {
        tag: 'Trace',
        stem: 'Given the procedure below, what does DISPLAY classify(45) show?',
        code: 'PROCEDURE classify(n)\n{\n  IF (n MOD 2 = 0)\n  {\n    RETURN "even"\n  }\n  ELSE\n  {\n    RETURN "odd"\n  }\n}',
        options: ['even', 'odd', '45', '1'],
        correct: 'B',
        why: {
          A: '45 divided by 2 leaves a remainder, so the first branch is not taken.',
          B: '45 MOD 2 is 1, which is not 0, so the ELSE branch returns odd and the caller displays it.',
          C: 'The argument is not what the procedure returns.',
          D: 'The remainder is computed internally but is not the return value.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A team member is told to use a procedure written by someone else.',
        stem: 'What do they need to know, and what can they safely not know?',
        options: [
          'They need the full implementation, and cannot use it without reading every line',
          'They need its name, what arguments it takes, and what it returns, and they do not need to know how it computes that internally',
          'They need only the name, since arguments can be inferred',
          'They need nothing, since procedures document themselves',
        ],
        correct: 'B',
        why: {
          A: 'Requiring the implementation defeats the purpose of the abstraction.',
          B: 'The interface, meaning name, inputs, and output, is the contract. Hiding the implementation behind it is exactly what procedural abstraction provides.',
          C: 'Argument order and meaning cannot be guessed and are part of the contract.',
          D: 'A procedure without a stated interface is precisely the one that gets misused.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student writes one procedure for the Create Task and it takes no parameters.',
        stem: 'Why is this likely to lose credit on the student developed procedure requirement?',
        options: [
          'Procedures must always take exactly two parameters',
          'The task asks for a procedure with a parameter that affects its behavior, and a procedure with no input cannot demonstrate that',
          'A procedure without parameters cannot be called',
          'The procedure will run too quickly to be graded',
        ],
        correct: 'B',
        why: {
          A: 'There is no fixed parameter count required.',
          B: 'The requirement is about a parameter that changes what the procedure does, since that is what shows the abstraction is real rather than decorative.',
          C: 'Parameterless procedures are callable. They simply do the same thing every time.',
          D: 'Execution speed has no bearing on the rubric.',
        },
      },
    ],
  },

  {
    slug: 'libraries',
    title: 'Libraries',
    blurb: 'Six decisions about using existing code, and about what you still owe the reader when you do.',
    brief: 'Using a library is normal and expected. Knowing what it does not free you from, including documentation and attribution, is the tested part.',
    seo: 'Applied AP CSP 3.14 practice: six questions on using libraries and APIs, reading documentation, and attributing borrowed code correctly.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A developer needs to sort a list and a well tested sort already exists in a library.',
        stem: 'What is the strongest reason to use it rather than write one?',
        options: [
          'Library code always runs faster than any code you could write',
          'It removes work that is already solved, and the library version has been tested against cases you would have to discover yourself',
          'Writing your own sort is not permitted on the exam',
          'A library sort uses less memory in every case',
        ],
        correct: 'B',
        why: {
          A: 'A library is often faster but not always, and speed is not the primary argument.',
          B: 'Reuse buys both the implementation and the accumulated testing, which is the part that is expensive to reproduce.',
          C: 'Writing your own is permitted, and is sometimes the right choice.',
          D: 'Memory use varies and is not a general guarantee.',
        },
      },
      {
        tag: 'Analyze',
        stem: 'What does an API provide to a developer?',
        options: [
          'The complete source code of the library',
          'A specification of what the library\'s procedures are called, what they take, and what they return, without requiring knowledge of how they work internally',
          'A guarantee that the library has no defects',
          'Permission to use the library commercially',
        ],
        correct: 'B',
        why: {
          A: 'An API is the interface, and the source may not be available at all.',
          B: 'An API is the contract that lets a developer use code as an abstraction, which is the same relationship a caller has with any procedure.',
          C: 'No interface guarantees correctness.',
          D: 'Usage rights come from a license, which is a separate document.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student copies a procedure from an online forum into their Create Task submission without noting where it came from.',
        stem: 'What is the problem?',
        options: [
          'Copied code always contains errors',
          'Code written by someone else must be attributed, and the student developed procedure requirement must be met by code the student wrote',
          'Online code cannot be used in AP CSP at all',
          'The program will not run without modification',
        ],
        correct: 'B',
        why: {
          A: 'Borrowed code may be perfectly correct. Correctness is not the issue.',
          B: 'Using existing code is allowed and expected, but it must be attributed, and it cannot satisfy a requirement that asks for the student\'s own work.',
          C: 'Using outside code with attribution is explicitly permitted.',
          D: 'It may run perfectly, which is exactly why the attribution rule matters.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A library procedure returns an unexpected result for certain inputs.',
        stem: 'What is the correct first step?',
        options: [
          'Rewrite the library from scratch',
          'Read the documentation to determine what the procedure is specified to do for those inputs, since the behavior may be correct and the assumption wrong',
          'Stop using libraries entirely',
          'Report the library as defective',
        ],
        correct: 'B',
        why: {
          A: 'Rewriting is an enormous response to a misunderstanding that has not been confirmed.',
          B: 'Documentation defines the contract. Most surprises turn out to be a caller expecting something the contract never promised.',
          C: 'One surprise is not a reason to abandon reuse.',
          D: 'Reporting a defect before checking the specification frequently reports the caller\'s own mistake.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which best describes how libraries relate to abstraction?',
        options: [
          'Libraries remove the need for abstraction',
          'A library is abstraction applied at scale: it lets a program use complex functionality through a simple interface without carrying the details',
          'Libraries and abstraction are unrelated concepts',
          'Libraries make programs harder to abstract',
        ],
        correct: 'B',
        why: {
          A: 'A library is an application of abstraction, not a replacement for it.',
          B: 'The interface is the abstraction, and it is what lets a developer use functionality whose implementation they never see.',
          C: 'They are directly related, since a library exists to hide implementation behind an interface.',
          D: 'Libraries support abstraction rather than obstructing it.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'Two libraries both provide a procedure named format.',
        stem: 'What problem can this create, and what generally prevents it?',
        options: [
          'The program will not compile under any circumstances',
          'A name collision, where it is ambiguous which procedure a call refers to, which naming conventions and qualified names prevent',
          'The libraries will overwrite each other on disk',
          'One library will run faster than the other',
        ],
        correct: 'B',
        why: {
          A: 'Most environments resolve this, and it is a resolvable ambiguity rather than a hard failure.',
          B: 'Two identical names in one namespace makes a call ambiguous, and qualifying the name with its library is the standard resolution.',
          C: 'Libraries occupy separate files and do not overwrite one another.',
          D: 'Relative speed has nothing to do with the shared name.',
        },
      },
    ],
  },

  {
    slug: 'random-values',
    title: 'Random Values',
    blurb: 'Six questions about the range RANDOM actually produces, and what randomness does and does not guarantee.',
    brief: 'The range is inclusive on both ends. Half of the exam questions on this topic are decided by that one fact.',
    seo: 'Applied AP CSP 3.15 practice: six questions on the RANDOM procedure, inclusive ranges, probability of outcomes, and testing programs that use randomness.',
    questions: [
      {
        tag: 'Apply',
        stem: 'What values can RANDOM(1, 6) produce?',
        options: [
          'Only 1 and 6',
          'Any integer from 1 through 6, including both 1 and 6',
          'Any integer from 2 through 5',
          'Any integer from 1 through 5',
        ],
        correct: 'B',
        why: {
          A: 'RANDOM produces any value in the range, not only the two endpoints.',
          B: 'The AP pseudocode RANDOM procedure is inclusive at both ends, so all six values are possible.',
          C: 'Excluding both endpoints is not how the procedure is defined.',
          D: 'Excluding the upper bound is the common wrong assumption, borrowed from other languages.',
        },
      },
      {
        tag: 'Trace',
        stem: 'How many distinct values can RANDOM(0, 9) return?',
        options: ['9', '10', '8', '11'],
        correct: 'B',
        why: {
          A: '9 forgets that 0 is included.',
          B: 'The values 0 through 9 inclusive are ten distinct values.',
          C: '8 excludes both endpoints.',
          D: '11 counts one value too many.',
        },
      },
      {
        tag: 'Transfer',
        stem: 'Which expression produces a random even number from 2 through 10 inclusive?',
        options: [
          'RANDOM(2, 10)',
          'RANDOM(1, 5) * 2',
          'RANDOM(2, 10) * 2',
          'RANDOM(1, 10) MOD 2',
        ],
        correct: 'B',
        why: {
          A: 'This produces odd values as well as even ones.',
          B: 'The five values 1 through 5 map onto 2, 4, 6, 8, and 10 when doubled, which is exactly the required set.',
          C: 'Doubling a value already up to 10 reaches 20.',
          D: 'This produces only 0 or 1.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A student runs a program using RANDOM twenty times and gets the value 3 only once out of a 1 through 5 range.',
        stem: 'What is the correct conclusion?',
        options: [
          'The RANDOM procedure is defective',
          'Nothing is necessarily wrong, because random values are not evenly distributed over a small number of trials',
          'The range must be wrong',
          'The program has a logic error',
        ],
        correct: 'B',
        why: {
          A: 'An uneven small sample is the expected behavior of randomness, not evidence of a defect.',
          B: 'Each value is equally likely on each draw, but equal likelihood only shows up as even counts over many trials.',
          C: 'The observed values fall within the range, so nothing indicates a range error.',
          D: 'Nothing in the description points to a defect in the program logic.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A program that uses randomness must be tested.',
        stem: 'What makes testing it harder, and what is a standard response?',
        options: [
          'Random programs cannot be tested, so testing is skipped',
          'Different runs produce different results, so testing focuses on whether every outcome falls within the expected range and on running many trials rather than on a single expected output',
          'Randomness makes the program run too slowly to test',
          'Testing requires removing all randomness permanently',
        ],
        correct: 'B',
        why: {
          A: 'Randomized programs are tested routinely. Skipping is not an option.',
          B: 'The response is to test properties that must hold on every run, such as the range, and to use repetition rather than a single expected value.',
          C: 'Randomness does not meaningfully slow execution.',
          D: 'Fixing the randomness is a useful testing technique, but permanently removing it changes the program.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A simulation should produce heads about half the time.',
        stem: 'Which condition models a fair coin?',
        options: [
          'IF (RANDOM(1, 2) = 1)',
          'IF (RANDOM(1, 3) = 1)',
          'IF (RANDOM(1, 2) > 2)',
          'IF (RANDOM(0, 0) = 0)',
        ],
        correct: 'A',
        why: {
          A: 'Two equally likely values with one selected gives a one in two chance, which is a fair coin.',
          B: 'Three values with one selected is a one in three chance.',
          C: 'No value in the range exceeds 2, so this is never true.',
          D: 'This range has a single value and is always true.',
        },
      },
    ],
  },

  {
    slug: 'simulations',
    title: 'Simulations',
    blurb: 'Six scenarios about when a simulation is the right tool, and what its results are worth.',
    brief: 'A simulation is a model, and every model leaves something out. These questions ask what was left out and whether it mattered.',
    seo: 'Applied AP CSP 3.16 practice: six scenario questions on when to use a simulation, the role of abstraction in models, and the limits of simulated results.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A city wants to know how a new traffic light timing will affect congestion.',
        stem: 'What is the strongest reason to simulate rather than test on the street?',
        options: [
          'A simulation will produce a more accurate answer than the real world',
          'Testing on real streets is expensive, slow, and risks real disruption, while a simulation allows many timings to be tried cheaply',
          'Simulations are required before any traffic change',
          'The real world cannot be measured',
        ],
        correct: 'B',
        why: {
          A: 'A simulation is always less accurate than reality. Its advantage lies elsewhere.',
          B: 'Cost, speed, safety, and the ability to try many variations are the reasons simulations are used, and none of them is accuracy.',
          C: 'No such universal requirement exists.',
          D: 'The real world is measurable. Measuring it is simply slow and costly here.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A simulation of a forest fire ignores wind entirely.',
        stem: 'What is the correct characterization?',
        options: [
          'The simulation is invalid and its results should be discarded',
          'The simulation abstracts away a factor, which makes it simpler and faster but limits how far its results can be trusted where wind matters',
          'The simulation will now run more slowly',
          'The simulation has a logic error that should be fixed before any use',
        ],
        correct: 'B',
        why: {
          A: 'Every simulation omits something. Omission alone does not make results worthless.',
          B: 'Choosing what to leave out is what makes a model a model. The cost is that conclusions do not extend to conditions the model does not represent.',
          C: 'Removing a factor reduces the work rather than increasing it.',
          D: 'A deliberate simplification is a design choice, not a defect.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A simulation run once predicts a 60 percent success rate.',
        stem: 'What is the most accurate statement?',
        options: [
          'The real success rate is 60 percent',
          'One run of a simulation that includes randomness is a single sample, so many runs are needed before the result means much',
          'The simulation is wrong, since real rates are never round numbers',
          'The result applies only to the exact inputs and can never generalize',
        ],
        correct: 'B',
        why: {
          A: 'A simulated rate is an estimate produced by a model, not a measurement of reality.',
          B: 'Randomized simulations vary between runs, so the meaningful result comes from aggregating many runs rather than reading one.',
          C: 'Round numbers are not evidence of an error.',
          D: 'Results do generalize within the range the model represents. The limit is real but not that absolute.',
        },
      },
      {
        tag: 'Transfer',
        stem: 'Which is the clearest example of a problem where a simulation is more appropriate than a direct experiment?',
        options: [
          'Measuring the length of a table',
          'Predicting how a disease spreads through a population over a year',
          'Counting the students in a classroom',
          'Adding two numbers',
        ],
        correct: 'B',
        why: {
          A: 'Direct measurement is immediate and exact.',
          B: 'The real experiment would take a year, cannot be repeated, and cannot ethically be run, which is precisely the situation simulations exist for.',
          C: 'Counting is direct and trivial.',
          D: 'A calculation needs no model.',
        },
      },
      {
        tag: 'Apply',
        scenario: 'A dice simulation always returns 4.',
        stem: 'What is most likely wrong?',
        options: [
          'The simulation is working correctly, since 4 is a possible value',
          'The randomness is missing or fixed, since a working model would produce varied values across runs',
          'The simulation needs more runs before it varies',
          'Dice cannot be simulated',
        ],
        correct: 'B',
        why: {
          A: 'One occurrence of 4 is fine. Every occurrence being 4 is not.',
          B: 'A constant result across many runs means the random draw is not happening, whether because it is outside the loop or fixed to a value.',
          C: 'Variation appears immediately in a working model, not after some threshold.',
          D: 'Dice are among the simplest things to simulate.',
        },
      },
      {
        tag: 'Analyze',
        stem: 'Why do simulations typically use abstraction?',
        options: [
          'To make the results more accurate than reality',
          'Because modeling every detail of a real system would be impossible or impractical, so a model keeps the factors that matter for the question being asked',
          'Because abstraction is required by the College Board',
          'To hide errors in the model from users',
        ],
        correct: 'B',
        why: {
          A: 'Abstraction reduces fidelity. Accuracy is what it trades away.',
          B: 'A model exists to answer a specific question, and abstraction is how it stays small enough to build and run while keeping the relevant factors.',
          C: 'It follows from what a model is, not from a requirement.',
          D: 'Hiding errors is a defect, never a purpose.',
        },
      },
    ],
  },

  {
    slug: 'algorithmic-efficiency',
    title: 'Algorithmic Efficiency',
    blurb: 'Six comparisons between reasonable and unreasonable running times, using concrete input sizes.',
    brief: 'The exam does not ask for formal notation. It asks whether the work grows in step with the input or explodes past it.',
    seo: 'Applied AP CSP 3.17 practice: six questions comparing linear and exponential growth, reasonable running time, and heuristic approaches to hard problems.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'Algorithm A examines each of n items once. Algorithm B examines every pair of items.',
        stem: 'How does the work compare as n grows?',
        options: [
          'Both grow at the same rate',
          'B grows much faster, roughly with the square of n, so doubling the input roughly quadruples B\'s work while doubling A\'s',
          'A grows faster because it runs first',
          'Neither grows, since both examine the same items',
        ],
        correct: 'B',
        why: {
          A: 'One pass and every pair grow at clearly different rates.',
          B: 'Examining every pair means roughly n times n comparisons, so the work scales with the square while a single pass scales directly with n.',
          C: 'Execution order has nothing to do with growth rate.',
          D: 'Both do more work as the input grows.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which describes an algorithm that runs in reasonable time?',
        options: [
          'One that finishes in under one second on every input',
          'One whose work grows at most as a polynomial in the input size, such as linear or squared growth',
          'One that uses no loops',
          'One that always returns the exact optimal answer',
        ],
        correct: 'B',
        why: {
          A: 'Reasonable time describes how work scales with input size, not a fixed wall clock target.',
          B: 'The line the course draws is polynomial growth on one side and exponential or factorial growth on the other.',
          C: 'Loops are unrelated to the classification.',
          D: 'Optimality and running time are separate properties.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A problem can be solved exactly only by checking every possible arrangement, and there are 2 to the n arrangements.',
        stem: 'What happens as n grows, and what is the standard response?',
        options: [
          'The work grows slowly, so the exact approach remains practical',
          'The work grows exponentially and quickly becomes infeasible, so a heuristic is used to find a good enough answer in reasonable time',
          'The problem becomes undecidable',
          'The algorithm must be rewritten in a faster language',
        ],
        correct: 'B',
        why: {
          A: 'Exponential growth is the definition of not remaining practical.',
          B: 'When exact solutions are unreachable at scale, a heuristic trades the guarantee of optimality for an answer that arrives.',
          C: 'Undecidable means no algorithm exists at all, which is a different category from slow.',
          D: 'A faster language shifts the constant factor and does nothing about exponential growth.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A delivery company needs a good route through 40 cities.',
        stem: 'Which characterization is correct?',
        options: [
          'The problem is undecidable, so no route can be found',
          'Finding the guaranteed shortest route is computationally expensive at this size, so a heuristic that finds a short route quickly is the practical approach',
          'The problem has a simple linear time exact solution',
          'The problem cannot be modeled by a computer',
        ],
        correct: 'B',
        why: {
          A: 'Routes are findable. The optimal one is merely expensive to prove.',
          B: 'This is the standard example of a problem where exact optimization scales badly and heuristics are used instead.',
          C: 'No linear time exact solution is known.',
          D: 'It is modeled by computers constantly, which is why heuristics for it are well studied.',
        },
      },
      {
        tag: 'Apply',
        stem: 'An algorithm takes 2 seconds on 1,000 items and 4 seconds on 2,000 items. What growth does this suggest?',
        options: [
          'Exponential growth',
          'Roughly linear growth, since doubling the input roughly doubled the time',
          'Constant time, since the increase is small',
          'Logarithmic growth',
        ],
        correct: 'B',
        why: {
          A: 'Exponential growth on a doubled input would be far more than double the time.',
          B: 'Time scaling in proportion to input size is what linear growth means.',
          C: 'Constant time would show the same duration for both sizes.',
          D: 'Logarithmic growth would add only a small increment rather than doubling.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student says a heuristic gives the wrong answer, so it should never be used.',
        stem: 'What is the correct response?',
        options: [
          'Agreed, since correctness is the only thing that matters',
          'A heuristic gives a good answer that is not guaranteed optimal, which is worth far more than an optimal answer that cannot be computed in time',
          'Heuristics always give the optimal answer anyway',
          'Heuristics apply only to undecidable problems',
        ],
        correct: 'B',
        why: {
          A: 'An exact answer that never finishes solves nothing.',
          B: 'The tradeoff is deliberate: give up the guarantee of optimality to get a usable answer within a practical amount of time.',
          C: 'They sometimes do, but without any guarantee, which is the whole distinction.',
          D: 'Heuristics apply to problems that are decidable but expensive. Undecidable problems have no algorithm at all.',
        },
      },
    ],
  },

  {
    slug: 'undecidable-problems',
    title: 'Undecidable Problems',
    blurb: 'Six questions separating hard from impossible, which is the distinction this topic exists to teach.',
    brief: 'Almost every wrong answer here confuses slow with impossible. An undecidable problem is not one nobody has solved yet.',
    seo: 'Applied AP CSP 3.18 practice: six questions distinguishing undecidable problems from computationally expensive ones, with the halting problem as the model case.',
    questions: [
      {
        tag: 'Analyze',
        stem: 'What makes a problem undecidable?',
        options: [
          'It takes an extremely long time to solve',
          'No algorithm can be constructed that gives a correct yes or no answer for every possible input',
          'It requires more memory than any computer has',
          'Nobody has found an efficient solution yet',
        ],
        correct: 'B',
        why: {
          A: 'A slow problem is still solvable. Time is not the criterion.',
          B: 'Undecidability is about the non existence of any correct general algorithm, not about resources or effort.',
          C: 'A memory limit is a practical constraint, not a proof of impossibility.',
          D: 'An unsolved problem may simply be waiting for a better idea. Undecidable means proven impossible.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student says the traveling salesman problem is undecidable.',
        stem: 'What is the correct correction?',
        options: [
          'The student is right, since no efficient solution exists',
          'It is decidable but computationally expensive: an exact algorithm exists and simply takes impractically long at scale',
          'It is undecidable only for large inputs',
          'It is neither decidable nor undecidable',
        ],
        correct: 'B',
        why: {
          A: 'Lacking an efficient solution is not the same as lacking any solution.',
          B: 'Checking every route is a correct algorithm, so the problem is decidable. Its cost is what makes it impractical.',
          C: 'Decidability is a property of a problem, not of a particular input size.',
          D: 'Every problem falls into one category or the other.',
        },
      },
      {
        tag: 'Apply',
        stem: 'The halting problem asks whether an arbitrary program will eventually stop on a given input. What is known about it?',
        options: [
          'It can be solved by running the program and waiting',
          'It is undecidable, so no general algorithm can answer it correctly for every program and input',
          'It is solvable but requires exponential time',
          'It is solvable for programs under 100 lines',
        ],
        correct: 'B',
        why: {
          A: 'Waiting never distinguishes a program that will stop later from one that never will.',
          B: 'This is the standard example of undecidability, proven rather than merely unsolved.',
          C: 'It is not a matter of time. No algorithm exists at any cost.',
          D: 'Line count does not change the result for the general problem.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A tool claims to detect every infinite loop in any submitted program.',
        stem: 'What can be concluded?',
        options: [
          'The tool must be extremely fast',
          'The claim cannot be fully true, since detecting whether an arbitrary program halts is undecidable, though the tool may catch many common cases',
          'The tool must use a heuristic that is always correct',
          'The claim is fine, since infinite loops are easy to spot',
        ],
        correct: 'B',
        why: {
          A: 'Speed does not make an impossible guarantee possible.',
          B: 'The general claim is exactly the halting problem, so a real tool catches recognizable patterns and cannot be complete.',
          C: 'A heuristic that is always correct on this problem would be a solution to it, which cannot exist.',
          D: 'Some are easy to spot. Detecting all of them in any program is not.',
        },
      },
      {
        tag: 'Analyze',
        stem: 'Which pair correctly classifies the two problems?',
        options: [
          'Sorting a list is undecidable, and the halting problem is decidable',
          'Sorting a list is decidable, and the halting problem is undecidable',
          'Both are undecidable',
          'Both are decidable',
        ],
        correct: 'B',
        why: {
          A: 'This reverses both classifications.',
          B: 'Sorting has well known correct algorithms, and the halting problem has been proven to have none.',
          C: 'Sorting is solved routinely.',
          D: 'The halting problem is the canonical undecidable problem.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student argues that faster computers will eventually make undecidable problems solvable.',
        stem: 'What is the correct response?',
        options: [
          'Correct, since speed removes every computational barrier',
          'Incorrect, because undecidability is about whether a correct algorithm can exist at all, which no amount of hardware changes',
          'Correct, but only for problems with small inputs',
          'Incorrect, because computers cannot get faster',
        ],
        correct: 'B',
        why: {
          A: 'Speed addresses how long an algorithm takes, and undecidable problems have no algorithm to speed up.',
          B: 'The limit is mathematical rather than physical, so hardware improvements are simply the wrong axis.',
          C: 'Input size does not change the result.',
          D: 'Computers do keep getting faster. That is not why the argument fails.',
        },
      },
    ],
  },
];
