'use strict';
// Big Idea 5: Impact of Computing. Exercise 2 banks, 6 topics.
// Applied challenge: Big Idea 5 questions fail when they become opinion prompts.
// Every stem here has a defensible correct answer grounded in the CED, and the
// distractors are the plausible positions that overstate or understate the case.
// Pure ASCII, no em-dashes. Zero PII: author content only.

module.exports = [
  {
    slug: 'beneficial-harmful-effects',
    title: 'Beneficial and Harmful Effects',
    blurb: 'Six innovations with real benefits and real harms. Identify both, and say who bears each.',
    brief: 'The exam never accepts an innovation being simply good or simply bad. The credit is in naming a benefit and a harm from the same feature.',
    seo: 'Applied AP CSP 5.1 practice: six scenario questions on the beneficial and harmful effects of computing innovations and their unintended consequences.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A navigation app routes drivers around highway traffic through residential side streets.',
        stem: 'Which pair correctly names a benefit and a harm of the same behavior?',
        options: [
          'Benefit: drivers save time. Harm: residential streets get traffic and risk they were not designed for',
          'Benefit: drivers save time. Harm: the app uses battery power',
          'Benefit: the app is free. Harm: drivers must own a phone',
          'Benefit: fewer cars on highways. Harm: the app is difficult to use',
        ],
        correct: 'A',
        why: {
          A: 'The rerouting that helps the driver is the same behavior that pushes volume onto streets with no capacity for it, and the two effects land on different people.',
          B: 'Battery use is real but trivial next to the effect, and it is not caused by the rerouting.',
          C: 'These describe the product rather than an effect of its use.',
          D: 'Usability is not a consequence of the routing behavior.',
        },
      },
      {
        tag: 'Apply',
        stem: 'What is an unintended consequence of a computing innovation?',
        options: [
          'A defect in the program that causes it to crash',
          'An effect the developers did not plan for, which may be beneficial or harmful',
          'A feature that was removed before release',
          'Any harmful effect of the innovation',
        ],
        correct: 'B',
        why: {
          A: 'A crash is a defect, which is different from an unplanned effect of correct operation.',
          B: 'Unintended means unplanned, and the CED is explicit that such effects run in both directions.',
          C: 'A removed feature has no effect to be unintended.',
          D: 'Harm is a common case but not the definition, since beneficial surprises count too.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A student writes that social media is harmful and nothing else.',
        stem: 'Why would this lose credit on the exam?',
        options: [
          'Social media is not a computing innovation',
          'The response names only one side, when the expectation is to identify both a beneficial and a harmful effect and connect each to the innovation',
          'Harmful effects cannot be discussed on the AP exam',
          'The response is too short to be graded',
        ],
        correct: 'B',
        why: {
          A: 'It is a standard example of a computing innovation.',
          B: 'The skill being tested is holding both effects at once and tying each to a specific behavior of the innovation.',
          C: 'Harm is explicitly part of the content.',
          D: 'Length is not the criterion. Coverage of both sides is.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A machine translation tool makes documents readable across languages.',
        stem: 'Which harmful effect is most directly tied to how the tool works?',
        options: [
          'It requires an internet connection',
          'Subtle mistranslations can carry authority they have not earned, so a reader may act on a confidently wrong translation',
          'It runs on a computer',
          'It was developed by a large company',
        ],
        correct: 'B',
        why: {
          A: 'A connectivity requirement is a limitation rather than a harm caused by the translation itself.',
          B: 'The harm comes from the same property that makes it useful: fluent output that reads as reliable whether or not it is.',
          C: 'Running on a computer is not an effect.',
          D: 'Who built it is not itself a harmful effect.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A hospital adopts an automated scheduling system and staffing needs drop.',
        stem: 'Which statement best captures the effect?',
        options: [
          'The system is purely beneficial, since scheduling improves',
          'The system benefits the hospital through efficiency while harming the workers whose roles are reduced, so benefit and harm fall on different groups',
          'The system is purely harmful, since jobs are affected',
          'The system has no effect worth analyzing',
        ],
        correct: 'B',
        why: {
          A: 'Focusing on the institution ignores who absorbs the cost.',
          B: 'Naming who benefits and who bears the harm is exactly the analysis the topic asks for, and the two are often different parties.',
          C: 'The efficiency gain is real and should not be dismissed.',
          D: 'Effects on employment are among the most consequential impacts of computing.',
        },
      },
      {
        tag: 'Evaluate',
        stem: 'Which statement about computing innovations is most accurate?',
        options: [
          'Every innovation is designed with its eventual uses fully anticipated',
          'An innovation can be used in ways its creators never intended, and those uses may produce effects the original design never accounted for',
          'Innovations only cause harm when they are poorly built',
          'Developers are not responsible for considering effects',
        ],
        correct: 'B',
        why: {
          A: 'Anticipating every use is not possible, which is why unintended consequences are a named topic.',
          B: 'Repurposing by users is common, and the resulting effects are a core part of what the course asks students to reason about.',
          C: 'Well built innovations produce harmful effects routinely, often through correct operation.',
          D: 'Considering effects during development is exactly what the course asks of developers.',
        },
      },
    ],
  },

  {
    slug: 'digital-divide',
    title: 'The Digital Divide',
    blurb: 'Six scenarios about unequal access, and about the difference between owning a device and being able to use it.',
    brief: 'The digital divide is not only about who has a computer. Several of these turn on access, skills, or connection quality instead.',
    seo: 'Applied AP CSP 5.2 practice: six scenario questions on the digital divide, unequal access to computing, and how access gaps compound over time.',
    questions: [
      {
        tag: 'Apply',
        stem: 'What does the digital divide refer to?',
        options: [
          'The difference between analog and digital data',
          'Differing access to computing devices and connectivity across groups, which may reflect geography, income, age, or other factors',
          'The gap between fast and slow processors',
          'The separation of a network into subnetworks',
        ],
        correct: 'B',
        why: {
          A: 'That is a data representation distinction, not a social one.',
          B: 'The divide is about who can access computing and connectivity, and the CED names socioeconomic, geographic, and demographic factors.',
          C: 'Hardware performance differences are not what the term describes.',
          D: 'That is a networking concept unrelated to access equity.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A district gives every student a laptop, and homework completion still lags in some neighborhoods.',
        stem: 'What is the most likely explanation?',
        options: [
          'The laptops are defective in those neighborhoods',
          'Device access was only part of the gap, and home internet access, quiet space, or support may still be missing',
          'Students in those neighborhoods do not want to use the laptops',
          'The digital divide has been fully closed by the laptops',
        ],
        correct: 'B',
        why: {
          A: 'Hardware failures would not follow neighborhood boundaries.',
          B: 'Access has several components, and closing the device gap leaves connectivity and conditions of use untouched.',
          C: 'Attributing the gap to motivation ignores the structural factors the topic is about.',
          D: 'The persisting gap is direct evidence that it has not.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A government moves benefit applications entirely online.',
        stem: 'Which consequence follows most directly from the digital divide?',
        options: [
          'Applications will be processed more slowly',
          'People without reliable internet access or the skills to use the system face a new barrier to a service they are entitled to',
          'The system will be more secure',
          'Everyone will receive benefits faster',
        ],
        correct: 'B',
        why: {
          A: 'Digitizing usually speeds processing, and speed is not the equity issue.',
          B: 'Moving a service online converts an access gap into a gap in receiving the service itself, which is the concrete harm.',
          C: 'Security may improve or worsen, and it is unrelated to the divide.',
          D: 'This is true for those who can use the system and false for those who cannot, which is the point.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A rural area has electricity and devices but only slow, intermittent connectivity.',
        stem: 'Does this count as part of the digital divide?',
        options: [
          'No, because the residents own devices',
          'Yes, because meaningful access includes the quality of connectivity, not only device ownership',
          'No, because slow access is still access',
          'Yes, but only if the residents cannot afford the devices',
        ],
        correct: 'B',
        why: {
          A: 'Ownership without usable connectivity does not deliver access.',
          B: 'The divide covers whether computing can actually be used for what it is needed for, and connection quality is part of that.',
          C: 'Connectivity too slow for the tasks people need effectively excludes them.',
          D: 'Affordability is one cause among several, and geography is a named factor on its own.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A company trains a hiring model on resumes submitted through its website.',
        stem: 'How does the digital divide affect the result?',
        options: [
          'It does not, since resumes are text',
          'People with less reliable access are underrepresented in the training data, so the model learns from a population that excludes them',
          'It makes the model run more slowly',
          'It guarantees the model will be fair',
        ],
        correct: 'B',
        why: {
          A: 'The format of the data does not determine who was able to submit it.',
          B: 'Data gathered through a channel reflects who can reach that channel, so an access gap becomes a representation gap in the data.',
          C: 'Data composition does not affect execution speed.',
          D: 'It makes the opposite more likely.',
        },
      },
      {
        tag: 'Evaluate',
        stem: 'Which action would most directly narrow the digital divide in a community?',
        options: [
          'Releasing a faster version of an existing app',
          'Funding public broadband access and training programs alongside device availability',
          'Adding more features to a government website',
          'Encouraging residents to buy newer phones',
        ],
        correct: 'B',
        why: {
          A: 'A faster app serves people who already have access.',
          B: 'Addressing connectivity, devices, and skills together targets all the components of access rather than one.',
          C: 'More features on a site people cannot reach widens the gap rather than narrowing it.',
          D: 'Encouragement does not address affordability or connectivity.',
        },
      },
    ],
  },

  {
    slug: 'computing-bias',
    title: 'Computing Bias',
    blurb: 'Six systems with bias in them. Locate where the bias entered.',
    brief: 'Bias enters at the data, at the design, or at the deployment. Naming which one is the whole skill.',
    seo: 'Applied AP CSP 5.3 practice: six scenario questions on bias in computing, identifying whether bias came from training data, design choices, or deployment.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A facial recognition system performs worse on some skin tones than others.',
        stem: 'Where did the bias most likely enter?',
        options: [
          'In the programming language chosen',
          'In the training data, which likely underrepresented those groups, so the system had less to learn from',
          'In the processor executing the model',
          'In the user interface design',
        ],
        correct: 'B',
        why: {
          A: 'Language choice has no bearing on what a model learns.',
          B: 'A model performs where it has seen examples, so an unrepresentative dataset produces uneven performance across groups.',
          C: 'Hardware executes the same computation for every input.',
          D: 'The interface is not where recognition accuracy comes from.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which statement about bias in computing is most accurate?',
        options: [
          'Bias only enters a program when a developer intends it',
          'Bias can be embedded unintentionally through data, design choices, or assumptions built into the system',
          'Programs cannot be biased, since they follow rules',
          'Bias only affects programs that use artificial intelligence',
        ],
        correct: 'B',
        why: {
          A: 'Most consequential bias is unintentional, which is why it is hard to catch.',
          B: 'Bias enters at multiple points, and none of them requires anyone to intend it.',
          C: 'Following rules faithfully is exactly how a biased rule produces biased outcomes at scale.',
          D: 'A plain conditional encoding an unfair rule is biased without any model involved.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A loan program excludes applicants from certain postal codes to reduce risk.',
        stem: 'What is the problem, even though postal code is not a protected characteristic?',
        options: [
          'Postal codes change too often to be reliable',
          'Postal code can act as a proxy for characteristics such as race or income, so the rule reproduces a discriminatory outcome without naming it',
          'The program will run too slowly with that check',
          'There is no problem, since postal code is objective data',
        ],
        correct: 'B',
        why: {
          A: 'Stability of the data is not the concern.',
          B: 'A neutral looking variable that correlates with a protected one delivers the same discriminatory result while appearing not to.',
          C: 'Execution speed is unrelated.',
          D: 'Data being objective says nothing about whether its use produces a fair outcome.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A team is about to deploy a hiring model.',
        stem: 'Which step would most directly reduce the risk of biased outcomes?',
        options: [
          'Making the model run faster',
          'Testing outcomes separately across the groups the system will affect, and examining the training data for representation gaps',
          'Adding more features to the model',
          'Deploying it and correcting problems as users report them',
        ],
        correct: 'B',
        why: {
          A: 'Speed does not change what the model decides.',
          B: 'Bias is found by measuring outcomes per group and auditing the data, since aggregate accuracy hides uneven performance.',
          C: 'More features can introduce more proxies rather than fewer.',
          D: 'Waiting for reports means the harm happens first, and the people affected are often least able to report.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A search system ranks results using what previous users clicked.',
        stem: 'How can this reinforce bias over time?',
        options: [
          'It cannot, since clicks reflect real preference',
          'Highly ranked results get more clicks, which raises their rank further, so an initial skew becomes self reinforcing',
          'Clicks are random and average out',
          'The system will correct itself as more users participate',
        ],
        correct: 'B',
        why: {
          A: 'Clicks reflect what was shown, so they measure exposure as much as preference.',
          B: 'A feedback loop between rank and clicks amplifies whatever skew the ranking started with rather than correcting it.',
          C: 'Clicks are heavily shaped by position and are not random.',
          D: 'More users feed the same loop, which entrenches the pattern.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A developer says their algorithm is fair because it does not use race as an input.',
        stem: 'What is the correct response?',
        options: [
          'Correct, since removing the variable removes the bias',
          'Removing the variable does not remove correlated variables that carry the same information, so outcomes must still be measured to establish fairness',
          'Correct, as long as the code is open source',
          'Incorrect, because every algorithm is biased and nothing can be done',
        ],
        correct: 'B',
        why: {
          A: 'Other variables frequently reconstruct the removed one, so the outcome can be unchanged.',
          B: 'Fairness is a property of outcomes, so it has to be measured rather than inferred from which inputs were excluded.',
          C: 'Open source improves scrutiny but does not establish fairness on its own.',
          D: 'Bias is measurable and reducible. Fatalism is as unhelpful as denial.',
        },
      },
    ],
  },

  {
    slug: 'crowdsourcing',
    title: 'Crowdsourcing',
    blurb: 'Six projects that depend on contributions from many people. Judge what the crowd can and cannot supply.',
    brief: 'Crowdsourcing gathers scale cheaply and gathers whoever showed up. Both halves of that sentence are tested.',
    seo: 'Applied AP CSP 5.4 practice: six scenario questions on crowdsourcing, citizen science, distributed contribution, and the limits of crowd-collected data.',
    questions: [
      {
        tag: 'Apply',
        stem: 'What is crowdsourcing?',
        options: [
          'Distributing a computation across many processors in one machine',
          'Obtaining input, data, or services from a large group of people, often over the internet',
          'Storing data across many servers for redundancy',
          'Selling a product directly to consumers',
        ],
        correct: 'B',
        why: {
          A: 'That describes parallel computing, which distributes computation rather than human contribution.',
          B: 'Crowdsourcing is about aggregating contributions from many people, which is what makes it distinct from distributing computation.',
          C: 'That is distributed storage.',
          D: 'A sales model is unrelated.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A bird tracking project collects sightings submitted by volunteers.',
        stem: 'Which limitation most affects the resulting data?',
        options: [
          'Volunteers cannot identify birds at all',
          'Sightings cluster where volunteers live and go, so absence of reports in an area may mean absence of observers rather than absence of birds',
          'The data will be too small to analyze',
          'Volunteers will only report common species',
        ],
        correct: 'B',
        why: {
          A: 'Volunteers identify birds reasonably well, often with verification.',
          B: 'Crowd collected data reflects the distribution of contributors, so coverage gaps look identical to genuine absence.',
          C: 'Crowdsourcing typically produces more data than traditional collection, not less.',
          D: 'Rare sightings are often over reported because they are exciting, which is a different bias.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A company crowdsources translations for its app.',
        stem: 'What is the main tradeoff?',
        options: [
          'Translations arrive faster but cost more',
          'Coverage across many languages arrives quickly and cheaply, but quality varies and needs review since contributors have differing expertise',
          'Translations are always more accurate than professional ones',
          'There is no tradeoff, since more contributors always improve quality',
        ],
        correct: 'B',
        why: {
          A: 'Cost is normally lower, which is a main reason to crowdsource.',
          B: 'Breadth and speed are what the crowd supplies well, and consistent quality is what it does not, so review is the standard complement.',
          C: 'Some crowd translations are excellent and others are not, with no guarantee either way.',
          D: 'More contributors add more variance as well as more coverage.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A mapping project lets anyone edit road data.',
        stem: 'Which practice best manages the risk of bad edits?',
        options: [
          'Preventing all edits after launch',
          'Keeping an edit history with review, so incorrect changes can be identified and reverted',
          'Accepting only edits from professional cartographers',
          'Removing the ability to see who made each edit',
        ],
        correct: 'B',
        why: {
          A: 'Freezing the data forfeits the continuous improvement that motivated the open model.',
          B: 'Versioned, attributable edits make errors reversible, which is what allows an open contribution model to stay trustworthy.',
          C: 'Restricting contributors to professionals abandons crowdsourcing entirely.',
          D: 'Removing attribution makes bad edits harder to trace, not easier.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which is the clearest example of crowdsourcing being the right approach?',
        options: [
          'Computing the average of a stored dataset',
          'Building a database of local sidewalk accessibility, which requires observations from many places no single team could visit',
          'Sorting a list of names',
          'Encrypting a file before sending it',
        ],
        correct: 'B',
        why: {
          A: 'A stored dataset needs a computation, not contributors.',
          B: 'The task needs geographically distributed human observation at a scale no single group could reach, which is exactly what a crowd supplies.',
          C: 'Sorting is a purely computational task.',
          D: 'Encryption requires no human contribution.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A crowdsourced review site shows a restaurant with a 4.8 rating from 6 reviews.',
        stem: 'What is the most accurate reading?',
        options: [
          'The rating is reliable, since it is high',
          'A small number of reviews makes the average unstable, and the reviewers may not represent typical customers',
          'The rating is meaningless and should be ignored entirely',
          'The rating proves the restaurant is better than one rated 4.5',
        ],
        correct: 'B',
        why: {
          A: 'A high value from few observations is not the same as a reliable one.',
          B: 'Small samples swing easily, and self selected reviewers are not a random sample of customers.',
          C: 'Six reviews carry some information, just less than a large sample would.',
          D: 'A higher average over far fewer reviews does not establish a real difference.',
        },
      },
    ],
  },

  {
    slug: 'legal-ethical-concerns',
    title: 'Legal and Ethical Concerns',
    blurb: 'Six situations where something is legal and questionable, or illegal and common. Tell them apart.',
    brief: 'Legal and ethical are two different tests, and the exam checks that you apply them separately.',
    seo: 'Applied AP CSP 5.5 practice: six scenario questions on copyright, licensing, intellectual property, open source, and the ethics of data collection.',
    questions: [
      {
        tag: 'Apply',
        scenario: 'A student finds an image online with no license or copyright notice.',
        stem: 'What is the correct assumption?',
        options: [
          'The image is public domain, since no notice appears',
          'The image is protected by copyright by default, and permission or an applicable license is needed to use it',
          'Any image found online may be used freely',
          'The image may be used if the source is credited',
        ],
        correct: 'B',
        why: {
          A: 'Copyright attaches automatically at creation, so the absence of a notice signals nothing.',
          B: 'Protection is the default, which is why creators use explicit licenses such as Creative Commons to grant permission.',
          C: 'Being findable online grants no rights.',
          D: 'Credit is good practice and is not a substitute for permission.',
        },
      },
      {
        tag: 'Analyze',
        stem: 'What does a Creative Commons license do?',
        options: [
          'It removes copyright from a work entirely',
          'It lets a creator grant specific permissions in advance, such as allowing reuse with attribution, while keeping copyright',
          'It transfers ownership to the public',
          'It prevents any reuse of the work',
        ],
        correct: 'B',
        why: {
          A: 'The creator retains copyright and uses it to grant terms.',
          B: 'A Creative Commons license is a standing grant of stated permissions, which removes the need to ask individually.',
          C: 'Ownership stays with the creator. Placing work in the public domain is a separate act.',
          D: 'Enabling reuse is the entire purpose.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'An app collects far more data than it needs, all disclosed in a long terms of service the user accepted.',
        stem: 'What is the most accurate assessment?',
        options: [
          'There is no concern, since the user agreed',
          'It may be legal because consent was obtained, and still ethically questionable, since consent buried in unread terms is not meaningful understanding',
          'It is illegal, since collecting extra data is prohibited',
          'It is ethical as long as the data is kept secure',
        ],
        correct: 'B',
        why: {
          A: 'Formal agreement satisfies a legal test and does not settle the ethical one.',
          B: 'The two tests come apart here, and separating them is precisely what the topic asks for.',
          C: 'Disclosed collection is generally legal, though specific jurisdictions add limits.',
          D: 'Security protects data that arguably should not have been collected.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A developer uses an open source library in a commercial product.',
        stem: 'What determines whether this is permitted?',
        options: [
          'Open source code may always be used commercially without conditions',
          'The specific license terms, which may require attribution, sharing modifications, or other conditions',
          'Whether the product is profitable',
          'Whether the original developer is contacted first',
        ],
        correct: 'B',
        why: {
          A: 'Open source licenses vary considerably in what they require.',
          B: 'The license is the governing document, and different open source licenses impose meaningfully different obligations.',
          C: 'Profitability does not determine permission.',
          D: 'Contact is unnecessary when the license already grants permission, and insufficient when it does not.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which use of another person\'s code in a Create Task submission is acceptable?',
        options: [
          'Copying a procedure and presenting it as the student developed procedure',
          'Using a properly attributed library or code segment for supporting functionality, while writing the student developed procedure yourself',
          'Copying an entire program and changing the variable names',
          'Using any code found online without attribution as long as it is short',
        ],
        correct: 'B',
        why: {
          A: 'The student developed procedure must be the student\'s own work.',
          B: 'Attributed reuse for supporting functionality is expected practice, provided the required original work is genuinely original.',
          C: 'Renaming variables does not make copied work original.',
          D: 'Length does not remove the attribution requirement.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A company sells anonymized user location data.',
        stem: 'What is the strongest concern?',
        options: [
          'Anonymized data has no value, so the sale is pointless',
          'Location patterns can often be re-identified by combining them with other data, so anonymized may not mean unidentifiable',
          'Selling data is always illegal',
          'The data will slow down the company servers',
        ],
        correct: 'B',
        why: {
          A: 'Its commercial value is exactly why it is sold.',
          B: 'Location traces are highly distinctive, and combining datasets frequently reverses anonymization, which undermines the protection the label implies.',
          C: 'Data sales are broadly legal, with jurisdictional limits.',
          D: 'Server performance is not the concern here.',
        },
      },
    ],
  },

  {
    slug: 'safe-computing',
    title: 'Safe Computing',
    blurb: 'Six security situations. Name the attack or the protection, and say what it actually defends against.',
    brief: 'Most security answers on the exam are wrong because the protection named does not address the threat described. Match them carefully.',
    seo: 'Applied AP CSP 5.6 practice: six scenario questions on PII, phishing, multifactor authentication, encryption, and what each protection actually defends against.',
    questions: [
      {
        tag: 'Analyze',
        scenario: 'A user receives an email that appears to be from their bank asking them to confirm their password at a linked site.',
        stem: 'What is this, and what defends against it?',
        options: [
          'A virus, defended against by antivirus software',
          'Phishing, defended against by verifying the sender and never entering credentials through a link in an unsolicited message',
          'A denial of service attack, defended against by a firewall',
          'Encryption failure, defended against by a stronger cipher',
        ],
        correct: 'B',
        why: {
          A: 'No malicious program is involved. The attack targets the person rather than the machine.',
          B: 'Phishing works by impersonation to obtain credentials, so the defense is verification and refusing to authenticate through unsolicited links.',
          C: 'Nothing here attempts to overwhelm a service.',
          D: 'No encrypted channel has failed.',
        },
      },
      {
        tag: 'Apply',
        stem: 'What does multifactor authentication protect against that a strong password alone does not?',
        options: [
          'It makes the password harder to guess',
          'It means a stolen or guessed password is not sufficient on its own, since a second independent factor is still required',
          'It encrypts the password in transit',
          'It prevents phishing emails from being sent',
        ],
        correct: 'B',
        why: {
          A: 'The password itself is unchanged by adding a second factor.',
          B: 'The value is that compromise of one factor does not grant access, which is exactly the case a strong password cannot cover.',
          C: 'Encryption in transit is a separate protection handled by the connection.',
          D: 'Nothing stops the messages from being sent. It limits what a successful one achieves.',
        },
      },
      {
        tag: 'Evaluate',
        scenario: 'A site uses HTTPS.',
        stem: 'What does that guarantee, and what does it not?',
        options: [
          'It guarantees the site is trustworthy and its content is accurate',
          'It protects data in transit from being read or altered between the user and the site, and says nothing about whether the site itself is honest',
          'It guarantees the site cannot be hacked',
          'It guarantees the user\'s data will not be sold',
        ],
        correct: 'B',
        why: {
          A: 'A fraudulent site can obtain a certificate as easily as an honest one.',
          B: 'HTTPS secures the channel. What the operator at the other end does with the data is entirely outside its scope.',
          C: 'Server compromise is unrelated to transport encryption.',
          D: 'Data handling policy is not a property of the connection.',
        },
      },
      {
        tag: 'Apply',
        stem: 'Which is an example of personally identifiable information?',
        options: [
          'The current temperature in a city',
          'A home address combined with a full name',
          'The number of users on a website',
          'A programming language name',
        ],
        correct: 'B',
        why: {
          A: 'Weather data identifies no one.',
          B: 'Information that identifies a specific person, directly or in combination, is PII, and name plus address is the standard example.',
          C: 'An aggregate count identifies no individual.',
          D: 'A technology name is not personal information.',
        },
      },
      {
        tag: 'Transfer',
        scenario: 'A public wifi network requires no password.',
        stem: 'What is the specific risk, and what reduces it?',
        options: [
          'The connection will be slow, reduced by using a wired connection',
          'Traffic on an open network can be observed by others nearby, reduced by using encrypted connections such as HTTPS or a VPN',
          'The device will be infected with a virus automatically, reduced by antivirus software',
          'The network will steal stored files, reduced by deleting them',
        ],
        correct: 'B',
        why: {
          A: 'Speed is an inconvenience rather than the security risk.',
          B: 'Without network level encryption, nearby parties can observe traffic, so encrypting at a higher layer restores confidentiality.',
          C: 'Connecting to a network does not by itself install anything.',
          D: 'A network does not reach into stored files on its own.',
        },
      },
      {
        tag: 'Analyze',
        scenario: 'A program stores user passwords exactly as typed.',
        stem: 'Why is this a problem, and what is the standard practice?',
        options: [
          'It uses too much storage, so passwords should be shortened',
          'Anyone who obtains the stored data has every password directly, so passwords should be stored as hashes rather than as readable text',
          'It is slower to compare stored passwords, so they should be encrypted for speed',
          'There is no problem as long as the database is behind a firewall',
        ],
        correct: 'B',
        why: {
          A: 'Storage size is irrelevant next to the exposure.',
          B: 'Hashing means a breach yields values that cannot be trivially reversed into the original passwords, which limits the damage of a compromise.',
          C: 'Speed is not the motivation, and comparing hashes is fast.',
          D: 'Perimeter defenses fail, and the design should limit what a breach yields when they do.',
        },
      },
    ],
  },
];
